### ISSUE TITLE
功能增加建议

### ISSUE THREAD

**Issue by youth5201314** [youth5201314/banner#1]
1、增加设置是否自动轮播
2、增加指示器位置设置

**Comment by youth5201314** [comment]
已经增加

**Comment by YumikoAzu** [comment]
建议增加 可以自定义 指示器样式

**Comment by youth5201314** [comment]
指示器是可以自定义的哦！可以自定义资源的，在布局文件里引用就行了。  app:indicator_drawable_selected="指示器选中效果"
app:indicator_drawable_unselected="指示器未选中效果"
app:indicator_height="指示器圆形按钮的高度"
app:indicator_width="指示器圆形按钮的宽度"

**Comment by YumikoAzu** [comment]
额 我要指示器有特别的效果呢。？！！

**Comment by youth5201314** [comment]
什么特别的效果，是增加自定义的动画吗。

**Comment by YumikoAzu** [comment]
对 切换时指示器 的点点会变大 之类的

**Comment by youth5201314** [comment]
ok 记下了，过两天去弄。谢谢你的建议。

**Comment by KevinJian** [comment]
可以增加指示器 形状的 扩展设置，有些个性化的需求 哭能不限定 圆形的指示器

**Comment by youth5201314** [comment]
指示器的形状是可以自定义的。
app:indicator_drawable_selected="指示器选中效果"
app:indicator_drawable_unselected="指示器未选中效果
这里可以设置xml文件和图片，你想要的形状完全可以自己实现。
