### ISSUE TITLE
banner出现重复加载

### ISSUE THREAD

**Issue by wuzhaohui026** [youth5201314/banner#10]
我在网络清理成功后将图片显示到banner里，但是刷新后出现数据重复加载的情况。不知道是不是我逻辑错了，总觉的banner却一个类似notifyDataSetChanged()的方法。
![image](https://cloud.githubusercontent.com/assets/7565399/17277877/77d264c8-5780-11e6-85fc-28eae68bf1a7.png)
![image](https://cloud.githubusercontent.com/assets/7565399/17277878/7c3f64fc-5780-11e6-9cb1-c21391a1c524.png)

**Comment by youth5201314** [comment]
刚测试框架不存在重复加载的情况。

**Comment by wuzhaohui026** [comment]
还奇怪，我一直找不到原因在哪里，命名显示返回的数据只有3，但是没刷新异常就增加3个。。。

**Comment by wuzhaohui026** [comment]
我想了下，应该和我吧banner昨晚Header放到RecyclereView里有关。

**Comment by youth5201314** [comment]
不会啊，我也是吧banner放到RecyclereView里的啊，如果你要验证是否是框架重复加载很简单，你在加载图片时打印加载的图片链接就能看出来了，你可以通过自定义记住方式去看。如果你实在找不到方便的话就将代码发过来我帮你看下！

**Comment by wuzhaohui026** [comment]
那我发你你帮我看下吧，已经纠结了好几天了
