### ISSUE TITLE
真是要疯了

### ISSUE THREAD

**Issue by Fisherman91** [youth5201314/banner#100]
总是报这个异常， Error inflating class com.youth.banner.Banner，新建个项目试了一下可以。我已经仔细检查过了，也不知问题出在哪。能帮我分析一下吗
![qq 20161227172740](https://cloud.githubusercontent.com/assets/17759213/21496475/cfc5ac0a-cc59-11e6-95f8-b6647c472e15.png)

**Comment by youth5201314** [comment]
把你的代码完整的贴出来，或者运行demo，我的文档你按照步骤写不会有问题的！

**Comment by Fisherman91** [comment]
布局文件非常简单，这个布局文件是给一个fragment，我的MainActivity布局就是一个简单的容器+底部导航，然后我用如图的方式切换Fragment。
![fragment_accountant](https://cloud.githubusercontent.com/assets/17759213/21496799/10f1dd14-cc5c-11e6-92bc-50e7a9b9f2fa.png)
![switch_fragment](https://cloud.githubusercontent.com/assets/17759213/21496798/1094ebcc-cc5c-11e6-8106-218e364d0c56.png)
发现一个奇怪的问题，我如果单独启动一个Activity，里边包含一个Fragment就可以。只要Fragment放在我的MainActivity进行切换，就报错

**Comment by Fisherman91** [comment]
![image](https://cloud.githubusercontent.com/assets/17759213/21499285/707b8092-cc6f-11e6-87f8-858257f9a3b9.png)
![image](https://cloud.githubusercontent.com/assets/17759213/21499297/8d1cceea-cc6f-11e6-9746-31a3ca7e9387.png)

编译不出viewpager、titleView...这些属性

**Comment by Fisherman91** [comment]
Iam sorry,你的布局文件叫banner，而我的一个库里也有个banner.xml..这个你在md文件里描述一下就好了
