### ISSUE TITLE
kotlin 使用问题

### ISSUE THREAD

**Issue by wlingf** [youth5201314/banner#1009]
把banner用于recyclerview item 结合BaseRecyclerViewAdapterHelper 使用，查找控件的时候会报错
<img width="928" alt="WX20210303-101934@2x" src="https://user-images.githubusercontent.com/19945512/109743967-818ec000-7c0c-11eb-963c-4b11d5369961.png">

**Comment by wlingf** [comment]
<img width="1136" alt="WX20210303-113426@2x" src="https://user-images.githubusercontent.com/19945512/109748825-7b044680-7c14-11eb-93ad-95d62f703c85.png">
这么写图片显示不出来

**Comment by JeffrayZ** [comment]
我也碰到同样的问题了，请问怎么解决的呢？
