### ISSUE TITLE
RecyclerView嵌套问题

### ISSUE THREAD

**Issue by chy116449859** [youth5201314/banner#101]
我用这个控件嵌套在recyclerview，在上下滑动过程中，无法保存viewpager的selectpostion，个人感觉应该是每次setdata时把currentItem自动设置为1了，所以我觉得还可以改进，因为目前这样是无法保存下来selectposition的，用于滑动控件时就会有点小问题。还有就是没有提供setcurrentitem的方法，个人觉得也可以添加进来。

**Comment by youth5201314** [comment]
这个不是保存的问题，关键是你上下滑动时把它回收了，请问怎么保存？难道我还能判断你是否上下滑动了？软件应用场景成千上万，你要自己处理一些业务逻辑，这些是你自己程序处理的好吗？
