### ISSUE TITLE
ConstraintLayout 不兼容 图片不显示

### ISSUE THREAD

**Issue by Biswangluo** [youth5201314/banner#1012]
android:layout_width="0"

会不显示图片 轮播图切换 指示点都正常 昨天排查这个问题整整一天 太坑了
必须 

android:layout_width="match_parent"

ConstraintLayout 不写match 的 这太奇怪了

**Comment by Biswangluo** [comment]
如果在布局外面 套一层 布局 里面写match 还是会不显示图片 简直太奇怪了 外面的布局必须写match
 <FrameLayout
        android:layout_width="0"
        android:layout_height="140dp"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent">

        <com.youth.banner.Banner
            android:id="@+id/banner"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />
    </FrameLayout>

**Comment by 542604974** [comment]
感谢，真的是这样，本来好的，突然就不行了，我看了你说的我查了下跟你一样的问题，我改成match_parent就好了，不然我打死想不到是这个问题，因为这个也没的其他控件没问题
