### ISSUE TITLE
总是从最后一个item显示

### ISSUE THREAD

**Issue by renmingjian** [youth5201314/banner#1014]
如果给数据集合先设置为空，之后有数据后，通过list.clear()和list.addAll(newList)和notifyDatSetChanged之后，item总是从最后一个显示

**Comment by weidongjian** [comment]
也碰到了同样的问题

**Comment by shq2333** [comment]
调用banner.setDatas()，而不是adapter的setDatas()
或者你调用了adapter.setDatas()后调用setCurrentItem(1, false);

**Comment by weidongjian** [comment]
> 调用banner.setDatas()，而不是adapter的setDatas()
> 或者你调用了adapter.setDatas()后调用setCurrentItem(1, false);

经验证，可以了，感谢！！

**Comment by DysaniazzZ** [comment]
> 调用banner.setDatas()，而不是adapter的setDatas()
> 或者你调用了adapter.setDatas()后调用setCurrentItem(1, false);

666666，这个方法可以，感谢老哥

**Comment by Ha2ryZhang** [comment]
> 调用banner.setDatas()，而不是adapter的setDatas()
> 或者你调用了adapter.setDatas()后调用setCurrentItem(1, false);

感谢
