### ISSUE TITLE
setDatas后没有调用initIndicator后导致指示器没有显示

### ISSUE THREAD

**Issue by xxm-sz** [youth5201314/banner#1017]
也就是说我提前创建了adapter和indicator，并设置给了banner
在数据来临后调用了adapter的setDatas函数，这时indicaotr是不会显示的。

**Comment by callhh** [comment]
同样遇到了

**Comment by youth5201314** [comment]
我测试过了，先创建banner和adapter，然后请求网络返回后再调用banner的setdata或者是调用adapter自己实现的更新数据操作，都无法复现，请贴下代码或者发下demo

**Comment by imtianx** [comment]
有同样的问题，应该是 `setDatas` 无法触发注册的数据变化监听，导致没有刷新 indicator 吧, 可以手动调用  `notifyDataSetChanged` 来解决。

**Comment by imtianx** [comment]
#1034
