### ISSUE TITLE
添加生命周期会导致部分手机快速跳跃轮播

### ISSUE THREAD

**Issue by Biswangluo** [youth5201314/banner#1018]
Degbug 发现stop()   removeCallbacks(mLoopTask);方法失效 然后不停的快速轮播 
只要不加addBannerLifecycleObserver就没问题 
仅在部分手机上面复现

**Comment by censhengde** [comment]
貌似我也遇到了类似问题

**Comment by zhangwm1219** [comment]
不加addBannerLifecycleObserver 也概率性复现
