### ISSUE TITLE
轮播的小问题

### ISSUE THREAD

**Issue by weight68kg** [youth5201314/banner#1019]
我遇到了三个问题：
1. 手指不松开一直滑动会划到尽头。
2. 设置setBannerGalleryEffect之后，划到做后一张时后面的会留白一下，然后马上会出现新的图片。
3. 在CoordinatorLayout布局下，banner部分滑出屏幕，导致无法轮播。

看了源码之后发现前两个问题可以归位一个问题。作者是通过viewpager的状态处理轮播逻辑的，当viewpager 状态为 idle时，会重新计算下标。

第一个问题一直滑动时不会触发idle状态，也就不会进行轮播操作。
参考ios同事的办法是，在发生偏移时重新计算下标。比如当手指滑动倒数第二个item时，直接计算前置位相同item的下标。这样就不会看到最后临界了。

第二个问题因为设置内边距可以一次看到三个item，轮播到最后一个才会重新计算下标，所以会有短时间的留白。
这个需要前后再各增加一个item做保护，也可以解决。

第三个问题我没有找到根本原因，只是知道setCurrentItem()之后viewpager没有刷新，我是用notifyDataSetChanged()强制刷新解决。如果有更好的解决办法麻烦也告诉我一下。

**Comment by android-1995** [comment]
老哥，提交个PR让我借鉴下呀

**Comment by android-1995** [comment]
@youth5201314 大佬有空修复下，demo也会复现这个问题

**Comment by weight68kg** [comment]
> 老哥，提交个PR让我借鉴下呀

我当时也是应付随便写的，现在逻辑我也捋不清，你要是需要我就发给你做个参考

**Comment by weight68kg** [comment]
> 老哥，提交个PR让我借鉴下呀

@android-1995  我当时也是应付随便写的，现在逻辑我也捋不清，你要是需要我就发给你做个参考

**Comment by android-1995** [comment]
> > 老哥，提交个PR让我借鉴下呀
> 
> @android-1995 我当时也是应付随便写的，现在逻辑我也捋不清，你要是需要我就发给你做个参考

感谢回复。我已经换框架了😀
