### ISSUE TITLE
不循环轮播

### ISSUE THREAD

**Issue by zabio** [youth5201314/banner#102]
怎么设置不循环

**Comment by chy116449859** [comment]
setAutoPlay(false)

**Comment by wei120698598** [comment]
怎么设置不循环播放，不是自动播放

**Comment by youth5201314** [comment]
is_auto_play=“false”或者setAutoPlay(false)，还有在使用时能不能看下文档，文档写的不清楚吗？不要什么都提问好吗？

**Comment by wei120698598** [comment]
//设置自动轮播，默认为true
你瞎啊？你看看文档是不是这么写的，我说的是循环播放，不是自动轮播，懂？

**Comment by youth5201314** [comment]
就你这态度，我又不是你什么？你说你给了我酬劳呢？还是我欠你什么呢？我不就是理解错了嘛！你至于吗？大哥我不欠你什么，也没有必要去管你，我开源只是方便大多数人，你也不一定在其中，没有人求着你使用好吗？我靠！

**Comment by wei120698598** [comment]
我向你道歉，有点冲动。

**Comment by youth5201314** [comment]
没事！你这需求太少，没有考虑进来，你只能本地依赖，改下代码。
