### ISSUE TITLE
JCenter服务关闭是不是对项目有影响？

### ISSUE THREAD

**Issue by zhangbingbing889** [youth5201314/banner#1020]
我在gradle中去掉jcenter仓库，构建失败。
![image](https://user-images.githubusercontent.com/59674702/114370631-46d85a00-9bb2-11eb-8afb-cada5845de24.png)

**Comment by tangmoushi** [comment]
有影响，过段时间不迁移到mavenCentral就要用不了了，只能jar,aar引用了

**Comment by parade0393** [comment]
> 有影响，过段时间不迁移到mavenCentral就要用不了了，只能jar,aar引用了

希望youth大佬尽快迁移到maven或者jitpack

**Comment by youth5201314** [comment]
已经迁移到mavenCentral了
