### ISSUE TITLE
关于banner展示发现的问题

### ISSUE THREAD

**Issue by StevenZhangHl** [youth5201314/banner#1021]
我的banner右侧始终有一条白的间隙，看源码应该是paint的颜色，但是看源码里的图片的宽度是match的，不知道为啥会出现这样的问题。
![image](https://user-images.githubusercontent.com/7867862/114482727-a6c61380-9c39-11eb-9368-d737c3572e9d.png)
问题图片如下
![IMG_20210413_092255](https://user-images.githubusercontent.com/7867862/114482949-09b7aa80-9c3a-11eb-8d0c-4be528073358.jpg)

**Comment by youth5201314** [comment]
我这无法复现啊，这个颜色这是为了绘制圆角设置的，就算有问题也是圆角问题啊，不会出现一个有一根线的，你检查下你的布局呢，如果没有解决，这个问题可以提供demo给我，我看下！
