### ISSUE TITLE
画廊效果设置圆角无效

### ISSUE THREAD

**Issue by ghost** [youth5201314/banner#1023]

**Comment by ssmessagess** [comment]
我也是同样的问题

**Comment by shuangqingfeng** [comment]
同样问题

**Comment by shuangqingfeng** [comment]
@dawnhope  @ssmessagess  加上这个试试

if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
                binding.bannerProduct.setBannerRound2(ScreenUtil.dip2px(8));
            } else {
                binding.bannerProduct.setBannerRound(ScreenUtil.dip2px(8));
            }

**Comment by GTX-GSO** [comment]
我也是同样的问题
