### ISSUE TITLE
使用banner显示视频和图片，在onPageSelected方法中调用banner.stop无法停止轮播

### ISSUE THREAD

**Issue by gaobin881201** [youth5201314/banner#1024]
banner.setAdapter(new MultipleTypesAdapter(this, DataBean.getTestDataVideo()))
                .setIndicator(new NumIndicator(this))
                .setIndicatorGravity(IndicatorConfig.Direction.RIGHT)
                .setOnBannerListener(new OnBannerListener() {
                    @Override
                    public void OnBannerClick(Object data, int position) {
                        Log.e("OnBannerClick", "position");
                        banner.stop();//点击可以停止轮播
                    }
                })
                .addOnPageChangeListener(new OnPageChangeListener() {
                    @Override
                    public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {

                    }

                    @Override
                    public void onPageSelected(int position) {
                        Log.e("onPageSelected", "" + position);
                        RecyclerView.ViewHolder viewHolder = ((MultipleTypesAdapter) banner.getAdapter()).getVHMap().get(position);
                        if (position == 0) {
                            banner.stop();//无法停止轮播
                        }
｝
因为我现在有个需求就是轮播会有视频和图片，滑动视频页的时候需要停止轮播 等视频播放完成后再次启动轮播，目前是在onPageSelected调用banner.stop()无法停止轮播

**Comment by shq2333** [comment]
用banner.isAutoLoop(false);暂停轮播，因为onPageScrolled执行完后又postDelay了，所以stop无效

**Comment by gaobin881201** [comment]
我现试过banner.isAutoLoop(false) 还是暂时不成功

**Comment by shq2333** [comment]
https://github.com/youth5201314/banner/blob/34eb6e1831825f161949c29e87ce6af0c8cfb80f/banner/src/main/java/com/youth/banner/Banner.java#L392-L412

**Comment by shq2333** [comment]
https://github.com/youth5201314/banner/blob/34eb6e1831825f161949c29e87ce6af0c8cfb80f/banner/src/main/java/com/youth/banner/Banner.java#L392-L412
不可能不能成功暂停的，你检查你的代码是不是没有执行isAutoLoop(false)

**Comment by isHaYiana** [comment]
我也遇到了该问题，设置  isAutoLoop(false)时会停止轮播，但是start和stop 都无法调用。想要设置在哪个item时轮播就不行。
override fun onPageSelected(position: Int) {
                /*if (videoPath.isNullOrEmpty()) {
                    banner.isAutoLoop(false)
                    banner.start()
                } else {
                    if (position == 0) {
                        banner.isAutoLoop(true)
                        banner.stop()
                        videoManager.startPlay(videoPath)
                    } else {
                        banner.isAutoLoop(false)
                        banner.start()
                        if (videoManager.isPlaying) {
                            videoManager.stopPlay(true)
                        }
                    }
                }*/
                banner.isAutoLoop(true)
                banner.stop()
                Log.e("addOnPageChangeListener", "onPageSelected: $position")
            }

**Comment by gaobin881201** [comment]
if(((DataBean)banner.getAdapter().getData(position)).viewType==2){
                            RecyclerView.ViewHolder viewHolder = ((MultipleTypesAdapter) banner.getAdapter()).getVHMap().get(position);
                            Log.e("--", "position:" + position + "VH Type is " + viewHolder.getClass().getCanonicalName());
                        }
这里第一次轮播的时候 这个viewHolder获取是空的是怎么回事

**Comment by xuhuanli** [comment]
首次加载时似乎没有触发onPageSelected的回调 我暂时没找到触发的方式 用了反射方案
val clz = banner::class.java
            val field = clz.getDeclaredField("mPageChangeCallback")
            field.isAccessible = true
            val instance = field.get(banner)
            val clzs = clz.declaredClasses
            for (subClz in clzs) {
                if (subClz.canonicalName == instance::class.java.canonicalName) {
                    val declaredField = subClz.getDeclaredField("isScrolled")
                    declaredField.isAccessible = true
                    declaredField.setBoolean(instance, true)
                }
            }
来触发onPageSelected的第一次回调

**Comment by NewDirection** [comment]
轮播到下一个界面拿到的是ImageHolder获取不到之前的VideoHolder，得不到player所以无法停止播放.

**Comment by hyvenzhu** [comment]
/**
     * 停止自动轮播
     */
    private fun stopAutoPlay() {
        viewBinding.banner.isAutoLoop(false)
        viewBinding.banner.stop()
    }

    /**
     * 开始自动轮播
     */
    private fun startAutoPlay() {
        viewBinding.banner.isAutoLoop(true)
        viewBinding.banner.start()
    }
