### ISSUE TITLE
使用banner显示纯视频列表时，滑动到当前position自动播放的问题

### ISSUE THREAD

**Issue by Youngkingtom** [youth5201314/banner#1027]
目前项目需要做一个滑动到所在position就自动播放视频的需求，已实现自动播放，但是当滑动到列表最小值和最大值的position时，视频会播放有声音但是没有画面，是无限滑动自动填充item的问题吗？
```kotlin
binding.videoBanner.apply {
            setIndicator(CircleIndicator(binding.root.context), false)
            setBannerGalleryEffect(90, 50)
            isAutoLoop(false)
            adapter = IndexAdapter(context, DataBean.getIndexData())
            addOnPageChangeListener(object : OnPageChangeListener {
                override fun onPageScrolled(position: Int, positionOffset: Float, positionOffsetPixels: Int) {
                    "${position}/${binding.videoBanner.realCount}".also { binding.videoListText.text = it }
                }

                override fun onPageSelected(position: Int) {
                    val video = (binding.videoBanner.adapter as IndexAdapter).getVHMap().get(position)
                    video.startPlayLogic()
                }
                override fun onPageScrollStateChanged(state: Int) {
                }
            })
        }
```

**Comment by Youngkingtom** [comment]
![banner](https://user-images.githubusercontent.com/65012404/117528637-b7ce2e80-b005-11eb-862a-388b7d8a5c86.gif)
这是实际效果，视频播放后没有画面

**Comment by isHaYiana** [comment]
很明显是预加载的问题啊

**Comment by Youngkingtom** [comment]
> 很明显是预加载的问题啊

我用的GSYVideoPlayer，没有设置预加载啊。还有可能是什么问题呢

**Comment by chenkexu** [comment]
兄弟，你这个问题，怎么解决的？

**Comment by xiaolunan** [comment]
我也发现了这个问题，当第一个item是视频的话，轮播一圈回到第一个视频，视频就没有画面里（但是声音已经开始播放了），第一个item是图片的话就没有问题，我发现是初次获得的第一个item的viewHolder和论一圈后第一个item后的viewHolder不是同一个对象了，我也尝试更换了视频库（饺子播放器），也还是存在同样的问题

**Comment by Louiswang86** [comment]
> 我也发现了这个问题，当第一个item是视频的话，轮播一圈回到第一个视频，视频就没有画面里（但是声音已经开始播放了），第一个item是图片的话就没有问题，我发现是初次获得的第一个item的viewHolder和论一圈后第一个item后的viewHolder不是同一个对象了，我也尝试更换了视频库（饺子播放器），也还是存在同样的问题

兄弟 我也遇到你这个问题了 请问解决了吗

**Comment by alphater** [comment]
发现不能在外面控制开始播放，直接setUp后，跟着调用startPlayLogic就没问题。我也是看了GSYVideoPlayer的官方demo是写在外面的，但是他的demo没问题，我这么写就有问题。最后写在adapter里就可以正常播放了
