### ISSUE TITLE
一屏多页无限滚动的时候，刷新adapter会显示错乱

### ISSUE THREAD

**Issue by coolfeng168** [youth5201314/banner#1031]

**Comment by coolfeng168** [comment]
banner.setBannerGalleryEffect(10, 12)

**Comment by coolfeng168** [comment]
![image](https://user-images.githubusercontent.com/41280578/118794005-bc2efd00-b8cb-11eb-87c8-82a720e2c247.png)
![image](https://user-images.githubusercontent.com/41280578/118794090-d072fa00-b8cb-11eb-99a9-d11c8fadcec3.png)

**Comment by coolfeng168** [comment]
见上面，第一个是错误的样式，第二个是正确的样式

**Comment by coolfeng168** [comment]
在显示第一个item时，去刷新adapter数据就会出现这种情况

**Comment by youth5201314** [comment]
我测试过了，没有复现你的问题

**Comment by EdwinShadow** [comment]
> banner.setBannerGalleryEffect(10, 12)
> 设置这个方法，刷新adapter，item显示错乱，会重叠

解决了吗 我这刷新也出现 类似的问题  当前的banner会变小
