### ISSUE TITLE
你好我在使用适配设置为头部View是获取不到banner

### ISSUE THREAD

**Issue by BatterMan-Li** [youth5201314/banner#1033]
你好，我使用Android kotlin编写代码的时候，获取banner的View 放入recycler view的头文件中，不管创建实例还是直接加载布局文件的方式都报如下的错误，请问我如何解决？
![image](https://user-images.githubusercontent.com/28614345/119425282-abeaa800-bd39-11eb-8dce-69ce988b1abe.png)

![image](https://user-images.githubusercontent.com/28614345/119425077-472f4d80-bd39-11eb-9f06-bf1114bb42e2.png)

**Comment by Moonkan** [comment]
因为返回值被作者改了，不知道为什么返回值要带上泛型，我这边kotlin也一样，撤回到jcenter仓库下的2.1.0就可以。
![image](https://user-images.githubusercontent.com/26988614/119642024-df6a2700-be4c-11eb-9e0c-9da97f54ddeb.png)

**Comment by youth5201314** [comment]
用2.2.2吧，这个泛型修改是一个使用者提交的，我直接就合并了，现在去掉了

**Comment by lee-mou** [comment]
![image](https://user-images.githubusercontent.com/12655246/120171064-3482b000-c234-11eb-8ca8-07590a7dc728.png)
好像还是一样的

**Comment by youth5201314** [comment]
泛型传参啊，象这样Banner<String, BannerImageAdapter<String>>

**Comment by DaWenXxi** [comment]
可以了 之前2.2.1提示一样的 我就没再试了
