### ISSUE TITLE
版本2.2.2，设置banner_infinite_loop为true，无效果

### ISSUE THREAD

**Issue by gitzgq** [youth5201314/banner#1035]
![image](https://user-images.githubusercontent.com/12247199/119796671-25d28b00-bf0c-11eb-9e30-fe43ea5f784e.png)

**Comment by youth5201314** [comment]
默认都是true，不需要设置的，你说的效果时什么效果，这个参数是设置是否无限轮播的

**Comment by gitzgq** [comment]
调用了destroy()方法之后，就不能无限轮播了

**Comment by gitzgq** [comment]
> 默认都是true，不需要设置的，你说的效果时什么效果，这个参数是设置是否无限轮播的

调用了destroy()方法之后，就不能无限轮播了

**Comment by rookiecai** [comment]
必


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月27日(周四) 下午5:00
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [youth5201314/banner] 版本2.2.2，设置banner_infinite_loop为true，无效果 (#1035)




 
默认都是true，不需要设置的，你说的效果时什么效果，这个参数是设置是否无限轮播的
 
&mdash;

**Comment by gitzgq** [comment]
设置 setBannerGalleryEffect(7, 7);
然后调用notifyDataSetChanged()方法刷新数据时，banner的图片会变小、间距会变大

**Comment by youth5201314** [comment]
你不看文档吗？

**Comment by gitzgq** [comment]
> 你不看文档吗？

额，肯定看了，调用了destroy()方法之后，就不能无限轮播了

**Comment by youth5201314** [comment]
你看了文档就应该知道，destroy（）是配合生命周期使用的，界面都销毁了轮播什么？你轮播时调用销毁方法的目的是什么？
