### ISSUE TITLE
请问在无title的情况下如何设置指示器背景颜色

### ISSUE THREAD

**Issue by is1988** [youth5201314/banner#104]
另外还有个小插曲，十几分钟前我再看大神Banner的几种BannerConfig 发现每次从最后一页循环到第一页的时候，数字和title总有点延迟，结果不小心刷新了一下页面怎么1.4.6成1.4.7了，再一看7分钟前更新，真是厉害了，word 哥，最后就那一个小问题，就是想给指示器加背景，请问如何实现。

**Comment by youth5201314** [comment]
你还是仔细看下demo吧，有例子！
