### ISSUE TITLE
嵌套RecycleView+banner自动上滑问题

### ISSUE THREAD

**Issue by yzhg-ux** [youth5201314/banner#1048]
使用RecycleView多item。banner放置在第一条。往上滑动半个banner的距离。banner滚动时会自动将banner全部显示出来？
请问这是什么原因造成的？怎么解决？

**Comment by zhoudaxia1990** [comment]
有解决吗

**Comment by yzhg-ux** [comment]
？有解决吧。不过我已经忘记啥问题了。加微信yzhg2012320766

发送自 Windows 10 版邮件应用

发件人: zhoudaxia1990
发送时间: 2021年7月13日 9:59
主题: Re: [youth5201314/banner] 嵌套RecycleView+banner自动上滑问题 (#1048)

有解决吗

**Comment by xiaxinqing** [comment]
感觉没解决啊，我也遇到了这个问题

**Comment by gudao20080** [comment]
我也遇到了，我用的是NestedScrollView, 然后ConstraintLayout里面套了banner和RecyclerView, 会自动往上跑

**Comment by Mubly** [comment]
+1

**Comment by ybw486** [comment]
在你的页面上找一个不会滑动的View设置    
android:focusableInTouchMode="true"
android:focusable="true"

**Comment by runfengai** [comment]
+1
