### ISSUE TITLE
最外层用SwipeRefreshLayout布局时，然后直接使用banner,设置高度无效。

### ISSUE THREAD

**Issue by HeQuanLi** [youth5201314/banner#105]
我在最外层用SwipeRefreshLayout布局时，然后直接使用banner,设置高度无效。需要单独的将其包裹在LinearLayout中，我看你是继承的FrameLayout的。当然这问题不严重，只是想少嵌套一层布局。

**Comment by youth5201314** [comment]
eg：
![image](https://cloud.githubusercontent.com/assets/8827239/21601726/2cf6f8de-d1c8-11e6-9af3-5beeddd4c57c.png)
