### ISSUE TITLE
第一个视频和图片混合轮播,轮播暂停不了视频。

### ISSUE THREAD

**Issue by NewDirection** [youth5201314/banner#1051]
轮播到下一个界面拿到的是ImageHolder获取不到之前的VideoHolder，得不到player所以无法停止播放.

**Comment by xhjww** [comment]
同样的问题，望解决

**Comment by chenkexu** [comment]
同样的问题，大佬们怎么解决的？

**Comment by muyuzhang** [comment]
onPageSelected 中  GSYVideoManager.releaseAllVideos();

**Comment by PeanutZhang** [comment]
请问老哥，滑动暂停后，回到视频变成黑屏了，没有视频预览了，这个怎么处理呀

**Comment by NewDirection** [comment]
> 请问老哥，滑动暂停后，回到视频变成黑屏了，没有视频预览了，这个怎么处理呀

你可以设置一个封面，这样回来后还会有封面，不会显示黑屏。

**Comment by HelloWangZhiYong** [comment]
> 轮播到下一个界面拿到的是ImageHolder获取不到之前的VideoHolder，得不到player所以无法停止播放.

可以在获取适配器里的getVHMap方法，视频源一般都放在数据源第一个位置，固定获取getVHMap[0]即可

**Comment by HelloWangZhiYong** [comment]
> 同样的问题，望解决

可以在获取适配器里的getVHMap方法，视频源一般都放在数据源第一个位置，固定获取getVHMap[0]即可

**Comment by HelloWangZhiYong** [comment]
> 同样的问题，大佬们怎么解决的？

可以在获取适配器里的getVHMap方法，视频源一般都放在数据源第一个位置，固定获取getVHMap[0]即可
