### ISSUE TITLE
默认第一个是从最后一个数据开始的

### ISSUE THREAD

**Issue by Quyunshuo** [youth5201314/banner#1056]
默认第一个是从最后一个数据开始的
设置开始位置，没有效果

**Comment by l793854601** [comment]
> 默认第一个是从最后一个数据开始的
> 设置开始位置，没有效果

我也遇到了这个问题，请你你那解决了吗？

**Comment by Iamdyh** [comment]
我也遇到了同样的问题

**Comment by JackliJ** [comment]
你解决这个问题了吗？

**Comment by JackliJ** [comment]
> 默认第一个是从最后一个数据开始的
> 设置开始位置，没有效果

我也是一样的问题 无法定位到第一个

**Comment by Quyunshuo** [comment]
> > 默认第一个是从最后一个数据开始的设置开始位置，没有效果
> 
> 我也是一样的问题，无法定位到第一个
这个问题我是最后使用 `setCurrentItem(int position)` 该方式指定了当前item解决的

**Comment by LeSwp** [comment]
就是banner数据源的问题，直接用banner.setDatas（list）
setStartPosition和setCurrentItem(int position, boolean smoothScroll)就生效了
估计你们使用的是bannerAdapter.setDatas；

**Comment by 333bkz** [comment]
1. 使用 Banner的`banner.setDatas()`,而不是使用Adapter的

2. mStartPosition默认为1，不要修改

**Comment by wannoo1990** [comment]
> 就是banner数据源的问题，直接用banner.setDatas（list） setStartPosition和setCurrentItem(int position, boolean smoothScroll)就生效了 估计你们使用的是bannerAdapter.setDatas；

感谢。
确实是要使用banner.setDatas（list）
