### ISSUE TITLE
有个问题请教一下

### ISSUE THREAD

**Issue by wangguifa** [youth5201314/banner#106]
请问使用CommonTabLayout和com.jcodecraeer.xrecyclerview.XRecyclerView和com.youth.banner.Banner。当三个同时出现时，XRecyclerView下拉刷新就不能用了，当Banner不存在时，刷新就可以使用，请问怎么解决呢？谢谢

**Comment by youth5201314** [comment]
这个是典型的事件冲突好吧，跟banner本身关系不大，最主要的原因是应用场景不同，我无法想象到所有的应用场景，这种情况你处理下事件拦截就行了啊！
