### ISSUE TITLE
kotlin中调用setAdapter提示第一个参数类型为Nothing!

### ISSUE THREAD

**Issue by KenningChen** [youth5201314/banner#1063]

**Comment by wu410830911** [comment]
我也出现了这个情况,  kotlin中banner.setAdapter(ImageAdapter) 提示
Type mismatch.
Required:
Nothing!
Found:
ImageAdapter

**Comment by KenningChen** [comment]
开启viewbinding,   代码里通过binding获取控件设置setAdapter,就不会报这个错了
----- 原始邮件 -----
发件人：wu410830911 ***@***.***>
收件人：youth5201314/banner ***@***.***>
抄送人：KenningChen ***@***.***>,  Author ***@***.***>
主题：Re:_[youth5201314/banner]_kotlin中调用setAdapter提示第一个参数类型为Nothing!_(#1063)
日期：2021年08月11日 15点46分



我也出现了这个情况,  kotlin中banner.setAdapter(ImageAdapter) 提示


Type mismatch.


Required:


Nothing!


Found:


ImageAdapter



&mdash;
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wu410830911** [comment]
我解决了,我是之前用了databinding,直接id.setAdapter(ImageAdapter)会报这个错
因为这个控件本身他是 Banner<*,*> 有两个泛型的
但是不知道是什么原因,以前老的,都不会报错,这个新的就报错了
Required:
Nothing!

Found:
ImageAdapter

最后我是手动初始化
 private lateinit var mBannerView: Banner<BannerBean, ImageAdapter>//把<*,*>里面的泛型规定好
...
mBannerView = findViewById(R.id.banner)
...
mBannerView.setAdapter(ImageAdapter)这样 就不会报Type mismatch.    预期是Nothing  找到的是ImageAdapter了

**Comment by KenningChen** [comment]
ok,解决就好了,我当时都郁闷死了
----- 原始邮件 -----
发件人：wu410830911 ***@***.***>
收件人：youth5201314/banner ***@***.***>
抄送人：KenningChen ***@***.***>,  Author ***@***.***>
主题：Re:_[youth5201314/banner]_kotlin中调用setAdapter提示第一个参数类型为Nothing!_(#1063)
日期：2021年08月12日 17点44分



我解决了,我是之前用了databinding,直接id.setAdapter(ImageAdapter)会报这个错


因为这个控件本身他是 Banner<,> 有两个泛型的


但是不知道是什么原因,以前老的,都不会报错,这个新的就报错了


Required:


Nothing!

Found:


ImageAdapter

最后我是手动初始化


private lateinit var mBannerView: Banner<BannerBean, ImageAdapter>//把<,>里面的泛型规定好


...


mBannerView = findViewById(R.id.banner)


...


mBannerView.setAdapter(ImageAdapter)这样 就不会报Type mismatch.    预期是Nothing  找到的是ImageAdapter了



&mdash;
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
