### ISSUE TITLE
在fragment中onCreateView使用addBannerLifecycleObserver会导致一次滚动2张图

### ISSUE THREAD

**Issue by hebing0305** [youth5201314/banner#1064]
猜测是开启了多个线程

**Comment by hebing0305** [comment]
应该多多次调用start方法原因 start方法线程不安全

**Comment by kavin-tian** [comment]
banner.stop(); //1.先停止轮播
 //等banner.mLoopTask 执行完 再添加生命周期监听
  banner.postDelayed(new Runnable() {
      @Override
      public void run() {
          banner.addBannerLifecycleObserver(LoginActivity.this);
      }
  }, BannerConfig.LOOP_TIME);
