### ISSUE TITLE
一个不太确定的冲突问题

### ISSUE THREAD

**Issue by wp549741214** [youth5201314/banner#1065]
在CoordinatorLayout的appbarlayout中引用了 banner库
CoordinatorLayout->AppBarLayout->LinearLayout->RelativeLayout->com.youth.banner.Banner
结构如上，banner位于 需要吸顶的TabLayout上方，在屏幕滚动到TabLayout吸顶之前，banner为可见状态时候，滑动屏幕会有抖动的情况发生，不确定是不是冲突所致。

**Comment by zhaobinsir** [comment]
+1

**Comment by zhaobinsir** [comment]
> 在CoordinatorLayout的appbarlayout中引用了 banner库 CoordinatorLayout->AppBarLayout->LinearLayout->RelativeLayout->com.youth.banner.Banner 结构如上，banner位于 需要吸顶的TabLayout上方，在屏幕滚动到TabLayout吸顶之前，banner为可见状态时候，滑动屏幕会有抖动的情况发生，不确定是不是冲突所致。

看最新问题 已经解决了
