### ISSUE TITLE
请问 有kotilin 版本吗    

### ISSUE THREAD

**Issue by LockeyWu** [youth5201314/banner#1068]
用当前版本转kotilin 会报错 特别适配器 adapter

**Comment by Smilefanlei** [comment]
val mAdapter = HomeBannerAdapter(
            mutableListOf(
                "https://img0.baidu.com/it/u=2806557270,1987133584&fm=26&fmt=auto&gp=0.jpg",
                "https://img2.baidu.com/it/u=1277094641,3005941665&fm=26&fmt=auto&gp=0.jpg"
            )
        )
        mBanner.adapter = mAdapter
        mBanner.addBannerLifecycleObserver(this)
            .setIndicator(CircleIndicator(this))
        mAdapter.notifyDataSetChanged()

**Comment by Smilefanlei** [comment]
> ```
>            用当前版本转kotilin 会报错 特别适配器 adapter                 
> ```

val mAdapter = HomeBannerAdapter(
            mutableListOf(
                "https://img0.baidu.com/it/u=2806557270,1987133584&fm=26&fmt=auto&gp=0.jpg",
                "https://img2.baidu.com/it/u=1277094641,3005941665&fm=26&fmt=auto&gp=0.jpg"
            )
        )
        mBanner.adapter = mAdapter
        mBanner.addBannerLifecycleObserver(this)
            .setIndicator(CircleIndicator(this))
        mAdapter.notifyDataSetChanged()
