### ISSUE TITLE
下载了，但是运行不起来，怎么才能运行起来

### ISSUE THREAD

**Issue by gudao20080** [youth5201314/banner#1074]

**Comment by QXH313** [comment]
我也是

**Comment by QXH313** [comment]
@youth5201314 大佬，必须添加这个账号吗？

![image](https://user-images.githubusercontent.com/20204169/132296511-1adc67e5-280e-404e-b333-ae9631a36186.png)

**Comment by youth5201314** [comment]
把这些配置全部删除就行了，这是上传仓库的配置

**Comment by QXH313** [comment]
@youth5201314 好的谢谢～已经运行起来了～
