### ISSUE TITLE
1.4.8只有一张图片时，点击事件触发问题

### ISSUE THREAD

**Issue by SmallDream** [youth5201314/banner#108]
当前版本1.4.8, 当banner里只有一张图片时，一般的action_down-> move->up也会触发点击事件

**Comment by youth5201314** [comment]
个人认为这个不算bug，首先一张时，我们的移动操作是多此一举的，其次ACTION_DOWN-》ACTION_MOVE-》ACTION_CANCEL这样的移动操作才不会触发事件，你说的按下移动再抬起我觉得没有必要，只有一张图片的时候你去触碰图片难道不是为了点击吗？就为了移动一下有必要吗？不过感谢你的意见，也许和你的观点不太一样，可以继续沟通！

**Comment by wyj365372704** [comment]
> 个人认为这个不算bug，首先一张时，我们的移动操作是多此一举的，其次ACTION_DOWN-》ACTION_MOVE-》ACTION_CANCEL这样的移动操作才不会触发事件，你说的按下移动再抬起我觉得没有必要，只有一张图片的时候你去触碰图片难道不是为了点击吗？就为了移动一下有必要吗？不过感谢你的意见，也许和你的观点不太一样，可以继续沟通！

我个人不这么认为。“件，你说的按下移动再抬起我觉得没有必要，只有一张图片的时候你去触碰图片难道不是为了点击吗？就为了移动一下有必要吗？”  站在APP角度确实没有必要，但是站在用户角度，这就是一张图片，我想去点击它，触发点击事件，而在这张图片上手指滑动一下，并不是去点击它，就像一张纯粹的ImageView一样，在上面滑动并不会触发点击事件，用户不关心它到底是一个Viewpager里面的图片。
