### ISSUE TITLE
请教，不同尺寸item下banner_example2.gif的效果，即每一个viewPager是不同尺寸的，但是两边又都要留出前后page的边框出来

### ISSUE THREAD

**Issue by iceskyang** [youth5201314/banner#1081]
https://github.com/youth5201314/banner/blob/master/images/banner_example2.gif

**Comment by yorkshenpolestar** [comment]
<img width="818" alt="image" src="https://user-images.githubusercontent.com/18043540/191668958-af2a5c0d-0041-4df9-8c77-553f4568f58b.png">
