### ISSUE TITLE
1.4.8只有一张图片时，外层的viewpager无法滑动翻页

### ISSUE THREAD

**Issue by SmallDream** [youth5201314/banner#109]
目前结构是viewpager下某个page的recylerview的header放了banner, 当banner只有一张图片时，左右滑动无法使外层的viewpager滑动翻页

**Comment by youth5201314** [comment]
这是专门这么设置的，一张图片你滑动个啥啊！有什么可以滑动的必要？

**Comment by SmallDream** [comment]
一张图片的时候banner不需要滑动，所以这时候该banner所处的父viewpager需要滑动。
