### ISSUE TITLE
destroy 忘记注销mAdapterDataObserver

### ISSUE THREAD

**Issue by huekeyu** [youth5201314/banner#1091]
设置adapter有调用registerAdapterDataObserver注册，但是在destroy没有调用unregisterAdapterDataObserver注销，用leakcanary会检测出内存泄漏的

**Comment by huekeyu** [comment]
> 用的版本是banner:2.1.0，设置adapter有调用registerAdapterDataObserver注册，但是在destroy没有调用unregisterAdapterDataObserver注销，用leakcanary会检测出内存泄漏的，这个我在fragment里发现的

**Comment by micdzm** [comment]
/**
     * 设置banner的适配器
     */
    public Banner setAdapter(BA adapter) {
        if (adapter == null) {
            throw new NullPointerException(getContext().getString(R.string.banner_adapter_null_error));
        }
        this.mAdapter = adapter;
        if (!isInfiniteLoop()) {
            getAdapter().setIncreaseCount(0);
        }
        getAdapter().registerAdapterDataObserver(mAdapterDataObserver);
        mViewPager2.setAdapter(adapter);
        setCurrentItem(mStartPosition, false);
        initIndicator();
        return this;
    }

getAdapter().registerAdapterDataObserver(mAdapterDataObserver); 当Fragment实例未销毁，只是把视图销毁了，这段代码代码导致内存泄漏，使用的是2.2.3版本，问题到至今还未修复
