### ISSUE TITLE
setCurrentItem会出现闪烁，并且滑动顺序错乱，见视频

### ISSUE THREAD

**Issue by yecaler** [youth5201314/banner#1095]
代码如下：
ivBanner.setAdapter(new SutraTopAdapter(images));
                    ivBanner.setCurrentItem(0, false);
                    ivBanner.isAutoLoop(false);
                    ivBanner.setUserInputEnabled(false);
                    ivBanner.start();
在viewpager滑动选中中设置：ivBanner.setCurrentItem(index);
结果从0切换到1的时候会闪一下，然后从3滑动到1.
如何解决？

**Comment by yecaler** [comment]
https://user-images.githubusercontent.com/25024969/139520714-063d0098-9a9e-4a18-aeb8-4f1741050494.mp4

**Comment by yecaler** [comment]
@youth5201314

**Comment by yecaler** [comment]
大佬帮忙瞅瞅

**Comment by LeSwp** [comment]
取消滚动动画

**Comment by li-xiaojun** [comment]
+1

**Comment by LXLYHM** [comment]
> 取消滚动动画

请问要怎么取消动画？
