### ISSUE TITLE
自动轮播的的时候，视图有明显伸拉了一下

### ISSUE THREAD

**Issue by zyxyuanxiao** [youth5201314/banner#11]
自动轮播的的时候 重新回到的第一个的时候，视图有明显伸拉了一下，有闪动····不知道别人会不会出现这情况·····

**Comment by zyxyuanxiao** [comment]
发现是这种缩放模式引起的
iv.setScaleType(ScaleType.CENTER_CROP);

**Comment by youth5201314** [comment]
好的，等会儿我看下，如果有问题下次一起更新。谢谢你的支持。

**Comment by youth5201314** [comment]
iv.setScaleType(ScaleType.CENTER_CROP);设置这个，是为了能图片填满整个imageview，测试没有发现你说的问题，不过可能是手机原因，我还是把它去掉了，加上了glide的centerCrop()方法，应该就不出现你说的问题了。下次版本一起提交。

**Comment by zhangchaoxu** [comment]
我用nexus 6测试，在1.1.9版本中，图片高度明显被拉伸了。回滚到1.1.7，显示正常。

**Comment by youth5201314** [comment]
用1.2.0版本

**Comment by zhangchaoxu** [comment]
v1.2.0 工作正常，Thanks
