### ISSUE TITLE
跟AppBarLayout一起用的时候，手指左右滑动不灵敏，有时候划不动

### ISSUE THREAD

**Issue by y1670323532** [youth5201314/banner#1105]
布局CoordinatorLayout->AppBarLayout->CollapsingToolbarLayout->FrameLayout->Banner，设置了setIntercept(false)

**Comment by y1670323532** [comment]
demo里面也有这个问题

**Comment by Lanzi-is** [comment]
我也有这个问题，我是scrollview里放了banner，滑动下一张滑不动，但是滑动上一张又很流畅

**Comment by duaiyun1314** [comment]
> demo里面也有这个问题

兄弟，这个问题解决了吗
