### ISSUE TITLE
Banner在setAdapter的时候,在kotlin 中直接强转失败

### ISSUE THREAD

**Issue by lv823063712** [youth5201314/banner#1106]
如题
banner.setAdapter(imageAdapter as Nothing?),这个写法报错cannot be cast to java.lang.Void,

**Comment by lv823063712** [comment]
看到demo的解决方案了,感觉在kotlin中还是不太友好

**Comment by jiaojiaozhe123456** [comment]
你是怎么做的？

**Comment by lv823063712** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        class HomeFragment : BaseFragment() {    var imageUrls = listOf(        "http://www.zhaoapi.cn//images//quarter//ad1.png",        "http://www.zhaoapi.cn//images//quarter//ad2.png",        "http://www.zhaoapi.cn//images//quarter//ad3.png",        "http://www.zhaoapi.cn//images//quarter//ad4.png"    )    override fun getLayout(): Int =R.layout.fragment_home    override fun initView() {//        var imageAdapter = ImageAdapter(ImageDataBean.getTestData())        var banner = (home_banner as Banner<String, ImageAdapter>)        banner.apply {            ***@***.***)            setBannerRound(20f)            setBannerGalleryEffect(20,10)            setIndicator(RoundLinesIndicator(mActivity))            setAdapter(ImageAdapter(imageUrls))        }    }    override fun initData() {    }}
            
        
    
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
    
        签名由网易邮箱大师定制
    
 

    在2022年1月4日 ***@***.***> 写道： 




你是怎么做的？

**Comment by lv823063712** [comment]
> 你是怎么做的？

你看着写写吧,我大概也是参考的作者的demo
`var banner = (home_banner as Banner<String, ImageAdapter>)
        banner.apply {
            addBannerLifecycleObserver(this@HomeFragment)
            setBannerRound(20f)
            setBannerGalleryEffect(20,10)
            setIndicator(RoundLinesIndicator(mActivity))
            setAdapter(ImageAdapter(imageUrls))

        }`

**Comment by jiaojiaozhe123456** [comment]
Indicator我需要自定义，位置要放在图片下面，banner的展示我打算用Java 写fragment了

**Comment by jiaojiaozhe123456** [comment]
setIndicator(numIndicator,false)在xml里面自定义了指示器，后面那个参数要设置为false，就可以了，不需要用Java再写个fragment了

**Comment by SaltedFish-Extreme** [comment]
#1130 我刚才没事写了个类似帮助文档的😂

**Comment by androidjanuary** [comment]
点击事件怎么写的

**Comment by SaltedFish-Extreme** [comment]
> 点击事件怎么写的

有个setOnBannerListener回调啊，在adapter里写，或者在外面写都行

**Comment by androidjanuary** [comment]
> > 点击事件怎么写的
> 
> 有个setOnBannerListener回调啊，在adapter里写，或者在外面写都行

een  看到了  谢谢
