### ISSUE TITLE
声明的Banner提示泛型有问题，Raw use of parameterized class 'Banner'

### ISSUE THREAD

**Issue by TruthOFT** [youth5201314/banner#1116]
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        banner = findViewById(R.id.myBanner);
        banner.addBannerLifecycleObserver(this)
                .setAdapter(new LooperAdapter(Data.getImgUrlList())).setIndicator(new CircleIndicator(this));
    }

这是我写的代码，他提示我泛型有问题，但是我不知道怎么去解决

**Comment by SaltedFish-Extreme** [comment]
嘿，我昨天也遇到了这个问题，作者的demo里有用法，我是用kotlin做的  

private lateinit var banner: Banner<String,BannerImageAdapter<String>>  
泛型里第一个传需要加载的资源类型，第二个传一个Adapter，我用的默认的

**Comment by Eobard-Thawne** [comment]
好嘞，了解了，谢谢
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "youth5201314/banner"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月28日(星期二) 下午2:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [youth5201314/banner] 声明的Banner提示泛型有问题，Raw use of parameterized class 'Banner' (Issue #1116)





 
嘿，我昨天也遇到了这个问题，作者的demo里有用法，我是用kotlin做的
 
private lateinit var banner: Banner<String,BannerImageAdapter&gt;
 
泛型里第一个传需要加载的资源类型，第二个传一个Adapter，我用的默认的

**Comment by SaltedFish-Extreme** [comment]
#1130 我刚才没事写了个类似帮助文档的😂
