### ISSUE TITLE
为什么这样使用不行

### ISSUE THREAD

**Issue by fearlesstrek** [youth5201314/banner#113]
List<String> stringList = new ArrayList<>();
                for (int i = 0; i < 5; i++) {
                    stringList.add("http://cdn-qn0.jianshu.io/assets/web/new-hot-3778ba94e7a0bd97f034c5ed28972a6d.png");
                }
                if (ValidateUtils.isValidate(stringList)) {
                    banner.setVisibility(View.VISIBLE);
                    banner.setImageLoader(new FrescoImageLoader());
                    //设置图片集合
                    banner.setImages(stringList);
                    //设置轮播时间
                    banner.setDelayTime(1500);
                    //设置自动轮播，默认为true
                    banner.isAutoPlay(true);
                    //不显示指示器和标题
                    banner.setBannerStyle(BannerConfig.NOT_INDICATOR);
                    banner.start();
                } else {
                    banner.setVisibility(View.GONE);
                }

而且我的FrescoImageLoader是：
**public class FrescoImageLoader extends ImageLoader {
    @Override
    public void displayImage(Context context, Object path, ImageView imageView) {
        //用fresco加载图片简单用法，记得要写下面的createImageView方法
        Uri uri = Uri.parse((String) path);
        imageView.setImageURI(uri);
    }
    //提供createImageView 方法，如果不用可以不重写这个方法，主要是方便自定义ImageView的创建
    @Override
    public ImageView createImageView(Context context) {
        //使用fresco，需要创建它提供的ImageView，当然你也可以用自己自定义的具有图片加载功能的ImageView
        SimpleDraweeView simpleDraweeView=new SimpleDraweeView(context);
        return simpleDraweeView;
    }
}**

**Comment by MIkeeJY** [comment]
fresco加载没问题的 请确定你加载的banner url 是否可用

**Comment by fearlesstrek** [comment]
@MIkeeJY 我使用的图片太大了，banner要加一个适配的属性image_scale_type
