### ISSUE TITLE
一页显示大于三个的功能还会加上吗？

### ISSUE THREAD

**Issue by loren325** [youth5201314/banner#1146]

**Comment by 541205249** [comment]
同问

**Comment by miantiaox** [comment]
同求

**Comment by ssz001** [comment]
val recyclerView = mBanner.viewPager2.getChildAt(0) as RecyclerView
        val padding: Int = R.dimen.qb_px_121.toXmlDimen().toInt()
        recyclerView.setPadding(padding,0,padding,0)
        recyclerView.clipToPadding = false
        
   public class ThreePageTransformer extends BasePageTransformer {

    private static final float DEFAULT_MIN_SCALE = 0.85f;
    private static final float DEFAULT_MIN_ALPHA = 0.5f;
    private float mMinScale = DEFAULT_MIN_SCALE;
    private float mMinAlpha = DEFAULT_MIN_ALPHA;

    public ThreePageTransformer() {
    }

    public ThreePageTransformer(float minScale) {
        this.mMinScale = minScale;
    }

    public ThreePageTransformer(float minScale, float minAlpha) {
        this.mMinScale = minScale;
        this.mMinAlpha = minAlpha;
    }

    public void transformPage(@NonNull View view, float position) {
        if (position < -1) {
            position = -1;
        }
        if (position > 1) {
            position = 1;
        }
        float scaleFactor = mMinScale + (1f - mMinScale) * (1f - Math.abs(position));
        view.setScaleX(scaleFactor);
        view.setScaleY(scaleFactor);
    }
}

在此基础上修改修改就好了，不用谢
