### ISSUE TITLE
画廊效果刷新数据后中间Item大小发生变化

### ISSUE THREAD

**Issue by feiyue0116** [youth5201314/banner#1149]
getBinding().banner.setBannerGalleryEffect(11, 11, 23);

将item 滑动至第二个

在onResume 调用adapter.notifyDataSetChanged();
按home 退至系统页面
再按应用图标返回页面    中间Item变小   后一个item 变大
期待效果   每个item大小不变  与退至系统桌面前一样

**Comment by li-xiaojun** [comment]
+1

**Comment by pecpwee** [comment]
> 解决方法，在画廊模式之下，调用setData，之后post一条Viewpager2.requestTransform(),准备提交mr请求，希望作者采纳

我试了下这个方案可以解决问题，但是会造成页面整体闪动一下
我的方式是不调用notifyDataSetChanged， 而是依次调用notifyItemChanged更新，这样更新就不会丢失画廊效果
