### ISSUE TITLE
banner第一次启动往右边滑动失效，必须左滑一下或者等自动滑动后才能右滑

### ISSUE THREAD

**Issue by Hopkin2016** [youth5201314/banner#1153]

**Comment by Chensp171254** [comment]
我遇到了类似的问题，我经过大量测试发现是由于在Banner的适配器布局里面使用了RecyclerView导致的，但是产生的现象很奇怪，往左滑是完全没有问题的，往右滑会发现失去了滑动惯性，松开手指后总是弹回原位置。
