### ISSUE TITLE
kotlin版本点击事件一直提示nothing,强转了之后 运行报错  大佬

### ISSUE THREAD

**Issue by 93daxiong** [youth5201314/banner#1159]

**Comment by xue1301117865** [comment]
我也遇到了这个问题，Kotlin提示类型不匹配，需要的是nothing
![image](https://user-images.githubusercontent.com/22724539/182404235-0b73fcc0-5c0d-4a9f-814a-1bfacdc5ad09.png)

**Comment by sunnnydaydev** [comment]
这个可参考作者提供的kt demo写法：
https://github.com/youth5201314/banner/tree/master/usekotlin/src/main/java/com/spring/usekotlin
