### ISSUE TITLE
这个框架只能加载图片不能加载视频吗？

### ISSUE THREAD

**Issue by yyy000112** [youth5201314/banner#116]
这个框架只能加载图片不能加载视频吗？

**Comment by youth5201314** [comment]
恩

**Comment by ufbeans** [comment]
我这边也是需要加载视频。我觉得这个banner写的很好。只需要稍作修改就能支持视频播放了。
这个加载图片的这个interface中把createImageView修改成带对象的。这样我就能加载自己的视频view
> public interface ImageLoaderInterface<T extends View> extends Serializable {

    void displayImage(Context context, Object path, T imageView);

    T createImageView(Context context, Object path);
}
