### ISSUE TITLE
开启了无限循环的话，监听点击时间，返回的position不对，然后setCurrentItem()会错乱

### ISSUE THREAD

**Issue by CordyHo** [youth5201314/banner#1166]

**Comment by ilovexy2tom** [comment]
我也遇到了，暂时只能关闭无限循环和自动轮播
作者应该不是用的builder模式
所以对设置的步骤有要求
看看demo按照demo的步骤来一遍吧

**Comment by ilovexy2tom** [comment]
今天又调试了一波，代码给你分享

xml
` 
<com.youth.banner.Banner
                        android:id="@+id/banner"
                        app:banner_auto_loop="true"
                        android:layout_width="match_parent"
                        android:layout_height="270pt"
                        app:banner_indicator_height="4pt"
                        app:banner_indicator_normal_color="#AAffffff"
                        app:banner_indicator_normal_width="4pt"
                        app:banner_indicator_selected_width="4pt"
                        app:banner_indicator_radius="10pt"
                        app:banner_indicator_selected_color="@color/button_color" />
`

kotlin

`  
//init
banner.indicator = RectangleIndicator(this)
banner.addBannerLifecycleObserver(this)
//setData

 (banner as Banner<UserCover, UserCoverBannerAdapter>)
            .setAdapter(UserCoverBannerAdapter(list, onItemClick = {
            XPopup.Builder(this@UserDetailActivity).asCustom(showBannerPopoup(this@UserDetailActivity, list,it)).show()
        }))
`
