### ISSUE TITLE
运行效果图3是哪个方法设置的，有大佬知道不

### ISSUE THREAD

**Issue by huangShan-gitHub** [youth5201314/banner#1167]
运行效果图3是哪个方法设置的，有大佬知道不，我把设置都是试过了，没有看到这个效果。

**Comment by huangShan-gitHub** [comment]
求回复，在线等......本人实在是菜看不懂，然后demo下载的话运行不起来也没发对照代码效果看。

**Comment by zhengfa365** [comment]
setBannerGalleryMZ(int,float) ，魅族效果
