### ISSUE TITLE
能否增加一个属性，让其不进行轮播啊！

### ISSUE THREAD

**Issue by HeQuanLi** [youth5201314/banner#117]
能否增加一个属性，让其不进行轮播啊！当我滑动到最后一个的时候，就不要在回到第一个去了。用于splash界面啊。弄一个开关嘛！

**Comment by BigTimo** [comment]
同问+1

**Comment by aesion** [comment]
同

**Comment by aesion** [comment]
@youth5201314

**Comment by kurong00** [comment]
xml文件里 app:is_auto_play="false"
设置成false

**Comment by luffykou** [comment]
想要设置不自动轮播：

- 在XML文件中配置：`app:is_auto_play="false"`

- 或者在代码中设置：`banner.isAutoPlay(false);//注意这个必须配置在banner.start();之前`
