### ISSUE TITLE
设置完 adapter之后，然后请求网络 用setDatas 加载数据 更新banner，banner 加载数据的时候 会默认选择最后一页

### ISSUE THREAD

**Issue by wangxiongtao** [youth5201314/banner#1170]
//使用自定义适配器，更多api方法自己尝试
        val adapter=ImageAdapter(ArrayList())
        var banner2 = (bannerLayout2 as Banner<String, ImageAdapter>)
        banner2.apply {
            addBannerLifecycleObserver(this@MainActivity)
            setBannerRound(20f)
            setIndicator(RoundLinesIndicator(this@MainActivity))
            setAdapter(adapter)
        }
        Handler(Looper.getMainLooper()).postDelayed({
           adapter.setDatas(imageUrls)
        },2000)

使用demo的例子 模拟延迟更新banner  ，会默认选中最后一页 ，期望是从第一页数据 开始轮询

**Comment by wangxiongtao** [comment]
经过测试，使用banner的setDatas方法 正常从第一页显示，adapter的setDatas方法 是从最后一页显示。。。。

**Comment by CruelLei** [comment]
> 
兄弟  我也遇到这个问题了  请问你解决了吗

**Comment by yulizi** [comment]
掉毛误导掉毛，直接用Banner的setDatas而不是用Adapter的setDatas就可以，搞了半天，每一个好心人告知方法，鄙视你们这些知道却不说的掉毛

**Comment by android-xiao-jun** [comment]
banner.setCurrentItem(banner.getStartPosition(), false);
这么写也能解决问题,  @yulizi

**Comment by TKLL** [comment]
如果这个banner是recycleview里的一个模块，那上面的方法也不起作用，必须在setAdapter或者setDatas之前设置currentItem = 0才能正常显示
