### ISSUE TITLE
大佬，请问这种banner效果咋实现啊

### ISSUE THREAD

**Issue by lujun525** [youth5201314/banner#1172]
![Screenshot_20221014_154539](https://user-images.githubusercontent.com/13325765/195792045-8ce75b98-caa8-4f3b-931c-21ebfb2ce20e.jpg)

**Comment by HotmilKz** [comment]
+1

**Comment by billdizl** [comment]
画廊效果  好实现

**Comment by lujun525** [comment]
咋搞啊，要跟下面联动，而且每次只能滑动一页

**Comment by payne1107** [comment]
+1 怎么实现啊  有大佬知道吗
