### ISSUE TITLE
魅族效果，不显示圆角

### ISSUE THREAD

**Issue by Staticzll** [youth5201314/banner#1188]
<ImageView xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/iv_banner"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:scaleType="centerCrop" />

 Glide.with(this)
                    .load(it[position].idRes)
                    .apply(options)
                    .into(this)

banner.setBannerGalleryMZ(160)

魅族效果，不显示圆角

**Comment by Staticzll** [comment]
imageview  用了android:scaleType="centerCrop"

**Comment by HeyBean-X** [comment]
最后有解决吗？ 大佬

**Comment by taotaodai** [comment]
android:scaleType="centerCrop"不显示圆角。用CardView可以解决。

**Comment by Zhiqing-Gong** [comment]
@taotaodai 还得是你啊！！！
