### ISSUE TITLE
ScaleInTransformer类在阿拉伯语这种左右结构颠倒的情况下，不会有画廊效果

### ISSUE THREAD

**Issue by Dingzx9527** [youth5201314/banner#1192]

**Comment by Dingzx9527** [comment]
public class ScaleInTransformer extends BasePageTransformer {
    private static final float DEFAULT_mMinScale = 0.85f;
    private float mMinScale = DEFAULT_mMinScale;

    public ScaleInTransformer() {
    }

    public ScaleInTransformer(float minScale) {
        this.mMinScale = minScale;
    }

    @Override
    public void transformPage(@NonNull View view, float position) {
        int pageWidth = view.getWidth();
        int pageHeight = view.getHeight();
        view.setPivotY(pageHeight / 2);
        view.setPivotX(pageWidth / 2);
        if (position < -1) {
            // [-Infinity,-1)
            // This page is way off-screen to the left.
            view.setScaleX(mMinScale);
            view.setScaleY(mMinScale);
            view.setPivotX(!BannerUtils.isRTL() ? pageWidth : 0);
            Log.d("transformPage", "[-Infinity,-1)  position=" + position);
        } else if (position <= 1) { // [-1,1]
            // Modify the default slide transition to shrink the page as well

            if (position < 0) {
                //1-2:1[0,-1] ;2-1:1[-1,0]
                float scaleFactor = (1 + position) * (1 - mMinScale) + mMinScale;
                view.setScaleX(scaleFactor);
                view.setScaleY(scaleFactor);

                view.setPivotX(pageWidth * (DEFAULT_CENTER + (DEFAULT_CENTER * (!BannerUtils.isRTL() ? -position : position))));
                Log.d("transformPage", "[-1,0)  position=" + position);
            } else {
                //1-2:2[1,0] ;2-1:2[0,1]
                float scaleFactor = (1 - position) * (1 - mMinScale) + mMinScale;
                view.setScaleX(scaleFactor);
                view.setScaleY(scaleFactor);
                view.setPivotX(pageWidth * (!BannerUtils.isRTL() ? (1 - position) : (1 + position) * DEFAULT_CENTER));
                Log.d("transformPage", "[0,1]  position=" + position);
            }
        } else {
            // (1,+Infinity]
            view.setPivotX(!BannerUtils.isRTL() ? 0 : pageWidth);
            view.setScaleX(mMinScale);
            view.setScaleY(mMinScale);
            Log.d("transformPage", "(1,+Infinity]  position=" + position);
        }
    }

**Comment by Dingzx9527** [comment]
上面的代码已经帮你解决了，希望你们能更新一下，让更多的小伙伴不踩坑

**Comment by yallachat** [comment]
阿拉伯语时，ScaleInTransformer ：transformPage方法中设置position=-position就可以了。
