### ISSUE TITLE
我想让第一个图片变大，不是中间的变大，应该怎么实现，能不能告知下，跪求 就是把第二张图片的效果放到第一张展示

### ISSUE THREAD

**Issue by payne1107** [youth5201314/banner#1196]
我想让第一个图片变大，不是中间的变大，应该怎么实现，能不能告知下，跪求

**Comment by payne1107** [comment]
画廊的那个效果

**Comment by payne1107** [comment]
![f6c85391368c962cde45b88dea49fd5](https://github.com/youth5201314/banner/assets/22141101/8af4d2d8-68b4-46ab-a5a8-76727ef2a30b)
我想实现这种第一张图是大的，但用画廊实现这个效果，这个第二个图和第三个图间距太大了 怎么能改成和第一个和第二个一样大间距啊，感觉！

**Comment by zhangxu2814** [comment]
找到方案了吗？最近也在做这种效果

**Comment by chen3441251** [comment]
> ![f6c85391368c962cde45b88dea49fd5](https://github.com/youth5201314/banner/assets/22141101/8af4d2d8-68b4-46ab-a5a8-76727ef2a30b) 我想实现这种第一张图是大的，但用画廊实现这个效果，这个第二个图和第三个图间距太大了 怎么能改成和第一个和第二个一样大间距啊，感觉！

您好怎么处理的，我有类似的需求

**Comment by zhangxu2814** [comment]
> > ![f6c85391368c962cde45b88dea49fd5](https://github.com/youth5201314/banner/assets/22141101/8af4d2d8-68b4-46ab-a5a8-76727ef2a30b) 我想实现这种第一张图是大的，但用画廊实现这个效果，这个第二个图和第三个图间距太大了 怎么能改成和第一个和第二个一样大间距啊，感觉！
> 
> 您好怎么处理的，我有类似的需求

去扒 洋钱罐借款 App首页的源码

**Comment by chen3441251** [comment]
> 找到方案了吗？最近也在做这种效果



> > > ![f6c85391368c962cde45b88dea49fd5](https://github.com/youth5201314/banner/assets/22141101/8af4d2d8-68b4-46ab-a5a8-76727ef2a30b) 我想实现这种第一张图是大的，但用画廊实现这个效果，这个第二个图和第三个图间距太大了 怎么能改成和第一个和第二个一样大间距啊，感觉！
> > 
> > 
> > 您好怎么处理的，我有类似的需求
> 
> 去扒 洋钱罐借款 App首页的源码

这么狠，洋钱罐是你做的吗

**Comment by zhangxu2814** [comment]
https://github.com/user-attachments/assets/9cd75106-0e73-4ec8-9888-d6fd3ad551a6

> > 找到方案了吗？最近也在做这种效果
> 
> > > > ![f6c85391368c962cde45b88dea49fd5](https://github.com/youth5201314/banner/assets/22141101/8af4d2d8-68b4-46ab-a5a8-76727ef2a30b) 我想实现这种第一张图是大的，但用画廊实现这个效果，这个第二个图和第三个图间距太大了 怎么能改成和第一个和第二个一样大间距啊，感觉！
> > > 
> > > 
> > > 您好怎么处理的，我有类似的需求
> > 
> > 
> > 去扒 洋钱罐借款 App首页的源码
> 
> 这么狠，洋钱罐是你做的吗

https://github.com/user-attachments/assets/86f08368-ed6a-4b2d-9f79-59c12d1d694d 抄就是

**Comment by chen3441251** [comment]
> 3f0435093d3ad79f471c0ba6e5914a0e.mp4 
> > > 找到方案了吗？最近也在做这种效果
> > 
> > 
> > > > > ![f6c85391368c962cde45b88dea49fd5](https://github.com/youth5201314/banner/assets/22141101/8af4d2d8-68b4-46ab-a5a8-76727ef2a30b) 我想实现这种第一张图是大的，但用画廊实现这个效果，这个第二个图和第三个图间距太大了 怎么能改成和第一个和第二个一样大间距啊，感觉！
> > > > 
> > > > 
> > > > 您好怎么处理的，我有类似的需求
> > > 
> > > 
> > > 去扒 洋钱罐借款 App首页的源码
> > 
> > 
> > 这么狠，洋钱罐是你做的吗
> 
> https://github.com/user-attachments/assets/86f08368-ed6a-4b2d-9f79-59c12d1d694d 抄就是

你的demo 源码不能开源一下吗

**Comment by chen3441251** [comment]
> 3f0435093d3ad79f471c0ba6e5914a0e.mp4 
> > > 找到方案了吗？最近也在做这种效果
> > 
> > 
> > > > > ![f6c85391368c962cde45b88dea49fd5](https://github.com/youth5201314/banner/assets/22141101/8af4d2d8-68b4-46ab-a5a8-76727ef2a30b) 我想实现这种第一张图是大的，但用画廊实现这个效果，这个第二个图和第三个图间距太大了 怎么能改成和第一个和第二个一样大间距啊，感觉！
> > > > 
> > > > 
> > > > 您好怎么处理的，我有类似的需求
> > > 
> > > 
> > > 去扒 洋钱罐借款 App首页的源码
> > 
> > 
> > 这么狠，洋钱罐是你做的吗
> 
> https://github.com/user-attachments/assets/86f08368-ed6a-4b2d-9f79-59c12d1d694d 抄就是

你的录屏效果比洋钱罐的要流畅许多啊，我扒了一下是一个自定义BannerView，里面的都是混淆过的，看不懂，你的代码能分享一下吗
