### ISSUE TITLE
图片不显示（只是改了demo的一句代码）

### ISSUE THREAD

**Issue by sunkeding** [youth5201314/banner#123]
我图片url的集合是这样写的：
   urllist = new ArrayList<String>();
        urllist.add("ww4.sinaimg.cn/large/006uZZy8jw1faic1xjab4j30ci08cjrv.jpg");
        urllist.add("ww4.sinaimg.cn/large/006uZZy8jw1faic21363tj30ci08ct96.jpg");

        banner1.setImages(urllist)
                .setImageLoader(new GlideImageLoader())
                .start();
这种情况下就不显示图片了。
DEMO原先的代码：
       banner2.setImages(App.images)
                .setImageLoader(new GlideImageLoader())
                .start();
这样写是可以显示的，非常奇怪

**Comment by youth5201314** [comment]
请加上------>  http://

**Comment by sunkeding** [comment]
哦哦，我去，犯了个低级错误，因为不加前缀，chrom浏览器正好也能显示，尴尬
