### ISSUE TITLE
如何动态设置轮播图的大小，根据网络图片的宽高比来动态设置；宽是必满屏，高要根据手机动态设置

### ISSUE THREAD

**Issue by sunkeding** [youth5201314/banner#125]
public class UILImageLoader extends ImageLoader {

    private DisplayImageOptions options;

    @Override
    public void displayImage(final Context context, Object path, final ImageView imageView) {
        options = new DisplayImageOptions.Builder()
                .showImageOnLoading(R.drawable.zhanw)
                .cacheInMemory(true)// 设置下载的图片是否缓存在内存中
                .cacheOnDisc(true)// 设置下载的图片是否缓存在SD卡中
                .considerExifParams(true) // 是否考虑JPEG图像EXIF参数（旋转，翻转）
                .imageScaleType(ImageScaleType.IN_SAMPLE_INT)// 设置图片以如何的编码方式显示
                .bitmapConfig(Bitmap.Config.RGB_565)// 设置图片的解码类型//
                .resetViewBeforeLoading(true)// 设置图片在下载前是否重置，复位
                .displayer(new SimpleBitmapDisplayer())
                .build();// 构建完成
        com.nostra13.universalimageloader.core.ImageLoader.getInstance().displayImage((String) path, imageView, options, new ImageLoadingListener() {
            @Override
            public void onLoadingStarted(String s, View view) {

            }

            @Override
            public void onLoadingFailed(String s, View view, FailReason failReason) {

            }

            @Override
            public void onLoadingComplete(String s, View view, Bitmap bitmap) {
                int screenHeight = ScreenUtil.getScreenHeight(context);
                int screenWidth = ScreenUtil.getScreenWidth(context);
                int height = bitmap.getHeight();
                int width = bitmap.getWidth();
                float i = (float) width / (float) height;
                float imgheight = screenWidth / i;
                LinearLayout.LayoutParams layoutParams = new LinearLayout.LayoutParams(screenWidth, (int) imgheight);

                imageView.setLayoutParams(layoutParams);
            }

            @Override
            public void onLoadingCancelled(String s, View view) {

            }
        });
    }
}
会报错，参数转换异常 Linelayout.layoutparams不能转为ViewPager.LayoutParams

**Comment by sunkeding** [comment]
当然前提是图片宽高未知。

**Comment by youth5201314** [comment]
你觉得图片可能动态去设定吗？你确定每个人都能保证每张片比例一样，我们通过动态设定Imageview不就能达到效果了吗？universalimageloader都很多年没更新，建议你可以考虑换一种图片加载框架！
