### ISSUE TITLE
我给banner设置了两张图，第一次能正常轮播，而第二次第一张图片就变白色了，是什么情况呢

### ISSUE THREAD

**Issue by xiongwei6756108** [youth5201314/banner#127]

**Comment by leowing** [comment]
Me too

**Comment by deltaguita** [comment]
+1

**Comment by deltaguita** [comment]
@leowing @xiongwei6756108 
你們的 banner parent view 是 ConstraintLayout 且 設定高度為 0dp嗎？
我剛剛試了下，只要給予固定的高度解決了輪播後第一頁空白的問題

**Comment by deltaguita** [comment]
@youth5201314 作者您好：
Banner 對 ConstraintLayout 有支持上的問題，知道您很忙沒時間調整，
您能否抽空在 readme 加些註解提醒後面的使用者呢 ：）
