### ISSUE TITLE
当只有一张图片时，点击事件无响应

### ISSUE THREAD

**Issue by RommelLiang** [youth5201314/banner#129]
首先感谢你，你的分享给我的工作带来了很大的便利
当只有一张图片时，点击事件无响应
如何设置当前显示的图片，比如我想让banner从第三张图片开始轮播

**Comment by RommelLiang** [comment]
还发现一个问题，当轮播没有开始的时候，点击banner没有响应（banner嵌套在ScrollView中）

**Comment by a362310485** [comment]
确实，只有一张图片的时候，不能触发点击事件，望修复

**Comment by youth5201314** [comment]
请看demo，这个我测试了很多道，事件没有问题，设置事件请放到start（）方法之前调用
