### ISSUE TITLE
banner如何清数据

### ISSUE THREAD

**Issue by jtyang** [youth5201314/banner#130]
banner数据应该在刷新服务器接口之后随时都可能有或者没有，在banner.update（）的时候，如果自己服务器返回banner无数据了，现在update应该会有问题。

**Comment by youth5201314** [comment]
服务器无数据你不判断吗？，之所以没有清空，是为了好的体验，难道你要显示一片空白吗？，我这是这样想的，当没有数据时，你可以设置一张默认的图片传进去。而且我实在想不出轮播图在产品运营阶段，公司会让他没有数据。
