### ISSUE TITLE
增加图片圆角

### ISSUE THREAD

**Issue by 731942771** [youth5201314/banner#134]
开启或关闭banner每页是否圆角

**Comment by MIkeeJY** [comment]
这个你自己扩展即可

**Comment by EpicWang** [comment]
@MIkeeJY 请问下，应该怎么做圆角，我添加了android:background="@drawable/service_banner_radius"这个属性不起作用。
service_banner_radius.xml如下：
<corners android:radius="50dp" />

**Comment by MIkeeJY** [comment]
@EpicWang 里面是ImageView 存在的一个集合  你替换成Rounded Imageview 然后设置圆角就好

**Comment by EpicWang** [comment]
@MIkeeJY 多谢，图片已经显示成圆角，但是图片轮播的时候由于外面的banner还是矩形，所以这个解决方案还不太完美。

**Comment by MIkeeJY** [comment]
@EpicWang 修改viewpager的背景即可~~~~~~

**Comment by EpicWang** [comment]
@MIkeeJY 不好意思，我研究了下，还是不太会，能说的详细点吗？

**Comment by MIkeeJY** [comment]
@EpicWang  你看懂源码 知道布局的层次 然后你想修改哪个的背景你自己设置下就是咯

**Comment by EpicWang** [comment]
@MIkeeJY 多谢，已解决！

**Comment by ArcherLucky** [comment]
@MIkeeJY 求助啊。。哈哈，还是这个问题，话说该贴出来源码啊

**Comment by jp1017** [comment]
https://github.com/youth5201314/banner/blob/master/app/src/main/java/com/test/banner/loader/GlideImageLoader.java 把圆角注释打开就可以了

**Comment by 44sakumi** [comment]
> https://github.com/youth5201314/banner/blob/master/app/src/main/java/com/test/banner/loader/GlideImageLoader.java 把圆角注释打开就可以了

这样在滑动的时候，依然会变成直角，有什么解决方法吗？

**Comment by 44sakumi** [comment]
> @MIkeeJY 多谢，已解决！

你好，请问是怎么解决的呢？

**Comment by jp1017** [comment]
> 这样在滑动的时候，依然会变成直角，有什么解决方法吗？

那就只有脱裤，然后自己自定义父布局

**Comment by kokobebekoko** [comment]
> @MIkeeJY 多谢，已解决！

请问你的怎么设置滑动的时候不是直角的 是把源码拿去改吗

**Comment by lixins** [comment]
> @MIkeeJY 多谢，已解决！

请问你是怎么解决滑动时候轮播图还是直角这个问题的？能告知一下吗？

**Comment by MIkeeJY** [comment]
@lixins 里面是ImageView 存在的一个集合 你替换成Rounded Imageview 然后设置圆角就好

**Comment by lixins** [comment]
> @lixins 里面是ImageView 存在的一个集合 你替换成Rounded Imageview 然后设置圆角就好

图片是圆角了，但由于轮播图还没圆角，所以在滑动的时候还是会变成矩形

**Comment by MIkeeJY** [comment]
@lixins imageview 肯定跟父布局有个margin的啊

**Comment by lixins** [comment]
哎哟喂，谢谢您内，辛苦回了两条完了还是等于没说，我是没看到你说的margin

**Comment by lixins** [comment]
> @lixins imageview 肯定跟父布局有个margin的啊

哎哟喂，谢谢您内，辛苦回了两条完了还是等于没说，我是没看到你说的margin
