### ISSUE TITLE
从后往前滑到第一张，图片边界出现异常

### ISSUE THREAD

**Issue by ehaahe** [youth5201314/banner#136]
我在一个Scrollview里面用了这个库，用的Default的动画效果，刚开始加载的时候，图片边界还没问题，可是当我从后面的图片滑动到第一张的时候，第一张的图片的左边出现了大概10dp的边距，不知道是什么原因，麻烦看下

**Comment by liuyuttkx** [comment]
您好,我可能出现了和您相同的问题, 我最后的解决方法是在ImageLoader子类中,即demo中的类GlideImageLoader, 在这个地方设置了图片的显示模式;imageView.setScaleType(ImageView.ScaleType.FIT_XY);
设置之后 ,在滑动的时候就不会出现图片边界问题了. 
设置图片的显示模式,让图片显示充满全view即可;imageView.setScaleType(ImageView.ScaleType.FIT_XY);这种显示模式会让图片拉伸变形,解决方法一: bannerview的宽高比一定, 加载的图片宽高比一定,且两者宽高比相同,则不会出现变形;方法二: imageview设置其它充满view的显示模式,但会裁剪图片
如果是图片默认的显示模式, 且你加载的图片宽高比很小, 很容易出现您描述的情况.

public class GlideImageLoader extends ImageLoader {
    @Override
    public void displayImage(Context context, Object path, ImageView imageView) {
        //具体方法内容自己去选择，次方法是为了减少banner过多的依赖第三方包，所以将这个权限开放给使用者去选择
        //        ImageLoader.getInstance().displayImage(path,imageView);
        imageView.setScaleType(ImageView.ScaleType.FIT_XY);//
        com.nostra13.universalimageloader.core.ImageLoader.getInstance().displayImage(((BannerBean) path).getPic().toString(), imageView);
    }
}
