### ISSUE TITLE
CPU内存占用过高

### ISSUE THREAD

**Issue by againTry** [youth5201314/banner#137]
你好，再使用Banner控件时，发现每次滑动Banner（自动滑动也一样）时，CPU绘制时会稍大，Log一直打印GC日志，不知道为什么会占用这么大，以前使用View Pager时内存要小于现在的Banner，Banner多占CPU约一半多点，还请多指教！

**Comment by DoomsDayXx** [comment]
我也遇到这问题了，Cpu占用会有点高，内存会一直蹭蹭蹭的增加

**Comment by xiaotut** [comment]
你好，如果设置圆形指示器的时候，指示器后面半透明的背景是禁止了吗？

**Comment by youth5201314** [comment]
没有！指示器你你可以自定义颜色

**Comment by xiaotut** [comment]
不是指示器颜色，是类似title_background属性

**Comment by youth5201314** [comment]
都是可以设置的

**Comment by xiaotut** [comment]
没有找到相关属性，就这几个属性
     app:indicator_drawable_selected=""
            app:indicator_drawable_unselected=""
            app:indicator_height=""
            app:indicator_margin=""
            app:indicator_width=""_
只有设置了titles，title_background属性才生效

**Comment by againTry** [comment]
呃，能说说CPU占用过高怎么解决的吗？

**Comment by xuejinwei** [comment]
把轮播间隔时间调到10ms，让他自己跑了十几分钟，发现内存虽然一轮播一次增长0.03MB，但是能够被GC掉，说明不会出现内存泄露。
