### ISSUE TITLE
只有一张图片时不会循环轮播

### ISSUE THREAD

**Issue by Lauzy** [youth5201314/banner#145]
mBanner.setImageLoader(new GlideImageLoader())
                .isAutoPlay(true).setDelayTime(2000).setIndicatorGravity(BannerConfig.CENTER)
                .setImages(imgUrls)
                .start();
这是代码，imgUrls是List<String>集合，只有一个图片的url，图片加载出来后指示器不显示并且不会轮播，多个的时候没有这个问题

XML文件

    <com.youth.banner.Banner
        android:id="@+id/head_pager_banner"
        android:layout_width="wrap_content"
        android:layout_height="200dp"
        app:indicator_drawable_selected="@mipmap/icon_dot_selected"
        app:indicator_drawable_unselected="@mipmap/icon_dot_not_selected"
        app:indicator_height="@dimen/dp_7"
        app:indicator_width="@dimen/dp_7">
    </com.youth.banner.Banner>
我记得之前不是这样的啊？1.4.5版本，更新了1.4.9还是这样

**Comment by youth5201314** [comment]
你可以问下其他人这样是问题吗？一张图干嘛要去轮播，如果你实在想要轮播，可以看下更新记录，以前的版本会轮播。
