### ISSUE TITLE
你这banner手动滚动 也只有高智商人群能衮过去了

### ISSUE THREAD

**Issue by qssq666123** [youth5201314/banner#147]
刚滚到一半给回去了，需要用手 用力 用力从最 右边 开始拖动到最左边，这让我怎么和老板叫差？

**Comment by qssq666123** [comment]
左边特么根本没法滚，这banner牛逼吹的太大了，

**Comment by qssq666123** [comment]
往右边滚动 滑动完了都能自动弹回去，受不了

**Comment by qssq666123** [comment]
概率性太大，我刚刚又重启一次发现滚动又可以了，但是不能反向滑动，嵌套在recyclerview

**Comment by qssq666123** [comment]
服了！写不好触摸事件建议 用viewpgaer,哎 还是自己写的简单实用也方便各种需求。

**Comment by youth5201314** [comment]
没人求着你用，大哥，我只是提供的一种思路，你可以修改，你可以提意见，还有就你说的问题很简单就能解决，至于吗？就你这口气？就是因为你这样的人太多，我才不想更新了，想用的人我都单独提供了解决方法的。我本地都更新了很多功能，但是就是提不起兴趣去上传。你还是自己写吧！我不欠你什么！你看过源码吗？我用的难道不是viewpgaer？

**Comment by qssq666123** [comment]
很简单就能解决的坑你咋没解决呢，如果自己用viewpgaer 问题都没有 关键是坑被挖出来了。

**Comment by youth5201314** [comment]
谁说我没解决，你可以去群里问下，看看我是不是解决了，只是我没有上传代码而已，他们私聊时我都单独说了的！

**Comment by youth5201314** [comment]
我是闲的蛋疼，为你这种人解决问题？你智商高那你有必要提问？

**Comment by qssq666123** [comment]
说的灵活，我只能说牛逼吹大了，指示器放在外头 这特么就不方便改了适配器是一张图片。呵呵哒

**Comment by qssq666123** [comment]
我只是举得牛逼吹的不负责任坑死人之后 就不管事了

**Comment by qssq666123** [comment]
bug您老继续留着我最不想看的就是别人的bug,

**Comment by pengkongkong** [comment]
有bug自己不会改？伸手党坐惯了吧




发自网易邮箱大师
在2017年03月24日 17:45，qssq666123 写道：

bug您老继续留着我最不想看的就是别人的bug,

**Comment by youth5201314** [comment]
大哥，我的思路早就在群里说了，最终的结果是全部用户自己自定义view，和自定义指示器，我只是提供轮播。我想说的是你sb吧，谁是伸手党？我像谁伸手了，你吗？别人提问都心平气和，你的教养炸怎么差呢

**Comment by pengkongkong** [comment]
回复错了，那个是回复给提问的那个人的




发自网易邮箱大师
在2017年03月24日 17:49，王兴春 写道：

大哥，我的思路早就在群里说了，最终的结果是全部用户自己自定义view，和自定义指示器，我只是提供轮播。我想说的是你sb吧，谁是伸手党？我像谁伸手了，你吗？别人提问都心平气和，你的教养炸怎么差呢

**Comment by qssq666123** [comment]
hheda

**Comment by qssq666123** [comment]
主要我被无数个这样的控件坑死了你这个东西是别人推荐的，结果呢 数组越界，还有一个问题是偏偏要-1而且由用户写，这样写了 还有概率越界，最新版别说不是，我就火大了，写的那么屌bug那么多

**Comment by youth5201314** [comment]
你没看更新吗？我有两个点击事件，那个被废弃了。

**Comment by qssq666123** [comment]
ok,收回我那些话，不过这个bug您不说算了，我也搞不懂自己为何这么没素质理所当然了，也许是被n多用户搞成这样的，结果对 大佬也开始这样说话了抱歉

**Comment by qssq666123** [comment]
也许这是我的本性，

**Comment by youth5201314** [comment]
sorry ！pengkongkong, 刚才没看清！下次换地方更新版本了，简直影响心情！

**Comment by qssq666123** [comment]
sorry,我的本性也许是自私，其实我说出去我自己都觉得羞耻为何这种口气说话。。但是我搞不懂我还是说了 对不起  对不起

**Comment by XXiaoQing** [comment]
github  上面的开源精神，珍惜 github 上面这种环境，不要将我们的陋习带向全世界

**Comment by qssq666123** [comment]
@XXiaoQing  ok关贴

**Comment by guanzhipeng** [comment]
不喜欢，或者不适合就自己去开发，开源是一种精神，不是义务。

**Comment by qssq666123** [comment]
@guanzhipeng 没别的意思，基本的滑动都用不了，吐槽一下而已希望打算用的朋友先三思，坑太多的东西 坑的是时间，  毕竟是写公司项目

**Comment by qssq666123** [comment]
滑动是基本的需求而已。 star 总数老高了，谁知道这么坑呢

**Comment by is1988** [comment]
@qssq666123 求你开源一个，求你别用，什么毕竟是公司的项目。公司是你爹？你没爹了活不了？一天天就知道吐槽别人的bug，是项目就必然有bug，嫌弃楼主不改是因为你自己不会改吧？自己说的那么牛逼，就自己封装一个呗，为什么我们可以用，你这傻吊就用不了？智商捉急还是没有脑子？你这充其量是个网络狂战士，真不敢想象你的项目会渣到什么程度，走好不送！

**Comment by qssq** [comment]
巧了，我已经开源了我的比他灵活的多， 你就是个万恶的喷子而已，

**Comment by is1988** [comment]
@qssq 大神，我只喷喷子。

**Comment by qssq** [comment]
要有否定精神，不行吐吐槽没啥的，不要骂人。@is1988  知道有一句话叫能力越大责任越大吗 因为用的人多所以必然会有更多人用，如果存在bug会影响的人越多我觉得 要接受批评。

**Comment by is1988** [comment]
@qssq 如果有人部分青红皂白在你开源项目下一顿吐槽，目的不是为了怎么去修改或优化这个项目，而是一味的放大bug指出博主的各种不足，相信你也很难平静自己的心情，批评肯定是要接受，但你看看标题不难感觉到带有明显的人身攻击。

**Comment by qssq** [comment]
欢迎你去我的项目指责。 我觉得 再人生攻击也没你们你刚才那样令人发指。 你装啥高清呢？ 就算别人万恶你也是第三者，你参合进来就很有素质了？ 而且这是很久以前的事情了，还特么扯

**Comment by is1988** [comment]
@qssq 不必，我是没素质，是很久以前了，我扯你也跟着扯，你是要强行把素质拉的跟我一样低？忙了。

**Comment by qssq** [comment]
你要素质高的话说说道理而不是骂人。你骂了我我也没骂你爹对吧。

**Comment by RaymanMartin** [comment]
伸手伸成这样的码农，不会自己改就回家耕田吧~不适合写代码

**Comment by qssq** [comment]
呵呵哒，我已经自己开发了一个，简单也比这个自由，不适合写代码》？你以为你算老几？@RaymanMartin   你给我的感觉就是喷子

**Comment by Jameni** [comment]
看到你们这样，我很伤心，世面上的安卓设备本来就是千千万的，一套代码怎么可能兼容那么多，作者就是写一个通用的，能用就用，不能用就自己改改，或者找个符合需求的，哎，很伤心。。。很伤心，其实我也用过好几个banner的框架，都有bug，还是要自己手动改改源码增加兼容性的，而且这种bug不是那么容易就测出来的，哎，伤心，心疼作者。

**Comment by fazhongxu** [comment]
本来觉得不错，然后也出现了拖动不了的这种情况，所以我不太敢用，项目着急实在没时间改源码，希望还是修复一下，不为我，为别人考虑下。demo就的图片+标题+指示器，图片+标题+数字 就滑动不了，手势向左边滑动就不行，我是没时间研究了。
