### ISSUE TITLE
这个banner的高度能够按比例显示嘛

### ISSUE THREAD

**Issue by BrickCat** [youth5201314/banner#149]
如果我的手机屏幕比较大，高度写死了，那这个banner不就成了很窄的一条了,怎么解决啊？

**Comment by gaochunchun** [comment]
根据图片高度动态计算。首先需要得到Banner对象，例如：
//设置Banner的高度 
// ViewGroup.LayoutParams params = mHomeBanner.getLayoutParams();
 // params.height = 800;
800 即需要设置的高度。
备注：需在调用start()方法之前设置
