### ISSUE TITLE
Lib version 1.4.9 3个内容后，从1的下标滑动到第二个下标，马上点击内容，下标返回为 -1

### ISSUE THREAD

**Issue by sinlov** [youth5201314/banner#150]
点击事件使用 setOnBannerListener

点击事件，下标返回异常

**Comment by youth5201314** [comment]
有两个点击事件，有一个过时了，你用另一个

**Comment by sinlov** [comment]
@youth5201314 

已经是最新的方法，和老的方法一样
原理是动画播放导致的
下标返回需要动画播放完毕才会正确

3个内容以后容易测试出来
- 先等待动画播放到下标1和下标2的一瞬间
- 马上下标1滑动到下标0，马上点击banner的下标返回错误的下标
- 因为动画播放未完毕，用户是有权点击banner的，而 banner 的监听是轮播优先，导致返回下标错误

多次测试，建议优先是下标，动画播放不影响下标返回
