### ISSUE TITLE
咨询个小问题

### ISSUE THREAD

**Issue by coder-xiaoshuai** [youth5201314/banner#152]
假如我想自定义item的布局  就是item不只是Imageview 怎么办

**Comment by youth5201314** [comment]
这个你本地依赖修改吧，吧imageview的地方替换成你想要的就行了

**Comment by coder-xiaoshuai** [comment]
这是不是需要我以module的形式导入类库呀

**Comment by youth5201314** [comment]
目前是这样的，以后考虑更新，这段时间特别忙，都好久没有去更新优化新的功能了

**Comment by coder-xiaoshuai** [comment]
嗯  好的  我自己修改一下  多谢了
