### ISSUE TITLE
自动重新循环滑动到第一页时，图片被上下拉大

### ISSUE THREAD

**Issue by ganshenml** [youth5201314/banner#159]
然后滑动至第三页是踩恢复正常？请问这个是什么原因导致的？

**Comment by himon** [comment]
我这也是，有些手机上没有问题，但在红米 2上，第一张图片会被拉伸，图片刚显示的时候是正常的，然后马上拉伸一下

**Comment by ganshenml** [comment]
我是荣耀6,系统是4.4.2

**Comment by goodgt** [comment]
我的也是  有的图片正常  有的就会拉伸一下  什么问题啊 有没有人解决了？
