### ISSUE TITLE
加载图片用的centerCrop造成部分图片显示不全，希望可以修改ScaleType属性

### ISSUE THREAD

**Issue by imexception** [youth5201314/banner#16]

**Comment by youth5201314** [comment]
根本原因是你的显示区域显示不下图片，请动态修改显示区域高度，或者规范图片参数好吧。

**Comment by imexception** [comment]
虽然你图片设置的属性是fitxy，但是设置默认图片后又用了glide的centercrop覆盖了图片的fitxy， if (defaultImage != -1)
                    Glide.with(context).load(url).centerCrop().crossFade().into(iv);
                else
                    Glide.with(context).load(url).centerCrop().crossFade().placeholder(defaultImage).into(iv);
自己看吧，你给写死了好不

**Comment by imexception** [comment]
图片应该能够修改这个属性来适应imageview的大小，而不是修改imageview的大小来适应图片，该属性应该暴露出来

**Comment by youth5201314** [comment]
你懂不懂fitxy这个是什么意思？我那样设置是为了不让图片拉伸好吗，有多大区域就截取中间去显示，这种banner产品部们是会规定比例的好吗？代码将高度设置成根据比例算出的才对，ok？还有请仔细看demo或者文档在发言好吗，自己没看完就那么肯定的发表一个问题。关于图片本身就要尽量不要拉伸，这些都是可以动态去计算的，建议少用fitxy这个属性。
![image](https://cloud.githubusercontent.com/assets/8827239/18190702/31cc71cc-70f7-11e6-9f99-75d42a1570a6.png)

**Comment by imexception** [comment]
为了修改一个属性，我需要重新写个listener，然后用glide去重新设置这个属性你觉得合理吗，我的意思是应该用xml配置的方式

**Comment by youth5201314** [comment]
呵呵。我还是第一次听说轮播图要去拉伸图片的说法，图片无非两个标准，一个是产品定义图片比例，以后的图片都是这个比例，又或者是产品没有定义图片比例，是随意上传图片，那么图片显示的大小是固定，就比如一个显示区域是16:9的大小，图片却是16:5、甚至是20:1的大小呢，请问fitxy后会怎么样？是否应该使用centercrop，你自己写个测试类看看效果就知道，当然如果产品规定了比例，那么你的程序肯定也是同样的比例那么设置centercrop也就不影响什么了。就解释这么多，你还要纠结我也没办法，我正在进行改版，你可以关注以后的版本，我会将显示区域全部自定义开放出去。

**Comment by imexception** [comment]
图片比例本来就跟imageview差不多，为了适应各种屏幕，稍微的拉伸也并不影响。

**Comment by youth5201314** [comment]
强词夺理，也就是说不边缘裁剪一点就影响了？一看就不是做的产品，产品在乎任何一个细节！

**Comment by xiangbo2015** [comment]
imageView.scaleType = ImageView.ScaleType.FIT_XY
在实例化ImageView 时，更改类型
