### ISSUE TITLE
Banner的高度可以自适应图片的高度吗

### ISSUE THREAD

**Issue by wenjian1314** [youth5201314/banner#167]

**Comment by gaochunchun** [comment]
需要根据图片高度动态计算。首先需要得到Banner对象，例如：` //设置Banner的高度
        // ViewGroup.LayoutParams params = mHomeBanner.getLayoutParams();
        // params.height = 800;`
800 即需要设置的高度。

**Comment by gaochunchun** [comment]
备注：需在调用start()方法之前设置
