### ISSUE TITLE
Banner设置点击监听后，第一项不响应点击

### ISSUE THREAD

**Issue by ShineYang** [youth5201314/banner#169]
Banner设置点击监听后，第一项不响应点击（无焦点？），其它项正常；
在第二波轮转时第一项点击事件才生效。
`public void setUpBanner(final TopBanners banners) {

        banner.setBannerStyle(BannerConfig.NUM_INDICATOR_TITLE)
                .setImageLoader(new GlideImageLoader())
                .setImages(banners.getImages())
                .setBannerTitles(banners.getTitles())
                .setBannerAnimation(Transformer.Default)
                .start();

        banner.setOnBannerListener(new OnBannerListener() {
            @Override
            public void OnBannerClick(int position) {
                Log.v("banner","-------->"+position);//第一次轮播时，第一项不会响应
                jumpToContent(banners.getIdList().get(position));
            }
        });

    }`

**Comment by ShineYang** [comment]
不好意思，没有仔细查看issue，发现是调用顺序的问题。先设置监听再初始化banner即可。

**Comment by alanzyz** [comment]
点击事件不灵，放到前后均不可以
