### ISSUE TITLE
图片显示不出来

### ISSUE THREAD

**Issue by sweet2o09** [youth5201314/banner#17]
我用compile 'com.youth.banner:banner:+'方式集成,然后代码里面写
`String[] images = getResources().getStringArray(R.array.url);
        Banner banner = (Banner) findViewById(R.id.home_banner);
        banner.setImages(images);`
但是图片显示不出来,不知道为什么

**Comment by youth5201314** [comment]
权限加了没有

**Comment by sweet2o09** [comment]
<uses-permission android:name="android.permission.INTERNET" />
没加,现在好了,我想问下,为什么要用Glide加载图片而不用Android-Universal-Image-Loader
