### ISSUE TITLE
当直接new出Banner对象的时候，无法显示圆点指示器

### ISSUE THREAD

**Issue by PrometNexus** [youth5201314/banner#175]
直接new Banner而不是放在布局文件中，并不会执行attr取值，故而圆点指示器的宽高是初始值0，进而显示不出来，需要在构造函数中赋值初始值或者抛出set方法。

**Comment by kinshasa** [comment]
我也遇到这种情况，找不到new的时候传入attr的方法，希望可以提供设置indicatorStyle的方法

**Comment by kinshasa** [comment]
Banner mBanner =(Banner) LayoutInflater.from(context).inflate(R.layout.item_banner, null);
目前暂时用xml解决，反正又不会出现大量创建Banner的情况，对性能影响不大
