### ISSUE TITLE
如何设置点击第一张图片也可以响应事件

### ISSUE THREAD

**Issue by Cashdispenser** [youth5201314/banner#176]

**Comment by Cashdispenser** [comment]
使用的是新的设置监听的api

**Comment by Cashdispenser** [comment]
问题在群里解决了，把点击监听放到start前面就可以了

**Comment by zjJunZhu** [comment]
我觉得这个需要特殊说明一下，折腾了一阵，在你这里找到了解决方法。随便写写这个库的作者，也写写你提供的解决办法

**Comment by zjJunZhu** [comment]
我觉得这个需要特殊说明一下，折腾了一阵，在你这里找到了解决方法。随便谢谢这个库的作者，也写写你提供的解决办法
