### ISSUE TITLE
轮播图监听器里获取位置有问题

### ISSUE THREAD

**Issue by xuixao** [youth5201314/banner#179]
自动轮播的时候没问题 ，  第一个位置是 总页数的  ，  第二个位置是0  
但是 如果 一上来就向左滑动轮播图  滑动之后出现的位置  就会有问题  第一个位置就是0  ；

**Comment by zypguhe** [comment]
@xuixao 我同样遇到点击监听的问题，和你的类似：在点击监听里toast出position，第一个页面里position是最后一个，第二个才是0，但是当我把setBannerAnimation（）方法注释掉，则一切是正常的。
@youth5201314 希望能给修复一下
