### ISSUE TITLE
默认图片不是失败的时候显示的吗？ app:default_image="@drawable/error"

### ISSUE THREAD

**Issue by 298068845** [youth5201314/banner#18]
我把网络关了，还是一片空白没有显示默认图片

**Comment by youth5201314** [comment]
这个是默认图片不是加载失败图片，你可以统过图片加载框架自定义。

**Comment by youth5201314** [comment]
![image](https://cloud.githubusercontent.com/assets/8827239/18190855/28e18de4-70f8-11e6-8943-0691a831c496.png)
