### ISSUE TITLE
轮播图 自动滑动,图片位置错乱

### ISSUE THREAD

**Issue by ccj659** [youth5201314/banner#185]
![如图](http://img.blog.csdn.net/20170426112309744?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvY2NqNjU5/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast)

**Comment by BD1028994041** [comment]
我这里也遇到同样的问题，很奇怪

**Comment by JiangSuyun** [comment]
我也遇到

**Comment by BD1028994041** [comment]
改一下，xml文件里的android:clipChildren属性，默认true就可以了

**Comment by Slice1129** [comment]
我也遇到
