### ISSUE TITLE
第一次进入轮播设置动画后，翻到最后一页会出现空白

### ISSUE THREAD

**Issue by yebook** [youth5201314/banner#190]
第一次进入，自动轮播还未完成一轮，这时设置动画，并翻到最后一页的时候会出现白页的情况，请问有什么解决方案么？

**Comment by qssq** [comment]
啊

**Comment by yebook** [comment]
问题已解决。
修改Banner.java中的onPageScrollStateChanged方法为

@Override
    public void onPageScrollStateChanged (int state) {
        if (mOnPageChangeListener != null) {
            mOnPageChangeListener.onPageScrollStateChanged(state);
        }
        currentItem = viewPager.getCurrentItem();
        if (state == ViewPager.SCROLL_STATE_IDLE)  {
            return;
        } else if (state == ViewPager.SCROLL_STATE_DRAGGING) {
            if (currentItem == count + 1) {
                viewPager.setCurrentItem(1, false);
            } else if (currentItem == 0) {
                viewPager.setCurrentItem(count, false);
            }
        }
    }
