### ISSUE TITLE
有几个问题

### ISSUE THREAD

**Issue by txxxtxx** [youth5201314/banner#198]
感觉有三个问题一定要说，第一个，点击图片的事件都没有列出来，我甚至没有欲望下载项目；第二个，对数据支持也太差了，只能放图片地址，我想放数据对象都不行；第三点还是不清不楚，切换时间，能不能无限滚动好像都没有交代

**Comment by youth5201314** [comment]
你说的三点，都满足，请看清楚下！回掉类型是object，懂什么意思吗？

**Comment by willqian** [comment]
txxxtxx 你这几个意见显然是没有用过才发表出来的，建议你先试用一下，我认为banner库还是不错的
