### ISSUE TITLE
能否有个设置在onStart中开启轮播，在onStop中停止轮播

### ISSUE THREAD

**Issue by yisiwei** [youth5201314/banner#2]

**Comment by youth5201314** [comment]
好的记下了！抽空改下，谢谢！

**Comment by youth5201314** [comment]
![image](https://cloud.githubusercontent.com/assets/8827239/16291178/912dd500-3936-11e6-8755-e4f1d92bd56c.png)以前都可以满足你的功能，但是没有写出代码方面的解释，现在加上了这方面的解释，你看下呢！

**Comment by yisiwei** [comment]
好的，已经知道了
