### ISSUE TITLE
如何获取当前是第几页（getCurrentItem）和设置当前的页数（setCurrentItem）

### ISSUE THREAD

**Issue by chenqunming** [youth5201314/banner#206]

**Comment by tanpuer** [comment]
getCurrentItem 
增加一个  需要用到。。。

**Comment by bakonMa** [comment]
version：v2.1.0
banner.getCurrentItem(),或者banner.getViewPager2().getCurrentItem()
获取到的pos不稳定，通过addOnPageChangeListener获取到的才准确
求修复此bug
