### ISSUE TITLE
有时候自动轮播会停止然后就不动了,还有设置的默图片没显示

### ISSUE THREAD

**Issue by littleViolence** [youth5201314/banner#21]

**Comment by youth5201314** [comment]
默认图片用的是glide框架的功能，只有在加载中和加载失败时才会显示，但是由于网络好的情况有时候加载中也来不及显示。

**Comment by littleViolence** [comment]
那停止呢 莫名的停止

**Comment by littleViolence** [comment]
我换了个框架 picasso 就会显示出 加载失败的图片 ,我故意在banner图中设置了一个加载不出得路径 换了 
picasso 就会`显示默认图片 用glide就没有显示

**Comment by youth5201314** [comment]
我没发现这个问题，还有如果你发现了问题请说明详情步骤或者日志等，第二关于加载框架可以自定义，都很灵活了，第三方的图片加载我不能保证什么，有问题可以自己换，反正我用是没有问题的。
