### ISSUE TITLE
java.lang.IllegalArgumentException pointerIndex out of range

### ISSUE THREAD

**Issue by ibenlim** [youth5201314/banner#210]
偶尔会报一下错误：
1 android.view.MotionEvent.nativeGetAxisValue(Native Method)
2 android.view.MotionEvent.getX(MotionEvent.java:2072)
3 android.support.v4.view.ViewPager.onInterceptTouchEvent(SourceFile:2064)
4 com.youth.banner.view.BannerViewPager.onInterceptTouchEvent(SourceFile:28)
5 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2125)
6 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2582)
7 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2271)
8 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2582)
9 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2271)
10 com.youth.banner.Banner.dispatchTouchEvent(SourceFile:477)
11 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2582)
12 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2271)
13 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2582)
14 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2271)
15 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2582)
16 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2271)
17 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2582)
18 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2271)
19 com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2506)
20 com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1792)
21 android.app.Activity.dispatchTouchEvent(Activity.java:2870)
22 com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2465)
23 android.view.View.dispatchPointerEvent(View.java:9564)
24 android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4331)
25 android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4185)
26 android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3703)
27 android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3769)
28 android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3729)
29 android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3868)
30 android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3737)
31 android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3925)
32 android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3703)
33 android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3769)
34 android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3729)
35 android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3737)
36 android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3703)
37 android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6058)
38 android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6032)
39 android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5989)
40 android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6168)
41 android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:193)
42 android.os.MessageQueue.nativePollOnce(Native Method)
43 android.os.MessageQueue.next(MessageQueue.java:323)
44 android.os.Looper.loop(Looper.java:135)
45 android.app.ActivityThread.main(ActivityThread.java:5619)
46 java.lang.reflect.Method.invoke(Native Method)
47 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:850)
48 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:734)

**Comment by ywp0919** [comment]
我这边收集到的日志也有这个  pointerIndex out of range

**Comment by sunnylovejordan** [comment]
这个有解决吗？

**Comment by peiniwan** [comment]
我也收到了
