### ISSUE TITLE
You cannot start a load for a destroyed activity

### ISSUE THREAD

**Issue by k354250377** [youth5201314/banner#212]
java.lang.IllegalArgumentException
You cannot start a load for a destroyed activity
![image](https://cloud.githubusercontent.com/assets/20323504/26432457/8a4a8d90-412e-11e7-9a4c-7feff025380f.png)
老大这是什么错啊

**Comment by zuijiusi** [comment]
same trouble.

**Comment by zhengweig** [comment]
你都没有用start方法去启动轮播图

**Comment by Wangct23** [comment]
我也遇到了同样问题。请问已经解决了吗？

**Comment by zhengweig** [comment]
Glide.with（getApplicationContext）加载图片，就行了。
