### ISSUE TITLE
Banner(Context context)的context如何传入的，我希望能传入getApplicationContext；

### ISSUE THREAD

**Issue by zuijiusi** [youth5201314/banner#227]
原因是：Glide在子线程使用造成You cannot start a load for a destroyed activity。
    public void displayImage(Context context, Object path, ImageView imageView) {
        if (path instanceof DownloadedImage) {
            Glide.with(context).load(((DownloadedImage)path).getUrl()).into(imageView);
        }
    }

**Comment by zuijiusi** [comment]
暂时使用了这个判断处理：if(Util.isOnMainThread()) {}

**Comment by youth5201314** [comment]
context直接可以获取getApplicationContext
