### ISSUE TITLE
Banner的滑动

### ISSUE THREAD

**Issue by Freedomhxb** [youth5201314/banner#23]
就是我手指先在banner上左右滑动，然后再上下滑动，如果我的布局中有下拉刷新的时候，下拉刷新也会出来，我想能不能让banner在我手动左右滑动的时候，消费掉这个事件，不让它的父布局处理

**Comment by youth5201314** [comment]
这个很简单啊，只能你自己处理了，我并不能确定所有人的应用环境，所以这个我不能去处理。况且不一定所有的下拉刷新控件都有冲突问题，如果处理了返回原本没有问题的变得有问题了。这个跟你的选择有关系好吧，也不难！你本地依赖工程，改下代码就行了。

**Comment by Freedomhxb** [comment]
大神，你好，还有个小问题，想请教你下，就是banner正在滚动的时候，我手指放上去后，banner不会滚动，然后我手指离开，banner也不会滚动，只有我点击后，banner才恢复滚动

**Comment by youth5201314** [comment]
你用的那个版本

**Comment by Freedomhxb** [comment]
compile 'com.youth.banner:banner:1.3.1'

**Comment by youth5201314** [comment]
这个版本没有你说的问题啊，看看demo，有没有你说的问题，也许我没有理解你的意思。如果demo也有再跟我说

**Comment by Freedomhxb** [comment]
关键demo导入as中报错。。。。运行不起来。。。。。。(┬＿┬)

**Comment by youth5201314** [comment]
那是你本地环境的问题，我的配置都是最新的。其他人都可以用的。你自己手动改下相关的版本就行了

**Comment by Freedomhxb** [comment]
demo中也是这个问题，就是 图片在 自动滚动的那个瞬间，把手指放上去，就会一直停止

**Comment by youth5201314** [comment]
更新1.3.2版本，看下还有问题吗？

**Comment by Freedomhxb** [comment]
好啦，大神牛逼
