### ISSUE TITLE
ImageLoader有无限下载图片的bug，建议替换！

### ISSUE THREAD

**Issue by yuCharles** [youth5201314/banner#235]
ImageLoader在一些Android机型上，当本地缓存的文件夹被清除后，ImageLoader会报创建文件夹错误的异常，并且每次轮播图片的时候都会触发图片下载请求，导致**每轮播一次都会重新下图片**，我们的app已经因为这个问题使用户一天损失1G流量了，建议用Glide替换！！！

**Comment by canceel** [comment]
使用哪个不是自己可以设定得吗？

**Comment by yuCharles** [comment]
确实，建议大家不要使用ImageLoader就好了
