### ISSUE TITLE
建议新增加载网络图片时，默认显示图片，并提供入口，方便使用

### ISSUE THREAD

**Issue by HLQ-Struggle** [youth5201314/banner#239]
加载网络图片时，首先是白色的，感觉不是好，可否新增一个入口，方便传入加载网络图片时默认的图片呢？

**Comment by HLQ-Struggle** [comment]
Sorry 已解决 哈哈

**Comment by shiguiyou** [comment]
@HLQ-Struggle 有这个方法吗？

**Comment by HLQ-Struggle** [comment]
> Glide中提供

**Comment by HLQ-Struggle** [comment]
@shiguiyou

**Comment by is1988** [comment]
Glide.with(context).load(path).placeholder(R.drawable.bg_default) //设置占位图
               .error(R.drawable.bg_default).into(imageView);
