### ISSUE TITLE
position 回调过来的值不对

### ISSUE THREAD

**Issue by ge1944633835** [youth5201314/banner#258]
一般顺着滑动，position的值都是对的，但是向相反的方法滑动，回调过来的值不对。比如3张图片，当position为2的时候，向左边滑动到第一个元素，这时候position也是2，应该是0的。（这种情况不是每次都发生，但是测试一下就可以发现）

**Comment by jeff-sun** [comment]
我的点击返回的position是没问题的啊,setOnBannerClickListener这个方法已经废弃了,改成setOnBannerListener.
