### ISSUE TITLE
动画有问题，轮播的时候会白屏 

### ISSUE THREAD

**Issue by dovginka** [youth5201314/banner#259]
我在onPageSelected（）中添加了一个循环动画（16中动画随机切换），出现白屏

代码如下

@Override
    public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {
        ViewPager.PageTransformer pageTransformer = null;
        try {
            pageTransformer = mAnimList.get(new Random().nextInt(mAnimList.size())).newInstance();
            mBannerViewPager.setPageTransformer(true, pageTransformer);
        } catch (Exception e) {
            e.printStackTrace();
        } 
    }

**Comment by dovginka** [comment]
我想了想，可能是某个动画类在Page切换完成后，把Page的设置成了全透明，应该是这个原因吧

**Comment by guhh110** [comment]
你试试吧设置动画的语句删了试试
