### ISSUE TITLE
第一张图片轮播时间过长

### ISSUE THREAD

**Issue by Damon-wei** [youth5201314/banner#26]
比如3张图，我设置时间间隔1s,但是每次到第一张之后都要多停留几秒

**Comment by youth5201314** [comment]
好的，最近很忙，下次修改下更新。在从最后过渡到第一张时，中间是加了一张图片过渡的，所以有点慢，后面优化下，你如果有好的算法也可以提。

**Comment by youth5201314** [comment]
更新1.3.3吧！
