### ISSUE TITLE
第一次进入的时，图片加载时会先白屏一会，然后出现图片轮播，怎么实现进入一个页面可以直接显示不白屏。。。

### ISSUE THREAD

**Issue by ChristChild0830** [youth5201314/banner#260]
如题！

**Comment by qssq** [comment]
这个问题早就存在了，我之前以为是调试版本可能有，现在感觉事情很严重，也许还是自己写的靠谱 ，再花哨的东西在bug面前，就是轮播显示然后白屏，什么翻页效果也没有了。。呵呵哒

**Comment by ChristChild0830** [comment]
...我是在fragment里用会出现这样的问题：就去会先白屏一会然后出现，直接在activity好像没有出现问题！

**Comment by qssq** [comment]
本库目测在对话框也出现一些奇怪的情况。 最后还是决定翻出我2015年的东西，重写了下， @ChristChild0830 使用我的banner库吧，so easy https://github.com/qssq/banner
