### ISSUE TITLE
如何修改指示器的位子呢

### ISSUE THREAD

**Issue by haozi050209** [youth5201314/banner#262]
我的需求是指示器需要居中，但是指示器下面刚好有个弧线的一个图片  怎么样才能把这个指示器往上去点呢？不让弧线的图片挡住指示器！

**Comment by kangjinwen** [comment]
我的需求也是类似的...
需要将原点指示器上移一点...
可是没有开放调节的方法..

**Comment by ania93** [comment]
遇到了同样的问题，不能调整indicator的位置，你们怎么解决的？ @haozi050209 @kangjinwen
