### ISSUE TITLE
图片能不能设置成圆角的

### ISSUE THREAD

**Issue by Jorble** [youth5201314/banner#269]
把轮播的图片弄成圆角，没有那么多直角好看点

**Comment by leveychen** [comment]
可以啊  你自己定义 imageloader 的时候写成圆角就好了。。

**Comment by Jorble** [comment]
是的，我已经这样实现了

**Comment by good-good-study** [comment]
不行呀 , 设置了 没效果 ,  还是直角的 ,  我在RecyclerView里面 可以显示圆角
