### ISSUE TITLE
Bug:setOnPageChangeListener方法回调接口中onPageSelected方法的position不正确

### ISSUE THREAD

**Issue by Mercury-Dai** [youth5201314/banner#278]
我目前有四张图，但是onPageSelected返回position返回1（很郁闷click事件position默认0开始，这儿为什么写1），2，3，4，5，导致我这边通过position去获取值时数组越界，这是第一个问题，第二个是onPageSelected会重复调用多次

**Comment by HStanN** [comment]
你可以用这个方法转换下
```java
int realPsition = banner.toRealPosition(position)
```

**Comment by Mercury-Dai** [comment]
@HStanN 这方法是作者提供的吗？我很奇怪这个为什么还要做转换才能获得正确position？

**Comment by INX0769** [comment]
@Mercury-Dai 你写过无限轮播的轮子，下标要改变的
