### ISSUE TITLE
如果设置了第一个为网页，则会闪烁一下。

### ISSUE THREAD

**Issue by nanchen2251** [youth5201314/banner#283]
我把setImageList改成了：
private void setBannerList(List<BannerModel> models) {
        if (models == null || models.size() <= 0) {
            Log.e(tag, "Please set the models data.");
            return;
        }
        initBanners();
        for (int i = 0; i <= count + 1; i++) {
            BannerModel model = null;
            if (i == 0) {
                model = models.get(count - 1);
            } else if (i == count + 1) {
                model = models.get(0);
            } else {
                model = models.get(i - 1);
            }
            if (model.type == 0){ // 图片
                View imageView = null;
                if (imageLoader != null) {
                    imageView = imageLoader.createImageView(context);
                }
                if (imageView == null) {
                    imageView = new ImageView(context);
                }
                setScaleType(imageView);
                mainViews.add(imageView);
                if (imageLoader != null)
                    imageLoader.displayImage(context, model.url, imageView);
                else
                    Log.e(tag, "Please set images loader.");

            }else if(model.type == 1){ // 网页
                WebView webView = new WebView(context);
                WebSettings settings = webView.getSettings();
                settings.setLoadWithOverviewMode(true);
                settings.setJavaScriptEnabled(true);
                settings.setAppCacheEnabled(true);
                settings.setLayoutAlgorithm(WebSettings.LayoutAlgorithm.SINGLE_COLUMN);
                settings.setSupportZoom(true);
                webView.setWebChromeClient(new MyWebChrome());
                webView.setWebViewClient(new MyWebClient());
                mainViews.add(webView);
                webView.loadUrl(model.url);
            }else{ // widgets
                View view = LayoutInflater.from(context).inflate(R.layout.layout_mine,null,false);
                final Button btn = (Button) view.findViewById(R.id.button);
                btn.setOnClickListener(new OnClickListener() {
                    @Override
                    public void onClick(View view) {
                        btn.setText("按钮已经被点击");
                        btn.setClickable(false);
                    }
                });
                mainViews.add(view);
            }

        }
    }

发现当第一个就是网页，并且点击进入了二级页面后，会出现闪烁一下。后面是网页就不会。不知道为什么。期待得到一个良好的解答，并且可以让该库更加良好的扩展。比较只是图片轮播已经满足不了很多需求了。

**Comment by wzn519** [comment]
我用这个也是的，第一次初始化Banner时，会闪一下，后面就不会了。
