### ISSUE TITLE
运行Demo首页的Banner在左上角和右上角滑动和下拉刷新有冲突无法滑动

### ISSUE THREAD

**Issue by CXX19901120** [youth5201314/banner#288]

**Comment by zhang214214** [comment]
没有错,这个才是大问题,其他都还是小事,这个问题没解决居然3000多个star我也是很奇怪

**Comment by jaysowen** [comment]
同意,这是最基础的体验了吧

**Comment by caobin821651400** [comment]
[http://blog.csdn.net/u010386612/article/details/50548977 ](url)
@jaysowen @zhang214214 去看看这个，

**Comment by zhang214214** [comment]
@caobin821651400 链接已报废，看不了

**Comment by Voidruiyi** [comment]
@ @zhang214214  自己在父容器增加个对滑动x y 的判断  自己决定是否分发不就行了
