### ISSUE TITLE
首頁和尾頁在滑動時有時會卡住不動一下下

### ISSUE THREAD

**Issue by TomWangTW** [youth5201314/banner#29]
Hi 作者,
剛剛試用了一下,發現有時首頁和尾頁在手動滑動時有時會卡住不動一下下...
條件是:首頁要往右滑時,尾頁要往左滑時

**Comment by youth5201314** [comment]
你用的是最新的版本吗？没有发现你说的问题呢

**Comment by TomWangTW** [comment]
我是用1.3.3的版本 蠻奇怪的問題,原本懷疑和autoplay有關.但關掉後也還是會有延遲的情況出現

**Comment by youth5201314** [comment]
首页和尾页之间是有500毫秒的过渡时间，是为了让过渡更加自然设置的，不清楚你说的延迟是什么呢？

**Comment by TomWangTW** [comment]
謝謝你的回應.
就是到首頁要往右滑動切到第二頁時,不會立即的切到第二頁.
不確定和7.0有沒有關係 我拿5.x的機器試試看

**Comment by youth5201314** [comment]
如果是兼容性问题请提交下你的解决办法，我加入到代码中更新下，因为我这没有6.0以上的手机测试。

**Comment by TomWangTW** [comment]
初步分析認為和ViewPager的default cache limit有關,稍微加大一點後就沒出現這情況.
建議新增一個public method來調整cache limit.

**Comment by youth5201314** [comment]
加载缓存数量会占用更大的内存，因为你并不能知道每个人banner页面的个数，所以这个并不能算解决问题，照你你这么弄如果数量过多也会再出现，我现在是没有遇见你说的问题没有看见效果，所以不能确定原因，等以后遇见了我在修改吧！

**Comment by TomWangTW** [comment]
不知為何在6.0以上的機器很容易出現,當頁面為三頁並且快速用手指滑動時就很容易出現.
加log看是快速在第一頁往右滑第三頁往左滑時,會連續觸發destroyitem兩次.
然後根據viewpager觸發onPageScrollStateChanged時,state會是 1 2 0.但當問題發生時只會有 1 2而已.
所以加大cache只是目前的workaround...
