### ISSUE TITLE
滚动到最后一张时，禁止再继续轮播，哪个方法？

### ISSUE THREAD

**Issue by xiaotut** [youth5201314/banner#290]

**Comment by CXJean** [comment]
Step 6.（可选）增加体验

//如果你需要考虑更好的体验，可以这么操作
@Override
protected void onStart() {
    super.onStart();
    //开始轮播
    banner.startAutoPlay();
}

@Override
protected void onStop() {
    super.onStop();
    //结束轮播
    banner.stopAutoPlay();
}
具体看使用说明
