### ISSUE TITLE
用boolean值控制是否轮播会有问题

### ISSUE THREAD

**Issue by JinyuZhang** [youth5201314/banner#3]
建议是否轮播使用handle 的 remove runable实现

**Comment by youth5201314** [comment]
我们要的效果都是通知轮播去停止和开启，所以不管是通过handle还是其他方式实现的本质一样，但是在处理的优化上handle是要好一点，毕竟可以减少耗时，可考虑到集成的简单性，我没有用handle，毕竟让人用用法越简单越好，不过你的建议我会考虑改下，能有什么更好的方式，下个版本改下。谢谢。
