### ISSUE TITLE
建议把 Glide 图片加载相关的代码从 banner 库中剥离

### ISSUE THREAD

**Issue by Piasy** [youth5201314/banner#30]
既然都考虑到了自定义图片加载框架，就可以把 Glide 依赖剥离，作为一个实现方案。如果我希望利用 Fresco 加载图片，那多依赖一个 Glide 就会很不爽。

类似于 Retrofit 的 converter 和 adapter，Retrofit 本身是不包含 Gson，RxJava 这些依赖的。

**Comment by youth5201314** [comment]
你说的这个开始我是这么做的，我自己也是把加载框架剔出来用的，后面主要是考虑到小白使用麻烦，才简化步骤，并不是所有人都能理解。不过还是谢谢你的反馈，我想办法综合下！
