### ISSUE TITLE
不能通过Api调用滚到指定位置吗？

### ISSUE THREAD

**Issue by tomUp** [youth5201314/banner#300]
比如viewPager.setCurrentItem（int item）

**Comment by kodeflow** [comment]
fun Banner.pre() {
    val field = Banner::class.java.getDeclaredField("viewPager")
    field.isAccessible = true
    val viewPager = field.get(this) as BannerViewPager
    viewPager.currentItem = viewPager.currentItem-1
}

我是这样搞的，但是第一页的时候滑动到上一页图片显示不正常。
