### ISSUE TITLE
[BUG]在调用update的时候会清空所有数据

### ISSUE THREAD

**Issue by silentcmz** [youth5201314/banner#301]
解决办法 
把
    public Banner setImages(List<?> imageUrls) {
       this.imageUrls = imageUrls;
        this.count = imageUrls.size();
        return this;
    }
修改为
    public Banner setImages(List<?> imageUrls) {
        this.imageUrls.clear();
        this.imageUrls.addAll(imageUrls);
        this.count = imageUrls.size();
        return this;
    }

titles 同理

**Comment by pixiaozhi** [comment]
同上，今天做更新的时候也发现这个bug，断点进去看，传进去的时候有值，执行完后会清空；更新的时候只好先手动清空在重新塞一遍值；希望作者有时间的话去看下，支持作者
