### ISSUE TITLE
关于update方法清空数据问题解决办法。

### ISSUE THREAD

**Issue by caobin821651400** [youth5201314/banner#304]
在调用banner的update（）方法时会清空我们之前添加的list集合，从而显示暂无图片，其实仔细看一下源码很快就能理解。
  一般我们使用banner的时候，设置图片和标题用的是banner.setImages(mList).setBannerTitles(mList2);
仔细看下这两个方法的源码this.imageUrls = imageUrls;和  this.titles = titles;。banner类中titles 和你在activity中添加titles所指的内存是一致的。
    再来看看update方法this.titles.clear();和this.imageUrls.clear();，清空了，当然就没数据了。遇到问题看下源码，很快就能理解为什么会这样了。
   解决方法也有很多种：
   ## 第一：
刷新数据时new 一个list添加新的数据，不要在原来的list中添加数据，然后再调update，这种方法不需要改源代码。
 ## 第二种：
给banner设置图片和标题集合时不要用setImages（）和setBannerTitles（），一直使用banner.update(images, titlesLists);，不管是第一次和是以后跟新数据都用update（）方法。这种方法也不需要改源代码。
 ## 第三种：
改源码，不要用==，用addAll。注释掉的是原来的方法。代码如下：
   public Banner setImages(List<?> imageUrls) {
//        this.imageUrls = imageUrls;
//        this.count = imageUrls.size();
//        return this;
        this.imageUrls.clear();
        this.imageUrls.addAll(imageUrls);
        this.count = imageUrls.size();
        return this;
    }

   public Banner setBannerTitles(List<String> titles) {
//        this.titles = titles;
//        return this;
        this.titles.clear();
        this.titles.addAll(titles);
        return this;
    }
三种方法都可以解决问题,亲测。

**Comment by CK875430315** [comment]
public void update(List<?> objects) {
      //  this.imageUrls.clear();
        this.imageViews.clear();
        this.indicatorImages.clear();
        //this.imageUrls.addAll(objects);
      this.imageUrls=objects;
        this.count = this.imageUrls.size();
        start();
    }
不要清空this.imageUrls，直接赋值好像也可以的
