### ISSUE TITLE
关于addheaderview的问题

### ISSUE THREAD

**Issue by LukaHan** [youth5201314/banner#31]
作者你好，我把banner作为gridview的header加进去，切换时没有了滑动的效果，求解。

**Comment by youth5201314** [comment]
这种问题一般都是冲突造成的重写gridview就好了，具体需要你自己去找问题，毕竟每个人的代码环境不一样，不过还是建议你使用RecyclerView

**Comment by cengjingcanghai** [comment]
解决了吗，一样的问题
