### ISSUE TITLE
高度超过370dp以后 图片就不会填充满了，会显示出左右俩边图片一点

### ISSUE THREAD

**Issue by a785334345** [youth5201314/banner#310]
咋回事啊，测试了好几个机器都这样 360dp都没事

**Comment by caobin821651400** [comment]
app:image_scale_type="fit_xy"设置了吗？
全屏都可以

**Comment by Billxxxx** [comment]
抱歉还是有这个问题 ，设置center_inside 与fit_xy 显示没问题，但是设置center_crop的时候，会显示出左右俩边图片一点。望解决
