### ISSUE TITLE
什么时候支持Glide4.0 

### ISSUE THREAD

**Issue by liangjingkanji** [youth5201314/banner#313]
我其他库更新了4.0 , Banner没有更新报错

**Comment by jinyneu** [comment]
我看最新的作者放开这部分权限了，可以自己继承ImageLoader设置图片加载这部分

**Comment by liangjingkanji** [comment]
不是这个地方, 是作者引入了一个图片预览的第三方(imagepreviewibrary), 这个依赖库用到了Glide3.0代码
