### ISSUE TITLE
你好，我在android4.1测试的时候白屏，没有任何的图片显示。

### ISSUE THREAD

**Issue by china-coder** [youth5201314/banner#315]
你好，我在android4.1测试的时候白屏，没有任何的图片显示。但是轮播的按钮是可以出现的，请我这个库最低支持的android版本是多少呢？还有就是在低版本上有什么解决方案没有呢？

**Comment by CXJean** [comment]
问：怎么显示的一片空白？

答：
1、没有添加网络权限
2、检查图片链接是否能打开。
