### ISSUE TITLE
和RecyclerView滑动冲突

### ISSUE THREAD

**Issue by chenxi0203** [youth5201314/banner#317]
RecyclerView头部添加banner后，设置banner不自动切换滑动，当滑动到最后一张图片时做下拉刷新操作，刷新完成后在向第一张图片滑动，滑动后在向第二张图片滑动时，滑动没效果，再次滑动时又可以啦。使用版本：1.4.10

**Comment by is1988** [comment]
嗯 问题一直 多次测试才发现是RecyclerView的嵌套问题 直接一直以为是headview
