### ISSUE TITLE
设置indicator选中和未选中的颜色后indicator变成了方形的，即使代码中设置了圆形的style

### ISSUE THREAD

**Issue by lyw-coder** [youth5201314/banner#318]

**Comment by xiyunanhai1028** [comment]
你可以直接把圆形图片加载到里面
 <com.youth.banner.Banner xmlns:app="http://schemas.android.com/apk/res-auto"
        android:id="@+id/banner"
        android:layout_width="match_parent"
        android:layout_height="@dimen/x360"
        app:banner_default_image="@drawable/default_banner"
        app:indicator_drawable_selected="@drawable/indicator_blue"
        app:indicator_drawable_unselected="@drawable/indicator_white"
        app:indicator_height="@dimen/x15"
        app:indicator_width="@dimen/x15"/>

<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="oval">
    <size
        android:width="@dimen/x20"
        android:height="@dimen/x20" />
    <solid android:color="@color/colorPrimaryDark" />

<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="oval">
    <size
        android:width="@dimen/x20"
        android:height="@dimen/x20" />
    <solid android:color="@color/whiteText" />

</shape>

**Comment by SkyZhang2013** [comment]
请问解决了吗，必须要自定义吗

**Comment by lyw-coder** [comment]
解决了，自定义shape就可以了~~
