### ISSUE TITLE
如果纯代码创建的setBannerStyle()不起作用，指示器出不来。我改成xml就可以

### ISSUE THREAD

**Issue by tikeyc** [youth5201314/banner#320]
如：
Banner headViewBanner = new Banner(getActivity());
        headViewBanner.setBackgroundColor(Color.GRAY);
        LinearLayout.LayoutParams layoutParams = new LinearLayout.LayoutParams(DensityUtil.getScreenWidth(), DensityUtil.dip2px(200));
        headViewBanner.setLayoutParams(layoutParams);
headViewBanner.setBannerStyle(BannerConfig.CIRCLE_INDICATOR);//不起作用
指示器出不来。
然后我改成xml指示器才出来：
Banner headViewBanner = (Banner) LayoutInflater.from(getActivity()).inflate(R.layout.banner_head_view, recyclerView, false);

**Comment by qssq** [comment]
可以试试我的项目https://github.com/qssq/banner 没那么花哨，但是很多布局很容易调整。
