### ISSUE TITLE
死活加载不出来圆角图片，求大神help

### ISSUE THREAD

**Issue by lh414035210** [youth5201314/banner#325]
![image](https://user-images.githubusercontent.com/24253339/32538402-dda0a6be-c4a0-11e7-9b76-73b95846e0bd.png)
![image](https://user-images.githubusercontent.com/24253339/32538420-eb374e36-c4a0-11e7-887d-7e60273e13d6.png)
![image](https://user-images.githubusercontent.com/24253339/32538431-f84687cc-c4a0-11e7-8b41-97de239c3d81.png)

**Comment by riven-du** [comment]
自己实现ImageLoaderInterface，自己写圆角的ImageView就行了啊

**Comment by lh414035210** [comment]
![image](https://user-images.githubusercontent.com/24253339/32657941-a1d1b3a4-c652-11e7-96b3-50363509a0a2.png)
 我这不是用glide加载了y圆角么，还是显示不出来啊

**Comment by lh414035210** [comment]
![image](https://user-images.githubusercontent.com/24253339/32658365-92d6461a-c654-11e7-9389-18924b71e23a.png)
  
c从这里传入imageview自定义的imageview进去？   貌似挺麻烦的啊

**Comment by riven-du** [comment]
![4a81aebc-20e9-457c-9d59-cc64b5af1fef](https://user-images.githubusercontent.com/19404514/32658872-053cc6b4-c657-11e7-86fa-569714793d82.jpeg)    兄弟，你没有理解，作者这个接口用意，阅读以下他的源码

**Comment by lh414035210** [comment]
好像懂了点，不再一头雾水了！  谢了，我在试试能不能改出来！

**Comment by jp1017** [comment]
https://github.com/youth5201314/banner/blob/master/app/src/main/java/com/test/banner/loader/GlideImageLoader.java 把圆角注释打开就可以了
