### ISSUE TITLE
图片宽度大于屏幕宽度时，图片旁边有一片是显示的左右的图片

### ISSUE THREAD

**Issue by renshaodong** [youth5201314/banner#327]

**Comment by caiguangzhao** [comment]
我也遇到过，是用picasso去加载图片的，然后换成glide就可以，不知道什么原因。

**Comment by caiguangzhao** [comment]
刚找到，在xml上面设置app:image_scale_type="fit_xy"这个属性就好

**Comment by renshaodong** [comment]
我就是用glide加载的，用的是centercrop

**Comment by yunfei01cs** [comment]
app:image_scale_type="fit_xy"后，会导致图片变形，如果比例不匹配的话

**Comment by yunfei01cs** [comment]
app:image_scale_type="fit_xy"后，会导致图片变形，如果比例不匹配的话

banner.xml的com.youth.banner.view.BannerViewPager不知作者为什么设置成android:clipChildren="false"

**Comment by LiuYiAC** [comment]
我用Gilde加载图片，然后fit_xy也设置了 如果图片巨宽 这个还是不行

**Comment by LiuYiAC** [comment]
我用fit_center图片就不会这样了
