### ISSUE TITLE
改变指示器颜色，圆点就会变成正方形

### ISSUE THREAD

**Issue by SeavenZhang** [youth5201314/banner#337]
只要设置了app:indicator_drawable_unselected（selected）=""，对应状态的圆点就成正方形了，要怎么解决，谢谢

**Comment by caobin821651400** [comment]
改源码，指示器的iamgeview是固定宽高的，

**Comment by coderkanb** [comment]
@SeavenZhang 要自己写一个shape，圆形的（oval），demo和源码里都是这样实现的。
