### ISSUE TITLE
gradle:3.0.0 下依赖错误。

### ISSUE THREAD

**Issue by abings** [youth5201314/banner#338]
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve compile '. Open File Show Details

app中buildTypes集合不是library的buildTypes集合子集，即app中buildType属性preview在依赖的library中找不到。你是不是需要buildTypes {
        release {
            ...
        }
        //增加这个代码，release， debug为library中已有buildType
     preview {
            ...
       
            matchingFallbacks = ['release', 'debug']
        }
        debug {
            ...
        }
    }

**Comment by NicodeLee** [comment]
3.0没问题的，看文档检查下吧
