### ISSUE TITLE
banner添加到recyclerview中的问题

### ISSUE THREAD

**Issue by a1048823898** [youth5201314/banner#34]
把banner添加到recyclerview中的一个viewtype中。下拉后返回顶部。banner翻页速度会非常快，直接无动画切换效果了，另外使用WeakReference fix会检测出 内存泄漏问题

**Comment by youth5201314** [comment]
我也加入了recyclerview但是没有问题，出现问题很正常，每个人的代码环境不一样，如果方便就提供你的代码，我不可能就一定能和你出现同样的问题。
