### ISSUE TITLE
动态加载新图片的时候，卡顿严重

### ISSUE THREAD

**Issue by SickoOrange** [youth5201314/banner#341]
在一个activity中，动态下载新的图片然后加载到轮播图中，卡顿

**Comment by SickoOrange** [comment]
下载没问题，banner每次数据都是空的，然后加载新的一组图片，发现加载图片的时候 效率很低，造成卡顿

**Comment by youth5201314** [comment]
加载图片效率问题是第三方的图片加载器问题，跟banner没有关系，加载图片的方法暴露出来了的
