### ISSUE TITLE
banner_default_image支持更改scaleType吗

### ISSUE THREAD

**Issue by kona5362** [youth5201314/banner#349]

**Comment by github5216** [comment]
你可以试试app:image_scale_type，这个属性看看能否生效

**Comment by HuJunYan** [comment]
I try  and success ,when you user the createImage  setting imageAttrbues.

**Comment by lizuojing** [comment]
app:image_scale_type这个属性完全不起作用啊！自定义bannerview会有问题，很多属性都不起作用了，效果完全达不到预期。

**Comment by Night-Kang** [comment]
+1
