### ISSUE TITLE
 You cannot start a load for a destroyed activity

### ISSUE THREAD

**Issue by ChangBaofeng** [youth5201314/banner#362]
// Short Msg: java.lang.IllegalArgumentException
// Long Msg: java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity
// Build Label: Meizu/meizu_PRO7H/PRO7H:7.0/NRD90M/1501691093:user/release-keys
// Build Changelist: 1501691093
// Build Time: 1501691092000
// java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity
// 	at com.bumptech.glide.manager.RequestManagerRetriever.assertNotDestroyed(RequestManagerRetriever.java:134)
// 	at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:102)
// 	at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:87)
// 	at com.bumptech.glide.Glide.with(Glide.java:629)
// 	at com.dragonfb.dragonball.main.firstpage.GlideImageLoader.displayImage(GlideImageLoader.java:34)
// 	at com.dragonfb.dragonball.main.firstpage.GlideImageLoader.displayImage(GlideImageLoader.java:16)
// 	at com.youth.banner.Banner.setImageList(Banner.java:361)
// 	at com.youth.banner.Banner.start(Banner.java:269)

"modelName": "meizu_M5 Note"

**Comment by ChangBaofeng** [comment]
what ,这里不知道填写啥

**Comment by youth5201314** [comment]
很明显啊，你的Activity被销毁了，但是你的图片还在加载，用getApplicationContext()就行了

**Comment by ChangBaofeng** [comment]
早就用getApplicationContext()这个了。。就魅族"modelName": "meizu_M5 Note"的那款手机会出现这样的问题。审核不通过。其他平台的都过了。

**Comment by ChangBaofeng** [comment]
我又修改了一些东西，，看看这次能不能通过把
