### ISSUE TITLE
banner_layout

### ISSUE THREAD

**Issue by ChangBaofeng** [youth5201314/banner#365]
<com.youth.banner.Banner xmlns:app="http://schemas.android.com/apk/res-auto"
                android:id="@+id/banner"
                app:banner_layout="@+id/bannerContainer"
                android:layout_width="match_parent"
                android:layout_height="@dimen/dimen_422dp"/>

banner_layout属性是这样用的吗？直接挂掉，，小白求教。

**Comment by ChangBaofeng** [comment]
android:layout_height是有固定值的，

**Comment by youth5201314** [comment]
这个是给需要修改布局文件用的，你不用就删掉，android:layout_height高度你自己设置，你动态也好写死也好，自己发挥

**Comment by ChangBaofeng** [comment]
就是要修改布局文件的，加入这个属性就报错，demo里面没找到范例

**Comment by youth5201314** [comment]
文档描述的很清楚啊，你只要保证id不变，你复制一份修改不就行了啊，然后将layout的id 设置进去就ok了啊，已经很简单了，实在用不了就本地依赖吧

**Comment by ChangBaofeng** [comment]
就是按照文档走的，，改成本地依赖把还是。

**Comment by zhaoxiuyu** [comment]
@youth5201314  大神 ，可以轮播其他的View吗，比如recycleView
