### ISSUE TITLE
部分手机banner划出屏幕再划入屏幕会概率出现白屏现象及解法，期待项目作者给出更优的解决办法

### ISSUE THREAD

**Issue by shutiger** [youth5201314/banner#367]
## 现象
将banner划出屏幕再划入屏幕会概率性出现banner变白的问题；在华为的某些机型上复现机率更大。
经过多次实验发现并不是概率性出现，banner出现白屏的条件是，由最后一个图切到第一个图时，迅速划出屏幕再划入屏幕就会出现上述现象。
## 分析原因
可能的原因是，这个项目中为了实现循环，是在前面和后面各加了一个item，当由最后一个item划到第一个item时，实际是划到了新加的最后一项，按道理项目中会触发如下代码(代码来自于banner类)
``` java
    private final Runnable task = new Runnable() {
        @Override
        public void run() {
            if (count > 1 && isAutoPlay) {
                currentItem = currentItem % (count + 1) + 1;
//                Log.i(tag, "curr:" + currentItem + " count:" + count);
                if (currentItem == 1) {
                    viewPager.setCurrentItem(currentItem, false);
                    handler.post(task);
                } else {
                    viewPager.setCurrentItem(currentItem);
                    handler.postDelayed(task, delayTime);
                }
            }
        }
    };
```
上面代码执行完后，会将currentItem(原来的值是新加的最后一项的值)重置为1，并调用了setCurrentItem（1，false）,由于第二个参数是false，**所以用户看不到滑动动作的情况下由新加的一项切到了第一项**。这里没有问题，出问题的应该是在如下代码(代码来自于banner类)
``` java
    class BannerPagerAdapter extends PagerAdapter {

        @Override
        public int getCount() {
            return imageViews.size();
        }

        @Override
        public boolean isViewFromObject(View view, Object object) {
            return view == object;
        }

        @Override
        public Object instantiateItem(ViewGroup container, final int position) {
            container.addView(imageViews.get(position));
            View view = imageViews.get(position);
            if (listener != null) {
                view.setOnClickListener(new OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        listener.OnBannerClick(toRealPosition(position));
                    }
                });
            }
            return view;
        }
        @Override
        public void destroyItem(ViewGroup container, int position, Object object) {
            container.removeView((View) object);
        }
    }
```
我们都知道如果没有手动设置，viewPager默认会加载当前项的前一项和后一项，当切到最后一项时，很明显第一项是已经回收了，这个时候如果第一项还没有走初始化方法而直接切到第一项你看到的就是一个白屏，个人猜测，华为机型系统对viewPager做了一个优化，即，当viewPager不可见时，会先调用destroyItem方法，但会延迟调用instantiateItem方法，这就解释了，当用户把banner划出屏幕时，由最后一项切换到了第一项（如上面黑体部分文字所述），这个时候第一项还没有走instantiateItem方法，所以第一项还没有创建出来，所以会出现白屏。
## 目前的解决办法
个人能力有限只想到了如下这个方法来解决目前的问题，即用户划入屏幕会调用onAttachedToWindow，所以把如下代码加入到banner类即可，其它人有好的方法可以评论到后面，帮助作者优化这个项目。
``` java
    @Override
    protected void onAttachedToWindow() {
        super.onAttachedToWindow();
        if (currentItem == (count + 1)) {
            viewPager.setCurrentItem(1, false);
            onPageSelected(1);
            adapter.notifyDataSetChanged();
        }
    }
```
注意：onPageSelected(1)这一句是因为出现白屏后，会伴随出现indicatorImages中资源出错，所以重新走一遍onPageSelected(1)方法来绑定一次定位器。

**Comment by djjackylei** [comment]
我也是碰到这个问题，感谢分享解决方案

**Comment by MrDeclanCoder** [comment]
这样做的话 就不能用compile的方式依赖该库了吧

**Comment by OathkeeperDL7** [comment]
谁有更好的方法？？分享一下啊，？

**Comment by OathkeeperDL7** [comment]
试了你的方法为什么没用啊? @shutiger

**Comment by AppUU** [comment]
如果是在列表中添加header，header的布局只有Banner才不会出现空白

**Comment by AppUU** [comment]
使用在列表中，Banner不要嵌套在其他布局中

**Comment by AppUU** [comment]
在RecyclerView中使用时候，要控制高度的话可以获取屏幕的宽高再算个比例，比如高度的1/4或宽度的1/2等等，如：banner.setLayoutParams(new RecyclerView.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, widthPixels / 2));

**Comment by huangzhaohao** [comment]
感谢分享解决方案，能解决从最后一张图刚切到第一张图时划出屏幕再划入屏幕出现的空白问题，但是从最后一张图快要切到第一张图时就划出屏幕，再划入屏幕还是会出现空白，不知道有没有更好的解决办法？

**Comment by nicelyjust** [comment]
@shutiger 老哥 request push

**Comment by plplum** [comment]
> 列表中，Banner不要嵌套在其他布局中

我处理后有效果

**Comment by leigayu** [comment]
> 使用在列表中，Banner不要嵌套在其他布局中

就是说，不要作为header吗？如果想跟随列表滑动的怎么办
