### ISSUE TITLE
不循环播放如何实现

### ISSUE THREAD

**Issue by zhouxxiaolong** [youth5201314/banner#369]
就是从第一个到最后一个，不能从最后一个到第一个，如何实现，谢谢

**Comment by xiang473535976** [comment]
我也需要这个功能     禁止循环  希望大婶更新哈 @youth5201314

**Comment by fishyuyu** [comment]
Auoscoll =flase?
属性有吧

**Comment by MuseYkh** [comment]
不知道还能否帮的上，我开了个fork，已经实现了这个效果，可以参照我所修改的Banner类https://github.com/MuseYkh/banner
