### ISSUE TITLE
无数据的时候，点击默认图片报错，除数不能为零

### ISSUE THREAD

**Issue by swt930** [youth5201314/banner#371]

**Comment by swt930** [comment]
一个界面，可根据地址切换数据和顶部Banner
两个问题：
1 ，切换的地址无数据的时候，banner默认显示的图片如何修改？ 
2 ，切换地址无数据的时候，点击默认图片报错，除数不能为零

**Comment by swt930** [comment]
![image](https://user-images.githubusercontent.com/10876333/34663341-5857bb3e-f491-11e7-986a-6470a940a811.png)

**Comment by a512509050** [comment]
+1

**Comment by guyulei** [comment]
+1
