### ISSUE TITLE
update(List<?> imageUrls)	更新图片失败

### ISSUE THREAD

**Issue by JavaBoyHW** [youth5201314/banner#375]
我在Button的点击事件中，想增加一张图片进Banner。
我再原图片集合mImageList中增加一个，然后调用mBanner.update(mImageList)；Banner图区域显示暂无图片。是不是除了调用update(mImageList)方法外还有其他操作？

**Comment by morethanmore** [comment]
我也遇到了同样的问题，不知为何

**Comment by lovesunflower** [comment]
清一下glide缓存

**Comment by 179098051** [comment]
我也遇到了同样的问题 蛋疼

**Comment by huangzhaohao** [comment]
我也遇到了同样的问题，调试发现update方法中调用了this.imageUrls.clear();这行代码后传进来的参数imageUrls的size也变为0了。目前解决办法是调用mBanner.setImages方法跟调用mBanner.update方法传不同的List对象

**Comment by devzwy** [comment]
同样遇到，更新数据时直接黑了。求解。

**Comment by devzwy** [comment]
@huangzhaohao 求解。我传的list是不同的对象。

**Comment by huangzhaohao** [comment]
@devzwy 你是报了什么错？

**Comment by devzwy** [comment]
@huangzhaohao 您好，我这边没有任何错误。看了Banner的代码，也是OK的。但是执行更新代码后，轮播图直接黑屏，啥没显示。

**Comment by huangzhaohao** [comment]
@devzwy 轮播图显示黑屏，程序没崩？

**Comment by devzwy** [comment]
@huangzhaohao  `  ArrayList<String> a =new ArrayList<>();
        a.add("http://imgstore04.cdn.sogou.com/v2/thumb/dl/12638245.jpg?appid=10150005&referer=sogou.com&url=https://img03.sogoucdn.com/app/a/100520021/7bdf96a88cf6e623f968f703e7879fdb");
        a.add("http://imgstore03.cdn.sogou.com/v2/thumb/dl/12638649.jpg?appid=10150005&referer=sogou.com&url=https://img04.sogoucdn.com/app/a/100520021/efce3f6d144e57a35cdd14bf8198d8eb");
        mBanner.update(a);`

**Comment by devzwy** [comment]
@huangzhaohao 程序没奔，只是轮播图控件黑屏。

**Comment by huangzhaohao** [comment]
@devzwy 这样我也看不出来，能不能把相关的代码都发下？也可能是版本问题，你用的是什么版本的，我用的1.4.10，加QQ283051928讨论下也可以

**Comment by devzwy** [comment]
@huangzhaohao 请求添加您了，谢谢啦。

**Comment by zhangshaobo87** [comment]
确实是这样  最好每次更新的时候新建一个集合对象穿进去

**Comment by qczgwxg** [comment]
我也遇到这个问题啦，报这个错误banner: The image data set is empty
