### ISSUE TITLE
初始化多次，图片显示不出来；

### ISSUE THREAD

**Issue by FY6** [youth5201314/banner#376]
banner.setBannerStyle(BannerConfig.NUM_INDICATOR)//设置banner样式
                                    .setImageLoader(new FrescoImageLoader())//设置图片加载器
                                    .setImages(adTurnImages.getFiles())//设置图片集合
                                    .setBannerAnimation(Transformer.DepthPage)//设置banner动画效果
                                    .setIndicatorGravity(BannerConfig.RIGHT)//设置指示器位置（当banner模式中有指示器时）
                                    .start() //banner设置方法全部调用完毕时最后调用
                                    .stopAutoPlay();

**Comment by MirrorFlower** [comment]
我也是遇到这个问题  你解决了吗？ 初始化多次 图片就加载不出来了
