### ISSUE TITLE
Glide加载drawable资源文件

### ISSUE THREAD

**Issue by Fermaa** [youth5201314/banner#38]
我用glide加载drawable里的资源文件报错，看你的demo中是直接加载网络图片，没有加载资源文件里的图片

**Comment by youth5201314** [comment]
![image](https://cloud.githubusercontent.com/assets/8827239/19225281/9f75c006-8ecb-11e6-9dc3-a3ecad89e3e1.png)

**Comment by Fermaa** [comment]
谢谢，已经解决了，是我的写法有问题
