### ISSUE TITLE
刷新设置数据的时候，闪白没人遇到吗

### ISSUE THREAD

**Issue by zhangniuniu** [youth5201314/banner#383]
我每次刷新设置数据时，都发现会闪一下，没人遇到吗，我调的方法update

**Comment by zhangniuniu** [comment]
。

**Comment by protectedMan** [comment]
解决了吗

**Comment by zhangniuniu** [comment]
> 解决了吗

好久了，记得是改了代码，加了缓存。作者写的 每次刷新数据，都重新创建每个条目，加缓存后，可以复用，而且可以加入tag，判断条目的图片url是否改变，没改 都不需要加载，不过glide这些框架，本身处理了的，本地缓存不加tag也可以
