### ISSUE TITLE
指示器图形的问题

### ISSUE THREAD

**Issue by Ocesdi** [youth5201314/banner#389]
app:indicator_drawable_selected="drawable/indicator_selected"
我的效果是想让指示器显示一个圆角矩形，当他选中的时候比未选中的时候要长一点。
我试图修改drawable，里面是一个矩形，但是运行的结果却是一个小方块点。
请问如何可以显示这个效果？

**Comment by taixiang** [comment]
@Ocesdi 我也有这个需求，  请问你解决没？

**Comment by Ocesdi** [comment]
还没有，想先问问，如果不行再找个库试试。

**Comment by izhuyifei** [comment]
设置指示器相应的宽高属性：indicator_height   ／ indicator_width

**Comment by Ocesdi** [comment]
嗯  上面的问题解决了，修改指示器的宽高，另外还删除了创建指示器中的一行代码 imageView.setScaleType(ScaleType.CENTER_CROP);

**Comment by HaoPz** [comment]
@Ocesdi  您好，我也遇到了这个问题，  app:indicator_width 也设置了 
  app:indicator_drawable_selected 设置了图片或者shape(shape 也有指定宽高)，结果都还是指示器选中和未选中的长度一致的

**Comment by drowtram** [comment]
> @Ocesdi 您好，我也遇到了这个问题， app:indicator_width 也设置了
> app:indicator_drawable_selected 设置了图片或者shape(shape 也有指定宽高)，结果都还是指示器选中和未选中的长度一致的

把源码中的Banner类单独提取出来，修改createIndicator方法如下：
```java
private void createIndicator() {
        this.indicatorImages.clear();
        this.indicator.removeAllViews();
        this.indicatorInside.removeAllViews();

        for(int i = 0; i < this.count; ++i) {
            ImageView imageView = new ImageView(this.context);
//            imageView.setScaleType(ScaleType.CENTER_CROP);
            android.widget.LinearLayout.LayoutParams params = new android.widget.LinearLayout.LayoutParams(this.mIndicatorWidth, this.mIndicatorHeight);
            params.leftMargin = this.mIndicatorMargin;
            params.rightMargin = this.mIndicatorMargin;
            if (i == 0) {
                imageView.setImageResource(this.mIndicatorSelectedResId);
            } else {
                imageView.setImageResource(this.mIndicatorUnselectedResId);
            }

            this.indicatorImages.add(imageView);
            if (this.bannerStyle != 1 && this.bannerStyle != 4) {
                if (this.bannerStyle == 5) {
                    this.indicatorInside.addView(imageView, params);
                }
            } else {
                this.indicator.addView(imageView, params);
            }
        }

    }
```
然后布局引用自己的Banner，把`indicator_height ／ indicator_width`设置成最大的indicator的宽高即可解决。

**Comment by returntoorigin** [comment]
> 嗯 上面的问题解决了，修改指示器的宽高，另外还删除了创建指示器中的一行代码 imageView.setScaleType(ScaleType.CENTER_CROP);

请问你是本地引用删除了这一行代码么

**Comment by drowtram** [comment]
> > 嗯 上面的问题解决了，修改指示器的宽高，另外还删除了创建指示器中的一行代码 imageView.setScaleType(ScaleType.CENTER_CROP);
> 
> 请问你是本地引用删除了这一行代码么

是的。
