### ISSUE TITLE
配合下拉刷新会有小bug

### ISSUE THREAD

**Issue by kxs109** [youth5201314/banner#39]
偶尔会有异常10-13 10:05:46.392: E/AndroidRuntime(7843): java.lang.IndexOutOfBoundsException: Invalid index 2, size is 2

10-13 10:05:46.392: E/AndroidRuntime(7843): 	at com.fragment.DynamicAllFrag$4.OnBannerClick(DynamicAllFrag.java:186)

**Comment by youth5201314** [comment]
你是按照我的demo写的吗

**Comment by kxs109** [comment]
是的
