### ISSUE TITLE
recyclerView中嵌套的banner，自动轮播时，每次当最后一个滑完到第一个图的时候，第一图需要加载一下。

### ISSUE THREAD

**Issue by Ocesdi** [youth5201314/banner#391]
描述一下：
我做的是平板自动轮播，一个页面显示三张图的哪种。每次轮播结束从头开始的时候，之间都会重新加载一下。使得轮播效果不连贯，给人卡顿的感觉。请问这是什么原因导致的，有没有办法修改使其连贯呢？

**Comment by CK875430315** [comment]
最后一张回到第一张，马上又重新加载一次第一张，这个过程会闪动怎么解决的额
