### ISSUE TITLE
ArithmeticException

### ISSUE THREAD

**Issue by LengM** [youth5201314/banner#397]
#1247 java.lang.ArithmeticException
divide by zero

com.youth.banner.Banner.onPageSelected(Banner.java:586)

**Comment by wangxue** [comment]
问题场景为数据源有更新，新数据数量为0，调用start方法就会出现上述错误。 

更新数据必须调用update方法，如果调用start方法会导致代码中imagelist和count有改变，但是viewPagerAdapter的数据源未改变，直接导致后续可能的除0错误。 

此处作者设计api不够合理。
