### ISSUE TITLE
建议支持比较常见的画廊效果

### ISSUE THREAD

**Issue by zjhcode** [youth5201314/banner#399]
就是一屏显示多个View，View之间有一定的间隔

**Comment by xiaolongwuhpu** [comment]
支持这个想法,大家也很喜欢这个效果

**Comment by bobohackbutter** [comment]
private void getViewPagerFromBanner() throws NoSuchFieldException, IllegalAccessException {
        Field fieldViewPager = Banner.class.getDeclaredField("viewPager");
        fieldViewPager.setAccessible(true);
        BannerViewPager viewPager= (BannerViewPager) fieldViewPager.get(banner);
        viewPager.setClipChildren(false);
        viewPager.setPageMargin(100);
        viewPager.setPageMargin(20);
        RelativeLayout.LayoutParams lp=new RelativeLayout.LayoutParams(viewPager.getLayoutParams());
        lp.setMargins(100,0,100,0);
        viewPager.setLayoutParams(lp);
//
//        BannerViewPager viewPager1 = null;
//        RelativeLayout rl1= (RelativeLayout) banner.getChildAt(0);
//        rl1.setClipChildren(false);
//        for (int i=0;i<rl1.getChildCount();i++){
//            View v=rl1.getChildAt(i);
//            Log.e("asd",v.toString());
//            if (v instanceof BannerViewPager){
//                viewPager1= (BannerViewPager) v;
//                viewPager1.setClipChildren(false);
//                viewPager1.setPageMargin(20);
//                RelativeLayout.LayoutParams lp=new RelativeLayout.LayoutParams(viewPager1.getLayoutParams());
//                lp.setMargins(100,0,100,0);
//                viewPager1.setLayoutParams(lp);
//                return;
//            }
//        }
    }
两种方法，可以实现画廊的效果。希望作者能提供个getViewpager 的方法

**Comment by HancockY** [comment]
上面的方法可以实现, 但是后边的图片会有显示空白的情况..
