### ISSUE TITLE
下拉刷新 有缓存问题

### ISSUE THREAD

**Issue by xyan988** [youth5201314/banner#40]
我的banner 有三张图，下拉刷新时 后台改变了 第二张第三章的顺序，发现banner  第二张图片和第三张图片重复了

**Comment by xyan988** [comment]
第一次轮播时时重复的，第二次轮播恢复正常，请问是什么原因

**Comment by youth5201314** [comment]
这个是之前的图片存储在内存中，如果你需要马上改变，就需要从新在初始化一次banner就行了

**Comment by xyan988** [comment]
我试过了，这样不行，还是存在问题

**Comment by xyan988** [comment]
没有什么方法可以清除以前加载的图片么？

**Comment by xyan988** [comment]
我的解决方式： 刷新之前，先将数据源清空 执行加载banner，获取数据后在 执行一边加载 banner

**Comment by huangliao** [comment]
我后台有3张图片 删除了第一张  在页面刷新 ( 重置banner )  标题改变了 , 图片没有改变,  我在glideImageLoad中输出path路径, 发现多输出了两次 , 有一张图片是后台已经删除,还有输出.

**Comment by xlc1540697096** [comment]
有没有异步加载网络图片的方法，新手第一次使用，fragment中在执行onCreateView时还没有拿到图片地址。导致空白页。我该怎么解决

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by huangliao** [comment]
这个是没有办法的,因为加载图片要一个过程,获取数据也要时间 , 我是用hanler +msg 做异步的 网络正常情况下空白不是很久啊

**Comment by youth5201314** [comment]
你有毛病吗？不停地提交！加载图片用第三方的加载器啊，你就不能等网络请求完再去初始化，多大个事！

**Comment by youth5201314** [comment]
你有毛病吗？不停地提交！加载图片用第三方的加载器啊，你就不能等网络请求完再去初始化，多大个事！

**Comment by huangliao** [comment]
博主 不好意思呐 ,刚刚网络出了问题,页面一直在刷新就提交了这么多~.~
