### ISSUE TITLE
希望添加轮播图片显示圆角设置

### ISSUE THREAD

**Issue by onedreamyyc** [youth5201314/banner#402]
这个banner框架Glide添加圆角处理，没有效果，希望作者处理下

**Comment by Andy319** [comment]
我今天也发现了。

**Comment by MirrorFlower** [comment]
public class PicassoImageLoader extends ImageLoader {
    @Override
    public void displayImage(Context context, Object path, ImageView imageView) {
        Picasso.with(context).load((String) path).transform(new PicassoRoundTransform(60)).into(imageView);
    }
}
我用Picasso发现也没有效果。。。

**Comment by weiwenhuaming01** [comment]
可以在imageloader里面的createImageView方法返回给banner 处理过的imageview,再在display中调用就可以了

**Comment by onedreamyyc** [comment]
@weiwenhuaming01 我在createImageView里面自定义了一个ImageView，实现圆角了，但是显示的效果是图片一出来是直角 然后在变成圆角

**Comment by jp1017** [comment]
https://github.com/youth5201314/banner/blob/master/app/src/main/java/com/test/banner/loader/GlideImageLoader.java 把圆角注释打开就可以了

**Comment by weiwenhuaming01** [comment]
`[package cc.fedtech.rugaoapp.net;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.Path;
import android.os.Build;
import android.util.AttributeSet;
import android.view.View;

import com.scwang.smartrefresh.layout.util.DensityUtil;


/**
 * Created by zz on 2018/1/3.
 *
 * 圆角ImageView
 */

public class RoundImageView extends android.support.v7.widget.AppCompatImageView {

    private Context mContext;
    float width,height;
    private int mRadiusPx;

    public RoundImageView(Context context) {
        this(context, null);
    }

    public RoundImageView(Context context, AttributeSet attrs) {
        this(context, attrs, 0);
    }

    public RoundImageView(Context context, AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
        mContext = context;
        mRadiusPx = DensityUtil.dp2px(5);
        if (Build.VERSION.SDK_INT < 18) {
            setLayerType(View.LAYER_TYPE_SOFTWARE, null);
        }
    }

    @Override
    protected void onLayout(boolean changed, int left, int top, int right, int bottom) {
        super.onLayout(changed, left, top, right, bottom);
        width = getWidth();
        height = getHeight();
    }

    @Override
    protected void onDraw(Canvas canvas) {

        //这里的目的是将画布设置成一个顶部边缘是圆角的矩形
        if (width > mRadiusPx && height > mRadiusPx) {
            Path path = new Path();

            path.moveTo(mRadiusPx, 0);
            path.lineTo(width - mRadiusPx, 0);
            path.quadTo(width, 0, width, mRadiusPx);
            path.lineTo(width, height - mRadiusPx);
            path.quadTo(width, height, width - mRadiusPx, height);
            path.lineTo(mRadiusPx, height);
            path.quadTo(0, height, 0, height - mRadiusPx);
            path.lineTo(0, mRadiusPx);
            path.quadTo(0, 0, mRadiusPx, 0);


            canvas.clipPath(path);
        }

        super.onDraw(canvas);
    }
}

](url)`

我是这么写的

**Comment by onedreamyyc** [comment]
@weiwenhuaming01 用你这个也有个直角边圆角的这个过程

**Comment by weiwenhuaming01** [comment]
我用的没有这个问题,你看下你的布局和用法有没有搞错

**Comment by onedreamyyc** [comment]
@weiwenhuaming01 
public class GlideImageLoader extends ImageLoader {
    @Override
    public void displayImage(Context context, Object path, ImageView imageView) {
        /**
         注意：
         1.图片加载器由自己选择，这里不限制，只是提供几种使用方法
         2.返回的图片路径为Object类型，由于不能确定你到底使用的那种图片加载器，
         传输的到的是什么格式，那么这种就使用Object接收和返回，你只需要强转成你传输的类型就行，
         切记不要胡乱强转！
         */
        //Glide 加载图片简单用法\
        Glide.with(context.getApplicationContext()).load(path).into(imageView);

//        //Picasso 加载图片简单用法
//        Picasso.with(context).load(path).into(imageView);

        //用fresco加载图片简单用法，记得要写下面的createImageView方法
//        Uri uri = Uri.parse((String) path);
//        imageView.setImageURI(uri);
    }

    @Override
    public ImageView createImageView(Context context) {
        //圆角
        return new RoundImageView(context);
    }

**Comment by Danniel-yan** [comment]
> 可以在imageloader里面的createImageView方法返回给banner 处理过的imageview,再在display中调用就可以了

**Comment by Danniel-yan** [comment]
> @weiwenhuaming01
> public class GlideImageLoader extends ImageLoader {
> @override
> public void displayImage(Context context, Object path, ImageView imageView) {
> /**
> 注意：
> 1.图片加载器由自己选择，这里不限制，只是提供几种使用方法
> 2.返回的图片路径为Object类型，由于不能确定你到底使用的那种图片加载器，
> 传输的到的是什么格式，那么这种就使用Object接收和返回，你只需要强转成你传输的类型就行，
> 切记不要胡乱强转！
> */
> //Glide 加载图片简单用法
> Glide.with(context.getApplicationContext()).load(path).into(imageView);
> 
> // //Picasso 加载图片简单用法
> // Picasso.with(context).load(path).into(imageView);
> 
> ```
>     //用fresco加载图片简单用法，记得要写下面的createImageView方法
> ```
> // Uri uri = Uri.parse((String) path);
> // imageView.setImageURI(uri);
> }
> 
> ```
> @Override
> public ImageView createImageView(Context context) {
>     //圆角
>     return new RoundImageView(context);
> }
> ```


请问这里的图片展示怎么让它宽度全屏？我在ImageView的控件中设置match_parent无效，不知道什么原因。。。

**Comment by qianshengta** [comment]
我也是这个问题 加载过来的图片和ImageView都是圆角的  一般显示也是圆角，但是只要滑动起来，过程中会变直角，我猜大概是根布局是个直角的。后来有人建议用ViewOutlineProvider直接把Banner裁剪成圆角的，真的成功了，正当我兴高采烈的以为问题解决了的时候，后面又变回老样子了。后来多次测试发现，只有在每次新装APP第一次打开的时候ViewOutlineProvider裁剪圆角才有效，后面再次打开又变回老样子了

**Comment by zhaichuankai** [comment]
banner.setOutlineProvider(new ViewOutlineProvider() {
                    @Override
                    public void getOutline(View view, Outline outline) {
                        outline.setRoundRect(0, 0, view.getWidth(), view.getHeight(), 6);
                    }
                });

亲测有用

**Comment by youth5201314** [comment]
内置的有方法哈，demo和文档有说明，看源码也行
