### ISSUE TITLE
设计缺陷：

### ISSUE THREAD

**Issue by EricMikaelson** [youth5201314/banner#410]
当setImageList(List<?>)imagesUrl 集合的size 为1 时，依然创建了三个ImageView 视图，而实际上单个视图时是不需要创建三个ImageView的。因为一张图片是不需要轮播的,只需创建一个ImageView, 减少资源的使用，也减少load 图片url 的次数。

**Comment by ZuoDong** [comment]
同感，把代码下载下来自己修改了

**Comment by qssq** [comment]
https://github.com/qssq/Banner
