### ISSUE TITLE
java.lang.IllegalStateException  The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 6, found: 0 Pager id: 

### ISSUE THREAD

**Issue by 1226362423** [youth5201314/banner#412]
偶尔出现这种问题是什么情况

**Comment by itdais** [comment]
我也出现这样的问题

**Comment by eziwen** [comment]
+1

**Comment by yinbiaos** [comment]
这个问题我找到了原因，第一次加载正常，按返回键后退出，没有杀死程序进程，第二次进来，调试banner中存在adapter,且数据不为空，如下图
![image](https://user-images.githubusercontent.com/12043685/53863549-786eb680-4025-11e9-86a7-7e40fda09e3c.png)
然后执行banner.start(); start()方法中setImageList方法会修改数据集，并且调整视图，而数据集修改后，没有notifyDataSetChanged，因此抛出异常。
![image](https://user-images.githubusercontent.com/12043685/53863806-08146500-4026-11e9-8c6b-bdb6100e7ca0.png)
解决方案是，退出程序后，杀死进程，确保banner被销毁。或者设置banner之前，先确保banner的adapter为空。

**Comment by 1226362423** [comment]
调用update方法设置数据
