### ISSUE TITLE
卡住的问题

### ISSUE THREAD

**Issue by MirrorFlower** [youth5201314/banner#42]
当用手指朝一个放向滑动banner的时候，多滑几下，会出现卡住，划不动的情况。

**Comment by youth5201314** [comment]
此问题已知道，但是年底了很忙，项目特别多，会过很长短时间才会更新，你可以加大buffer试下！

**Comment by xyan988** [comment]
我也遇到这个问题，在哪里设置buffer

**Comment by MIkeeJY** [comment]
banner.setDelayTime(3000);
                    banner.setOnBannerClickListener(new OnBannerClickListener() {
                        @Override
                        public void OnBannerClick(int position) {
                            if (position < 1) {
                                position = 1;//防止下标越界
                            }
                            if (position == urlList.size()) {
                                position = urlList.size() - 1;
                            }


                                }
                            }

                        }
                    });

                    banner.start();

作者这个点击的下标是从1开始的 我跑monkey测试发现多次滑动点击过快可能造成 下标越界   点击事件我还是严谨的判断了下

**Comment by FeverCombo3** [comment]
@MirrorFlower @youth5201314 @xyan988 关于这个问题需要修改源码，在源码中的onPageScrollStateChanged(state)方法中只是判断了在state=0即不操作的时候的切换逻辑，加入一下代码： case 1://开始滑动
                if (currentItem == count + 1) {
                    viewPager.setCurrentItem(1, false);
                }else if(currentItem == 0){
                    viewPager.setCurrentItem(count, false);
                }
                break;
即可解决滑动到左右边缘卡住的问题，亲测有效。

**Comment by youth5201314** [comment]
@FeverCombo3 感谢贡献，等会儿我测试下，下个版本更新！

**Comment by youth5201314** [comment]
@FeverCombo3 感谢贡献，等会儿我测试下，下个版本更新！
