### ISSUE TITLE
可以设置不无限轮播吗?

### ISSUE THREAD

**Issue by zhan521533** [youth5201314/banner#422]

**Comment by GavinDon** [comment]
目前来说是不支持的，需要修改源码  重写onPageScrollStateChanged()方法即可

**Comment by GavinDon** [comment]
目前来说是不支持的 因为作者采用的是给imageurls集合中前后加1 达到无限循环的作用，所以修改setImageList()方法 修改currentItem 从0 开始 （因为作者默认从1开始）注释掉onPageScrollStateChanged()方法的实现
`    private void setImageList(List<?> imagesUrl) {
        if (imagesUrl == null || imagesUrl.size() <= 0) {
            bannerDefaultImage.setVisibility(VISIBLE);
            Log.e(tag, "The image data set is empty.");
            return;
        }
        bannerDefaultImage.setVisibility(GONE);
        initImages();
        for (int i = 0; i <count; i++) {
            View imageView = null;
            if (imageLoader != null) {
                imageView = imageLoader.createImageView(context);
            }
            if (imageView == null) {
                imageView = new ImageView(context);
            }
            setScaleType(imageView);
            Object url = null;
//            if (i == 0) {
//                url = imagesUrl.get(count - 1);
//            } else if (i == count + 1) {
//                url = imagesUrl.get(0);
//            } else {
//                url = imagesUrl.get(i - 1);
//            }
            url = imagesUrl.get(i);
            imageViews.add(imageView);
            if (imageLoader != null)
                imageLoader.displayImage(context, url, imageView);
            else
                Log.e(tag, "Please set images loader.");
        }
    }
    private void setData() {
        currentItem = 0;
        if (adapter == null) {
            adapter = new BannerPagerAdapter();
            viewPager.addOnPageChangeListener(this);
        }
        viewPager.setAdapter(adapter);
        viewPager.setFocusable(true);
        viewPager.setCurrentItem(0);
        if (gravity != -1)
            indicator.setGravity(gravity);
        if (isScroll && count > 1) {
            viewPager.setScrollable(true);
        } else {
            viewPager.setScrollable(false);
        }
        if (isAutoPlay)
            startAutoPlay();
    }
    @Override
    public void onPageScrollStateChanged(int state) {
        if (mOnPageChangeListener != null) {
            mOnPageChangeListener.onPageScrollStateChanged(state);
        }
//        Log.i(tag,"currentItem: "+currentItem);
//        switch (state) {
//            case 0://No operation
//                if (currentItem == 0) {
//                    viewPager.setCurrentItem(count, false);
//                } else if (currentItem == count + 1) {
//                    viewPager.setCurrentItem(1, false);
//                }
//                break;
//            case 1://start Sliding
//                if (currentItem == count + 1) {
//                    viewPager.setCurrentItem(1, false);
//                } else if (currentItem == 0) {
//                    viewPager.setCurrentItem(count, false);
//                }
//                break;
//            case 2://end Sliding
//                break;
//        }
    }

`

**Comment by JohnsonJLi** [comment]
再把指示器变一下就ok了

**Comment by MuseYkh** [comment]
我开了个fork，已经实现了这个效果，可以参照我所修改的Banner类https://github.com/MuseYkh/banner
