### ISSUE TITLE
图片大小超出屏幕怎么办?

### ISSUE THREAD

**Issue by skythinking** [youth5201314/banner#423]
加载banner的时候,因图片过大,导致部分被隐藏,要怎么解决呢?    android:scaleType="fitCenter" 也有问题
<?xml version="1.0" encoding="utf-8"?>
<com.youth.banner.Banner xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/banner"
    android:scaleType="fitCenter"
    android:layout_width="match_parent"
    android:layout_height="180dp" />
这样会在控件两边显示部分其他图片.

**Comment by hehejl666** [comment]
用 app:image_scale_type 来设置图片显示的属性

<com.youth.banner.Banner
        xmlns:android="http://schemas.android.com/apk/res/android"
        app:image_scale_type="fit_xy"
        android:id="@+id/home_banner"
        android:layout_width="match_parent"
        android:layout_height="120dp">
