### ISSUE TITLE
图片之间的间隔如何设置  ？ 图片圆角设置不管用

### ISSUE THREAD

**Issue by p15038534252** [youth5201314/banner#424]
- 类似魅族应用广告的 样式 ，当前展示的Banner两侧的图片展示出来一部分并且之间要有间隔，要比展示的小
如图效果
![_20180412_201336](https://user-images.githubusercontent.com/19451773/38676709-75e84bc2-3e8e-11e8-91ea-fa2dc30c3b56.png)

**Comment by jp1017** [comment]
这个可以用viewpager https://github.com/44kksharma/Android-ViewPager-Carousel-UI

**Comment by wzlsz** [comment]
如果你的设备是5.0以上，那么这里有个万能的方法    https://panda912.com/2017/01/12/Android-L-%E4%BD%BF%E7%94%A8-ViewOutlineProvider-%E8%A3%81%E5%89%AA-View/
