### ISSUE TITLE
设置image_scale_type="fit_xy"无效

### ISSUE THREAD

**Issue by coding0man** [youth5201314/banner#426]
你好，我这边遇到一个问题，把Banner的宽度设置成屏幕宽度，高度随便设置一个值，然后设置image_scale_type="fit_xy",但是无论怎么操作，图片的显示方式还是centercrop，请问这个是什么问题呢？

设置参数
        <com.youth.banner.Banner
            android:id="@+id/banner_guide_content"
            android:layout_width="match_parent"
            android:layout_height="100dp"
            app:image_scale_type="fit_xy" />

**Comment by Qiang11** [comment]
我的也是这个问题 ，大兄弟解决没

**Comment by nightkidfifa** [comment]
我也是。。。。

**Comment by Panxiaoan1993** [comment]
没发现是什么问题，检查有没有其它地方设置了scaletype，如果没有的话，可以在ImageLoader中给imageView设置scaleType。
