### ISSUE TITLE
支持纵向显示吗?

### ISSUE THREAD

**Issue by 282167361** [youth5201314/banner#428]

**Comment by stefaliu** [comment]
今天花了点时间研究它所用的动画框架。动画框架缺省都是在从右到左的水平变换中加上各种特效，并不直接支持垂直变换。但是，只要抵消掉x轴的变换，再转到y轴的变换上，也能简单实现垂直方向的动画。自己定义一个Transformer子类就可以了：

```
public class SlideUpTransformer extends ABaseTransformer {

    @Override
    protected void onTransform(View view, float position) {
        view.setTranslationX(-view.getWidth() * position);
        view.setTranslationY(view.getHeight() * position);
    }

}
```

如果要向下变换，只需要给y轴变换取负就可以。

**Comment by zhangguannan** [comment]
> 今天花了点时间研究它所用的动画框架。动画框架缺省都是在从右到左的水平变换中加上各种特效，并不直接支持垂直变换。但是，只要抵消掉x轴的变换，再转到y轴的变换上，也能简单实现垂直方向的动画。自己定义一个Transformer子类就可以了：
> 
> ```
> public class SlideUpTransformer extends ABaseTransformer {
> 
>     @Override
>     protected void onTransform(View view, float position) {
>         view.setTranslationX(-view.getWidth() * position);
>         view.setTranslationY(view.getHeight() * position);
>     }
> 
> }
> ```
> 
> 如果要向下变换，只需要给y轴变换取负就可以。

谢谢大佬
