### ISSUE TITLE
bugly上看到一个错误:throwIndexOutOfBoundsException 

### ISSUE THREAD

**Issue by zmylls** [youth5201314/banner#430]
1 java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:260)
--
2 java.util.ArrayList.get(ArrayList.java:313)
3 android.support.v4.view.ViewPager.performDrag(ViewPager.java:2315)
4 android.support.v4.view.ViewPager.onTouchEvent(ViewPager.java:2234)
5 com.youth.banner.view.BannerViewPager.onTouchEvent(BannerViewPager.java:26)
6 android.view.View.dispatchTouchEvent(View.java:8668)
7 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2517)
8 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2161)
9 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
10 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2175)
11 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
12 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2175)
13 com.youth.banner.Banner.dispatchTouchEvent(Banner.java:493)
14 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
15 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2175)
16 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
17 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2175)
18 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
19 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2175)
20 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
21 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2175)
22 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
23 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2175)
24 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
25 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2175)
26 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
27 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2175)
28 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
29 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2175)
30 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
31 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2175)
32 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
33 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2175)
34 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
35 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2175)
36 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
37 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2175)
38 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
39 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2175)
40 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
41 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2175)
42 com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2559)
43 com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1815)
44 android.app.Activity.dispatchTouchEvent(Activity.java:2835)
45 android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:63)
46 com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2516)
47 android.view.View.dispatchPointerEvent(View.java:8874)
48 android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4814)
49 android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4672)
50 android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4162)
51 android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4215)
52 android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4181)
53 android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4318)
54 android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4189)
55 android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4375)
56 android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4162)
57 android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4215)
58 android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4181)
59 android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4189)
60 android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4162)
61 android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6628)
62 android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6602)
63 android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6555)
64 android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6808)
65 android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
66 android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
67 android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
68 android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6746)
69 android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6835)
70 android.view.Choreographer$CallbackRecord.run(Choreographer.java:800)
71 android.view.Choreographer.doCallbacks(Choreographer.java:603)
72 android.view.Choreographer.doFrame(Choreographer.java:570)
73 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:786)
74 android.os.Handler.handleCallback(Handler.java:815)
75 android.os.Handler.dispatchMessage(Handler.java:104)
76 android.os.Looper.loop(Looper.java:192)
77 android.app.ActivityThread.main(ActivityThread.java:5917)
78 java.lang.reflect.Method.invoke(Native Method)
79 java.lang.reflect.Method.invoke(Method.java:372)
80 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1099)
81 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:865)

这个问题是在bugly上看到的，我自己本身是没有碰到过。不知道其它同学有么有碰到过。
bugly上给出了解决方案：

该异常表示不合法下标，通常是因为访问了list不合法的位置，建议检查数据是否越界。
[解决方案]：
1.遍历数组/字符串等集合前，要判断遍历对象的长度；
2.操作数组/字符串等集合前，要检查角标是否在长度允许范围内；
3.ListView操作不当也会引起该异常，这种情况下一般是由于List渲染的时候，外面的数据源发生变化导致的。举例如ListView滚动时点击刷新将会报错，解决方法是ListView滚动时将刷新置为不可点击。或者改变数据源之前调用adapter的notifyDataSetInvalidated()方法将原数据源设置为无效。

因为我自己其实么有碰到这个问题，然后我想到，我的轮播内容是可能动态变化的，就时不时会update一下[ banner.update(list) ]。这是不是就是解决方案中的第三点，数据仍在变化，但用户却在这个时候做了点击操作？请问各位同学有什么具体些的解决方法

**Comment by itdais** [comment]
我也是这个错误 ,已经出现一个多月了

**Comment by zmylls** [comment]
@itdais 你那边也是需要时不时更新下数据吗？
