### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by ruanbaojun1105** [youth5201314/banner#432]
![image](https://user-images.githubusercontent.com/7459297/39160050-bcba794c-479b-11e8-9a47-532e60ae131f.png)

**Comment by liu149339750** [comment]
除0就会报这个错误，比如 1/0。

**Comment by wangxue** [comment]
问题场景为数据源有更新，新数据数量为0，调用start方法就会出现上述错误。

更新数据必须调用update方法，如果调用start方法会导致代码中imagelist和count有改变，但是viewPagerAdapter的数据源未改变，直接导致后续可能的除0错误。

此处作者设计api不够合理。
