### ISSUE TITLE
如何设置圆角

### ISSUE THREAD

**Issue by zhaoxiuyu** [youth5201314/banner#434]
banner 如何设置圆角显示

**Comment by jp1017** [comment]
https://github.com/youth5201314/banner/issues/269

**Comment by wzlsz** [comment]
设置轮廓    https://panda912.com/2017/01/12/Android-L-%E4%BD%BF%E7%94%A8-ViewOutlineProvider-%E8%A3%81%E5%89%AA-View/ ， 不然图片会出现从直角过度到圆角的效果

**Comment by wzlsz** [comment]
设置轮廓    https://panda912.com/2017/01/12/Android-L-%E4%BD%BF%E7%94%A8-ViewOutlineProvider-%E8%A3%81%E5%89%AA-View/ ， 不然图片会出现从直角过度到圆角的效果

**Comment by liuhuiAndroid** [comment]
@wzlsz 学习了

**Comment by kangaroo1122** [comment]
glide可以设置

**Comment by qianshengta** [comment]
@RubinTry 正解 亲用可用 不设置
