### ISSUE TITLE
如何实现卡片式效果

### ISSUE THREAD

**Issue by liulance** [youth5201314/banner#436]
您好，请问下如何实现如图所示的卡片式效果，谢谢
![aa65f929-dbc6-4f1a-8b34-e73ecb0ce42f](https://user-images.githubusercontent.com/22095781/39641053-7d32e9dc-4fff-11e8-9551-78c677373383.png)

**Comment by wenchaosong** [comment]
https://github.com/wenchaosong/Banner

**Comment by gaoguanqi** [comment]
@Override
    public ImageView createImageView(Context context) {
        View view =  ArmsUtils.inflate(context,R.layout.item_view_pager);
        ImageView iv = view.findViewById(R.id.iv_viaew_pager);
        return iv;
    }

banner 要的是一个ImageView，所以  CardView是不行 把

**Comment by gaoguanqi** [comment]
重写 
public abstract class MyImageLoader implements ImageLoaderInterface<CardView> {
    @Override
    public CardView createImageView(Context context) {
        CardView view = new CardView(context);
        return view;
    }
}
可以吗？

**Comment by gaoguanqi** [comment]
请重写 
public abstract class MyImageLoader implements ImageLoaderInterface<View> {
    @Override
    public View createImageView(Context context) {
        View view = ArmsUtils.inflate(context, R.layout.item_banner_item);
        return view;
    }
}

然后
public class MyGlideImageLoader extends MyImageLoader {
    @Override
    public void displayImage(Context context, Object path,View view) {
        ImageView imageView = view.findViewById(R.id.iv_view_pager);
        ArmsUtils.obtainAppComponentFromContext(context).imageLoader().loadImage(context, ImageConfigImpl.builder().url(path.toString()).imageView(imageView).build());
    }
    
    @Override
    public View createImageView(Context context) {
        View view =  ArmsUtils.inflate(context,R.layout.item_banner_item);
        return view;
    }
}
最后
//设置图片加载器
        banner.setImageLoader(new MyGlideImageLoader());
        //设置图片集合
        banner.setImages(mLists);
        //banner设置方法全部调用完毕时最后调用
        banner.start();

**Comment by Danniel-yan** [comment]
ArmsUtils是什么鬼？？？？？？？
