### ISSUE TITLE
首次加载特别慢用的fresco

### ISSUE THREAD

**Issue by MIkeeJY** [youth5201314/banner#44]
第一张图过了好久才会加载出来 会出现大概两三秒的空白，第二张图都出来了第一张还是有问题

**Comment by youth5201314** [comment]
这个跟banner 没有关系好吧！图片加载的过程是开放出去处理的，我们用glide都好好的！用fresco 也不少，但是没人反应这个问题！看问题究其本质好吧！

**Comment by MIkeeJY** [comment]
好的 已经切换为glide。。。 应该是fresco 加载图片的时候用自己的imageview 那个限制是因为它的宽度高度不能为wrapcontent
