### ISSUE TITLE
最后一张回到第一张，马上又重新加载一次第一张，这个过程会闪动怎么解决的额

### ISSUE THREAD

**Issue by CK875430315** [youth5201314/banner#441]
最后一张回到第一张，马上又重新加载一次第一张，这个过程会闪动怎么解决的额

**Comment by ironman6121** [comment]
我也遇到了，解决了吗

**Comment by CodingMing4XQ** [comment]
同问，回到第一张，停顿之后会闪白

**Comment by WangcWj** [comment]
我正在解决该作者出现的这个问题...

**Comment by WangcWj** [comment]
我已解决...

**Comment by JSnail** [comment]
@WangcWj 请问怎么解决的

**Comment by chuwe1** [comment]
@WangcWj 怎么解决的？

**Comment by ZakLiml** [comment]
@WangcWj 请问怎么解决的？

**Comment by ZakLiml** [comment]
我设置给 banner 设置了 animation 就不会闪了

**Comment by ZakLiml** [comment]
还需要看加载的图片控件，我使用 SimpleDraweeView，若没有设置 Hierarchy，使用加上动画是不会闪的，否则可以去掉动画的设置，已达到效果

**Comment by nwang28-ford** [comment]
> 我已解决...

怎么解决的，麻烦告知下

**Comment by Chensp171254** [comment]
这个问题没有解决方案吗？

**Comment by ZakAnun** [comment]
> 这个问题没有解决方案吗？

可以看看记录

**Comment by HarryPotterr** [comment]
怎么解决的
