### ISSUE TITLE
Error:(532) Attribute "title_background" already defined with incompatible format.

### ISSUE THREAD

**Issue by wanghuitaolove** [youth5201314/banner#45]
compile 'com.youth.banner:banner:1.4.1'  //最新版本加入后报属性冲突,请解决一下!

**Comment by MIkeeJY** [comment]
我都是把整个类copy到项目的呵呵~

**Comment by youth5201314** [comment]
你说的错误我测试过了，没有问题，请检查自己的工程！要么你使用有问题，要么你的工程其他地方有相同的命名在引用！
