### ISSUE TITLE
下一个版本升级建议

### ISSUE THREAD

**Issue by tanzhihao1qaz** [youth5201314/banner#450]
目前展示图片的地方只能是ImageView，如果可以自定义布局就好了，因为有些需求例如：第一张图要在右上角显示“热门”图标，其他就不用，这样就要通过position是否为0，来显示或隐藏右上角的图标，而且这个图标和图片一样有动画效果，可目前的app:banner_layout这个属性还是无法满足以上需求，谢谢你们。

**Comment by wzgl5533** [comment]
支持楼主观点
