### ISSUE TITLE
请问一下，如何正常显示圆角

### ISSUE THREAD

**Issue by SunxiaoyaoHHL** [youth5201314/banner#452]
设置了圆角，只要滑动时就会变成直角，怎么解决呢

**Comment by SiberiaDante** [comment]
自定义圆角ImageView

**Comment by SunxiaoyaoHHL** [comment]
@SiberiaDante 设置了，滑动过程中还是会变成直角

**Comment by shenyunmeng0519** [comment]
试试在自定义imageloader设置图片圆角显示

**Comment by caocao123** [comment]
请问你是怎么解决的呢？？？？

**Comment by 44sakumi** [comment]
请问有解决方法吗？

**Comment by SiberiaDante** [comment]
自定义ImageView或者Glide加载圆角应该都没问题吧，我用的自定义Imageview没发现问题

**Comment by 44sakumi** [comment]
> 自定义ImageView或者Glide加载圆角应该都没问题吧，我用的自定义Imageview没发现问题

自定义ImageView和Glide加载圆角都试过了，但是在页面滚动过程中，圆角会切换成直角诶

**Comment by wzlsz** [comment]
设置轮廓    https://panda912.com/2017/01/12/Android-L-%E4%BD%BF%E7%94%A8-ViewOutlineProvider-%E8%A3%81%E5%89%AA-View/

**Comment by CoderAstro** [comment]
> > 自定义ImageView或者Glide加载圆角应该都没问题吧，我用的自定义Imageview没发现问题
> 
> 自定义ImageView和Glide加载圆角都试过了，但是在页面滚动过程中，圆角会切换成直角诶

请问最后解决了吗。我也遇到同样的问题

**Comment by 44sakumi** [comment]
> > > 自定义ImageView或者Glide加载圆角应该都没问题吧，我用的自定义Imageview没发现问题
> > 
> > 
> > 自定义ImageView和Glide加载圆角都试过了，但是在页面滚动过程中，圆角会切换成直角诶
> 
> 请问最后解决了吗。我也遇到同样的问题

我后面设置了它的动画效果可以解决这个问题，不过不记得是哪个效果了，你可以一个个试试。

**Comment by caocao123** [comment]
> > > 自定义ImageView或者Glide加载圆角应该都没问题吧，我用的自定义Imageview没发现问题
> > 
> > 
> > 自定义ImageView和Glide加载圆角都试过了，但是在页面滚动过程中，圆角会切换成直角诶
> 
> 请问最后解决了吗。我也遇到同样的问题



> > > 自定义ImageView或者Glide加载圆角应该都没问题吧，我用的自定义Imageview没发现问题
> > 
> > 
> > 自定义ImageView和Glide加载圆角都试过了，但是在页面滚动过程中，圆角会切换成直角诶
> 
> 请问最后解决了吗。我也遇到同样的问题

没有解决

**Comment by wzlsz** [comment]
@caocao123 [添加轮廓](https://panda912.com/2017/01/12/Android-L-使用-ViewOutlineProvider-裁剪-View/)

**Comment by qianshengta** [comment]
@RubinTry  这位大哥的是正解

**Comment by qianshengta** [comment]
@RubinTry   大佬 你有晕倒过这这样的问题吗？
使用ViewOutlineProvider将View裁剪成圆角的，出现了一个很奇怪的问题，就是第一次进入app的时候是有效果的，一直都是圆角的没问题，但是以后再打开app，就没效果了，滑动的时候又变回直角了，这是什么鬼问题？

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            //getBannerView添加圆角轮廓，否则在滑动过程中会变成直角
            val provider = object : ViewOutlineProvider() {
                override fun getOutline(view: View, outline: Outline?) {
                    outline?.setRoundRect(0, 0, view.width, view.height, ConvertUtils.dp2px(20f).toFloat())
                }

            }
            banner.outlineProvider = provider
            banner.clipToOutline = true
        }

**Comment by RubinTry** [comment]
> @RubinTry 大佬 你有晕倒过这这样的问题吗？
> 使用ViewOutlineProvider将View裁剪成圆角的，出现了一个很奇怪的问题，就是第一次进入app的时候是有效果的，一直都是圆角的没问题，但是以后再打开app，就没效果了，滑动的时候又变回直角了，这是什么鬼问题？
> 
> ```
>     if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
>         //getBannerView添加圆角轮廓，否则在滑动过程中会变成直角
>         val provider = object : ViewOutlineProvider() {
>             override fun getOutline(view: View, outline: Outline?) {
>                 outline?.setRoundRect(0, 0, view.width, view.height, ConvertUtils.dp2px(20f).toFloat())
>             }
> 
>         }
>         banner.outlineProvider = provider
>         banner.clipToOutline = true
>     }
> ```

没出现过
