### ISSUE TITLE
轮播图展示的问题

### ISSUE THREAD

**Issue by wang521314** [youth5201314/banner#461]
作者您好，您的框架非常好用使用也很简单，但是今天测试的兄弟拿着手机来告诉我说在轮播图的展示上出现了一点小问题，图片是从网络获取的，在上一张图向下一张滑动的时候，他卡住了，这时若是用手指滑一下就好了，或者切换下页面也可以，如果有空能否看一下，虽然这个问题很少出现，但是有的话总是不好

**Comment by nb312** [comment]
我也有同样的问题，并且和手机边有一定距离

**Comment by ThugKd** [comment]
@wang521314  您好，解决了吗？

**Comment by nb312** [comment]
@ThugKd 修改动画类型就可以解决这个问题

**Comment by huangShan-gitHub** [comment]
请求有解决的楼主不分享下方法，我这边也碰到了一样的问题
