### ISSUE TITLE
把轮播放入到headview中使用，出现了轮播不平滑过渡，而是一张张图片生硬的切换，这是为啥

### ISSUE THREAD

**Issue by shenyunmeng0519** [youth5201314/banner#465]

**Comment by aBenVip** [comment]
@shenyunmeng0519 请问上述问题有解决吗?

**Comment by shenyunmeng0519** [comment]
没有，是GridViewWithHeaderAndFooter控件会出现的问题，我换了用recycleview就好了

**Comment by nb312** [comment]
我在nestedScrollview 中出现卡吨 ，并且有空白

**Comment by MakeCodeFly** [comment]
我也出现类似的情况    第一张过渡到第二张的时候会出现这种情况

**Comment by nb312** [comment]
> 我也出现类似的情况 第一张过渡到第二张的时候会出现这种情况

你修改一下动画格式就不会出现这个问题了

**Comment by leigayu** [comment]
> > 我也出现类似的情况 第一张过渡到第二张的时候会出现这种情况
> 
> 你修改一下动画格式就不会出现这个问题了

我也出现卡顿和空白，请问你解决了吗？求教
