### ISSUE TITLE
banner作为recyclerview的header滑动

### ISSUE THREAD

**Issue by QianChaoGit** [youth5201314/banner#468]
recyclerview 滑动到banner不可见时 如果正好banner轮播到下一页，banner轮播图会卡在中间，影响体验

**Comment by gzpaiwxc** [comment]
所以这个问题是什么情况呢? 没有谁解答一下的吗? 如果当 banner 正在滚动时, 这时刚好滑动 recyclerview 到 banner 不可见, banner 就会卡在中间不动了, banner 是 recyclerview 的 header

**Comment by gzpaiwxc** [comment]
用的已经是最新的 2.1.0 版本了

**Comment by gzpaiwxc** [comment]
作者的 Demo 上与 RecyclerView 嵌套使用的例子里也有这个问题, 并没有局限在 RecyclerView 的 Header 上, 就是 banner 在滚动的时候滑动 RecyclerView 到 banner 不可见, 就会出现 banner 滚动到一半停住的问题

**Comment by gzpaiwxc** [comment]
我这边用了个比较笨的方法解决了, 监听 banner 是否可见, 在可见的时候设置位置到下一个 page, 这样就永远不会卡在中间位置了
![1608197468(1)](https://user-images.githubusercontent.com/16586195/102469641-f468b000-408d-11eb-9b90-b487dec2f53d.jpg)
![1608197508(1)](https://user-images.githubusercontent.com/16586195/102469688-04808f80-408e-11eb-888b-fbe16f1d5381.jpg)

**Comment by gzpaiwxc** [comment]
图片传上来看不了, 把代码贴一下
`
    //banner选中的位置
    private var mBannerSelectedPosition: Int = 0
    //banner是否是第一次可见,首次加载时是不需要设置位置的
    var isBannerFirstAttached = true

    //监听banner选中的位置
    private val bannerPageChangeListener = object : OnPageChangeListener {
        override fun onPageScrollStateChanged(state: Int) {
        }

        override fun onPageScrolled(position: Int, positionOffset: Float, positionOffsetPixels: Int) {
        }

        override fun onPageSelected(position: Int) {
            mBannerSelectedPosition = position
        }
    }

    //监听banner是否可见
    private val onAttachStateChangeListener = object : View.OnAttachStateChangeListener {
        override fun onViewDetachedFromWindow(v: View?) {
            isBannerFirstAttached = false
        }

        override fun onViewAttachedToWindow(v: View?) {
            if (!isBannerFirstAttached) {
                val bannerSize = mModel.bannerList.size
                mBanner?.currentItem = if (mBannerSelectedPosition == (bannerSize - 1)) 1 else mBannerSelectedPosition + 2
            }
        }
    }
    private fun initBannerLayout() {
        bannerLayout = layoutInflater.inflate(R.layout.item_module_banner, null) as LinearLayout
        bannerLayout.run {
            mBanner = findViewById<Banner<*, *>>(R.id.banner)
            mBanner?.run {
                addOnPageChangeListener(bannerPageChangeListener)
                addOnAttachStateChangeListener(onAttachStateChangeListener)
                setLoopTime(2500)
                scrollTime = 350
                isNestedScrollingEnabled = false
                adapter = HomeBannerAdapter(mModel.bannerList)
                indicator = BgIndicator(mActivity)
            }
        }
    }

`

**Comment by gzpaiwxc** [comment]
图片传上来看不了, 把代码贴一下
`//banner选中的位置
private var mBannerSelectedPosition: Int = 0
//banner是否是第一次可见,首次加载时是不需要设置位置的
var isBannerFirstAttached = true

//监听banner选中的位置
private val bannerPageChangeListener = object : OnPageChangeListener {
    override fun onPageScrollStateChanged(state: Int) {
    }

    override fun onPageScrolled(position: Int, positionOffset: Float, positionOffsetPixels: Int) {
    }

    override fun onPageSelected(position: Int) {
        mBannerSelectedPosition = position
    }
}

//监听banner是否可见
private val onAttachStateChangeListener = object : View.OnAttachStateChangeListener {
    override fun onViewDetachedFromWindow(v: View?) {
        isBannerFirstAttached = false
    }

    override fun onViewAttachedToWindow(v: View?) {
        if (!isBannerFirstAttached) {
            val bannerSize = mModel.bannerList.size
            mBanner?.currentItem = if (mBannerSelectedPosition == (bannerSize - 1)) 1 else mBannerSelectedPosition + 2
        }
    }
}
private fun initBannerLayout() {
    bannerLayout = layoutInflater.inflate(R.layout.item_module_banner, null) as LinearLayout
    bannerLayout.run {
        mBanner = findViewById<Banner<*, *>>(R.id.banner)
        mBanner?.run {
            addOnPageChangeListener(bannerPageChangeListener)
            addOnAttachStateChangeListener(onAttachStateChangeListener)
            setLoopTime(2500)
            scrollTime = 350
            isNestedScrollingEnabled = false
            adapter = HomeBannerAdapter(mModel.bannerList)
            indicator = BgIndicator(mActivity)
        }
    }
}`

**Comment by liweiGe** [comment]
你这个法子最好加个判断
  override fun onPageScrolled(position: Int, positionOffset: Float, positionOffsetPixels: Int) {
                    isNeedCorrect = positionOffset > 0.0f
                }

然后再双重判断
 if (!isBannerFirstAttached&& isNeedCorrect)
