### ISSUE TITLE
从有轮播图片刷新到无图片崩溃

### ISSUE THREAD

**Issue by guyunke123** [youth5201314/banner#471]
从有轮播图片刷新到无图片崩溃，应该是adapter没有adapter.notifyDataSetChanged(),导致点击计算位置时count = 0，除数为0异常。releaseBanner方法是否应该notifyDataSetChanged()一下

**Comment by Dizner** [comment]
![image](https://user-images.githubusercontent.com/16025854/44614640-0427af00-a85b-11e8-930a-48d8d87f2729.png)
从有图刷新到无图时，这里在计算position会出现除数为零的异常，建议判断一下

**Comment by guyunke123** [comment]
判断的话，得修改在源码里。compile 'com.youth.banner:banner:xxx‘不支持改源码。

**Comment by zuoce** [comment]
这个问题我也遇到了，大佬们这么解决的，求分享下

**Comment by YiXiXiao** [comment]
同样问题，求解

**Comment by Dizner** [comment]
项目是开源的，可以用源码修改
