### ISSUE TITLE
图片切换的时候会有白条闪烁

### ISSUE THREAD

**Issue by chuwe1** [youth5201314/banner#476]
这个怎么破？

**Comment by chuwe1** [comment]
![123](https://user-images.githubusercontent.com/13444312/44192652-dbb8fa00-a162-11e8-8bf5-9859331903cc.gif)

**Comment by nb312** [comment]
@chuwe1     setBannerAnimation(Transformer.Stack)  刚试了一下 设置动画 就没有这个现象了

**Comment by chuwe1** [comment]
@nb312 3Q
