### ISSUE TITLE
同一个页面多个banner时点击事件怎么区分不同banner?

### ISSUE THREAD

**Issue by DaleSmith** [youth5201314/banner#483]
项目中上面一个轮播图下面一个广告轮播,调用setOnBannerListener(this),实现OnBannerClick(int position)方法,发现没法判断是点击了哪一个banner

**Comment by lh414035210** [comment]
请问你解决这个问题 了么?

**Comment by DaleSmith** [comment]
没呢


| |
Dale
|
|
邮箱：15650768800@163.com
|

Signature is customized by Netease Mail Master

在2018年11月02日 16:48，lh414035210 写道：

请问你解决这个问题 了么?

**Comment by ender115** [comment]
楼上两位，这个问题解决了么

**Comment by DaleSmith** [comment]
没有

**Comment by DaleSmith** [comment]
还没解决呢

**Comment by ender115** [comment]
可以了，有另外一个方法，每一个banner都去设置点击事件就可以了

**Comment by ASOLaoJiang** [comment]
放置多个banner自动滚动关联到一起去了，什么原因

**Comment by DaleSmith** [comment]
> 可以了，有另外一个方法，每一个banner都去设置点击事件就可以了

ok,有空试试
