### ISSUE TITLE
建议ImageLoaderInterface的createImageView方法增加当前Object的参数

### ISSUE THREAD

**Issue by Panxiaoan1993** [youth5201314/banner#485]
之前刚好做完轮播不同view的需求，突然想到也可以用作者这个控件去实现，看了一下发现createImageView的时候没办法返回不同的view，提个小建议，createImageView增加一个参数。
Object url = null;
if (i == 0) {
    url = imagesUrl.get(count - 1);
} else if (i == count + 1) {
    url = imagesUrl.get(0);
} else {
    url = imagesUrl.get(i - 1);
}
if (imageLoader != null) {
       imageView = imageLoader.createImageView(context, url);
}

这样的话一个imageLoader可以根据实体来返回view，这样轮播的每个view都可以自由定制了

**Comment by wenchaosong** [comment]
@Panxiaoan1993 其实我已经实现了 https://github.com/wenchaosong/Banner 这是我修改这个库实现的

**Comment by qssq** [comment]
https://github.com/qssq/Banner

**Comment by wenchaosong** [comment]
@Panxiaoan1993  根据类型返回不同的 view ，第一个想到的难道不是面向对象吗，做一个实体类，实体类的属性就决定了返回的 view 的类型，那这个实体类肯定就可以作为 createview 的依据
