### ISSUE TITLE
怎么实现banner图底部弧度？类似淘宝

### ISSUE THREAD

**Issue by hardgit** [youth5201314/banner#496]
有实现底部弧度的API吗？

**Comment by wenchaosong** [comment]
@hardgit  其实我已经实现了 https://github.com/wenchaosong/Banner 这是我修改这个库实现的

**Comment by hardgit** [comment]
@wenchaosong 感谢

**Comment by wzlsz** [comment]
其实自己用onDraw绘制就可以，就是比较费时间
