### ISSUE TITLE
我想实现下画廊效果，子父view都设置了 android:clipChildren="false"

### ISSUE THREAD

**Issue by EmperorZzl** [youth5201314/banner#500]
还是不能出来画廊效果

**Comment by GreenhairTurtle** [comment]
你需要给BannerViewPager设置margin

另外 这个库不推荐实现画廊，因为他内部长度不是Integer.MAX_VALUE

轮播采用的是不断更改CurrentItem的方式

这导致在画廊效果下，末页的右边那一页出现的时间会较晚，体验不好

由于只是粗略的瞄了两眼，所以简单的说下，如有大神有办法，望指正

**Comment by Leekalun** [comment]
楼上说的不错，这个库 用画廊设置两头margin 和 clipChildren 的话，左右滑动会有延迟

**Comment by DongDian455** [comment]
楼上说的不错，左右滑动延迟还会导致pageTransformer出问题
