### ISSUE TITLE
如何去掉指示器，只显示标题？

### ISSUE THREAD

**Issue by nxnyk** [youth5201314/banner#508]

**Comment by wenchaosong** [comment]
@nxnyk  用自定义布局  https://github.com/wenchaosong/Banner 这是我修改这个库实现的

**Comment by nxnyk** [comment]
> @nxnyk 木有这个，要修改源码自己实现

哈哈，我找到办法了，把属性里的指示器宽和高设置为0，强行让其看不见。。。
