### ISSUE TITLE
如何实现选中和未选中的时候，指示器显示不同宽度？

### ISSUE THREAD

**Issue by erichyx** [youth5201314/banner#510]

**Comment by wenchaosong** [comment]
@erichyx  作者设置的是同一个宽高，没有办法实现，https://github.com/wenchaosong/Banner 这是我修改这个库实现的

**Comment by erichyx** [comment]
@wenchaosong 好的，用你的库试试。

**Comment by hiphonezhu** [comment]
indicatorSize = ViewGroup.LayoutParams.WRAP_CONTENT; 就可以了
