### ISSUE TITLE
如何滚动到指定位置

### ISSUE THREAD

**Issue by ShenHaiyi** [youth5201314/banner#514]
如何滚动到指定位置

**Comment by ShengjieGeng** [comment]
我也在找，类似于viewpager的
![_20181210165921](https://user-images.githubusercontent.com/18364968/49721397-11976680-fc9d-11e8-81fc-24206bfd9282.png)

**Comment by sdgSnow** [comment]
请问有没有找到呢

**Comment by ShengjieGeng** [comment]
nope
