### ISSUE TITLE
添加画廊效果

### ISSUE THREAD

**Issue by zhongxiong00** [youth5201314/banner#521]
需要画廊效果的Banner、

**Comment by wenchaosong** [comment]
@zhongxiong00  https://github.com/wenchaosong/Banner 这是我修改这个库实现的

**Comment by zhongxiong00** [comment]
> @zhongxiong00 https://github.com/wenchaosong/Banner 这是我修改这个库实现的

看到了，你两是同一个人吗？

**Comment by wenchaosong** [comment]
不是，作者好久不更新，我自己修改的
