### ISSUE TITLE
我发现不同的机型展示的图片的高度不一样

### ISSUE THREAD

**Issue by bdxtx** [youth5201314/banner#525]
比如华为p6和小米5，banner看到的图片高度不一样，有被遮挡部分，这个问题导致我在使用Glide设置圆角的时候小米5可以正常显示，p6显示的是直角

**Comment by wenchaosong** [comment]
这种可以截图的你可以发图说明更直观

**Comment by bdxtx** [comment]
我换了一个框架>_<来实现
