### ISSUE TITLE
图片只有二张，banner OnBannerClickListener,position  出现3

### ISSUE THREAD

**Issue by MitchZhang** [youth5201314/banner#53]
OnBannerClickListener(int Position);
只有二张图片 轮播的点击事件 positon出现3.

**Comment by FeeAlan** [comment]
position 貌似是从1开始的

**Comment by youth5201314** [comment]
position 是从1开始的，我文档上有标注的啊！至于出现3，这个我没有测试出来。希望能写出你的操作步骤等等！
