### ISSUE TITLE
NestedScrollView 中嵌套ConstraintLayout中使用滑动的时候卡顿

### ISSUE THREAD

**Issue by hcs-xph** [youth5201314/banner#531]
我在NestedScrollView中嵌套了ConstraintLayout中使用了该banner,在上下滑动页面过程中,当banner自动播放切换的时候如果正在滑动 会导致页面卡顿.

**Comment by liz821** [comment]
我这里不是卡顿 是滑动幅度大的时候列表会回弹?就像弹性滑动那种 请问有老哥知道怎么弄吗

**Comment by zhaobinsir** [comment]
+1
