### ISSUE TITLE
updata方法无效，希望大大可以看一下

### ISSUE THREAD

**Issue by xyZangGit** [youth5201314/banner#533]

**Comment by FynnJason** [comment]
+1

**Comment by Mubly** [comment]
+1，我最终选择重新init了一下

**Comment by strivecheng** [comment]
> +1，我最终选择重新init了一下

我换库了，正好有其他需求也不满足

**Comment by gxh-apologize** [comment]
@strivecheng 有比较好用的库推荐吗？我也是update之后有问题。

**Comment by strivecheng** [comment]
> @strivecheng 有比较好用的库推荐吗？我也是update之后有问题。

加我微信吧xcc2734，在这里推荐其他博主的库，感觉不太好🤣

**Comment by gxh-apologize** [comment]
@strivecheng ok，哈哈其实这个库很不错，非常感谢作者。只是我项目没时间改了，所以还是换个哈哈。
