### ISSUE TITLE
Banner中的WeakHandler初始化存在缺陷，导致非UI线程中不能播放动画。

### ISSUE THREAD

**Issue by Lurkyli** [youth5201314/banner#542]
Banner中的WeakHandler初始化，默认Banner在UI线程中完成初始化。当Banner在非UI线程中进行初始化时，WeakHandler的初始化无法得到UI线程Looper，导致无法处理task任务，不能播放动画效果。

建议：
Banner构造函数中，可以增加Looper参数，以便WeakHandler可以根据Looper进行初始化。

**Comment by wanghaibao123** [comment]
请问一下怎么修改呢

**Comment by Lurkyli** [comment]
增加一个构造方法  
    public Banner(Context context, Looper uiLooper) {
        this.handler = new WeakHandler(uiLooper);
        this(context, null);
    }

有需要使用自定义的uiLooper时，使用这个构造方法。你可以在非UI线程里尝试一下。
我们是在开发SDK时发现的这个问题。
