### ISSUE TITLE
老铁们，我在这个基础上精简了banner,大家来试试啊

### ISSUE THREAD

**Issue by AlpsDog** [youth5201314/banner#543]
1.支持一屏一页，一屏多页
2.基本涵盖所有动画
3.指示器支持图片，支持尺寸定义
4.可以添加任意view作为banner显示的item
5.可以自定义指示器
6.用法很简单~

**Comment by AlpsDog** [comment]
banner就是一个RelativeLayout，直接在xml里面用banner包裹你自己定义的指示器，位置，颜色，你随意都可以！！我里面写了一个demo，大家试试！banner大神现在不维护了，我只能自己在这个基础上精简~很简单的，大家可以看看我里面写的~

**Comment by ender115** [comment]
你写的在哪里啊

**Comment by AlpsDog** [comment]
[banner链接：](https://github.com/AlpsDog/Banner)
欢迎大家指正

**Comment by AlpsDog** [comment]
> 你写的在哪里啊

：

> 你写的在哪里啊

https://github.com/AlpsDog/Banner，欢迎老铁指正

**Comment by AlpsDog** [comment]
Banner传送们，欢迎大家指正
[https://github.com/AlpsDog/Banner](https://github.com/AlpsDog/Banner)
