### ISSUE TITLE
引入youthBanner提示找不到该类

### ISSUE THREAD

**Issue by wwwjiandan** [youth5201314/banner#558]
在xml中定义com.youth.banner.Banner这个布局，给出宽带高度参数，在Activity中没写和Banner相关的任何代码，运行时提示找不到com.youth.banner.Banner这个类，我可以通过点击这个布局中的<com.youth.banner.Banner跳转到对应的Java代码，但是就是提示找不到这个class,另外一个报错就是提示Banner类中的initView()中bannerDefaultImage.setImageResource(bannerBackgroundImage);提示空指针，但是奇怪的是同事的电脑就可以正常运行，不知道为什么我的不行，我用的是最新版本的compile,麻烦告知下怎么回事，btw,我也是看着7k的star来的，而且说明特别详细，但是为啥不能用呢！

**Comment by deltaguita** [comment]
+1

**Comment by deltaguita** [comment]
@wwwjiandan  我找到原因了
<img width="1018" alt="螢幕快照 2019-06-25 下午3 45 08" src="https://user-images.githubusercontent.com/3380016/60081699-e241d600-9764-11e9-87eb-78868fe5236d.png">
是資源名稱衝突了，我的解法是 fork 下來自己改掉，順便升級 AndroidX
