### ISSUE TITLE
banner 怎么监听滑动

### ISSUE THREAD

**Issue by luhuanxml** [youth5201314/banner#561]
需要监听banner的滑动来控制首页背景色随着banner图片主题色渐变

**Comment by gs666** [comment]
binding.banner.viewPager2.registerOnPageChangeCallback(object : ViewPager2.OnPageChangeCallback() {
            override fun onPageSelected(position: Int) {
                super.onPageSelected(position)
                Log.d("TAG", "pos:$position")
            }
        })
