### ISSUE TITLE
建议加一个控制指示器marginBottom的属性

### ISSUE THREAD

**Issue by RubinTry** [youth5201314/banner#562]
如题，由于项目需求，banner底部需要加上一段圆弧，如图，该圆弧是我自己做的一个view，可控制高度，但是没法做到让banner的指示器一定在圆弧之上
![1](https://user-images.githubusercontent.com/25943524/52685985-c04e7080-2f86-11e9-9688-6119efc30ec4.png)

无奈之下将作者的项目clone下来自己扩展了下:relieved:

**Comment by jp1017** [comment]
@wzlsz 请问有代码吗，哈哈哈

**Comment by wzlsz** [comment]
@jp1017 我是把作者代码clone下来然后作为library导入项目进行更改的，你自己弄一下吧，很简单的
