### ISSUE TITLE
当图片只有一张的时候

### ISSUE THREAD

**Issue by INX0769** [youth5201314/banner#57]
当图片只有一张的时候，下方的指示器样式是CIRCLE_INDICATOR的时候是不是应该隐藏一下，一个黑点在那里，或者提供一个方法隐藏INDICATOR比较好，不然数据源为1的时候不够灵活

**Comment by INX0769** [comment]
好吧，发现有NOT_INDICATOR这个标签可以设置不显示

**Comment by youth5201314** [comment]
用1.4.4版本
