### ISSUE TITLE
应用本地存储的照片转bitmap，显示空白

### ISSUE THREAD

**Issue by AugustusGriffin** [youth5201314/banner#571]
使用本地数据库存储的byte[]数据转成bitmap后在banner中显示空白，本地数据库存的是通过自定义相册获取的系统照片，普通的imageview上可以显示出来，在banner上就不行了

**Comment by AugustusGriffin** [comment]
应该是在recyclerview中使用就会这样，望大神赐教

**Comment by cvvbbo** [comment]
同问
