### ISSUE TITLE
下拉刷新数据，banner最后一条数据图片闪屏

### ISSUE THREAD

**Issue by qq45119626FangZhi** [youth5201314/banner#572]
使用Scrollview嵌套banner和recyclerview,,和使用recyclerview添加头部使用banner，刷新数据时，图片会闪屏（此处已自己解决），自动轮播时，播到最后一张又会闪屏

**Comment by budou1994** [comment]
同问，只是给recycleview添加header，header中就只有一个banner，每次设置自动轮播，最后一张图片就会一闪而过？下标显示的是正常，但是图片展示很不正常。
