### ISSUE TITLE
作者不更新,大家有问题可以看这里

### ISSUE THREAD

**Issue by wenchaosong** [youth5201314/banner#576]
其实我不太想发出来,因为侵害了本库作者的所有权,但是不更新也是一个大问题,为了广大程序员能开心的使用,我在这个库的基础上改了一点东西,使用的范围更广

下面是我修改的库
https://github.com/wenchaosong/Banner

欢迎大家来提 issue,共同进步

**Comment by weiaiCmeng** [comment]
非常好,多谢了

**Comment by micenote** [comment]
好像你的也好久没有更新了

**Comment by MahatmaSun** [comment]
最好加一下原库地址  感谢一下吧
