### ISSUE TITLE
使用自定义的shape代替选中指示器,shape宽度无效怎么办呢?就是要选中为一个矩形,未选中是圆形

### ISSUE THREAD

**Issue by roybill** [youth5201314/banner#579]
布局:
<com.youth.banner.Banner
                android:id="@+id/banner_tool"
                android:layout_width="match_parent"
                android:layout_height="220dp"
                app:indicator_drawable_selected="@drawable/banner_selected_shape"
                app:indicator_drawable_unselected="@drawable/banner_unselected_shape">

            </com.youth.banner.Banner>

banner_selected_shape文件:
<shape xmlns:android="http://schemas.android.com/apk/res/android">

    <size
        android:width="20dp"
        android:height="5dp" />

    <corners android:radius="20dp" />

    <solid android:color="#ffffff" />

</shape>

**Comment by XW837156540** [comment]
楼主解决了吗，我的也是，显示出来是个方形

**Comment by roybill** [comment]
@XW837156540  差不多,主要是宽度设置无效

**Comment by XW837156540** [comment]
那这个效果你实现了吗？

**Comment by roybill** [comment]
@XW837156540  需求改了就没有去继续研究了,如果这个库不好改,建议在网上找一下其他的库

**Comment by XW837156540** [comment]
根据使用这个库的一个朋友的思路，修改了下源码，新增一种样式，实现了这个效果

**Comment by mzhkby** [comment]
@dzs-yaodi 怎么解决的？

**Comment by dzs-yaodi** [comment]
@mzhkby  https://github.com/dzs-yaodi/Banner，修改了banner的一点点源码

**Comment by dzs-yaodi** [comment]
@mzhkby  修改了一点点源码
https://github.com/dzs-yaodi/Banner
