### ISSUE TITLE
banner从第一个item往右滑至最后一个item点击时，banner变空白

### ISSUE THREAD

**Issue by Sky-Walkrr** [youth5201314/banner#58]
从demo中发现，当banner初始化完成，从第一个item往右划至最后一个item，此时点击最后一个item时，banner会变空白，且无法继续往右滑动。

**Comment by youth5201314** [comment]
刚看了！真心没有发现

**Comment by youth5201314** [comment]
你用的是什么版本的，是最新的demo吗

**Comment by Sky-Walkrr** [comment]
是最新的呢

**Comment by Sky-Walkrr** [comment]
你初次进入主界面时，banner刚好是第一个item时就往右划看看。

**Comment by youth5201314** [comment]
就是这样操作的！没有问题啊！我用的是新款红米4高配版测试的！

**Comment by Sky-Walkrr** [comment]
从onPageSelected中打log可以看到此时position为0

**Comment by youth5201314** [comment]
你提供的信息太少了！我测试了很多道，都没有发现！position=0是为了循环过渡下！

**Comment by zhjunvj** [comment]
我也遇到同样的问题 ：第一次进入主界面时，banner刚好是第一个item时立马往右划会到最后一个图片，然后banner会变空白

**Comment by skyYoungJade** [comment]
同样遇到这问题~~~
