### ISSUE TITLE
指示器不显示

### ISSUE THREAD

**Issue by dlgchg** [youth5201314/banner#584]
![image](https://user-images.githubusercontent.com/20040601/56413187-3c33a480-62b9-11e9-9756-67409454b4ce.png)
![image](https://user-images.githubusercontent.com/20040601/56413200-45bd0c80-62b9-11e9-8e4b-5a3961f42ba7.png)
![image](https://user-images.githubusercontent.com/20040601/56413215-5077a180-62b9-11e9-8f6f-d6d489b9f4ca.png)

**Comment by ZakLiml** [comment]
banner 的指示器可以在 xml 文件中设置（建议看下文档，里面有）
代码如下：
<com.youth.banner.Banner
        android:layout_width="match_parent"
        android:layout_height="160dp"
        app:indicator_width="10dp"
        app:indicator_height="2dp"
        app:indicator_margin="5dp"
        app:indicator_drawable_selected="@drawable/banner_indicator_selected"
        app:indicator_drawable_unselected="@drawable/banner_indicator_unselected"/>

**Comment by dlgchg** [comment]
我还以为是默认的

**Comment by dlgchg** [comment]
谢谢
