### ISSUE TITLE
请问怎么设置banner加载出来的图片是圆角的呢

### ISSUE THREAD

**Issue by yuan023** [youth5201314/banner#590]

**Comment by yuan023** [comment]
请问怎么设置banner加载出来的图片是圆角的呢
用Glide4.8.0设置了圆角在ImageView上是有圆角的但是在banner上就失效了，请问我要怎么处理呢

**Comment by caizhixing** [comment]
‘’‘
    private class CustomRoundedImageLoader implements ImageLoaderInterface<ImageView> {

        @Override
        public void displayImage(Context context, Object path, ImageView imageView) {
            ImageManager.getInstance().loadImage(context, path.toString(), imageView);
        }

        @Override
        public ImageView createImageView(Context context) {
            RoundedImageView roundedImg = new RoundedImageView(context, null);
            roundedImg.setCornerRadius(DensityUtils.dip2px(context, 10));
            return roundedImg;
        }
    }
’‘’

**Comment by RexHuang1** [comment]
> ‘’‘
> private class CustomRoundedImageLoader implements ImageLoaderInterface {
> 
> ```
>     @Override
>     public void displayImage(Context context, Object path, ImageView imageView) {
>         ImageManager.getInstance().loadImage(context, path.toString(), imageView);
>     }
> 
>     @Override
>     public ImageView createImageView(Context context) {
>         RoundedImageView roundedImg = new RoundedImageView(context, null);
>         roundedImg.setCornerRadius(DensityUtils.dip2px(context, 10));
>         return roundedImg;
>     }
> }
> ```
> 
> ’‘’

RoundedImageView 是自定义的类？

**Comment by guitarock** [comment]
> > ‘’‘
> > private class CustomRoundedImageLoader implements ImageLoaderInterface {
> > ```
> >     @Override
> >     public void displayImage(Context context, Object path, ImageView imageView) {
> >         ImageManager.getInstance().loadImage(context, path.toString(), imageView);
> >     }
> > 
> >     @Override
> >     public ImageView createImageView(Context context) {
> >         RoundedImageView roundedImg = new RoundedImageView(context, null);
> >         roundedImg.setCornerRadius(DensityUtils.dip2px(context, 10));
> >         return roundedImg;
> >     }
> > }
> > ```
> > 
> > 
> > ’‘’
> 
> RoundedImageView 是自定义的类？



> > ‘’‘
> > private class CustomRoundedImageLoader implements ImageLoaderInterface {
> > ```
> >     @Override
> >     public void displayImage(Context context, Object path, ImageView imageView) {
> >         ImageManager.getInstance().loadImage(context, path.toString(), imageView);
> >     }
> > 
> >     @Override
> >     public ImageView createImageView(Context context) {
> >         RoundedImageView roundedImg = new RoundedImageView(context, null);
> >         roundedImg.setCornerRadius(DensityUtils.dip2px(context, 10));
> >         return roundedImg;
> >     }
> > }
> > ```
> > 
> > 
> > ’‘’
> 
> RoundedImageView 是自定义的类？

一样是开源框架，搜一下就好

**Comment by qianshengta** [comment]
显示时可以显示成圆角了 但是在滑动的时候会变成直角这该怎么接解决？图片和ImageView都是圆角的
@guitarock @caizhixing
