### ISSUE TITLE
新需求：关于轮播时间

### ISSUE THREAD

**Issue by yx971072369** [youth5201314/banner#592]
此前版本以满足较多应用场景、假设目前有5张图片、分别显示 5s 10s 20s 4s 3s、可不可以在原有的基础上设置每个图片的展示时间、以满足更多的需求。

**Comment by mzzdxt** [comment]
作者已经不维护了，自己改源码吧

**Comment by yx971072369** [comment]
> 作者已经不维护了，自己改源码吧

行的、我试着改改

**Comment by 258188170** [comment]
实现不同图片显示不同时间了吗

**Comment by yx971072369** [comment]
我在原有的基础上做了下增强、已经实现了

在 2019-07-04 10:24:09，"wp" <notifications@github.com> 写道：


实现不同图片显示不同时间了吗

**Comment by JunFengZhou** [comment]
> 我在原有的基础上做了下增强、已经实现了 在 2019-07-04 10:24:09，"wp" <notifications@github.com> 写道： 实现不同图片显示不同时间了吗 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

怎么实现啊大佬

**Comment by woshihfh0123** [comment]
> 我在原有的基础上做了下增强、已经实现了 在 2019-07-04 10:24:09，"wp" <notifications@github.com> 写道： 实现不同图片显示不同时间了吗 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

怎么实现的？这个position的位置，只要一滑动就会错乱
