### ISSUE TITLE
啥还没有操作只是include一个banner就白屏卡死

### ISSUE THREAD

**Issue by QQwangxiaoqing** [youth5201314/banner#594]
我是在activity的layout文件inlcude一个layout文件，就是下面的代码，直接白屏了卡死！！是我操作方式不对嘛？？！纳尼。
<com.youth.banner.Banner
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/banner"
    android:layout_width="match_parent"
    android:layout_height="180dp" />

**Comment by yx971072369** [comment]
最外层加上布局文件啊
