### ISSUE TITLE
不自动轮播

### ISSUE THREAD

**Issue by yanpengqing** [youth5201314/banner#595]
setViewPagerIsScroll(boolean isScroll) | 设置是否允许手动滑动轮播图
设置为false之后，只要触摸了屏幕就不会自动轮播了

**Comment by hyccode** [comment]
我也遇到了,你解决了吗

**Comment by hyccode** [comment]
![image](https://user-images.githubusercontent.com/26076350/59751456-22abda80-92b3-11e9-9dc9-bdb708a1035e.png)
应该是这里有问题,能收到ACTION_DOWN事件,收不到ACTION_UP,ACTION_CANCEL等事件,所以重新开启不了自动轮播了
