### ISSUE TITLE
CIRCLE_INDICATOR样式中，条目从最后一页翻回到第一页，或从第一页翻回到最后一页下边指示点加载有延迟

### ISSUE THREAD

**Issue by imexception** [youth5201314/banner#6]
1、createIndicator中应初始化指示点，默认第一个显示颜色，防止第一次时下边什么都不显示
           if(i==0){
                imageView.setImageResource(mIndicatorSelectedResId);
            }else{
                imageView.setImageResource(mIndicatorUnselectedResId);
            }
2、onPageSelected中判断条件有误，当position==0或position==indicatorImages.size()+1时
      for循环中都为false造成延迟加载，if中的判断条件应改为
      i== (position - 1+indicatorImages.size())%indicatorImages.size()

**Comment by imexception** [comment]
onPageSelected中使用for循环来改变指示点效率比较低，用一个标记位来记录上次的指示点，这样只用改变两个指示点就行了
声明局部变量用来记录上一次改变的指示点位置
private int lastPosition=1;
onPageSelected中的for循环替换为
indicatorImages.get((lastPosition - 1+indicatorImages.size())%indicatorImages.size()).setImageResource(mIndicatorUnselectedResId);
 indicatorImages.get((position - 1+indicatorImages.size())%indicatorImages.size()).setImageResource(mIndicatorSelectedResId);
  lastPosition=position;

**Comment by youth5201314** [comment]
ok，thank you！

**Comment by youth5201314** [comment]
已修改提交，非常感谢你的反馈！
