### ISSUE TITLE
如何设置指示器的颜色或者图片？

### ISSUE THREAD

**Issue by pwj1568** [youth5201314/banner#60]
想要修改指示器的的颜色或者是换成本地的图片（不同颜色的小圆点）怎么办？

**Comment by pwj1568** [comment]
我已经知道了，app:indicator_drawable_selected和app:indicator_drawable_unselected这两个属性

**Comment by Klay-11** [comment]
> 我已经知道了，app:indicator_drawable_selected和app:indicator_drawable_unselected这两个属性
感谢分享，我试试，刚刚还在想这个轮播star这么多，竟然连改圆点大小和颜色的方法都没有。
