### ISSUE TITLE
33张图，每次会有不同图片出现空白

### ISSUE THREAD

**Issue by kjtown** [youth5201314/banner#603]
总放置了33张自已服务器上的图片，但每次轮播会出不同图片不能显示出来，出现空白的现象，图片网址正确，下一次轮播可能正常。
另外当图片较多时，性能问题较严重，切换到其它activity会直接闪退现象。

**Comment by robinhoo2010** [comment]
我这边也出现了，27几张图片，在第22张的时候就显示不出来了，异常如下，应该是加载时oom了。

2019-08-29 11:28:23.867 30534-30615/com.boka.poster W/art: Throwing OutOfMemoryError "Failed to allocate a 8294412 byte allocation with 3872264 free bytes and 3MB until OOM"
2019-08-29 11:28:24.222 30534-30534/com.boka.poster W/Glide: Load failed for http://static.bokao2o.com/images/push/2019013117570881300.png with size [-2147483648x-2147483648]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There were 13 causes:
    java.lang.OutOfMemoryError(Failed to allocate a 8294412 byte allocation with 4031016 free bytes and 3MB until OOM)
    java.lang.OutOfMemoryError(Failed to allocate a 8294412 byte allocation with 3959872 free bytes and 3MB until OOM)
    java.lang.OutOfMemoryError(Failed to allocate a 8294412 byte allocation with 3889496 free bytes and 3MB until OOM)
    java.lang.OutOfMemoryError(Failed to allocate a 8294412 byte allocation with 3887968 free bytes and 3MB until OOM)
    java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0xBEBBB1B7)
    java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0xBEBBB1B7)
    java.lang.OutOfMemoryError(Failed to allocate a 8294412 byte allocation with 3887032 free bytes and 3MB until OOM)
    java.lang.OutOfMemoryError(Failed to allocate a 8294412 byte allocation with 3886376 free bytes and 3MB until OOM)
    java.lang.OutOfMemoryError(Failed to allocate a 8294412 byte allocation with 3884272 free bytes and 3MB until OOM)
    java.lang.OutOfMemoryError(Failed to allocate a 8294412 byte allocation with 3878424 free bytes and 3MB until OOM)
    java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0xBEBBB1B7)
    java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0xBEBBB1B7)
    java.io.FileNotFoundException(No content provider: http://static.bokao2o.com/images/push/2019013117570881300.png)
     call GlideException#logRootCauses(String) for more detail
      Cause (1 of 7): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{DirectByteBuffer->Object->Drawable}, DATA_DISK_CACHE, http://static.bokao2o.com/images/push/2019013117570881300.png
    There were 2 causes:
    java.lang.OutOfMemoryError(Failed to allocate a 8294412 byte allocation with 4031016 free bytes and 3MB until OOM)
    java.lang.OutOfMemoryError(Failed to allocate a 8294412 byte allocation with 3959872 free bytes and 3MB until OOM)
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->GifDrawable->Drawable}
        Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->Bitmap->Drawable}
    There was 1 cause:
    java.lang.OutOfMemoryError(Failed to allocate a 8294412 byte allocation with 4031016 free bytes and 3MB until OOM)
     call GlideException#logRootCauses(String) for more detail
          Cause (1 of 1): class java.lang.OutOfMemoryError: Failed to allocate a 8294412 byte allocation with 4031016 free bytes and 3MB until OOM
        Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->BitmapDrawable->Drawable}
    There was 1 cause:
    java.lang.OutOfMemoryError(Failed to allocate a 8294412 byte allocation with 3959872 free bytes and 3MB until OOM)
     call GlideException#logRootCauses(String) for more detail
          Cause (1 of 1): class java.lang.OutOfMemoryError: Failed to allocate a 8294412 byte allocation with 3959872 free bytes and 3MB until OOM
      Cause (2 of 7): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{FileInputStream->Object->Drawable}, DATA_DISK_CACHE, http://static.bokao2o.com/images/push/2019013117570881300.png
    There were 2 causes:
    java.lang.OutOfMemoryError(Failed to allocate a 8294412 byte allocation with 3889496 free bytes and 3MB until OOM)
    java.lang.OutOfMemoryError(Failed to allocate a 8294412 byte allocation with 3887968 free bytes and 3MB until OOM)
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->GifDrawable->Drawable}
        Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->Bitmap->Drawable}
2019-08-29 11:28:24.223 30534-30534/com.boka.poster W/Glide: There was 1 cause:
    java.lang.OutOfMemoryError(Failed to allocate a 8294412 byte allocation with 3889496 free bytes and 3MB until OOM)
     call GlideException#logRootCauses(String) for more detail
          Cause (1 of 1): class java.lang.OutOfMemoryError: Failed to allocate a 8294412 byte allocation with 3889496 free bytes and 3MB until OOM
        Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->BitmapDrawable->Drawable}
    There was 1 cause:
    java.lang.OutOfMemoryError(Failed to allocate a 8294412 byte allocation with 3887968 free bytes and 3MB until OOM)
     call GlideException#logRootCauses(String) for more detail
          Cause (1 of 1): class java.lang.OutOfMemoryError: Failed to allocate a 8294412 byte allocation with 3887968 free bytes and 3MB until OOM
      Cause (3 of 7): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{ParcelFileDescriptor->Object->Drawable}, DATA_DISK_CACHE, http://static.bokao2o.com/images/push/2019013117570881300.png
    There were 2 causes:
    java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0xBEBBB1B7)
    java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0xBEBBB1B7)
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->Bitmap->Drawable}
    There was 1 cause:
    java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0xBEBBB1B7)
     call GlideException#logRootCauses(String) for more detail
          Cause (1 of 1): class java.io.IOException: java.lang.RuntimeException: setDataSource failed: status = 0xBEBBB1B7
        Cause (2 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->BitmapDrawable->Drawable}
    There was 1 cause:
    java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0xBEBBB1B7)
     call GlideException#logRootCauses(String) for more detail
          Cause (1 of 1): class java.io.IOException: java.lang.RuntimeException: setDataSource failed: status = 0xBEBBB1B7
      Cause (4 of 7): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{DirectByteBuffer->Object->Drawable}, REMOTE, http://static.bokao2o.com/images/push/2019013117570881300.png
    There were 2 causes:
    java.lang.OutOfMemoryError(Failed to allocate a 8294412 byte allocation with 3887032 free bytes and 3MB until OOM)
    java.lang.OutOfMemoryError(Failed to allocate a 8294412 byte allocation with 3886376 free bytes and 3MB until OOM)
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->GifDrawable->Drawable}
        Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->Bitmap->Drawable}
    There was 1 cause:
    java.lang.OutOfMemoryError(Failed to allocate a 8294412 byte allocation with 3887032 free bytes and 3MB until OOM)
     call GlideException#logRootCauses(String) for more detail
          Cause (1 of 1): class java.lang.OutOfMemoryError: Failed to allocate a 8294412 byte allocation with 3887032 free bytes and 3MB until OOM
        Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->BitmapDrawable->Drawable}
    There was 1 cause:
    java.lang.OutOfMemoryError(Failed to allocate a 8294412 byte allocation with 3886376 free bytes and 3MB until OOM)
     call GlideException#logRootCauses(String) for more detail
          Cause (1 of 1): class java.lang.OutOfMemoryError: Failed to allocate a 8294412 byte allocation with 3886376 free bytes and 3MB until OOM
      Cause (5 of 7): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{FileInputStream->Object->Drawable}, REMOTE, http://static.bokao2o.com/images/push/2019013117570881300.png
    There were 2 causes:
    java.lang.OutOfMemoryError(Failed to allocate a 8294412 byte allocation with 3884272 free bytes and 3MB until OOM)
2019-08-29 11:28:24.224 30534-30534/com.boka.poster W/Glide: java.lang.OutOfMemoryError(Failed to allocate a 8294412 byte allocation with 3878424 free bytes and 3MB until OOM)
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->GifDrawable->Drawable}
        Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->Bitmap->Drawable}
    There was 1 cause:
    java.lang.OutOfMemoryError(Failed to allocate a 8294412 byte allocation with 3884272 free bytes and 3MB until OOM)
     call GlideException#logRootCauses(String) for more detail
          Cause (1 of 1): class java.lang.OutOfMemoryError: Failed to allocate a 8294412 byte allocation with 3884272 free bytes and 3MB until OOM
        Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->BitmapDrawable->Drawable}
    There was 1 cause:
    java.lang.OutOfMemoryError(Failed to allocate a 8294412 byte allocation with 3878424 free bytes and 3MB until OOM)
     call GlideException#logRootCauses(String) for more detail
          Cause (1 of 1): class java.lang.OutOfMemoryError: Failed to allocate a 8294412 byte allocation with 3878424 free bytes and 3MB until OOM
      Cause (6 of 7): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{ParcelFileDescriptor->Object->Drawable}, REMOTE, http://static.bokao2o.com/images/push/2019013117570881300.png
    There were 2 causes:
    java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0xBEBBB1B7)
    java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0xBEBBB1B7)
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->Bitmap->Drawable}
    There was 1 cause:
    java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0xBEBBB1B7)
     call GlideException#logRootCauses(String) for more detail
          Cause (1 of 1): class java.io.IOException: java.lang.RuntimeException: setDataSource failed: status = 0xBEBBB1B7
        Cause (2 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->BitmapDrawable->Drawable}
    There was 1 cause:
    java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0xBEBBB1B7)
     call GlideException#logRootCauses(String) for more detail
          Cause (1 of 1): class java.io.IOException: java.lang.RuntimeException: setDataSource failed: status = 0xBEBBB1B7
      Cause (7 of 7): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class android.content.res.AssetFileDescriptor, LOCAL, DataCacheKey{sourceKey=http://static.bokao2o.com/images/push/2019013117570881300.png, signature=EmptySignature}
    There was 1 cause:
    java.io.FileNotFoundException(No content provider: http://static.bokao2o.com/images/push/2019013117570881300.png)
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 1): class java.io.FileNotFoundException: No content provider: http://static.bokao2o.com/images/push/2019013117570881300.png
2019-08-29 11:28:24.226 30534-30534/com.boka.poster I/Glide: Root cause (1 of 13)
    java.lang.OutOfMemoryError: Failed to allocate a 8294412 byte allocation with 4031016 free bytes and 3MB until OOM
        at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
        at android.graphics.Bitmap.nativeCreate(Native Method)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:879)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:856)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:823)
        at com.bumptech.glide.load.engine.bitmap_recycle.LruBitmapPool.createBitmap(LruBitmapPool.java:149)
        at com.bumptech.glide.load.engine.bitmap_recycle.LruBitmapPool.getDirty(LruBitmapPool.java:142)
        at com.bumptech.glide.load.resource.bitmap.Downsampler.setInBitmap(Downsampler.java:689)
        at com.bumptech.glide.load.resource.bitmap.Downsampler.decodeFromWrappedStreams(Downsampler.java:298)
        at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:208)
        at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:161)
        at com.bumptech.glide.load.resource.bitmap.ByteBufferBitmapDecoder.decode(ByteBufferBitmapDecoder.java:33)
        at com.bumptech.glide.load.resource.bitmap.ByteBufferBitmapDecoder.decode(ByteBufferBitmapDecoder.java:16)
        at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:72)
        at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:55)
        at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:45)
        at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:58)
        at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:43)
        at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:501)
        at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:472)
        at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:458)
        at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:410)
        at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:379)
        at com.bumptech.glide.load.engine.DataCacheGenerator.onDataReady(DataCacheGenerator.java:95)
        at com.bumptech.glide.load.model.ByteBufferFileLoader$ByteBufferFetcher.loadData(ByteBufferFileLoader.java:74)
        at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:75)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:302)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:269)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:233)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
