### ISSUE TITLE
Android P上几率出现crash

### ISSUE THREAD

**Issue by 1wayticket** [youth5201314/banner#605]
java.lang.IllegalStateException
Can't call getPixels() on a recycled bitmap

com.youth.banner.Banner.initView(Banner.java:111)

1 android.view.InflateException:Binary XML file line #71: Binary XML file line #71: Error inflating class <unknown>
--
2 ......
3 Caused by:
4 java.lang.IllegalStateException:Can't call getPixels() on a recycled bitmap
5 android.graphics.Bitmap.checkRecycled(Bitmap.java:560)
6 android.graphics.Bitmap.getPixels(Bitmap.java:2035)
7 huawei.android.hwutil.IconBitmapUtils.getIconInfo(IconBitmapUtils.java:274)
8 android.content.res.HwResourcesImpl.addIconBackgroud(HwResourcesImpl.java:533)
9 android.content.res.HwResourcesImpl.handleAddIconBackground(HwResourcesImpl.java:597)
10 android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:943)
11 android.content.res.Resources.getDrawableForDensity(Resources.java:1074)
12 android.content.res.Resources.getDrawable(Resources.java:1013)
13 android.content.Context.getDrawable(Context.java:630)
14 android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:463)
15 android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:203)
16 android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:191)
17 android.support.v7.content.res.AppCompatResources.getDrawable(AppCompatResources.java:102)
18 android.support.v7.widget.AppCompatImageHelper.setImageResource(AppCompatImageHelper.java:86)
19 android.support.v7.widget.AppCompatImageView.setImageResource(AppCompatImageView.java:94)
20 com.youth.banner.Banner.initView(Banner.java:111)
21 com.youth.banner.Banner.<init>(Banner.java:96)
22 com.youth.banner.Banner.<init>(Banner.java:84)
23 java.lang.reflect.Constructor.newInstance0(Native Method)
24 java.lang.reflect.Constructor.newInstance(Constructor.java:343)
25 android.view.LayoutInflater.createView(LayoutInflater.java:658)
26 android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:801)
27 android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
28 android.view.LayoutInflater.rInflate(LayoutInflater.java:874)
29 android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
30 android.view.LayoutInflater.rInflate(LayoutInflater.java:877)
31 android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
32 android.view.LayoutInflater.rInflate(LayoutInflater.java:877)
33 android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
34 android.view.LayoutInflater.rInflate(LayoutInflater.java:877)
35 android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
36 android.view.LayoutInflater.rInflate(LayoutInflater.java:877)
37 android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
38 android.view.LayoutInflater.inflate(LayoutInflater.java:515)
39 android.view.LayoutInflater.inflate(LayoutInflater.java:423)
40 android.view.LayoutInflater.inflate(LayoutInflater.java:374)
41 com.mszmapp.detective.base.BaseFragment.onCreateView(BaseFragment.java:48)
42 android.support.v4.app.Fragment.performCreateView(Fragment.java:2439)
43 android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
44 android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
45 android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
46 android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
47 android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
48 android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
49 android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
50 android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3273)
51 android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
52 android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
53 android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:620)
54 android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
55 android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1419)
56 android.app.Activity.performStart(Activity.java:7462)
57 android.app.ActivityThread.handleStartActivity(ActivityThread.java:3388)

在华为手机上一定几率出现这个crash日志

**Comment by yansenkeler** [comment]
请问这个问题解决了吗
