### ISSUE TITLE
如何设置不可滑动

### ISSUE THREAD

**Issue by zhongzhihuashanghai** [youth5201314/banner#607]
是否可以设置不循环呢，滑到最后一张不可以再滑到第一张

**Comment by Steadyoung** [comment]
你现在解决了吗？我在引导页用这个也想禁止滑到最后一页不循环了

**Comment by zhongzhihuashanghai** [comment]
没有，因为没有这个方法，不过应该有其他方法实现的

**Comment by ZoeTTTT** [comment]
请问最新版本加了这个功能吗？我看了这个问题相关的提问没看到结论，我目前用2.0.1版本也没找到，请大神指点一下 @youth5201314

**Comment by youth5201314** [comment]
2.0还没有考虑这个，我一开始想的是既然要轮播肯定是要无限循环的，如果不是想无限循环原生viewpager就能解决了。我下个版本加吧，顺便增加你说的引导页功能。
