### ISSUE TITLE
如何自适应图片

### ISSUE THREAD

**Issue by zhongzhihuashanghai** [youth5201314/banner#608]
有时候图片的大小不一，但现在banner的高度是固定的，图片显示不完全，能自动把图片进行拉伸么

**Comment by id-apple** [comment]
布局文件中加上 app:image_scale_type="fit_center"即可解决。
`<com.youth.banner.Banner
        android:id="@+id/banner"
        android:layout_width="219dp"
        android:layout_height="226dp"
        android:layout_marginTop="16dp"
        app:image_scale_type="fit_center"
...`

**Comment by zhongzhihuashanghai** [comment]
用fit_xy会更好，虽然图片会有一点点拉伸，但所有的图片都是一样大的，也能显示完全，还不会把北京颜色显示出来

**Comment by id-apple** [comment]
看具体需求，不希望拉伸可以用fit_center
