### ISSUE TITLE
setOnBannerClickListener有问题

### ISSUE THREAD

**Issue by 13588823551** [youth5201314/banner#61]
mBanner.setOnBannerClickListener(new OnBannerClickListener() {
	@Override
	public void OnBannerClick(int position) {
		Data item = datas.get(position);
	}
});
这个postion怎么是从1开始到datas.size() 
而不是从0到datas.size()-1 ?

**Comment by MIkeeJY** [comment]
position是从1开始 你就按1的逻辑写咯

**Comment by youth5201314** [comment]
恩
