### ISSUE TITLE
主界面Fragment之间切换,banner的位置偶尔会变灰是怎么回事?

### ISSUE THREAD

**Issue by roybill** [youth5201314/banner#611]
已经在设置过开始轮播和停止
@Override
    public void onStart() {
        super.onStart();
        mTopBanner.startAutoPlay();  //开始轮播
    }
    @Override
    public void onStop() {
        super.onStop();
        mTopBanner.stopAutoPlay();//结束轮播
    }

**Comment by loptreival** [comment]
遇到同样的问题。请问你解决了吗

**Comment by roybill** [comment]
没有,改用其他库了,这个问题建议作者优化一下

**Comment by elimuhub** [comment]
#69

**Comment by hui928636443** [comment]
用了哪个库？

**Comment by roybill** [comment]
BGABanner-Android

**Comment by lucf1103** [comment]
我这边也出现了，5张图片，一进入界面就切换，只加载了前面2张图，后面都显示不出来，重新设置setImageLoader也不行，看到ImageUrls size = 5 是对的。地址也都在
