### ISSUE TITLE
可不可以来个广告，我在大神的基础上重新构建了这个库

### ISSUE THREAD

**Issue by AlpsDog** [youth5201314/banner#614]
支持一屏三页
支持任意View显示在Banner上
支持自定义显示器
支持多种Banner动画
创建的View内部已做缓存，性能更佳
一句话：更加精简，更加智能，更加好用！！！

**Comment by xyZangGit** [comment]
这么牛批么？创建的View内部已做缓存？是list保存起来了么？如果下拉刷新数据变了 会更新么？

**Comment by AlpsDog** [comment]
老铁可以去看一下啊，https://github.com/AlpsDog/Banner，我里面源码备注的很清楚
