### ISSUE TITLE
禁止自动滚动后，滑动到上一页，图片显示异常

### ISSUE THREAD

**Issue by kodeflow** [youth5201314/banner#621]
版本：implementation 'com.youth.banner:banner:1.4.10'
模拟器：Nexus 10 API 26
操作步骤：1、app:is_auto_play="false"；2、向右滑动到上一页
最终效果：图片先满屏显示（正常的），然后闪一下自动缩放显示为异常状态了

**Comment by mezcreate** [comment]
> 版本：implementation 'com.youth.banner:banner:1.4.10'
> 模拟器：Nexus 10 API 26
> 操作步骤：1、app:is_auto_play="false"；2、向右滑动到上一页
> 最终效果：图片先满屏显示（正常的），然后闪一下自动缩放显示为异常状态了

我也遇到这个问题了，不知道大兄弟是怎么解决的
