### ISSUE TITLE
Banner 就一张图片时，点击事件无效

### ISSUE THREAD

**Issue by SixGL** [youth5201314/banner#622]

**Comment by SixGL** [comment]
homeHDIm.setOnBannerListener(object :OnBannerListener{
                    override fun OnBannerClick(position: Int) {
                        ToastUtil.showShortToast("pos= $position")
                        ARouter.getInstance().build(RouteUtils.Home_KWebActivity)
                                .withString("httpurl", hd.result?.get(position)?.vcUrl)
                                .navigation()
                    }
                })

**Comment by cxMax** [comment]
遇到同样的问题， 如果第一张，接收不到点击事件

**Comment by cxMax** [comment]
将点击事件放到start()之前执行
已解决

**Comment by wukangjie** [comment]
@cxMax 原因是什么，可以解释一下吗
