### ISSUE TITLE
加载圆角图片的时候 在滑动的时候会变直角，使用圆角ImageView一样

### ISSUE THREAD

**Issue by qianshengta** [youth5201314/banner#624]
加载圆角图片的时候 在滑动的时候会变直角，使用圆角ImageView一样。可以在库里添加一个圆角的选项吗？

**Comment by qianshengta** [comment]
听从别人的建议使用ViewOutlineProvider将View裁剪成圆角的，出现了一个很奇怪的问题，就是第一次进入app的时候是有效果的，一直都是圆角的没问题，但是以后再打开app，就没效果了，滑动的时候又变回直角了，这是什么鬼问题？
```
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            //getBannerView添加圆角轮廓，否则在滑动过程中会变成直角
            val provider = object : ViewOutlineProvider() {
                override fun getOutline(view: View, outline: Outline?) {
                    outline?.setRoundRect(0, 0, view.width, view.height, ConvertUtils.dp2px(20f).toFloat())
                }

            }
            banner.outlineProvider = provider
            banner.clipToOutline = true
        }
```

**Comment by yyyAndroid** [comment]
me too

**Comment by guoshilun** [comment]
> 听从别人的建议使用ViewOutlineProvider将View裁剪成圆角的，出现了一个很奇怪的问题，就是第一次进入app的时候是有效果的，一直都是圆角的没问题，但是以后再打开app，就没效果了，滑动的时候又变回直角了，这是什么鬼问题？
> 
> ```
>         if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
>             //getBannerView添加圆角轮廓，否则在滑动过程中会变成直角
>             val provider = object : ViewOutlineProvider() {
>                 override fun getOutline(view: View, outline: Outline?) {
>                     outline?.setRoundRect(0, 0, view.width, view.height, ConvertUtils.dp2px(20f).toFloat())
>                 }
> 
>             }
>             banner.outlineProvider = provider
>             banner.clipToOutline = true
>         }
> ```

我也遇到了这个问题，你解决了吗？

**Comment by qianshengta** [comment]
@guoshilun  试试开启硬件加速
