### ISSUE TITLE
个性化定制每张图片的轮播时长

### ISSUE THREAD

**Issue by langrenbule** [youth5201314/banner#63]
如题，能否让每张图片的播放时间都可以 指定
比如第一张播放 3秒 第二张播放 10秒 等等...
期待回复

**Comment by youth5201314** [comment]
你这个需求太冷门了吧！我写这个的目的是方便大多数人，而你这个我根本想不到应用场景，如果你真要做，要么自己改下，要么你可以用banner开放的setOnPageChangeListener(this)事件，再轮播发生改变时，调用setDelayTime(int time)方动态改变下一个图片的时间。

**Comment by langrenbule** [comment]
OK,Thx
