### ISSUE TITLE
2019年10月25日之前，你的Android Studio运行这个项目时候不报错吗？！

### ISSUE THREAD

**Issue by laimiewoa** [youth5201314/banner#640]
2019年10月25日，
下载你这个Demo最新版，
banner-master\banner\src\main\java\com\youth\banner\Banner.java
第505行代码，public int toRealPosition(int position) 方法里面的int realPosition; 
新建了一个对象realPosition却没有赋值，
下面直接判断是否小于0， if (realPosition < 0)  ，
你的Android Studio运行的时候不报错吗？！

    /**
     * 返回真实的位置
     *
     * @param position
     * @return 下标从0开始
     */
    public int toRealPosition(int position) {
        int realPosition;
        if(count!=0){
            realPosition = (position - 1) % count;
        }
        if (realPosition < 0)
            realPosition += count;
        return realPosition;
    }

**Comment by charmeleon2** [comment]
这东西只是个警告，你可以手动初始化为0，不管也能运行。局部变量不会自动初始化（原则上是要手动初始化的），旧版本估计编译器没有检查
