### ISSUE TITLE
在使用BRVAH 给rv增加头部时，里面使用banner发生问题

### ISSUE THREAD

**Issue by WangMiaoGit** [youth5201314/banner#646]
在使用BRVAH 给rv增加头部时，里面使用banner，设定自动轮播时候，跳转icon和  图片的跳转对不上，还出现空白页问题

**Comment by moz1q1** [comment]
放弃不要使用

**Comment by WangMiaoGit** [comment]
还有啥好用 的 banner？ 我试过别的，好像  放着BRVAH 的  头部，banner宽度匹配父窗口，都会有问题。

**Comment by moz1q1** [comment]
用viewpager2
