### ISSUE TITLE
刷新banner 解决方案

### ISSUE THREAD

**Issue by zhangmengjia** [youth5201314/banner#648]
动态添加 banner
ll_banner_contain.removeAllViews();
        List<String> extensionimages = new ArrayList<>();

    
        View view = View.inflate(mContext, R.layout.view_banner_item, null);

        Banner banner = (Banner) view.findViewById(R.id.banner);

            banner.setImages(extensionimages)
                    .setImageLoader(new GlideImageLoader())
                    .setDelayTime(5000)
                    .setOnBannerListener(new OnBannerListener() {
                        @Override
                        public void OnBannerClick(int position) {
                    

                        }
                    })
                    .start();

        ll_banner_contain.addView(view);

**Comment by hexu2016** [comment]
你也是刷新偶尔出现白屏问题吗?
