### ISSUE TITLE
1.4.10的Banner和源码里的不一样

### ISSUE THREAD

**Issue by chris6868** [youth5201314/banner#652]
打包的时候是不是没有更新到，源码里面有indicator_selected_width，1.4.10里面没有这个字段

**Comment by beibeiandroid** [comment]
我也发现了 这个问题 
对不想 下载源码的 所以打了 aar 包 下载链接：https://pan.baidu.com/s/1JBs6QoDCFWrePTjpbItX7A 

android {
    repositories {
        flatDir {
            dirs 'libs'
        }
    }
}

dependencies {
      compile(name: 'banner-1.4.10', ext: 'aar')
}

**Comment by chris6868** [comment]
我已经down了源码自己弄好了本地库，并且升级成了Androidx，感谢
