### ISSUE TITLE
设置数字指示器无效不显示出来

### ISSUE THREAD

**Issue by Dorsey-C** [youth5201314/banner#653]
//设置图片加载器
        //设置banner样式
        banner.setBannerStyle(BannerConfig.NUM_INDICATOR)
        //设置图片加载器
        banner.setImageLoader(GlideImageLoader())
        //设置图片集合
        banner.setImages(bamnerDatas)
        //设置banner动画效果
        banner.setBannerAnimation(Transformer.RotateDown)
        //设置标题集合（当banner样式有显示title时）
//        banner.setBannerTitles(titles)
        //设置自动轮播，默认为true
        banner.isAutoPlay(true)
        //设置轮播时间
        banner.setDelayTime(2000)
        //设置指示器位置（当banner模式中有指示器时）
        banner.setIndicatorGravity(BannerConfig.CENTER)
        //banner设置方法全部调用完毕时最后调用
        banner.start()
设置数字指示器，该指示器不显示，请问下是什么原因呢？

**Comment by RookieJay** [comment]
是不是用代码new的Banner,我的是代码创建的不行，看了另外一个issue，我使用LayoutInflater把xml给inflate到布局就可以了
