### ISSUE TITLE
Recyclerview中使用banner会导致加载的image错乱

### ISSUE THREAD

**Issue by arronvera** [youth5201314/banner#659]
Recyclerview中使用banner会导致加载的image错乱

**Comment by arronvera** [comment]
在使用下拉刷新的时候会出现

**Comment by arronvera** [comment]
解决方式：    在start前先更新banner的数据
 List<String> updateList = new ArrayList<>();
 banner.update(updateList );
然后再start
    banner.setImages(images)
                            .setImageLoader(banneLoad)
                            .isAutoPlay(false)
                            .start();

**Comment by arronvera** [comment]
越滑到后面会出现滑动卡顿

**Comment by WayneSimon** [comment]
> 
> 
> 越滑到后面会出现滑动卡顿

我也是，我的每个Item里都有一个Banner，在滑动时受轮播的影响会很卡顿。即便图片只有一张也是如此。
