### ISSUE TITLE
关于setData 与 指示器的问题

### ISSUE THREAD

**Issue by pgyCode** [youth5201314/banner#667]
使用的版本：2.0
场景：网络加载之后显示带有指示器的轮播图
1.初始化设置了data参数，但是后续直接notify发现不能刷新数据，检查代码发现

    public BannerAdapter(List<T> datas) {
        setDatas(datas);
    }
构造函数并不是直接使用了此数据，网络数据回来之后依旧需要重新setDatas.不能是修改了数据直接notify,使用有些不便利
2.初始设置了指示器，网络回来setData之后不显示指示器，需要重新setIndicator一次，表现来看是个bug

**Comment by youth5201314** [comment]
**首先表示感谢！**不知道我理解是否有误哈！我是这么想的：
1、我之所以没有提供什么刷新、或者集合的各种添加，删除等方法是因为，adapter本身已经暴露给使用者了，这些方法因为业务不同可以都有差异。adapter中可以自己添加任何方法来满足自己的需求，。
2、我觉得初始化的是相关配置方法，如果是网络请求你在网络请求成功调用setAdapter方法，或者在adapter提供自己使用的方法都是能满足你的需求的。

**现在发布预览版本，就是为了大家都能持续沟通来完善，没有一开始弄的大而全，这样反而到时候更新起来麻烦。**你说的是缺少直接notify这些，我的想法如下在adapter自己提供：
`   //更新数据
    public void updateData(List<DataBean> data){
        //这里的代码自己发挥，比如如下的写法等等
        mDatas.addAll(data);
        notifyDataSetChanged();
    }
`
   **你可以提出你的想法，你想是什么样的！大家再讨论，我只能是在我的使用角度看怎么方便，不一定适合多数人。** 我会再提供几个常用的数据操作方法，大家看下需要提供哪些，我们尽量做到合适而不累赘。
