### ISSUE TITLE
2.0是否支持圆角图片设置

### ISSUE THREAD

**Issue by lzjin** [youth5201314/banner#668]
2.0是否支持圆角图片设置

**Comment by youth5201314** [comment]
图片圆角肯定支持啊！使用第三方图片加载器glide、picasso等，或者自定义view都可以实现。**是否是我理解的这个意思？**

**Comment by swallowsonny** [comment]
自定义圆角view，图片的四个角在轮播的时候会闪烁一下

**Comment by jiansheliuxing** [comment]
> 自定义圆角view，图片的四个角在轮播的时候会闪烁一下

我也遇到这个问题了，我用的[vinc3m1/RoundedImageView](https://github.com/vinc3m1/RoundedImageView)轮播的时候，图片会变为非圆角，停下之后才会是圆角

**Comment by hellolemon666** [comment]
> 2.0是否支持圆角图片设置
代码设置背景圆角裁剪：
        banner.setOutlineProvider(new ViewOutlineProvider() {
            @Override
            public void getOutline(View view, Outline outline) {
                outline.setRoundRect(0, 0, view.getWidth(), view.getHeight(), 20);
            }
        });
        banner.setClipToOutline(true);

**Comment by youth5201314** [comment]
@hellolemon666 感谢！ 代码已加入库里面setBannerRound()。

**Comment by lzjin** [comment]
终于等到这个功能了，希望作者尽快发布版本。手动点赞10000
