### ISSUE TITLE
Banner作为Header，当滑出屏幕,RecyclerView会回滚到顶部

### ISSUE THREAD

**Issue by LZKDreamer** [youth5201314/banner#669]
将Banner作为Recyclerview的headerView时，如果Banner已经滑出屏幕，在Banner切换时，Recyclerview会自动回滚到顶部，也就是Banner所处位置，请问怎么解决？PS:在AS的模拟器（Pixel 2 API27）上有这个问题

**Comment by youth5201314** [comment]
这个我才弄得基础版本还没有考虑到各种控件嵌套问题，正式版前我会完善这部分，你使用的搜索原生的控件嘛！是否使用的是第三方自定义的Recyclerview？还有什么问题？

**Comment by LZKDreamer** [comment]
Recyclerview是原生的，Adapter是用的BRVAH，只有Pixel 2 API27这个模拟器有这个问题，安卓10.0的模拟器和真机没有问题，可能是模拟器的原因

**Comment by liuxuesong001** [comment]
我的华为荣耀也出现了这个问题，滑动到其他位置，自动轮播就回到最上边了；

**Comment by youth5201314** [comment]
我用荣耀v8 使用BRVAH添加的header，测试没有问题啊？还有我用的Recyclerview是Androidx的，我这里无法还原你的问题。**不过我建议你在Recyclerview嵌套banner时，最好监听滑动item时是否可见，可见才轮播，不可见时暂停！**

**Comment by youth5201314** [comment]
```java
可以参考下面的代码：
   @Override
    public void onViewDetachedFromWindow(@NonNull BaseViewHolder holder) {
        super.onViewDetachedFromWindow(holder);
        Log.e("----", "onViewDetachedFromWindow:" + holder.getAdapterPosition());
        //定位你的header位置
        if (holder.getAdapterPosition()==0) {
            if (getHeaderLayoutCount() > 0) {
                //这里是获取你banner放的位置，这个根据你自己实际位置来获取，我这里header只有一个所以这么获取
                Banner banner = (Banner) getHeaderLayout().getChildAt(0);
                banner.stop();
            }
        }
    }

    @Override
    public void onViewAttachedToWindow(BaseViewHolder holder) {
        super.onViewAttachedToWindow(holder);
        Log.e("----", "onViewAttachedToWindow:" + holder.getAdapterPosition());
        if (holder.getAdapterPosition()==0) {
            if (getHeaderLayoutCount() > 0) {
                Banner banner = (Banner) getHeaderLayout().getChildAt(0);
                banner.start();
            }
        }
    }
```

**Comment by zhaolin8** [comment]
遇到了同样的问题，华为，上滑能看到一部分banner时，自动滚回顶部。有解决办法吗？

**Comment by wp549741214** [comment]
小米note10也出现问题。而且不止是header的时候会出现问题。多种布局作为第一个item也会出现。不论是否自动滚动。只要滚动就回回弹

**Comment by ddt2016** [comment]
view.setFocusable(true);
view.setFocusableInTouchMode(true);
view.requestFocus();
随便找个view夺取焦点就解决了  2.0.2还是有那个问题

**Comment by wz5779354** [comment]
这个问题在三星s8  8.0系统也出现了，测试了一下，Android 9.0 OPPO手机 及Android10.0 三星s9 plus系统不会出现这个问题,这个bug 可能跟手机系统版本有关

**Comment by wz5779354** [comment]
在模拟器上8.0系统能复现这个问题

**Comment by wz5779354** [comment]
还是  setBannerRound(BannerUtils.dp2px(5f))引起的此bug,去掉圆角或者修改Build.VERSION.SDK_INT >= Build.VERSION_CODES.P 为  if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                canvas.clipPath(path);
            } else {
                canvas.clipPath(path, Region.Op.REPLACE);
            }  就可以了

**Comment by youth5201314** [comment]
好的

**Comment by LoAlex** [comment]
@youth5201314 不好意思, 這個問題最終怎樣解決, 我已經用了最新的banner版本, 三星s8 8.0系统還是會出現這問題

**Comment by LoAlex** [comment]
我不知道你們最後怎樣解決

view.setFocusable(true);
view.setFocusableInTouchMode(true);
view.requestFocus();

以上的答案我都試過, 不太行, 最後發現加了這句 setOnBannerListener 就沒有上述的問題
我也覺得很奇怪, 但我反覆測試過其他手機, 是真的解決了

kotlin:
setOnBannerListener { data, position -> }
