### ISSUE TITLE
能否支持kotlin

### ISSUE THREAD

**Issue by zjw950323** [youth5201314/banner#670]
在使用kotlin时 setAdapter报错
Out-projected type 'Banner<*, *>' prohibits the use of 'public open fun setAdapter(@NonNull p0: BA): Banner<(raw) Any!, (raw) BannerAdapter<*, *>!>! defined in com.youth.banner.Banner'

**Comment by youth5201314** [comment]
刚完成基础版本，kotlin还没有适配，下个版本完善！你可以将你用kotlin写的使用代码简化下贴出来，方便我测试！

**Comment by zjw950323** [comment]
好的 回头我会贴一下 再次感谢大佬贡献这么好用的库 祝大佬新年快乐

**Comment by swallowsonny** [comment]
我也遇到相同的问题，是kotlin的项目代码用不了这个库吗

**Comment by swallowsonny** [comment]
可以这样写 banner.adapter = MyBannerAdapter(list)，就不报错了

**Comment by pumatus** [comment]
@swallowsonny  感谢大佬🧍‍♂️
