### ISSUE TITLE
能简单说一下如何实现视频图片混合轮播？谢谢大神

### ISSUE THREAD

**Issue by JohnGreenn** [youth5201314/banner#673]

**Comment by youth5201314** [comment]
item现在你可以自定义的，你平时怎么使用adapter实现多布局的，现在就怎么实现视频和图片不同类型的轮播，只是目前还没有测试过视频，demo里有多布局的实现，视频这个后面可以考虑再适配，不过我更倾向于轮播的是视频的缩略图和宣传图等，点击在进行视频播放，如果要直接轮播的就是视频播放，这个需要考虑的问题比较多，目前市面上也没有发现类似的案例，你可以整理下你的需求，列出来，我们讨论下！

**Comment by JohnGreenn** [comment]
是这样子的，我觉得您做的banner可以用于类似淘宝的商品详情页头部的宝贝展示，第一个是视频可以播放，后面是图片，我觉得蛮实用的，如果大神有时间并且考虑做的话，https://github.com/Jzvd/JiaoZiVideoPlayer可以考虑这个播放器，我自己也在尝试做，出了不少问题（来自底层码农的尴尬）anyway，感觉大神的开源，respect~

**Comment by youth5201314** [comment]
目前已经在demo中简单实现了类似淘宝的效果，你可以参考
