### ISSUE TITLE
setOnBannerListener出现空指针问题

### ISSUE THREAD

**Issue by lau1989** [youth5201314/banner#675]
getRealCount方法里面getAdapter没判空

**Comment by jerry9433** [comment]
不需要判空吧，没有设置adapter，肯定没法获取到banner数量啊，否则源码里面判空或捕捉到了异常，给你return 0，你岂不是要一脸懵逼找半天。

**Comment by youth5201314** [comment]
理解，这样吧！我打印一个错误日志，提示你先调用setAdapter()方法
