### ISSUE TITLE
ConstraintLayout 嵌套问题

### ISSUE THREAD

**Issue by Yuto910928** [youth5201314/banner#676]
ConstraintLayout中嵌套Banner, android:layout_width="0dp"时，会出现页面一半的情况，设置为match_parent则没事，是不是计算宽度有问题

<com.hyperion.wanre.widget.banner.Banner
                        android:id="@+id/b_banner"
                        android:layout_marginTop="15dp"
                        android:layout_marginStart="15dp"
                        android:layout_marginEnd="15dp"
                        app:layout_constraintLeft_toLeftOf="parent"
                        app:layout_constraintRight_toRightOf="parent"
                        app:layout_constraintTop_toBottomOf="@id/rv_header"
                        android:layout_width="0dp"
                        android:layout_height="85dp" />

**Comment by youth5201314** [comment]
你确定使用的是我的库吗？不过我按照你说的已经测试过了，没有发现问题，后面demo里面会有测试代码！

**Comment by mufaith** [comment]
确实有这个问题，我也是 @Yuto910928  你解决了么

**Comment by Yuto910928** [comment]
> 确实有这个问题，我也是 @Yuto910928 你解决了么

外层换一个布局就好了，或者设置 match_parent
