### ISSUE TITLE
viewpager +fragment里面使用此库滑动冲突

### ISSUE THREAD

**Issue by Jiang00** [youth5201314/banner#677]

**Comment by youth5201314** [comment]
你的viewpager是否是用的AndroidX？能把你的代码贴出来吗？或者弄成demo发到我邮箱。不然我要为每个人去模拟各种使用场景太难了！

**Comment by Jiang00** [comment]
使用了AndroidX，等周末的时候我搞个demo，我暂时使用了其他库

**Comment by keybalabala** [comment]
确实会有这个问题，当一组轮播划完，到第二轮第一个图片时，滑动事件就到viewpager上面了

**Comment by keybalabala** [comment]
问题复现demo已发qq邮箱

**Comment by HancockY** [comment]
那我的应该也是这个问题了 viewpager2+fragment, 用了 AndroidX

**Comment by PhoneBison** [comment]
同样的问题，有解决方案可以参考一下吗？ @keybalabala @Jiang00

**Comment by keybalabala** [comment]
@PhoneBison 我觉得是vp2没处理好的问题，使用1.x的banner库不会出现，不升级就行
