### ISSUE TITLE
在部分机型上资源占用过多导致卡顿严重

### ISSUE THREAD

**Issue by SGPublic** [youth5201314/banner#683]
我使用了自定义banner布局，不知道是不是这部分原因，总之使用banner之后，我的工程在835、660等处理器上卡顿严重，如果以的话，希望作者您能尝试寻找一下可能的原因，需要的话我愿意配合测试。

**Comment by youth5201314** [comment]
这个卡顿跟处理器没什么关系吧，你详细说下你怎么用的？我在使用中确实未发现你说的卡顿严重！

**Comment by SGPublic** [comment]
可能的原因我已经找到了，我使用了Glide加载图片，并在加载完成的时候使用了transition完成了渐入的动画：
.transition(DrawableTransitionOptions.withCrossFade())
此行代码删除即正常。
我所使用的banner最少的情况下有五张图片轮播，使用了渐入动画后全程卡顿，如果这种情况可以修复的话，期待您的更新，感谢。

**Comment by SGPublic** [comment]
> 这个卡顿跟处理器没什么关系吧，你详细说下你怎么用的？我在使用中确实未发现你说的卡顿严重！

可能的原因我已经找到了，我使用了Glide加载图片，并在加载完成的时候使用了transition完成了渐入的动画：
.transition(DrawableTransitionOptions.withCrossFade())
此行代码删除即正常。
我所使用的banner最少的情况下有五张图片轮播，使用了渐入动画后全程卡顿，如果这种情况可以修复的话，期待您的更新，感谢。

**Comment by youth5201314** [comment]
建议：因为是轮播，那么有可能使用者的图片或者view会有很多，如果你使用第三方图片加载器来实现动画，体验真正的不是很好，因为你的轮播间隔时间是固定的，然后你还要考虑的动画执行时间，而你是加载成功后才有的动画，看起来就会很卡样子。你要实现动画可以用PageTransformer，或者参考RecyclerView的动画实现（因为viewpager2基于RecyclerView实现）

**Comment by Wynsbin** [comment]
当前用的是banner1.4.10版本，在部分机子上也有出现滑动卡顿
前提：
scrollview嵌套了banner+recyclerview，recyclerview每个item都是单张图片
当recyclerview item多的情况，就会出现滑动卡顿。
但是如果不嵌套banner的话，recyclerview添加再多的item也没有卡顿问题。
设置了banner.isAutoPlay(false)，BannerLoader没有设置动画
