### ISSUE TITLE
setUserInputEnabled(false)时，触摸banner导致调用stop()

### ISSUE THREAD

**Issue by jerry9433** [youth5201314/banner#684]
![image](https://user-images.githubusercontent.com/31622465/75227628-7b8c2500-57e9-11ea-883b-76eed0d3461e.png)
正常轮播时，点击banner会调用stop()，应该判断getViewPager2().getUserInputEnabled

**Comment by youth5201314** [comment]
已修改

**Comment by jerry9433** [comment]
已经提交最新版了吗

**Comment by youth5201314** [comment]
今天提交
