### ISSUE TITLE
关闭自动轮询的情况下,手动滑动banner,onBannerChanged方法不回调

### ISSUE THREAD

**Issue by weinierfei** [youth5201314/banner#689]
关闭自动轮询的情况下,手动滑动banner,onBannerChanged方法不回调

**Comment by qq84266454** [comment]
> 关闭自动轮询的情况下,手动滑动banner,onBannerChanged方法不回调

你可以试试addOnPageChangeListener方法

**Comment by youth5201314** [comment]
这个设计之初，就是为了区分自动和手动回调。有些特殊的需求需要区分统计手动滑动和自动滑动的！比如广告等，所以onBannerChanged自动轮播才会调用，如果要保证每次都调用可以用OnPageChangeListener
