### ISSUE TITLE
能否支持遥控按键事件，方便TV端开发使用。

### ISSUE THREAD

**Issue by jamin918** [youth5201314/banner#690]
非常感谢作者开源，在使用过程中发现该库好像暂时不支持遥控按键事件。能否支持遥控事件呢？

**Comment by youth5201314** [comment]
@jamin918 我没有真实的机器测试，这是在模拟器跑的方法，你可以测试下，目前监听了左右按键切换banner。
如果你测试稳定我在加入到库里面，有什么问题你可以修改下！
` 
   @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        int count = banner.getAdapter().getItemCount();
        switch (keyCode) {
            case KeyEvent.KEYCODE_DPAD_LEFT:
                Log.d(TAG, "向左");
                int prev = (banner.getViewPager2().getCurrentItem() - 1) % count;
                if (prev == 0) {
                    prev = banner.getRealCount();
                } else if (prev == count - 1) {
                    prev = 1;
                }
                banner.getViewPager2().setCurrentItem(prev, false);
                break;
            case KeyEvent.KEYCODE_DPAD_RIGHT:
                Log.d(TAG, "向右");
                int next = (banner.getViewPager2().getCurrentItem() + 1) % count;
                if (next == 0) {
                    next = banner.getRealCount();
                } else if (next == count - 1) {
                    next = 1;
                }
                banner.getViewPager2().setCurrentItem(next, false);
                break;
        }
        int real = BannerUtils.getRealPosition(banner.isInfiniteLoop(), banner.getViewPager2().getCurrentItem(), banner.getRealCount());
        banner.getIndicator().onPageSelected(real);
        return super.onKeyDown(keyCode, event);
    }
`

**Comment by jamin918** [comment]
感谢作者在百忙之中回复我的提问。我目前使用的是1.4.10版本的，将源码接入到项目中然后进行修改暂时满足了遥控操作，并且处理了当只有一张图片时按遥控左右键然后能切换图片的问题。

**Comment by jamin918** [comment]
对遥控按键的监听是仿照源码，在BannerPagerAdapter的instantiateItem方法里对view设置onKeyListener, 然后通过接口回调的方式公布出去，这种方式在遥控左右切换频繁时偶尔会出现图片闪烁（销毁重新加载）的现象。
