### ISSUE TITLE
多个图片轮播各图片停留时间不一致怎么解决

### ISSUE THREAD

**Issue by kenxiong0113** [youth5201314/banner#697]
比如三张图片 A、B、C、D ,图片轮播的时候A、停留5秒，B停留4秒，C 停留3秒，D停留2秒，这个能解决吗？

**Comment by youth5201314** [comment]
你这个需求确实挺特殊，可以解决你可以监听轮播切换addOnPageChangeListener，然后调用setDelayTime改变时间就行了
