### ISSUE TITLE
Banner 点击事件无效（多张图）

### ISSUE THREAD

**Issue by alanzyz** [youth5201314/banner#698]
现象：多张图，采用ImageNetAdapter 加载网络图片。点击，不走：OnBannerClick 回调。
采用类实现的方式不走，直接监听（匿名内部类）也不走。
tips：偶先走过一次。之后绝大多数情况都不走。

**Comment by alanzyz** [comment]
原因找到了。用了两个adapter，应该用同一个，第二个用setdata，然后
  imageNetAdapter.setDatas(body.getTyeslides());
                imageNetAdapter.notifyDataSetChanged();

有不理解的：加v信alanzyz123

**Comment by liugt34** [comment]
感谢，问题已解决
