### ISSUE TITLE
关于setDatas出现的两个问题

### ISSUE THREAD

**Issue by MrXiaoLiu** [youth5201314/banner#699]
第一：当使用banner.setDatas(mDataBeans)更新数据时，会崩溃发现是这个方法里Indicator没有做非空判断。
第二：如果设置adapter时集合为0，请求完数据在次调用setDatas更新会从最后一位开始，并且第一次轮播时会跳过第一个

**Comment by MrXiaoLiu** [comment]
版本为2.0.0-alpha02

**Comment by youth5201314** [comment]
已经修改，到时候你用下最新版本
