### ISSUE TITLE
加载文字

### ISSUE THREAD

**Issue by wuzhaohui026** [youth5201314/banner#7]
我的请求数据是个list，里面有图片地址和对应的标题，但是发现用这个只能加载图标，你的标题的方法是个数组，是否可以增加个List类型的

**Comment by youth5201314** [comment]
ok，等会加上通知你！

**Comment by youth5201314** [comment]
已更新。你用1.1.7版本的setBannerTitleList 方法

**Comment by wuzhaohui026** [comment]
我去，这么高效！我可以直接添加moudle依赖吗？

**Comment by youth5201314** [comment]
可以

**Comment by wuzhaohui026** [comment]
谢谢。可以赞赏你的开源和高效么。嘿嘿
