### ISSUE TITLE
首次进入fragment时，banner会卡到第1张的右半边和第2张的左半边，自动轮播也不好使，必须手动滑动一下。

### ISSUE THREAD

**Issue by jerry9433** [youth5201314/banner#700]
首次进入Fragment，请求接口后设置banner，就会卡到1张半的位置。项目中用到了两个地方，首页的banner没问题，最后一个Fragment出现的这种情况，fragment是懒加载的

**Comment by jerry9433** [comment]
还有个问题就是如果banner有两张，刚进来页面时，会默认显示第二张，并且第二张会播放两次，随后正常。卡住的那个问题我用mBanner.getViewPage2().setCurrentItem()暂时解决了

**Comment by xuhuanli** [comment]
你好 有什么解决的办法吗
