### ISSUE TITLE
关于最低版本的sdk

### ISSUE THREAD

**Issue by HolmesBill** [youth5201314/banner#702]
加了banner库和Glide库后最低版本要求要26以上，这个很难做低版本的适配
还有banner里面用Glide加载图片不能用Glide自带的圆角功能

**Comment by hellolemon666** [comment]
我添加这个没有版本提示了
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

**Comment by HolmesBill** [comment]
好神奇，突然又可以了，不加你这段代码突然又可以了
