### ISSUE TITLE
请问怎么监控什么时候轮播，我需要根据图片更换背景颜色

### ISSUE THREAD

**Issue by TangShuShu** [youth5201314/banner#703]

**Comment by jerry9433** [comment]
setOnBannerListener.onBannerChanged(int position)

**Comment by TangShuShu** [comment]
谢谢您的帮助

**Comment by youth5201314** [comment]
使用addOnPageChangeListener方法

**Comment by TangShuShu** [comment]
谢谢 现在正是用的这个您的这个方法

**Comment by lll1590** [comment]
> ```
> mBanner.setOnBannerListener(new OnBannerListener() {
>                     @Override
>                     public void OnBannerClick(Object data, int position) {
>                     }
> 
>                     @Override
>                     public void onBannerChanged(int position) {
>                           //这里写逻辑
>                     }
>                 });
> ```

我使用这个方法，有时有用，有时没用是为什么？
