### ISSUE TITLE
RecyclerView banner滑动时会置顶

### ISSUE THREAD

**Issue by byc4426** [youth5201314/banner#705]
RecyclerView  中第一个 item 是 banner，后面都是常规item,
当上滑到banner部分不可见时（如banner一半可见一半不可见），banner自动滑动时，RecyclerView  会置顶至banner全可见。

**Comment by happyHou** [comment]
+1

**Comment by yueyufan** [comment]
感觉是嵌套之后的焦点问题

**Comment by jerry9433** [comment]
[参考这个issues](https://github.com/youth5201314/banner/issues/669)

**Comment by LoAlex** [comment]
以上的答案我都試過, 不太行, 最後發現加了這句 setOnBannerListener 就沒有上述的問題
我也覺得很奇怪, 但我反覆測試過其他手機, 是真的解決了

kotlin:
setOnBannerListener { data, position -> }
