### ISSUE TITLE
不能使用MarginPageTransformer(1500)

### ISSUE THREAD

**Issue by happyHou** [youth5201314/banner#706]
I want to implement Carousel using View Pager2 with preview of left and right page like this:
![image](https://user-images.githubusercontent.com/13503990/77223282-16ccac00-6b96-11ea-9a2e-4d23a8f2c6ab.png)

**Comment by youth5201314** [comment]
可以参考demo，使用下面的方式看看应该能达到你的要求，后面我再适配到库中
`banner.addItemDecoration(new MarginItemDecoration((int) BannerUtils.dp2px(20)));
banner.setPageTransformer(new MultiplePagerScaleInTransformer((int) BannerUtils.dp2px(30),0.1f));`
