### ISSUE TITLE
老哥版本编译失败了，升级一下gradle版本

### ISSUE THREAD

**Issue by SherlockGougou** [youth5201314/banner#708]
Build file '/home/jitpack/build/app/build.gradle' line: 1

* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'com.android.application']
   > Minimum supported Gradle version is 5.4.1. Current version is 4.8.1. If using the gradle wrapper, try editing the distributionUrl in /home/jitpack/build/gradle/wrapper/gradle-wrapper.properties to gradle-5.4.1-all.zip

**Comment by youth5201314** [comment]
我用的5.4.1，你用的是4.8.1太老了。你升级下吧
