### ISSUE TITLE
banner点击事件----点击的位置显示错乱

### ISSUE THREAD

**Issue by AlvinQiang** [youth5201314/banner#71]
banner自动轮播时点击每个图片，Position显示没问题（默认从1开始的吧），但是手动反向滑动图片时，再点击图片出现当前位置-1的问题

**Comment by youth5201314** [comment]
Transformer.Accordion动画暂时有点影响，你换个动画！

**Comment by apm29** [comment]
现在版本Accordion动画还有这个问题吗
