### ISSUE TITLE
2.0.0

### ISSUE THREAD

**Issue by liu19890210** [youth5201314/banner#710]
2.0.0版，imageView 显示图片拉伸，<ImageView android:id="@+id/ivBanner"
           android:layout_width="match_parent"
           android:layout_height="178dp"
           android:scaleType="center"
           android:adjustViewBounds="true"/>

**Comment by youth5201314** [comment]
图片怎么显示，这个是你可以自己控制的，跟banner本身没有关系哈！

**Comment by liu19890210** [comment]
<ImageView android:id="@+id/ivBanner"
           android:layout_width="match_parent"
           android:layout_height="match_parent"
           android:adjustViewBounds="true"/&gt;这样设值，不会铺满banner
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Spring"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月27日(星期五) 中午12:02
收件人:&nbsp;"youth5201314/banner"<banner@noreply.github.com&gt;;
抄送:&nbsp;"601329828"<601329828@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youth5201314/banner] 2.0.0 (#710)





 
图片怎么显示，这个是你可以自己控制的，跟banner本身没有关系哈！
