### ISSUE TITLE
vp2滑动冲突

### ISSUE THREAD

**Issue by likexjw** [youth5201314/banner#712]
vp2里面有fragment，fragment里面有recyclerview，item里面有banner。banner只有在切换中的时候（动的时候）才能手动滑动，否则滑动的时候会滑动最外层的vp2

**Comment by likexjw** [comment]
尝试改了下demo中的RecyclerViewBannerActivity，发现也是会出现滑动冲突的

**Comment by youth5201314** [comment]
已经解决，明天上传！

**Comment by youth5201314** [comment]
已经上传，用下最新版本看看

**Comment by LeonShannon** [comment]
这个问题测试成功了，#711 这个还是存在
