### ISSUE TITLE
不设置layout_margin的情况下，无法加载图片

### ISSUE THREAD

**Issue by listensong** [youth5201314/banner#713]
你好
感谢你的banner控件
我在使用的时候，遇到一个问题。
当我的布局文件里 banner 的 layout_margin 为 0dp 的时候，会导致 banner 图片无法加载。
但是如果设置 layout_margin 为 1dp(只要大于0) 的时候，图片可以正常加载显示。
以下是无法加载图片时候的布局代码：
`
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/drawer_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true"
    tools:openDrawer="start">

    <com.youth.banner.Banner
        android:id="@+id/banner"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        android:layout_width="0dp"
        android:layout_margin="0dp"
        android:layout_height="180dp" />
</androidx.constraintlayout.widget.ConstraintLayout>

`
用的库版本是这个：
    //轮播库
    api "com.youth.banner:banner:2.0.0-beta01"

然而，我下载banner的demo，尝试在demo上修改layout_margin来重现的时候，发现demo又没有问题。

我现在只是想列出来让大家看到，避免在layout_margin上踩坑。

感谢banner，我会找时间试着查找原因，反正目前也不急。

**Comment by youth5201314** [comment]
我多次测试也没有发现你说的问题

**Comment by listensong** [comment]
@youth5201314 
感谢回复。
这是我发现这个问题的文件 [https://github.com/listensong/WanAndroidWorld/blob/master/app/src/main/res/layout/activity_welcome.xml](https://github.com/listensong/WanAndroidWorld/blob/master/app/src/main/res/layout/activity_welcome.xml)

我试着新建demo想最小化重现这个问题，又重现不了了。
所以我暂时也不想改了，直接加个 1dp 了。
