### ISSUE TITLE
轮播图首次加载数据，图片的轮播不是从第一张开始

### ISSUE THREAD

**Issue by seen2016** [youth5201314/banner#715]
轮播图首次加载数据，图片的轮播不是从第一张开始，如何设置 从第一张图片开始轮播？

**Comment by youth5201314** [comment]
是从第一张开始轮播的啊

**Comment by seen2016** [comment]
忘了说了，我的图片是网络请求获取的，如果仅仅是本地初始化的数据不会有问题，但是网络请求的话就会出现我说的那个问题

**Comment by youth5201314** [comment]
我demo也有网络图片加载的例子，我也测试过没有问题啊。你要是有问题可以发下你的代码，或者一个错误的demo

**Comment by seen2016** [comment]
是这样的，我们是调用接口返回 轮播图片的url  ，这里返回的是list集合 ，在请求成功之后，获取到 轮播图集合 往控件里设置后，会出现我说的那种图片加载顺序的问题

**Comment by royorange** [comment]
我这边网络数据回来后也是第一帧在最后一张

**Comment by seen2016** [comment]
有可能是ViewPage的数据展示有问题

**Comment by youth5201314** [comment]
我理解你的情况了，我再看看！下个版本提交优化！

**Comment by CJR10032** [comment]
2.0.12版本没能解决这个bug，使用场景是把adapte抽取为成员变量了，初始化给了一个空集合，等网络请求数据回来后更新集合的值然后调用adapter的notifyDataSetChange就能重现

**Comment by liuteng0117** [comment]
请问解决这个问题了么 我这边也遇到了同样的问题

**Comment by sinduanan** [comment]
我也遇到同样问题啊
