### ISSUE TITLE
Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed

### ISSUE THREAD

**Issue by MorningBreeze** [youth5201314/banner#716]
Banner类第248行，应该加个判断

if(Build.VERSION.SDK_INT >= 26){
                canvas.clipPath(path);
 }else {
                canvas.clipPath(path, Region.Op.UNION);
            }

**Comment by JasonTian23** [comment]
是Android 9.0以上，修改如下可运行：
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
	canvas.clipPath(path);
} else {
	canvas.clipPath(path, Region.Op.REPLACE);
}

**Comment by youth5201314** [comment]
我测试下看看
