### ISSUE TITLE
recyclerview头部添加banner会滚动

### ISSUE THREAD

**Issue by ddt2016** [youth5201314/banner#717]
recyclerview头部添加banner, banner向上划出屏幕一半距离,当banner切换,banner就会滚动下去

**Comment by youth5201314** [comment]
这个你需要监听recyclerview的item可见和消失，进行判断暂停和开始，item都已经不可见如果再轮播也不合理，文档有提供简单的方案参考，有问题继续反馈

**Comment by ddt2016** [comment]
> 这个你需要监听recyclerview的项目可见和消失，进行判断暂停和开始，item都已经不可见如果再轮播也不合理，文档有提供简单的方案参考，有问题继续反馈

我是用viewpager做的,在一个fragment添加了rv,rv添加banner就出现这情况,今天发现给view pager添加了setOffscreenPageLimit,就发现banner不会滚动下来,测试单纯在ac上的rv头banner是不会出现那个情况,大佬可以参考一下

**Comment by ddt2016** [comment]
> 这个你需要监听recyclerview的item可见和消失，进行判断暂停和开始，item都已经不可见如果再轮播也不合理，文档有提供简单的方案参考，有问题继续反馈

**Comment by ddt2016** [comment]
> 这个你需要监听recyclerview的item可见和消失，进行判断暂停和开始，item都已经不可见如果再轮播也不合理，文档有提供简单的方案参考，有问题继续反馈


大佬大佬,已经解决了,焦点问题,在布局上随便找个view拿到焦点就解决了,就下面三句代码
view.setFocusable(true);
view.setFocusableInTouchMode(true);
view.requestFocus();
