### ISSUE TITLE
2.0.1 banner 最后一张到第一张会有一个闪烁的

### ISSUE THREAD

**Issue by Ymars1990** [youth5201314/banner#720]
如题，这个问题需要如何解决

**Comment by youth5201314** [comment]
已解决，过两天一起提交

**Comment by Ymars1990** [comment]
> 已解决，过两天一起提交
感谢作者！

**Comment by Ymars1990** [comment]
2.0.2版本依旧还有这个问题，修改没加进去？
是否可以在加载图片那，我自行处理？

**Comment by youth5201314** [comment]
图片加载本来就是你处理啊

**Comment by Ymars1990** [comment]
我知道图片是自己处理，我说的闪烁问题在加载图片那处理，我试了一下2.0.2 还是存在上诉问题。glide 已做了换出处理

**Comment by youth5201314** [comment]
抱歉！我没有能理解你的问题，加载图片我是无法控制的，这个已经完全交给使用者来实现了。banner内部没有做任何加载图片的处理，所以我也无法给你提供什么在加载图片那处理。然后我测试的结果并没有发现什么闪烁？你可以说的更详细下或者提供下截图或者视频或者问题demo。这个目前就只有你反馈了，我真的无法定位。其他朋友遇见也可以来反馈下！
