### ISSUE TITLE
怎么设置滑动到第N张，或从第N张开始滑动

### ISSUE THREAD

**Issue by byc4426** [youth5201314/banner#722]
banner:2.0.1
需要一开始就从第N张开始轮播，如有5张轮播图，一开始需要从第3张开始轮播。
尝试  banner.getViewPager2().setCurrentItem(p);   没效果

**Comment by youth5201314** [comment]
这个已经修改了，后面一起提交

**Comment by Qdafengzi** [comment]
> 这个已经修改了，后面一起提交

2.1.0用
 banner.getViewPager2().setCurrentItem(0);
 banner.setCurrentItem(0,false);
都没起作用，这个更新了吗？大佬

**Comment by youth5201314** [comment]
我测试有效果的！如果使用了指示器，最后再调用下setIndicatorPageChange方法！
