### ISSUE TITLE
android.view.View.canScrollVertically(int)' on a null object reference

### ISSUE THREAD

**Issue by agonytyh** [youth5201314/banner#723]
在锤子手机上遇到的  问题
 java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.view.View.canScrollVertically(int)' on a null object reference

**Comment by youth5201314** [comment]
使用下最新版本在看看

**Comment by weinihecai** [comment]
这个问题我也遇到了
宇飞来 YU FLY F9,
金立 M7

**Comment by youth5201314** [comment]
用下最新的版本，再反馈还有没有问题

**Comment by weinihecai** [comment]
好的,我给客户试试

**Comment by weinihecai** [comment]
好了,现在没问题了
