### ISSUE TITLE
为什么首次进入fragment时，banner没有轮播呢？和Demo的代码对照过了

### ISSUE THREAD

**Issue by jiapengtao** [youth5201314/banner#724]
为什么首次进入fragment时，banner没有轮播呢？和Demo的代码对照过了，代码一致，但是demo首次进入可以轮播，我的就不行

**Comment by youth5201314** [comment]
首先你没有关闭自动轮播或者设置的不能无限循环，然后你需要调用start方法后才会开始轮播，我是将方法放在生命周期里的，这个你可以根据你的实际情况来

**Comment by jiapengtao** [comment]
谢谢你，确实是没加start的原因，但是我把demo的代码拷贝到一个新的工程中依旧不行，而demo首次是可以轮播的，它没调start方法

**Comment by jiapengtao** [comment]
谢谢你，可以用
