### ISSUE TITLE
2.0.2框架依然会存在canScrollVertically(int)' on a null object reference

### ISSUE THREAD

**Issue by RoyZhang94** [youth5201314/banner#726]
Attempt to invoke virtual method 'boolean android.view.ViewGroup.canScrollVertically(int)' on a null object reference
com.youth.banner.util.ProxyLayoutManger.onInitializeAccessibilityNodeInfo(ProxyLayoutManger.java:1)
bugly上显示存在该错误的机型有华为 VCE AL00| Android 9,level 28、一加 GM1910| Android 10,level 29、OPPO PCAM00 | Android 9,level 28等

**Comment by royorange** [comment]
![image](https://user-images.githubusercontent.com/12166563/78634576-d16ae700-78d6-11ea-8674-a8a1a71bcca7.png)
我这边在小米的兼容测试中也出现了这个问题，版本为2.0.2

**Comment by royorange** [comment]
兼容测试中Nexus 5X 6.0.1 也有发生

**Comment by Dragonles** [comment]
锤子pro2 也是这个问题

**Comment by Dragonles** [comment]
@youth5201314

**Comment by youth5201314** [comment]
我真的太难了，我的几款测试机都无法复现你们的问题。我只能在理论上分析后进行修改，还希望你们再测试下了。使用最新2.0.3版本看看，文档还么有更新直接改版本号就行

**Comment by jhwsx** [comment]
辛苦了。

**Comment by zguop** [comment]
@youth5201314 很感谢作者使用我的方式哈  给LayoutManager塞mRecyclerView，一定要在recyclerView.setLayoutManager(proxyLayoutManger);调用之后，因为setLayoutManager才会清空之前的layout ，我看到作者是最后才设置的，这样就导致了之前LinearLayoutManager里的mRecyclerView为null了

**Comment by youth5201314** [comment]
@zguop 感谢

**Comment by zhpanvip** [comment]
直接copy banner的这个类，果真页出现了这个问题。
