### ISSUE TITLE
没有升级x的项目看着干着急=_=

### ISSUE THREAD

**Issue by lisai555** [youth5201314/banner#728]

**Comment by yangmengli** [comment]
+1

**Comment by youth5201314** [comment]
Androidx已经普及很久了啊！因为我是基于viewpager2实现的，所以工程必须支持Androidx的，现在在提供viewpager的版本有点浪费，你们使用viewpager的就只能用1.0版本了。我是推荐你们将项目升级到Androidx的！

**Comment by chanchangxing** [comment]
为了用这个库升了androidx，更新一个库两个绩效，香

**Comment by wangpingtaohn** [comment]
我项目使用了AndroidX，但是其他页面还在使用Viewpager，引入该依赖后，fragment的onAttach()，activity的onActivityResult()都报错。

**Comment by Towns-Leo** [comment]
只能放弃这个库了，升级androidX,成本太高，绩效要凉凉了

**Comment by keaitao0321** [comment]
项目中必须要用的第三方库没有升级androidx，崩溃
