### ISSUE TITLE
滑动冲突问题

### ISSUE THREAD

**Issue by RealFeeling** [youth5201314/banner#729]
Activity中使用了Viewpager2，其中一页使用的Recyclerview 加上Header，Header里用的该库的banner。在切换banner换页时，极其容易导致Activity的Viewpager2换页~ 望回复，谢谢

**Comment by youth5201314** [comment]
这个我demo中已经测试过了，没有问题啊，你先看下demo呢

**Comment by keybalabala** [comment]
@youth5201314 大佬，还是有问题，我把视频发你qq邮箱了，麻烦看一下哈

**Comment by keybalabala** [comment]
如果在banner上movedown，然后不松开滑动，是不会滑动冲突，但是像视频里一样，我在banner上直接滑，就冲突了

**Comment by youth5201314** [comment]
我看了，ViewConfiguration.get(context).getScaledTouchSlop()推荐的最小距离，实际使用确实存在问题，我将最小距离调小了测试没有问题了。明天你在用最新版试试
