### ISSUE TITLE
indicator_selected_color设置为白色#FFFFFF，显示的却是灰色

### ISSUE THREAD

**Issue by ooftf** [youth5201314/banner#731]
indicator_selected_color设置为白色#FFFFFF，显示的却是灰色

**Comment by youth5201314** [comment]
你可以仔细看下demo，是没问题的。你反馈的太简单的，我不了解你是怎么用的

**Comment by ooftf** [comment]
我设置成红色，绿色都没问题，设置成#FFFFFF或#FFFFFFFF显示的却不是白色，最后用#FEFFFFFF代替用了个伪白色，你可以试一下

**Comment by youth5201314** [comment]
已经找到原因了，我改完其他的下周再一起更新
