### ISSUE TITLE
急！更新到最新版后，自动化测试vivo手机全部阵亡

### ISSUE THREAD

**Issue by jerry9433** [youth5201314/banner#732]
![image](https://user-images.githubusercontent.com/31622465/78874255-ae7b3700-7a7e-11ea-967c-b55790dd2865.png)

![image](https://user-images.githubusercontent.com/31622465/78874315-c783e800-7a7e-11ea-81fb-b7137d0d76d1.png)

**Comment by youth5201314** [comment]
图片加载不出来，你详细描述下呢？

**Comment by jerry9433** [comment]
你邮箱多少，我发给你，还有Vivo提供的log日志

**Comment by youth5201314** [comment]
1028729086 你加我qq吧
