### ISSUE TITLE
RecyclerView + banner 问题

### ISSUE THREAD

**Issue by gh4work** [youth5201314/banner#733]
运行Demo, 在RecyclerView + banner界面，上滑，至第一个banner部分滑出屏外，然后静止不动。过一会儿，这个banner自动播放下一页，整个界面闪动，向下移，滑出的banner又完整显示了。这种情形下，如何改动可以使得banner自动播放时界面没有任何变化，求教

**Comment by youth5201314** [comment]
文档有建议关于滑动的策略：当banner不可见时我们应该停止轮播，可见时开始轮播的操作。看下demo和文档的方法然后你试试看呢？不知道能不能解决你的问题，可以持续反馈！

**Comment by youth5201314** [comment]
我更新下，你明天用下2.0.5看看

**Comment by gh4work** [comment]
嗯，在提问前有看过文档，重写onViewDetachedFromWindow和onViewAttachedToWindow方法，没走通。看Demo，运行后发现Demo也有类似的情况。bannner是在部分可见、另一部分不可见（滑出屏外）的状态下

**Comment by youth5201314** [comment]
和我理解的不一样，我还以为是完全消失呢，你这样的不完全消失时真的不好监听了!

**Comment by gh4work** [comment]
哦，知道了，谢谢你

**Comment by youth5201314** [comment]
有思路能解决，但是个人觉的是否有必要做这个限制？如果有部分不可见你轮播时确实是应该下滑到显示全部，不然轮播就没有意义；如果选择有一点不可见就不轮播，这一点是否合理呢？这个问题看大家的思考了。如果确实需要的话，那么可以监听RecyclerView 的滑动，然后来计算判断的，或者在在图片最上面加一像素view来判断是否可见。你可以尝试下

**Comment by youth5201314** [comment]
你用最新版本，然后不用调用start方法，参考demo，然后给父控件设置焦点就能解决你的问题。考虑到不是所有人都需要这样的效果，所以没有加到库里面。

**Comment by youth5201314** [comment]
@gh4work

**Comment by liyahui2015** [comment]
您好，我也遇到了这个问题，感觉像是banner在没有停止时，每次切换都会捕获焦点，导致RecyclerView上移到了顶部

**Comment by liyahui2015** [comment]
根据大佬的解决思路，只要给RecyclerView的父控件设置焦点就可以了：
android:focusable="true"
android:focusableInTouchMode="true"
其他都不用动，希望遇到同样问题的小伙伴快速解决！

**Comment by gh4work** [comment]
问题已解决，谢谢你们

**Comment by HeroLBJ** [comment]
@WestWerewolf 

android:focusable="true"
android:focusableInTouchMode="true" 
我这边
RecyclerView的父布局是SmartRefreshLayout，添加了还是会跳一下，未解决

**Comment by WestWerewolf** [comment]
@HeroLBJ 切换到最新版本2.0.5了吗？
implementation 'com.youth.banner:banner:2.0.5'

**Comment by HeroLBJ** [comment]
@WestWerewolf 切换了试了一下，还是跳一下， 我是在RecyclerView Adapter中设置的Banner

**Comment by WestWerewolf** [comment]
@HeroLBJ 那你把onViewDetachedFromWindow和onViewAttachedToWindow这俩方法注掉试试吧，我也是Adapter中设置的Banner，父布局也是一个刷新控件，我这里没问题了

**Comment by HeroLBJ** [comment]
@WestWerewolf 谢谢回复，已修改完毕，并不是Banner控件的问题，我布局中有TextSwitch，同样也会导致页面网上跳一下，我的情况和这位大佬一样，把ViewPager2改成ViewPager就好了。最终原因不清楚 #688
