### ISSUE TITLE
自动轮播

### ISSUE THREAD

**Issue by GodOfChen** [youth5201314/banner#734]
大佬，这个轮播到最后一张咋不能自动轮播了

**Comment by youth5201314** [comment]
怎么会呢？你运行下demo看看呢？如果还有问题，在反馈下你怎么用的

**Comment by GodOfChen** [comment]
你好大佬，是这样的，我这里的需求是视频和图片混合轮播，视频需要在滑到时自动播放，所以我模仿这个demo里的淘宝案例，修改一些自动轮播属性，让它自行滑动，而且监听了您demo使用的播放控件的生命周期，在播放控件onPrepared准备播放时调用了banner.stop()方法,在播放完后调用了banner.start()方法继续轮播，但是滑到最后一张图片时，可能由于预加载，还没滑到视频页，播放控件执行了onPrepared方法里的banner.stop()，就停留在了最后一张图片页，要等到视频播放完了执行了banner.start()才能继续滑动（这需要好久体验不好），想问您有没有方法能让banner不预加载，不然这生命周期不好控制，麻烦您了

**Comment by youth5201314** [comment]
首先我不建议你自动轮播，毕竟是视频自动播放的话，你还要监听播放进度然后在控制切换。你出现的问题是因为自动轮播，在实现无线循环时候在首尾各多放了一个item，所以我才提供了禁止无线循环的属性。你要是想实现那就只能通过setcurrentitem来控制切换，而不是靠我内部的自动轮播，毕竟我是不知道你的视频是否播放完了

**Comment by GodOfChen** [comment]
请问如何使用这个setcurrentitem来实现无限轮播呢？能提供一下思路吗？感谢

**Comment by youth5201314** [comment]
你看下我的tvactivity里面，思路类似

**Comment by tangmoushi** [comment]
> 请问如何使用这个setcurrentitem来实现无限轮播呢？能提供一下思路吗？感谢

请问你解决了吗。我也遇到相同的需求

**Comment by GodOfChen** [comment]
你好我的实现方法是在适配器的onBindView方法里赋值完成后执行一个回调，回调的实现主要是执行延迟几秒的runnable,runnable里调setCurrentItem来切换轮播
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"TangMs"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月9日(星期二) 下午5:36
收件人:&nbsp;"youth5201314/banner"<banner@noreply.github.com&gt;;
抄送:&nbsp;"陈智健"<1258178275@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youth5201314/banner] 自动轮播 (#734)





  
请问如何使用这个setcurrentitem来实现无限轮播呢？能提供一下思路吗？感谢
  
请问你解决了吗。我也遇到相同的需求

**Comment by tangmoushi** [comment]
> 你好我的实现方法是在适配器的onBindView方法里赋值完成后执行一个回调，回调的实现主要是执行延迟几秒的runnable,runnable里调setCurrentItem来切换轮播 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"TangMs"<notifications@github.com&gt;; 发送时间:&nbsp;2020年6月9日(星期二) 下午5:36 收件人:&nbsp;"youth5201314/banner"<banner@noreply.github.com&gt;; 抄送:&nbsp;"陈智健"<1258178275@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [youth5201314/banner] 自动轮播 (#734) 请问如何使用这个setcurrentitem来实现无限轮播呢？能提供一下思路吗？感谢 请问你解决了吗。我也遇到相同的需求 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
谢谢分享思路，我是在onBindView里设置setIsRecyclable(false)来达到每次切换到都走onBindView，然后在播放器的回调onStartPrepared里判断当前position跟banner的getCurrentItem是一致就停止轮播否则就在onPrepared里暂停播放来解决预加载的时候视频页面还没显示就播放，然后在onPageSelected判断是否是播放状态来恢复播放视频，在播放完成后再setcurrentitem跳到下一个并且start重新轮播来实现视频跟图片自动轮播的

**Comment by wjy000** [comment]
解决这个问题方法很简单, 你既然自动viewHolder会提前加载,那么延迟一个循环再停掉banner的轮播即可.大概代码如下
videoHolder.player.setOnPreparedListener(mp -> {
                            JLog.i("video onPrepared");
                            JUi.postDelayed(loopTime+100,()->{
                                videoHolder.player.start();
                                banner.stop();
                            });
                        });
videoHolder.player.setOnCompletionListener(mp -> {
                            JLog.i("video onCompletion");
                            banner.start();
                        });

**Comment by LiWeiQiangAndroid** [comment]
有demo吗
