### ISSUE TITLE
能否添加一个removeOnPageChangeListener方法

### ISSUE THREAD

**Issue by JasonTian23** [youth5201314/banner#735]
Banner里有mViewPager2.registerOnPageChangeCallback(new BannerOnPageChangeCallback());
能否添加个removeOnPageChangeListener方法，里面mViewPager2.unregisterOnPageChangeCallback(mPageChangeCallback);
比如在在activity的onDestroy里调用

**Comment by youth5201314** [comment]
好的，我提供一个banner的销毁方法，配合生命周期使用
