### ISSUE TITLE
网络图片加载不出来，有人遇到过么？Demo里的网络图片都加载不出来

### ISSUE THREAD

**Issue by XingtianXin** [youth5201314/banner#736]

**Comment by youth5201314** [comment]
你看看网络有问题没呢？用流量看看

**Comment by XingtianXin** [comment]
> 你看看网络有问题没呢？用流量看看

非常感谢这么及时回复。
网络没问题，流量wifi都试过，我编译安装的Demo,除了内置样式那页本地图片显示了，Demo里其他页的图片全都没显示出来。demo的array网络图片，我在浏览器显示都没问题。

您的Demo里ImageLoader用的Glide,我的项目里用的Picasso.都一样的现象。

我的手机是三星note8, android 9 的版本。
我自己在项目里用，也是，本地图片能显示出来，网络图片不行。

我再继续调查下现象和原因。

**Comment by XingtianXin** [comment]
项目没有升androidx,我用的是release 1.4.10的branch

**Comment by youth5201314** [comment]
我以为你用的是2.0的呢，老版本的好久没更新了，我后面在看看

**Comment by XingtianXin** [comment]
问题解决了，是因为networksecurity的问题，
https://stackoverflow.com/questions/51902629/how-to-allow-all-network-connection-types-http-and-https-in-android-9-pie

**Comment by youth5201314** [comment]
我刚刚已经测试过老版本可以加载出图片，demo没有问题，而且我公司有生产的项目也是使用的老版本的

**Comment by XingtianXin** [comment]
> 我刚刚已经测试过老版本可以加载出图片，demo没有问题，而且我公司有生产的项目也是使用的老版本的

嗯，谢谢~
我找到原因了，我的这个问题是android 9上，networksecurity设置的问题。
感谢啦~
