### ISSUE TITLE
banner上下滚动的时候会有问题

### ISSUE THREAD

**Issue by zhongzhihuashanghai** [youth5201314/banner#738]
在xml中设置banner滚动的方向为上下滚动的时候，每次滚动完都自动回到第一张图，本来应该滚动到第二张图的，但是在手滑了之后会恢复正常，看下这个能解决么

banner_category.setAdapter(new ImageAdapter(bannerImages));
            banner_category.setIndicator(new CircleIndicator(mContext))
                    .setIndicatorSelectedColor(Color.RED)
                    .setIndicatorNormalColor(Color.WHITE)
                    .setIndicatorGravity(IndicatorConfig.Direction.CENTER)
                    .setDelayTime(3000)
//                    .setScrollTime(800)
                    .isAutoLoop(true)
                    .setPageTransformer(new ZoomOutPageTransformer())
                    .setOnBannerListener(new OnBannerListener() {
                        @Override
                        public void OnBannerClick(Object data, int position) {
                            Info.showToastTip(mContext,"第"+(position+1)+"张图",true);
                        }
                    }).start();

**Comment by youth5201314** [comment]
我测试没有发生这个问题啊，你去掉ZoomOutPageTransformer试试，目前提供的两种PageTransformer效果是我从官网拷贝的。我本地测试不管是水平还是垂直都没发现问题。可能与环境有关吧！你去掉试试，如果还有问题在给我说，实在想要更多的效果也可以自己自定义的！我后面会再提供一些效果！
