### ISSUE TITLE
设置圆角  的mBannerRadius没有使用

### ISSUE THREAD

**Issue by wslerz** [youth5201314/banner#740]
···
 @Override
    protected void dispatchDraw(Canvas canvas) {
        if (mBannerRadius > 0) {
            Path path = new Path();
            path.addRoundRect(new RectF(0, 0, getMeasuredWidth(), getMeasuredHeight()),
                    BannerUtils.dp2px(5), BannerUtils.dp2px(5), Path.Direction.CW);
            canvas.clipPath(path);
        }
        super.dispatchDraw(canvas);
    }
···

**Comment by youth5201314** [comment]
好的，感谢，没注意到，我等会儿改了
