### ISSUE TITLE
禁止滚动后，手动滑动，又开始自动滚动

### ISSUE THREAD

**Issue by inwindtears** [youth5201314/banner#742]
调用了banner的stop方法，手动滑动banner后，banner又开始自动滚动

**Comment by youth5201314** [comment]
你要是不想自动轮播时可以关闭的，默认是打开的

**Comment by inwindtears** [comment]
我已经调用关闭了自动轮播，但是当我用手滑动到下一个图片之后，轮播又自动开始了。我并不想这个时候有轮播效果，该怎么处理？
