### ISSUE TITLE
”画廊“ 效果会有bug

### ISSUE THREAD

**Issue by qaz5391450** [youth5201314/banner#744]
大佬，按照你Demo中画廊的设置：
1、图片自动轮播时(从左至右)，每隔一张，右侧就丢失画廊效果；
2、手动轮播，手势往哪个方向滑动，哪边的画廊效果就会丢失。
在你Demo中也是这种情况...

**Comment by youth5201314** [comment]
好的，我已经发现了，主要是我自己的测试机没有出现，换了台手机才出现的。下个版本修复

**Comment by yuwensi** [comment]
目前也发现了这个问题，还请大佬有时间更新一下

**Comment by AlienChao** [comment]
目前也发现了这个问题，还请大佬有时间更新一下

**Comment by AlienChao** [comment]
大佬大概什么时候更新？？

**Comment by youth5201314** [comment]
已经修复，下个版本一起上传，下周一前会上传的

**Comment by AlienChao** [comment]
You are great！

**Comment by xyZangGit** [comment]
大大，这个画廊效果的bug，还有个问题，就是我设置 banner.setBannerGalleryEffect 每个item左右间距没有效果，还有是否可以尝试添加用 rv实现banner效果，毕竟viewpage2目前滑动冲突问题没办法解决，定义成final了
