### ISSUE TITLE
内部的指示器能否单独去给Viewpager使用？

### ISSUE THREAD

**Issue by withyou-zxl** [youth5201314/banner#745]

**Comment by youth5201314** [comment]
不能哈，我的指示器是给banner提供的，而且banner使用的也是viewpager2

**Comment by withyou-zxl** [comment]
后续可以把指示器独立出来，因为banner下方有个Viewpager+Recyclerview的分页，用其他指示器的话，样式和大小不一致 ，想着看能不能使用banner中的指示器
