### ISSUE TITLE
刷新会闪一下

### ISSUE THREAD

**Issue by chenni521** [youth5201314/banner#746]
我初始化好   在请求到数据拿到之后调用   
   homeBanner.setDatas(list);
            homeBanner.start();

每次都会闪一下怎么办

**Comment by youth5201314** [comment]
我没有能理解到你的闪一下什么意思？但是给出以下几种方法，你可以：

1. 在成功后在调用setadapter
2. 你也可以自己在adapter中进行数据操作，不一定要用setdatas。你平时怎么使用adapter，就能怎么发挥的，提供setdatas只是为了方便大多数使用者
3.正常的体验建议banner要有一定的交互，比如占位图，加载效果等，这些我没有提供是因为每个app设计的不一样就不好提供

我希望你们反馈问题能说明版本，使用场景等，最好能提供视频截图代码这些作为定位依据，方便我能接收到你的具体情况。换位思考下
