### ISSUE TITLE
增添新功能

### ISSUE THREAD

**Issue by alanzyz** [youth5201314/banner#747]
viewpager里面套用咱们的banner，banner向左滑动至尽头后，事件传递给外层的viewpager。能否增添新功能。事件不传递给外层viewpager？

**Comment by alanzyz** [comment]
我们的解决方案：

public class Mybanner extends Banner {

    public Mybanner(@NonNull Context context) {
        super(context);
    }

    public Mybanner(@NonNull Context context, @NonNull AttributeSet attrs) {
        super(context, attrs);
    }

    public Mybanner(@NonNull Context context, @NonNull AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
    }


    float startY = 0;


    @Override
    public boolean onInterceptTouchEvent(MotionEvent ev) {

        switch (ev.getAction()) {
            case MotionEvent.ACTION_DOWN:
                startY = ev.getY();
                break;
            case MotionEvent.ACTION_MOVE:
                float y = ev.getY();
                getParent().requestDisallowInterceptTouchEvent(Math.abs((int)(startY - y))<50);
                return super.onInterceptTouchEvent(ev);
            default:
        }
        return super.onInterceptTouchEvent(ev);
    }
}

**Comment by alanzyz** [comment]
建议增加此功能

**Comment by youth5201314** [comment]
我测试过viewpager嵌套没有你说的现象啊，你用的是最新的版本吗？
