### ISSUE TITLE
androidx 引入2.0.7版本出现冲突

### ISSUE THREAD

**Issue by githubghb** [youth5201314/banner#749]
更改为1.4.10版本就不会有问题

C:\Users\....\.gradle\caches\transforms-2\files-2.1\30f549780e14687677bac472bd111ffd\jetified-banner-2.0.5\res\values\values.xml:7:5-42:25: AAPT: error: duplicate value for resource 'attr/indicator_gravity' with config ''.

**Comment by youth5201314** [comment]
jetified-banner-2.0.5？？？？你确定是2.0.7，你可以清下缓存试试
