### ISSUE TITLE
最后一张图片切换到第一张，会出现卡顿

### ISSUE THREAD

**Issue by qq527743998** [youth5201314/banner#75]
仔细看很容易看出来

**Comment by youth5201314** [comment]
是最新的版本吗？

**Comment by qq527743998** [comment]
是的吧    我在Androidstudio导入的   然后copy到eclipse

**Comment by youth5201314** [comment]
你运行demo看下呢？我这运行并没有你说的那样啊！

**Comment by qq527743998** [comment]
//设置banner动画效果
       // banner.setBannerAnimation(Transformer.CubeOut);
去掉viewpage动画  就可以看到。  自动播放状态下。最后一页回到第一页         仔细看最后滑动的距离过渡。

**Comment by youth5201314** [comment]
已解决！下个版本一起更新！
