### ISSUE TITLE
部分手机报错没有mLayoutManager属性:No field mLayoutManager in class Landroidx/viewpager2/widget/f;

### ISSUE THREAD

**Issue by huangxiaoyu** [youth5201314/banner#750]
![image](https://user-images.githubusercontent.com/4270373/79553477-1f4dcf00-80cf-11ea-9b9e-ed72c8b39478.png)

**Comment by youth5201314** [comment]
你的图片看不了，麻烦说的详细点

**Comment by huangxiaoyu** [comment]
感谢回复,问题在附件里面了
有一部分手机会闪退&nbsp; 一直没有找到原因,今天用云测的金立s10c测试出了一个问题,不知道是不是这个问题导致的闪退,麻烦看下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Spring"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月17日(星期五) 下午5:22
收件人:&nbsp;"youth5201314/banner"<banner@noreply.github.com&gt;;
抄送:&nbsp;"懒鱼"<592010803@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youth5201314/banner] 部分手机报错没有mLayoutManager属性:No field mLayoutManager in class Landroidx/viewpager2/widget/f; (#750)





 
你的图片看不了，麻烦说的详细点

**Comment by youth5201314** [comment]
你使用最新的版本再试试！

**Comment by huangxiaoyu** [comment]
正在用2.0.2测试&nbsp; 一会给你说结果


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Spring"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月17日(星期五) 下午5:33
收件人:&nbsp;"youth5201314/banner"<banner@noreply.github.com&gt;;
抄送:&nbsp;"懒鱼"<592010803@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youth5201314/banner] 部分手机报错没有mLayoutManager属性:No field mLayoutManager in class Landroidx/viewpager2/widget/f; (#750)





 
你使用最新的版本再试试！

**Comment by youth5201314** [comment]
那就没有问题了，现在都更新到2.0.7了，你用最新的版本就可以了

**Comment by huangxiaoyu** [comment]
新版本可以


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Spring"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月17日(星期五) 下午5:37
收件人:&nbsp;"youth5201314/banner"<banner@noreply.github.com&gt;;
抄送:&nbsp;"懒鱼"<592010803@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youth5201314/banner] 部分手机报错没有mLayoutManager属性:No field mLayoutManager in class Landroidx/viewpager2/widget/f; (#750)





 
那就没有问题了，现在都更新到2.0.7了，你用最新的版本就可以了
