### ISSUE TITLE
有混淆的问题看过来

### ISSUE THREAD

**Issue by Wrocker** [youth5201314/banner#752]
未打包之前就是完美的
打包之后就出现了
1、滑动图片和下方按钮不匹配
2、左滑几次之后滑不动了
3、滚动图片会出现从头滚动到尾的情况
请问需要添加什么混淆规则？

**Comment by youth5201314** [comment]
直接忽略我的包名com.youth.banner啥

**Comment by youth5201314** [comment]
-keep class com.youth.banner.** {*;}

**Comment by Wrocker** [comment]
欧克，谢谢大佬

**Comment by Wrocker** [comment]
加了这一句还是一样的问题。。。

**Comment by Wrocker** [comment]
#==================gson && protobuf==========================
-dontwarn com.google.**
-keep class com.google.gson.** {*;}
-keep class com.google.protobuf.** {*;}

#banner
-keep class com.youth.banner.** {*;}

**Comment by JingweiWang** [comment]
@youth5201314 上次我也提过，混淆包名确实不大管用

-dontwarn com.youth.banner.**
-keep class com.youth.banner.**{*;}

**Comment by JingweiWang** [comment]
看了下代码，大概率是由于ScrollSpeedManger中使用反射造成的。
尝试keep `RecyclerView.LayoutManager`/`ViewPager2`/`PageTransformerAdapter`/`ScrollEventAdapter` 这几个类

**Comment by JingweiWang** [comment]
@youth5201314 @Wrocker 
经过测试，问题已解决，请使用以下规则：
```
-dontwarn com.youth.banner.**
-keep class com.youth.banner.**{*;}

-dontwarn androidx.recyclerview.widget.RecyclerView$LayoutManager
-keep class androidx.recyclerview.widget.RecyclerView$LayoutManager{*;}
-dontwarn androidx.viewpager2.widget.ViewPager2
-keep class androidx.viewpager2.widget.ViewPager2{*;}
-dontwarn androidx.viewpager2.widget.PageTransformerAdapter
-keep class androidx.viewpager2.widget.PageTransformerAdapter{*;}
-dontwarn androidx.viewpager2.widget.ScrollEventAdapter
-keep class androidx.viewpager2.widget.ScrollEventAdapter{*;}
```

**Comment by youth5201314** [comment]
感谢 @JingweiWang 我改了下已经更新，测试无误，使用2.0.8版本

**Comment by JingweiWang** [comment]
https://github.com/youth5201314/banner/commit/c6a2f38f035bac5643d89df5b75ecff4b3974e2a#r38607731

建议按照这种方式引入。

**Comment by youth5201314** [comment]
好的，我直接加入到defaultConfig中吧，lib不用区分debug

**Comment by Wrocker** [comment]
谢谢两位大佬
