### ISSUE TITLE
Indicator不显示

### ISSUE THREAD

**Issue by v5b7c6** [youth5201314/banner#754]
库版本2.0.7
测试手机:pixel2
问题:Indicator引入项目之后不显示，新启一个项目就没问题，代码都一样。

**Comment by youth5201314** [comment]
你这样描述我不好进行问题定位啊，你只能自己分析了。看看是否有数据，无数据时肯定无法显示的哈

**Comment by panzhenglian** [comment]
这个问题大概是初次设置 Indicator 时，adapter 中没有数据，再次给adapter 中赋值时，没有调用 adapter.notifyDataSetChanged().
