### ISSUE TITLE
[2.0.2-2.0.7]当is_infinite_loop默认true且is_auto_loop为false时，关闭自动轮播失效

### ISSUE THREAD

**Issue by JingweiWang** [youth5201314/banner#756]
问题代码如下，建议加个判断：

https://github.com/youth5201314/banner/blob/2adae1c3223685de035c7217cc3f3697d6b6a0fe/banner/src/main/java/com/youth/banner/Banner.java#L378-L382

自动轮播与无限循环应该是解耦的，有个场景：既不需要自动轮播，又要首尾过渡。

**Comment by youth5201314** [comment]
那你不用is_infinite_loop属性啊，用is_auto_loop啊

**Comment by JingweiWang** [comment]
https://github.com/youth5201314/banner/blob/2adae1c3223685de035c7217cc3f3697d6b6a0fe/banner/src/main/java/com/youth/banner/Banner.java#L129-L152

不用is_infinite_loop属性，is_infinite_loop默认为true。
上面第150行，会把用is_auto_loop 设置的mIsAutoLoop刷新成is_infinite_loop默认值。@youth5201314

**Comment by youth5201314** [comment]
懂起了，你先用isAutoLoop方法吧，我等下改在提交

**Comment by youth5201314** [comment]
已经修改，用2.0.8
