### ISSUE TITLE
快速左右滑动时指示器下标有些问题，自动轮播也有些问题

### ISSUE THREAD

**Issue by conghuahuadan** [youth5201314/banner#757]
你好，作者，2.0版本，原Demo发现有两个问题：
1. 快速左右连续滑动时指示器下标定位有些问题

2. 如图，自动轮播时，每次滚动到第一张图片，过后又回到最后一 张图片，接着才正常
![GIF](https://user-images.githubusercontent.com/20864280/79736284-23c2f380-832c-11ea-8bd8-485e6005005b.gif)

**Comment by youth5201314** [comment]
先确定下是不是用的最新版本哈

**Comment by conghuahuadan** [comment]
我拉了最新代码哈，第一个问题像这样，指示器的下标偶尔会有延迟很大（这里已经是第二张图了）
![image](https://user-images.githubusercontent.com/20864280/79765942-e70df100-8359-11ea-8d52-002d2db91018.png)

**Comment by aer874475222** [comment]
我也发现了，华为手机会这样，每次滚动到第一张图片，过后又回到最后一 张图片
