### ISSUE TITLE
与appbarlayout嵌套，事件冲突

### ISSUE THREAD

**Issue by fishsoft** [youth5201314/banner#758]
将banner嵌套在AppBarLayout中，banner的点击事件和AppBarLayout的上下滑动事件冲突
`<androidx.swiperefreshlayout.widget.SwipeRefreshLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/refreshLayout"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <androidx.coordinatorlayout.widget.CoordinatorLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@color/bg_page">

        <com.google.android.material.appbar.AppBarLayout
            android:id="@+id/abl_home"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="@color/bg_page"
            app:elevation="0dp">

            <com.google.android.material.appbar.CollapsingToolbarLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:layout_scrollFlags="scroll|exitUntilCollapsed">

                <RelativeLayout
                    android:id="@+id/rl_demo"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    app:layout_collapseMode="pin"
                    app:layout_collapseParallaxMultiplier="1.0">

                    <com.youth.banner.Banner
                        android:id="@+id/iv_top_image"
                        android:layout_width="match_parent"
                        android:layout_height="150dp"
                        android:focusable="true"
                        android:focusableInTouchMode="true"
                        android:scaleType="fitXY"
                        android:src="@mipmap/icon_f_banner" />
            </com.google.android.material.appbar.CollapsingToolbarLayout>
    </androidx.coordinatorlayout.widget.CoordinatorLayout>
</androidx.swiperefreshlayout.widget.SwipeRefreshLayout>`

**Comment by crystalboyice** [comment]
我也出现这个问题，请问怎么解决啊？

**Comment by 0blivionU** [comment]
我也出现这个问题，请问怎么解决啊？

**Comment by SmileJason** [comment]
我也出现这个问题，有解决方案吗？

**Comment by WinsorLwj** [comment]
我也出现这个问题，请问怎么解决啊？

**Comment by SmileJason** [comment]
我自己写了个viewpage代替了，目前没有很好的解决方案

**Comment by xyZangGit** [comment]
我也出现了这个问题，应该是 viewpage2和 原因，目前viewpage2是final，好像没有解决办法

**Comment by SmileJason** [comment]
我用的viewpage

**Comment by limbowangqi** [comment]
都没有解决 为啥要关闭啊

**Comment by CJR10032** [comment]
> 我也出现了这个问题，应该是 viewpage2和 原因，目前viewpage2是final，好像没有解决办法

和ViewPager2没关系，是大佬做了拦截事件的处理。。。

**Comment by CJR10032** [comment]
目前我的处理方法是写了一个类继承Banner，然后把onInterceptTouchEvent的代码覆盖掉了，因为我这里用了这个Banner的页面不需要左右滑动，所以不需要这个处理，这样就能避免上下滑动的冲突

**Comment by CJR10032** [comment]
最新版已经解决了，加了一个标识，setIntercept设置为false即可

**Comment by zhaobinsir** [comment]
setIntercept 还是不行

**Comment by SmileJason** [comment]
您好，您的邮件已经收到，祝身体健康。

**Comment by zhaobinsir** [comment]
正解：已验证：[ViewPager2]使用RecyclerView实现，RecyclerView吃掉了nested的一系列方法，导致无法回传至CoordinatorLayout，导致behavior失效，最终无法滑动
vBanner.viewPager2.children.find { it is RecyclerView }?.let {
(it as RecyclerView).isNestedScrollingEnabled = false
}

**Comment by zhaobinsir** [comment]
> 将banner嵌套在AppBarLayout中，banner的点击事件和AppBarLayout的上下滑动事件冲突 `<androidx.swiperefreshlayout.widget.SwipeRefreshLayout xmlns:android="http://schemas.android.com/apk/res/android" xmlns:app="http://schemas.android.com/apk/res-auto" xmlns:tools="http://schemas.android.com/tools" android:id="@+id/refreshLayout" android:layout_width="match_parent" android:layout_height="match_parent">
> 
> ```
> <androidx.coordinatorlayout.widget.CoordinatorLayout
>     android:layout_width="match_parent"
>     android:layout_height="match_parent"
>     android:background="@color/bg_page">
> 
>     <com.google.android.material.appbar.AppBarLayout
>         android:id="@+id/abl_home"
>         android:layout_width="match_parent"
>         android:layout_height="wrap_content"
>         android:background="@color/bg_page"
>         app:elevation="0dp">
> 
>         <com.google.android.material.appbar.CollapsingToolbarLayout
>             android:layout_width="match_parent"
>             android:layout_height="wrap_content"
>             app:layout_scrollFlags="scroll|exitUntilCollapsed">
> 
>             <RelativeLayout
>                 android:id="@+id/rl_demo"
>                 android:layout_width="match_parent"
>                 android:layout_height="wrap_content"
>                 app:layout_collapseMode="pin"
>                 app:layout_collapseParallaxMultiplier="1.0">
> 
>                 <com.youth.banner.Banner
>                     android:id="@+id/iv_top_image"
>                     android:layout_width="match_parent"
>                     android:layout_height="150dp"
>                     android:focusable="true"
>                     android:focusableInTouchMode="true"
>                     android:scaleType="fitXY"
>                     android:src="@mipmap/icon_f_banner" />
>         </com.google.android.material.appbar.CollapsingToolbarLayout>
> </androidx.coordinatorlayout.widget.CoordinatorLayout>
> ```
> 
> </androidx.swiperefreshlayout.widget.SwipeRefreshLayout>`

https://github.com/youth5201314/banner/issues/758#issuecomment-2463684462

**Comment by zhaobinsir** [comment]
> > 我也出现了这个问题，应该是 viewpage2和 原因，目前viewpage2是final，好像没有解决办法
> 
> 和ViewPager2没关系，是大佬做了拦截事件的处理。。。

就是ViewPager2问题、我把源码拦截事件全部注释、CoordinatorLayout仍然无法上下滑动
解决方案：https://github.com/youth5201314/banner/issues/758#issuecomment-2463684462
