### ISSUE TITLE
希望保留自定义两个属性，indicator_drawable_selected和indicator_drawable_unselected

### ISSUE THREAD

**Issue by Starfallmundane** [youth5201314/banner#764]
app:indicator_drawable_selected="@drawable/selected_radius"
        app:indicator_drawable_unselected="@drawable/unselected_radius"
直接设置指示器选中和未选中的图标，很实用

**Comment by youth5201314** [comment]
现在的指示器全是自定义的，现在还没有支持直接设置drawable。后面会提供相应的指示器，最近比较忙，后面会抽时间更新，你也可以自己自定义

**Comment by liukai2530533** [comment]
Indicator我想换成图片该怎么实现？ 以前都是indicator_drawable_selected设置drawable 可以设置选中的一个drawable未选中的一个drawable。现在都是继承View了该如何实现Drawable
