### ISSUE TITLE
混淆

### ISSUE THREAD

**Issue by lijun952048910** [youth5201314/banner#767]
内部混淆好像有问题 
proguard.txt, offset: 791, line: 23, column: 7, Expected [!]interface|@interface|class|enum

**Comment by lijun952048910** [comment]
> 内部混淆好像有问题
> proguard.txt, offset: 791, line: 23, column: 7, Expected [!]interface|@interface|class|enum

**Comment by lijun952048910** [comment]
![微信截图_20200426111547](https://user-images.githubusercontent.com/5387535/80296691-b55cb600-87af-11ea-9010-c3c238bc8da2.png)

**Comment by youth5201314** [comment]
你把本地缓存清理下，重新下载依赖包试下呢

**Comment by lijun952048910** [comment]
> 你把本地缓存清理下，重新下载依赖包试下呢

试了不行，还是这个问题

**Comment by youth5201314** [comment]
我测试了没有问题的，我中间提交错了一次，后面删除从新提交了一次。你这个问题应该就是使用时刚好下载了我没有删除前的然后缓存到本地了，你删除重新下载就行了，我说的是删除gradle本地缓存的包，不是clean功能哈

**Comment by 917163738** [comment]
![image](https://user-images.githubusercontent.com/8401617/82324297-fbeaac80-9a0b-11ea-8e5b-5ecb49f3525c.png)

**Comment by 917163738** [comment]
作者少些了class  
-dontwarn androidx.viewpager2.**
-keep androidx.viewpager2.** {*;}
-dontwarn androidx.recyclerview.widget.RecyclerView
-keep class androidx.recyclerview.widget.RecyclerView{*;}

第二行少了class
