### ISSUE TITLE
指示器显示错误

### ISSUE THREAD

**Issue by wjianchen13** [youth5201314/banner#768]
Vivo x21上直接跑最新版本的代码，指示器没有一个是显示对的，显示和图片位置根本不对应，不知道有没有发现和我一样的问题

**Comment by youth5201314** [comment]
你运行的demo吗？

**Comment by zhouchiyu** [comment]
我运行的demo，在仿淘宝商品详情界面，指示器与图片不对称

**Comment by zhouchiyu** [comment]
> 你运行的demo吗？

我运行的demo，在仿淘宝商品详情界面，指示器与图片不对称

**Comment by wjianchen13** [comment]
是运行的demo呀，指示器完全不对



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zhouchiyu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月7日(星期四) 下午4:35
收件人:&nbsp;"youth5201314/banner"<banner@noreply.github.com&gt;;
抄送:&nbsp;"小鱼"<1812821235@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youth5201314/banner] 指示器显示错误 (#768)





  
你运行的demo吗？
  
我运行的demo，在仿淘宝商品详情界面，指示器与图片不对称

**Comment by wjianchen13** [comment]
能否加下我的QQ沟通呀？282330332
  

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"zhouchiyu"<notifications@github.com&gt;;
 发送时间:&nbsp;2020年5月7日(星期四) 下午4:35
 收件人:&nbsp;"youth5201314/banner"<banner@noreply.github.com&gt;;
 抄送:&nbsp;"小鱼"<1812821235@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
 主题:&nbsp;Re: [youth5201314/banner] 指示器显示错误 (#768)

 

 

  
你运行的demo吗？
 
我运行的demo，在仿淘宝商品详情界面，指示器与图片不对称
