### ISSUE TITLE
banner图片设置padding之后，圆角会失效

### ISSUE THREAD

**Issue by liosen** [youth5201314/banner#769]
需求：
1.图片圆角
2.图片之间要有间隔
3.自动切换图片/滑动图片时，不能被遮挡，需要贴合屏幕左右两侧
复现：
自定义RoundImageView, 继承ImageView.
自定义ImageAdapter, 将adapter中的ImageView 替换成RoundImageView
会实现圆角图片
但是，图片与图片直接没有间隔
在adapter中设置imageView.setPadding(30, 0, 30, 0);
圆角会变回直角
尝试：
1.
banner.setBannerRound(20f);
banner.setBannerRound2(20f);
两个方法无效
结果：
需求中①②都可以单独实现，但是无法同时实现
demo中，效果其实是banner上方用圆角容器限制。但是左右滑动的时候，容器是固定的。

是否有解决思路？

我在查看源码imageView.setPadding(30, 0, 30, 0);时，看到View.java的23383行的方法有以下源码：
`boolean changed = false;
if (mPaddingLeft != left) {
    changed = true;
    mPaddingLeft = left;
}
if (mPaddingTop != top) {
    changed = true;
    mPaddingTop = top;
}
if (mPaddingRight != right) {
    changed = true;
    mPaddingRight = right;
}
if (mPaddingBottom != bottom) {
    changed = true;
    mPaddingBottom = bottom;
}
if (changed) {
    requestLayout();
    invalidateOutline();
}`
应该是setPadding后，源码中的changed对象变成了true，导致RoundImageView失效的
我暂时没想到解决思路

**Comment by youth5201314** [comment]
我初步理解你的需求完全能实现，仔细看demo就行，但也有可能理解错了，你最好能提供下效果图

**Comment by liosen** [comment]
![Screenshot_2020-04-27-17-29-22-322](https://user-images.githubusercontent.com/33013300/80357394-86c50500-88ad-11ea-96f6-0b263c2ef23d.png)
![Screenshot_2020-04-27-17-30-16-553_com test banner](https://user-images.githubusercontent.com/33013300/80357424-8dec1300-88ad-11ea-88e1-35876eceb242.png)
图一是我项目中的样式
图中第1点：切换banner图片时，需要贴合屏幕，所以无法直接给banner设置margin值
图中第2点：需要圆角
图中第3点：图片与图片之间需要间距
可以在图二看到demo中的圆角，其实是外部实现的。在切换图片过程中，依然是直角。并且圆角的那个容器没有动

我所遇到的问题是，
1.如果设置成圆角，就无法设置padding
2.如果增加imageView.settingPadding 就会出现圆角时效。
很是头疼

**Comment by liosen** [comment]
> ![Screenshot_2020-04-27-17-29-22-322](https://user-images.githubusercontent.com/33013300/80357394-86c50500-88ad-11ea-96f6-0b263c2ef23d.png)
> ![Screenshot_2020-04-27-17-30-16-553_com test banner](https://user-images.githubusercontent.com/33013300/80357424-8dec1300-88ad-11ea-88e1-35876eceb242.png)
> 图一是我项目中的样式
> 图中第1点：切换banner图片时，需要贴合屏幕，所以无法直接给banner设置margin值
> 图中第2点：需要圆角
> 图中第3点：图片与图片之间需要间距
> 可以在图二看到demo中的圆角，其实是外部实现的。在切换图片过程中，依然是直角。并且圆角的那个容器没有动
> 
> 我所遇到的问题是，
> 1.如果设置成圆角，就无法设置padding
> 2.如果增加imageView.settingPadding 就会出现圆角时效。
> 很是头疼

我那么大的图呢...我这边看...图片挂了

**Comment by youth5201314** [comment]
我看懂了，很简单实现的方式很多，我说两种简单的：1、给父容器设置间距 2、MarginPageTransformer。这样就有间距，四周就是圆角的了，间距中间也是圆角的话要看实际情况，可以通过图片加载器或者自定义控件等

**Comment by youth5201314** [comment]
你要的应该是这种效果，按我上面的方法就行

![D1B9207FC726F11563E8F2C1CD4BE129](https://user-images.githubusercontent.com/8827239/80359497-7c583a80-88b0-11ea-963d-b3ae4e25ab65.jpg)

**Comment by liosen** [comment]
非常感谢你提供的思路
1.给父容器设置间距，我用这个实现了
2.viewPage2中的MarginPageTransformer方法，我也实现了，但是效果不是我想要的：
![Screenshot_2020-04-27-18-08-13-699](https://user-images.githubusercontent.com/33013300/80360907-a579ca80-88b2-11ea-9867-fda2c8970679.png)
因为banner图片与屏幕也需要间距。所以，只设置viewPager.setPageTransformer(...)的话，无法实现图中效果。

我实现的思路：（可以不看）（给之后有类似问题的同学，提供思路）
1.给banner的图片外 套一层父容器，给父容器设置间距
2.父容器设置了间距，就不影响ImageView的属性设置了。
具体：
1.在ImageAdapter中的 onCreateHolder中给RoundImageView(extent ImageView)套一层父容器，比如LinearLayout。给LinearLayout设置padding即可。（我这里没用动态添加，而是引用布局文件）
`View view = LayoutInflater.from(context).inflate(R.layout.item_banner, null);`
2.当然，inner class也要改，找到BannerViewHolder
`class BannerViewHolder extends RecyclerView.ViewHolder {   
        RoundImageView imageView;   
        public BannerViewHolder(@NonNull View view) {   
            super(view);   
            this.imageView = view.findViewById(R.id.imageView);   
        }   
    }`
大概这样改。（我好像不会在编辑器中，给代码换行，行数不多，辛苦一下 :-)）
这样就添加好了。
