### ISSUE TITLE
当轮播数据源为空时报错，有设置轮播占位图的方法没

### ISSUE THREAD

**Issue by cjj-sal** [youth5201314/banner#770]

**Comment by jerry9433** [comment]
此库基于viewPager2编写，其实就是RecyclerView，当数据源为空时，getItemCount()应该是0，不应该报错啊，可以提供下报错详细log。另外暂未提供设置占位图的方法，可以基于recyclerView和adapter的使用，数据为空时提供一个占位的数据即可。
