### ISSUE TITLE
初始化的时候会白一会

### ISSUE THREAD

**Issue by chenlijia1111** [youth5201314/banner#775]
初始化的时候会白一会，但是这个时候已经可以看到指示器在切换了，大概要白4-5秒的样子，图片才显示出来。不应该是我网络请求的问题吧。
源码里的开始方法：
/**
     * 开始轮播
     *
     * @return
     */
    public Banner start() {
        if (mIsAutoLoop) {
            stop();
            postDelayed(mLoopTask, mDelayTime);
        }
        return this;
    }
貌似启动的时候延时了3秒？

**Comment by xiaolanbuzaiaixinyi** [comment]
我也遇到这个问题了。很奇怪
