### ISSUE TITLE
版本2.0.8上，使用banner.setOnBannerListener设置banner点击事件，取到的position对不上数据

### ISSUE THREAD

**Issue by vix79879** [youth5201314/banner#778]
作者你好，近日升级了2.0.8版本的banner控件，在使用过程中，发现setOnBannerListener事件监听中，点击获取到的position跟点击的数据对应不上，我打印数据发现，自动轮播过程中，点击控件position会出现错乱，我尝试在adapter中添加点击事件，取到的position和data数据也是有问题
目前我只能通过addOnPageChangeListener监听来手动记录当前position，然后在点击事件中根据记录的position来实现正确的点击事件。希望作者有时间可以验证下此问题

**Comment by ALoung** [comment]
> 作者你好，近日升级了2.0.8版本的banner控件，在使用过程中，发现setOnBannerListener事件监听中，点击获取到的position跟点击的数据对应不上，我打印数据发现，自动轮播过程中，点击控件position会出现错乱，我尝试在adapter中添加点击事件，取到的position和data数据也是有问题
> 目前我只能通过addOnPageChangeListener监听来手动记录当前position，然后在点击事件中根据记录的position来实现正确的点击事件。希望作者有时间可以验证下此问题

**Comment by ALoung** [comment]
我也测试了，setOnBannerListener事件监听position确实对不上!

**Comment by youth5201314** [comment]
我实际测试没有发现你说的点击事件错乱的问题，如果硬要说错乱有可能是添加了PageTransformer，有些效果在实现上，可能你看到的还是第一页，但是实际上已经开始位移到第二页了，比如层叠的一个效果，所以加了效果使用点击事件需要考虑实际情况，这个不能兼得！

**Comment by yangfeng1994** [comment]
通过setCurrentItem 设置position 然后在onPageSelected 回调的position不对
