### ISSUE TITLE
完全退出demo后再次进入banner所在的界面时，滑动banner从第一个图片往右划一下到最后一个图片（动画的反方向滑动），一开始最后那个图片是显示的 ，很快图片消失变成空白

### ISSUE THREAD

**Issue by zhjunvj** [youth5201314/banner#79]
完全退出demo后再次进入banner所在的界面时，滑动banner从第一个图片往右划一下到最后一个图片（动画的反方向滑动），一开始最后那个图片是显示的 很快图片消失变成空白。

**Comment by youth5201314** [comment]
此问题已收录，主要是动画不兼容引起的，你先暂时不用动画吧！下次更新了提醒你！

**Comment by qssq** [comment]
这种bug不应该关闭的，我盲目的使用了banner库现在很后悔

**Comment by perfunctory** [comment]
已经解决了吗？我也碰到这个问题
