### ISSUE TITLE
OnBannerListener监听到的position跟实际对不上

### ISSUE THREAD

**Issue by ALoung** [youth5201314/banner#797]
在正常不停左滑时每问题，但左滑几次后再右滑，此时OnBannerListener返回的position与实际的位置对不上，有图有真相，我做了很多次测试了。

banner.setAdapter(new PicSlideAdapter<>(getActivity(), data.getData().getCarousel()));
banner.setIndicator(new RectangleIndicator(getActivity()));
banner.setIndicatorSelectedColorRes(R.color.white);
banner.setIndicatorNormalColorRes(R.color.transparentWhite);
banner.setIndicatorGravity(IndicatorConfig.Direction.CENTER);
banner.setIndicatorSpace((int) BannerUtils.dp2px(6));
banner.setIndicatorMargins(new IndicatorConfig.Margins(0, 0, 0, (int) BannerUtils.dp2px(15)));
banner.setIndicatorWidth((int) BannerUtils.dp2px(14), (int) BannerUtils.dp2px(14));
banner.setIndicatorHeight((int) BannerUtils.dp2px(2));
banner.setPageTransformer(new DepthPageTransformer());
banner.setDelayTime(5000);
banner.setOnBannerListener(new OnBannerListener() {
            @Override
            public void OnBannerClick(Object object, int position) {
                
            }
        });
banner.start();

**Comment by youth5201314** [comment]
DepthPageTransformer 这个你有了解吗？建议你看看。有时候想实现一些效果，我们看到的和运行的位置是不一样的，就像这个效果，在你看来是在0时，其实已经在慢慢的位移到1了。这个效果和点击事件之间取舍自己把握，想用PageTransformer你完全可以自定义，或者使用不需要改变位置的效果，框架中给的几种效果完全是只是建议
