### ISSUE TITLE
我尝试在kotlin中使用baner插件 但报了TypeCaseException异常

### ISSUE THREAD

**Issue by kevinMintnick** [youth5201314/banner#799]
kotlin.TypeCastException: null cannot be cast to non-null type com.youth.banner.Banner
=======
 lateinit var viewModel: RegionDetailsViewModel
    //banner的图片集合
    var bannerImageList: List<URL> = ArrayList()
    lateinit var banner: Banner

    var mAdapter: MiaoRecyclerViewAdapter<RegionTypeDetailsInfo.Result>? = null

    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View? {
        viewModel = getViewModel { RegionDetailsViewModel(context!!, tid) }
        banner = find(R.layout.item_banner)
        ////设置banner样式(显示圆形指示器)
        banner?.setBannerStyle(BannerConfig.CIRCLE_INDICATOR)
                ?.setDelayTime(4000) //设置轮播时间 ms
                ?.isAutoPlay(true) //是否自动播放
        return render().view
    }

**Comment by youth5201314** [comment]
推荐使用2.0的最新版本,1.0很久没有维护了！
