### ISSUE TITLE
轮播图放在fragment里面，在启动其他fragment的时候会引起页面闪动

### ISSUE THREAD

**Issue by lskxxf** [youth5201314/banner#801]
轮播图放在首页的fragment里面，点击轮播图启动一个页面，如果这个页面是fragment的时候，页面的创建和销毁都会闪烁几下，但是如果启动换成activity页面就不会闪烁了

**Comment by youth5201314** [comment]
你这样我并不好定位问题啊！首先大部分使用者都是在fragment中使用，有上线的都没有问题，你只是简单的文字描述连代码都没有无法确实是什么原因造成的，如果现在还没有解决，那么你可以提供详细点！
