### ISSUE TITLE
关于混淆的bug反映及解决办法

### ISSUE THREAD

**Issue by june5753** [youth5201314/banner#802]
在引入viewpager2后 混淆说明文档中：
-dontwarn androidx.viewpager2.**
-keep androidx.viewpager2.** {*;}

文档中 这样写打包后会出现：
R8: Expected [!]interface|@interface|class|enum

原因：文档中少写了class 字段
即应该将  -keep androidx.viewpager2.** {*;}
改为：-keep class androidx.viewpager2.** {*;}

**Comment by youth5201314** [comment]
感谢！这个应该是你本地的缓存的问题，我以前加混淆时中途有提交错一次，但是马上就纠正了，有可能你就是在我提交错的时候下载使用了，但是我后面改了你本地判断版本是一样的就没有更新，你清除下缓存就好了，或者用最新的版本哈！
