### ISSUE TITLE
规范代码

### ISSUE THREAD

**Issue by fuxianwen** [youth5201314/banner#805]
···java
    @NonNull
    public BA getAdapter() {
        if (mAdapter == null) {
            LogUtils.e(getContext().getString(R.string.banner_adapter_use_error));
        }
        return mAdapter;
    }
···

·@NonNull· 声明的方法， 本应该确保一定不会返回·null·， 但是源码里面却允许返回·null·。

这是自欺欺人吗？

**Comment by wang2793312458** [comment]
你可以不用啊，能不能好好说话
