### ISSUE TITLE
CoordinatorLayout-AppBarLayout-CollapsingToolbarLayout-Banner 触摸Banner无法上下滑动，并且抬手后会触发OnBannerListener

### ISSUE THREAD

**Issue by lic2050** [youth5201314/banner#807]
banner:2.0.10

<CoordinatorLayout
--<AppBarLayout
----<CollapsingToolbarLayout
------<Banner
--<RecyclerView
这种布局结构，Banner设置水平滚动。
触摸Banner上下滑动时没有效果，CoordinatorLayout不会收起，滑动RecyclerView时CoordinatorLayout可以正常工作，抬起手后Banner还会回调OnBannerListener
![111](https://user-images.githubusercontent.com/24469361/82856931-09d78a80-9f42-11ea-8220-5006f7ad6ce2.gif)

**Comment by ouyuan2019** [comment]
setIntercept(false)

**Comment by leichangwen** [comment]
可以将banner作为library引入项目，找到Banner.java的onInterceptTouchEvent，去掉getParent().requestDisallowInterceptTouchEvent(true); 可以解决“触摸Banner上下滑动时没有效果”；
