### ISSUE TITLE
kotlin   banner.setAdapter报错

### ISSUE THREAD

**Issue by wang2793312458** [youth5201314/banner#808]
type  mismitch
required  nothing!
found   imageAdapter

 ImageAdapter继承 BannerAdapter

**Comment by TracyEminem** [comment]
最后怎么解决的？

**Comment by blueskky** [comment]
也遇到这个问题了，不晓得kotlin是咋处理这个泛型的

**Comment by beike6688** [comment]
//这样设置就行了，不要用 banner.setAdapter() 方法，BannerImageAdapter继承 BannerAdapter
banner.adapter =  BannerImageAdapter(BannerDataBean.getTestData())

**Comment by imtianx** [comment]
目前这个问题有解么，banner.adapter 目前无法使用
