### ISSUE TITLE
指示器显示问题

### ISSUE THREAD

**Issue by lucky-you** [youth5201314/banner#810]
当只有一条数据的时候，指示器显示的位置不对。能否增加一个判断，只有一条数据的时候不显示指示器。
![image](https://user-images.githubusercontent.com/22268878/83126542-89648580-a10b-11ea-8a75-0a057b41b368.png)

**Comment by ShirleyLuoppx** [comment]
兄弟，有没有出现指示器设置了圆形之后没有效果的情况，没有升到Androidx，用的banner的1.4.0版本的。（ps：android菜鸟，第一次提issue，望回复）

**Comment by youth5201314** [comment]
@lucky-you 库本身内置的指示器都是判断的哈，你运行的demo，demo中我只是举例下怎么来自定义指示器，你举一反三，稍微思考下呢？这个你可以自己发挥的！这种数字指示器并不是每个产品都会选择隐藏的，看使用者本身了！
