### ISSUE TITLE
setDatas出现的问题

### ISSUE THREAD

**Issue by KalvinZhuang** [youth5201314/banner#811]
如果设置adapter时集合为0，请求完数据在次调用setDatas更新会从最后一位开始，并且第一次轮播时会跳过第一个

版本
`2.0.10'

**Comment by youth5201314** [comment]
首先你说的这个情况，我测试过很多次没有发现问题！其次setdata是为了方便提供的，这个你可以不用这个方法，然后自己支配数据的更新删除添加操作的，不要局限到具体的方法上，可以举一反三下！demo也有提示怎么弄。以前怎么弄adapter的，现在也可以怎么弄！
