### ISSUE TITLE
最新版 AppBarLayout上下滑动和banner 滑动冲突的问题 没解决 咋都关闭了

### ISSUE THREAD

**Issue by limbowangqi** [youth5201314/banner#812]

**Comment by limbowangqi** [comment]
看了demo才知道  自己傻逼了
.setIntercept(false)

**Comment by zhaobinsir** [comment]
正解、已验证、[ViewPager2]使用RecyclerView实现，RecyclerView吃掉了nested的一系列方法，导致无法回传至CoordinatorLayout，导致behavior失效，最终无法滑动
vBanner.viewPager2.children.find { it is RecyclerView }?.let {
            (it as RecyclerView).isNestedScrollingEnabled = false
        }
