### ISSUE TITLE
在viewpager2上的bug

### ISSUE THREAD

**Issue by ouyuan2019** [youth5201314/banner#813]
viewpager2 + fragment + scrollview + banner
viewpager2里装的是fragment。fragment布局是scrollview + banner。当banner自动轮播或者手动拖动banner滑动的时候，scrollview会跳到最顶部。 换成viewpager则不会出现这个情况
banner:2.0.10
viewpager2:1.1.0-alpha01
视频：https://m-blog.oss-cn-shenzhen.aliyuncs.com/other/test.mp4

**Comment by youth5201314** [comment]
试试给scrollview 加上android:focusable="true"
android:focusableInTouchMode="true"

**Comment by ouyuan2019** [comment]
> 试试给scrollview 加上android:focusable="true"
> android:focusableInTouchMode="true"

这个试过了，如果是焦点的问题，好像只会滑动到banner那，而不是跳到最顶部

**Comment by leon2017** [comment]
这个确实是viewpager2的问题

**Comment by rgdzh1** [comment]
> 这个确实是viewpager2的问题

解决了么, 我也碰到了, 有没有好的办法解决掉?

**Comment by 925941723** [comment]
+1
