### ISSUE TITLE
有人遇见过循环图片时候滑到一半的么？

### ISSUE THREAD

**Issue by KupoGu** [youth5201314/banner#816]
<img width="369" alt="image" src="https://user-images.githubusercontent.com/48119994/83474672-1b2f1280-a4bf-11ea-8e39-d04e7f50773b.png">

**Comment by yokin86558543** [comment]
遇到了  当切换的时候切到其他页面再返回就是显示这样  然后等3秒钟又开始走起来

**Comment by KupoGu** [comment]
这玩意儿还会内存泄露，我都不知道star那么高怎么来的？
