### ISSUE TITLE
destroy 空指针异常

### ISSUE THREAD

**Issue by lizhaoXXX** [youth5201314/banner#818]
使用场景：切换本地语言，重启应用。
在Activity的onDestroy()中调用mBanner.destroy()，会出现空指针异常。
` Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.viewpager2.widget.ViewPager2.unregisterOnPageChangeCallback(androidx.viewpager2.widget.ViewPager2$OnPageChangeCallback)' on a null object reference`

错误定位：
`
  /**
     * 移除一些引用
     */
    public void destroy() {
        getViewPager2().unregisterOnPageChangeCallback(mPageChangeCallback);
        removeCallbacks(mLoopTask);
        mCompositePageTransformer = null;
        mPageChangeCallback = null;
        mOnPageChangeListener = null;
        mLoopTask = null;
        mIndicator = null;
        mAdapterDataObserver = null;
        mAdapter = null;
        mViewPager2 = null;
    }
`

**Comment by Chee94** [comment]
主要是Banner.destroy方法里面的getViewPager2()找不到unregisterOnPageChangeCallback这个方法，是出现在5.1.1版本系统里的，不知道能不能做一个兼容

**Comment by Chee94** [comment]
引入viewpage2库就可以了

**Comment by yeaper** [comment]
> 引入viewpage2库就可以了

anddroidx引入了，还是报这个问题

**Comment by youth5201314** [comment]
@yeaper viewpage2和anddroidx不是一个东西哈
