### ISSUE TITLE
希望可以把Banner类中构造函数的@NotNull注解去掉

### ISSUE THREAD

**Issue by plumcookingwine** [youth5201314/banner#820]
项目统一封装banner，会自定义Banner对象
 public Banner(@NonNull Context context) {
        this(context, null);
    }

    public Banner(@NonNull Context context, @NonNull AttributeSet attrs) {
        this(context, attrs, 0);
    }
注解为了非空，但是传入了null， 这样在java中是被允许的。
在kotlin中会报错，为了兼容kotlin，希望可以把这个注解去掉

**Comment by youth5201314** [comment]
好的
