### ISSUE TITLE
recyleview 嵌套 Banner，滑动有空白的问题

### ISSUE THREAD

**Issue by laiyadianzi** [youth5201314/banner#823]
我用的是BaseQuickAdapter 的适配器，嵌套 banner, 刚开始滑动，正常，滑动一下就有空白的，有人之前这样用过吗？

**Comment by laiyadianzi** [comment]
手机是一加7t, 系统是Android 10

**Comment by laiyadianzi** [comment]
Banner banner = baseViewHolder.getView(R.id.banner);
        banner.setId(baseViewHolder.getLayoutPosition());
        TextView my_pet_dynamic_text = baseViewHolder.getView(R.id.my_pet_dynamic_text);
        if(!StringUtils.isEmpty(myListBean.getDetail())){
            my_pet_dynamic_text.setText(myListBean.getDetail());
        }
        banner.setImages(imagelist.get(baseViewHolder.getLayoutPosition())).setImageLoader(new GlideImageLoad())
                .setIndicatorGravity(BannerConfig.CENTER).isAutoPlay(false).start();

**Comment by laiyadianzi** [comment]
@Override
    protected void convert(@NotNull BaseViewHolder baseViewHolder, PersonCenter.MyListBean myListBean) {
        Banner banner = baseViewHolder.getView(R.id.banner);
        banner.setId(baseViewHolder.getLayoutPosition());
        TextView my_pet_dynamic_text = baseViewHolder.getView(R.id.my_pet_dynamic_text);
        if(!StringUtils.isEmpty(myListBean.getDetail())){
            my_pet_dynamic_text.setText(myListBean.getDetail());
        }
        banner.setImages(imagelist.get(baseViewHolder.getLayoutPosition())).setImageLoader(new GlideImageLoad())
                .setIndicatorGravity(BannerConfig.CENTER).isAutoPlay(false).start();
    }

**Comment by laiyadianzi** [comment]
解决啊，

**Comment by thaixp** [comment]
我也遇到了这种，有什么好的解决方式吗？

**Comment by thaixp** [comment]
@youth5201314 作者能帮忙看看吗
