### ISSUE TITLE
Touch事件响应问题

### ISSUE THREAD

**Issue by lll1590** [youth5201314/banner#824]
大神好，我在项目中使用了你这个库，布局结构是：SmartRefreshLayout+CoordinatorLayout+AppBarLayout+CollapsingToolbarLayout+ViewPager+Fragment；YouthBanner组件在CollapsingToolbarLayout这里面，设置水平滑动，这时当手指放在Banner上下滑动时，没反应，试着重写组件的事件，也没解决，请问这时什么原因

**Comment by youth5201314** [comment]
这个你怎么写，我判断不出事什么原因的，你现在要是还没有解决，可以将代码发出来看看，或者写一个简单的demo发给我！

**Comment by wangyuhang0469** [comment]
我也遇到了同样的问题，布局是CoordinatorLayout—AppBarLayout—LinerLayout—YouthBanner依次嵌套，请问有解决方案了吗

**Comment by davy445** [comment]
设置  setIntercept(false)了吗
