### ISSUE TITLE
用MultipleTypesAdapter，第一张是图片的时候总是显示不出图片，要滑倒第二张再滑回来，第一张的内容才显示

### ISSUE THREAD

**Issue by douxiaofu** [youth5201314/banner#826]

**Comment by youth5201314** [comment]
这个你要网络图片，那肯定有一个加载过程的，你可以设置下加载占位图，如果是本地图片我测试也不会有你说的问题。你的问题描述我只能判断出这么多，如果没回答到，你要具体描述下哈

**Comment by LxzBUG** [comment]
第一张图片要摸一下才会显示 哈哈哈哈哈 真的 why @youth5201314

**Comment by ginkwang** [comment]
占位图的设置方法有向外暴露接口吗？
