### ISSUE TITLE
指示器在选中和未选中的宽度设置时候，无效果

### ISSUE THREAD

**Issue by luotext** [youth5201314/banner#827]
如题：我只是就这样设置，但是选中的和未选中的依然只对未选择宽度进行实现。
        banner.setIndicator(new RectangleIndicator(mActivity));
        banner.setIndicatorNormalWidth((int) BannerUtils.dp2px(28));
        banner.setIndicatorSelectedWidth((int) BannerUtils.dp2px(12));
        banner.setIndicatorSpace((int) BannerUtils.dp2px(5));
        banner.setIndicatorRadius(2);

**Comment by luotext** [comment]
> 
> 
> 如题：我只是就这样设置，但是选中的和未选中的依然只对未选择宽度进行实现。
> banner.setIndicator(new RectangleIndicator(mActivity));
> banner.setIndicatorNormalWidth((int) BannerUtils.dp2px(28));
> banner.setIndicatorSelectedWidth((int) BannerUtils.dp2px(12));
> banner.setIndicatorSpace((int) BannerUtils.dp2px(5));
> banner.setIndicatorRadius(2);

因此我在RectangleIndicator修改了onMeasure，onDraw，在里面修改
onMeasure：
//间距*（总数-1）+默认宽度*总数
        int width = 0;
        if (config.getSelectedWidth() != BannerConfig.INDICATOR_SELECTED_WIDTH) {
            //若设置了选中以及未选中长度不一致（这里只针对getSelectedWidth有修改的情况）
            width = (int) ((count - 1) * config.getIndicatorSpace() + config.getNormalWidth() * (count - 1) + config.getSelectedWidth());
        } else {
            width = (int) ((count - 1) * config.getIndicatorSpace() + config.getNormalWidth() * count);
        }
onDraw：
for (int i = 0; i < count; i++) {
            mPaint.setColor(config.getCurrentPosition() == i ? config.getSelectedColor() : config.getNormalColor());
            if (config.getCurrentPosition() == i) {
                RectF rectF = new RectF(left, 0, left + config.getSelectedWidth(), config.getHeight());
                left = left + config.getSelectedWidth() + config.getIndicatorSpace();
                canvas.drawRoundRect(rectF, config.getRadius(), config.getRadius(), mPaint);
            } else {
                RectF rectF = new RectF(left, 0, left + config.getNormalWidth(), config.getHeight());
                left = left + config.getNormalWidth() + config.getIndicatorSpace();
                canvas.drawRoundRect(rectF, config.getRadius(), config.getRadius(), mPaint);
            }
        }
这是只针对ui的简单绘制。

**Comment by youth5201314** [comment]
你setMeasuredDimension方法调了吗？如果调了，从你的代码贴出来的部分看是能达到你要的效果的。你也可以等下个版本我会后面再库里面修改下指示器，增加点样式

**Comment by AttITuder** [comment]
代码指示器颜色和宽度都无效，xml中设置有效
