### ISSUE TITLE
NestedScroll behavior上下滑动冲突

### ISSUE THREAD

**Issue by Dirtyshushu** [youth5201314/banner#829]
比如在bottomsheet中滑动会拦截behavior的事件

**Comment by youth5201314** [comment]
这个我看不到你怎么实现的，很难给到你帮助，就算我写一个demo，也不一定会复现你相同的问题的

**Comment by zhaobinsir** [comment]
vBanner.viewPager2.children.find { it is RecyclerView }?.let {
            (it as RecyclerView).isNestedScrollingEnabled = false
        }
