### ISSUE TITLE
removeCallbacks(mLoopTask)无效的问题

### ISSUE THREAD

**Issue by nuurwing** [youth5201314/banner#830]
可以在真机4.3，安卓4.4模拟器上复现，
        banner.setAdapter(new ImgBannerAdapter(mDatas))
                .addBannerLifecycleObserver(this)
                .setIndicator(new CircleIndicator(this))
                .setDelayTime(6000)
                .setScrollTime(1000);
就一个简单的代码，有2张图，现象：刚翻到第二张，马上跳回第一张，原因是初始化的start()和onAttachedToWindow中的start()都在运行mLoopTask，stop()方法失效。
我现在是给AutoLoopTask加了id，stop()里面移除removeCallbacks的同时，新new一个新ID的AutoLoopTask，就这样用了

**Comment by youth5201314** [comment]
这个我测试下，主要是我没想到现在还有5.0以下的手机要适配，我们线上项目早就开始只适配5.0以上了
