### ISSUE TITLE
一直报错

### ISSUE THREAD

**Issue by githubghb** [youth5201314/banner#835]
![image](https://user-images.githubusercontent.com/26829506/85260986-1ea23200-b49e-11ea-9b6e-3a1b4a5a4b74.png)
![image](https://user-images.githubusercontent.com/26829506/85260994-219d2280-b49e-11ea-9a04-652bb2e342d1.png)

**Comment by githubghb** [comment]
然后更改为1.4.10就没有问题，2.0.11版本，只要引入就编译不通过

**Comment by youth5201314** [comment]
indicator_gravity这个属性冲突了， 你检查下还有什么地方也是这么定义的。

**Comment by xyzeng12** [comment]
indicator_gravity我也冲突啊，我看见都有好几个提issues了，如果方便的话，麻烦您改一下嘛
