### ISSUE TITLE
CoordinatorLayout嵌套banner

### ISSUE THREAD

**Issue by HelloAnyu** [youth5201314/banner#836]
CoordinatorLayout嵌套banner得时候，折叠部分为banner，底部滚动上去以后，折叠得banner会显示出来

**Comment by HelloAnyu** [comment]
版本为2.0.11，折叠得banner不会立刻显示出来，而是等一会才会显示出来

**Comment by HelloAnyu** [comment]
麻烦作者看到给回复一下，万分感谢

**Comment by xuzhu19930323** [comment]
作者文档的那两行代码，我设置了，也还是会这样，我是recyclerview添加banner为head，也自动被顶下来了
