### ISSUE TITLE
只加载布局，不写代码都运行不了，打开就闪退

### ISSUE THREAD

**Issue by mutoujun** [youth5201314/banner#837]
就只在布局文件里把banner控加进去都不行，一直闪退，什么情况，我用的是最新版2.0.11

**Comment by mutoujun** [comment]
![image](https://user-images.githubusercontent.com/32905492/85266457-7775c880-b4a6-11ea-8c0d-056bea577e6e.png)

**Comment by githubghb** [comment]
我的只要引入2.0.11版本，就编译不通过。然后更改为1.4.10就没有问题

**Comment by mutoujun** [comment]
> 我的只要引入2.0.11版本，就编译不通过。然后更改为1.4.10就没有问题

1.4.10是老版本啊，老版本我也没问题
