### ISSUE TITLE
关于自动切换的时的圆角问题

### ISSUE THREAD

**Issue by lchang70163** [youth5201314/banner#840]
你好，我引用库之后，加载网络图片，在轮播状态下imageview先直角后圆角 想问一下是什么原因

**Comment by youth5201314** [comment]
圆角有两种，一种是整个view的圆角一个是图片本身的圆角，你只有当两种都设置成圆角了，才会达到你想要的效果，你如果只是设置了banner的圆角，但是你的图片是直角了，那么在图片滑动过程中肯定也是直角的啊，可以参考demo，你在设置了banner圆角后，将你的图片也设置成圆角就行了，可以用图片加载器设置也可以用自定义控件

**Comment by lchang70163** [comment]
您好，看了demo ,首页的初始化填充 您只设置了    banner:banner_radius="5dp" 图片是直角图片，运行demo看到的就是圆角，而填充网络的那个您是裁剪实现的，复制demo 中的相关内容之后 还是先直角然后紧接着变成圆角

**Comment by lchang70163** [comment]
不好意思，找到问题了，是我的原因，抱歉了

**Comment by HeyBean-X** [comment]
@lchang70163 你好，最后解决了吗？ 是什么问题
