### ISSUE TITLE
混淆文件的配置

### ISSUE THREAD

**Issue by fxlcy** [youth5201314/banner#841]
#banner
-keep class androidx.viewpager2.widget.ViewPager2{
    androidx.viewpager2.widget.PageTransformerAdapter mPageTransformerAdapter;
    androidx.viewpager2.widget.ScrollEventAdapter mScrollEventAdapter;
}

-keep class androidx.viewpager2.widget.PageTransformerAdapter{
    androidx.recyclerview.widget.LinearLayoutManager mLayoutManager;
}

-keep class androidx.recyclerview.widget.RecyclerView$LayoutManager{
    androidx.recyclerview.widget.RecyclerView mRecyclerView;
}

-keep class androidx.viewpager2.widget.ScrollEventAdapter{
    androidx.recyclerview.widget.LinearLayoutManager mLayoutManager;
}

**Comment by youth5201314** [comment]
什么意思？
