### ISSUE TITLE
加个接口设置无限轮播

### ISSUE THREAD

**Issue by zhouxinghua9527** [youth5201314/banner#842]
加个接口设置无限轮播吧，现在如果直接new的话没办法设置无限轮播）
直接new的话attrs 为空，直接return了，所以默认是false

**Comment by youth5201314** [comment]
关于new的默认参数和无限循环，新版已经修改了，等会上传

**Comment by zhouxinghua9527** [comment]
> 关于new的默认参数和无限循环，新版已经修改了，等会上传

点赞
