### ISSUE TITLE
有没有遇到，轮播图片显示一半，没有滑动过去，等几秒又可以了.

### ISSUE THREAD

**Issue by lijun952048910** [youth5201314/banner#843]
![微信截图_20200623144745](https://user-images.githubusercontent.com/5387535/85370132-d861d700-b560-11ea-858d-396d696fa831.png)

**Comment by youth5201314** [comment]
目前来说你是第一个这么反馈，你详细说下你的运行环境和怎么弄的，不然我也没法确定问题

**Comment by Alexxiaopang** [comment]
我也碰到过，不过这个几率很低，其实就是切换其他页面再回来，或者切换tab

**Comment by lijun952048910** [comment]
> 我也碰到过，不过这个几率很低，其实就是切换其他页面再回来，或者切换tab

对，几率很低，我也是切换tab有时候会出现，

**Comment by hkhv** [comment]
这个 我也遇到过，，在viewpager2 中有四个 fragment  banner  在其中的一个 fragment  中， 我在banner  自动滚动中的时候点击其他 tab 在回到这个页面的时候，， banner 就会卡住，，可以手动滚动复原或者让他自动开始滚动也可以复原

**Comment by dawnhope** [comment]
> 这个 我也遇到过，，在viewpager2 中有四个 fragment banner 在其中的一个 fragment 中， 我在banner 自动滚动中的时候点击其他 tab 在回到这个页面的时候，， banner 就会卡住，，可以手动滚动复原或者让他自动开始滚动也可以复原

+1，而且是必复现

**Comment by XiaoQiWen** [comment]
这个问题是Viewpager2自带的BUG，随便写一个tab+fragment的导航页。在其中一个fragment中添加一个viewpager2控件。滑动到一半点击tab切换就重现了。

**Comment by XiaoQiWen** [comment]
我尝试了一个临时的解决办法
```
    override fun onResume() {
        super.onResume()
        banner?.findViewById<ViewPager2>(R.id.vp_main)?.let { pager ->
            (pager.getChildAt(0) as? RecyclerView)?.smoothScrollToPosition(pager.currentItem)
        }
        banner?.startLoop()
    }

    override fun onPause() {
        super.onPause()
        banner?.stopLoop()
    }
```

**Comment by zjxuzhj** [comment]
必现的问题

**Comment by longdw** [comment]
这个问题解决了吗？为啥要关掉？
