### ISSUE TITLE
banner焦点冲突

### ISSUE THREAD

**Issue by xuzhu19930323** [youth5201314/banner#844]
我将banner作为recyclerview的head，向上滑动recyclerview，静止之后banner又自己获取到了焦点，导致页面又自动滑下来了

**Comment by qiangzengli** [comment]
同问

**Comment by youth5201314** [comment]
这个问题已经回答了很多次了，可以看文档，或者demo

**Comment by xuzhu19930323** [comment]
我按照文档给父控件加了那两行代码，也是依赖的最新版本，还是出现问题
    //banner也一定要用最新版哦！
    android:focusable="true"
    android:focusableInTouchMode="true"









在 2020-06-29 14:21:08，"Spring" <notifications@github.com> 写道：

这个问题已经回答了很多次了，可以看文档，或者demo

**Comment by youth5201314** [comment]
这个问题很多朋友都已经反馈没有问题，都已经上线运行了！你反馈时只说了一句话，我不知道你怎么用的，添加的header使用的是第三方的框架还是自己写的，recyclerView是不是原生的还是第三方修改过的，等等，这些细节什么的都不愿意多说一下，那我只能按照我的理解这么回复你了！而且demo也有例子，你运行下demo看看有没有问题，header不管怎么添加的都是一个item，首先我不知道你的环境那么你就按照demo来运行，这样都还有问题那么我也好处理，很容易就能确定问题所在，然后再详细反馈下！

**Comment by qiangzengli** [comment]
不好意思，我是在配合vlayout使用的使用遇到的，在使用LinearLayoutHelper()添加banner的时候，手动滚动到banner中间，它会自己回到顶部




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Spring"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月29日(星期一) 下午3:05
收件人:&nbsp;"youth5201314/banner"<banner@noreply.github.com&gt;;
抄送:&nbsp;"[-disingenu°]言不由衷"<2224357370@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [youth5201314/banner] banner焦点冲突 (#844)





 
这个问题很多朋友都已经反馈没有问题，都已经上线运行了！你反馈时只说了一句话，我不知道你怎么用的，添加的header使用的是第三方的框架还是自己写的，recyclerView是不是原生的还是第三方修改过的，等等，这些细节什么的都不愿意多说一下，那我只能按照我的理解这么回复你了！而且demo也有例子，你运行下demo看看有没有问题，header不管怎么添加的都是一个item，首先我不知道你的环境那么你就按照demo来运行，这样都还有问题那么我也好处理，很容易就能确定问题所在，然后再详细反馈下！
