### ISSUE TITLE
为什么新版本比老版本帧数差好多，测试机型小米8se

### ISSUE THREAD

**Issue by susyimes** [youth5201314/banner#845]
**老版本帧数稳定且流畅 version 1.4.10**  
![d2202cb35c1c15898f4a5cda0e35089](https://user-images.githubusercontent.com/15085918/85937150-68be6400-b933-11ea-9f12-70d88a455d36.jpg)
![d0c6ef88d2ad6823f6155a9d4330453](https://user-images.githubusercontent.com/15085918/85937157-7378f900-b933-11ea-94ed-7d5ffdd62f9a.jpg)

**新版本帧数变低了，而且波动比较大 version 2.0.11** 
![1c541e3917119ca678146f73f801f93](https://user-images.githubusercontent.com/15085918/85937158-75db5300-b933-11ea-9d95-7f87c8d4b67d.jpg)
![ac4f8e86dd5b4ca1cc0d50ed5e13559](https://user-images.githubusercontent.com/15085918/85937160-77a51680-b933-11ea-9a83-3fd087734da4.jpg)

**Comment by youth5201314** [comment]
两个版本分别是基于viewpager和viewpager2实现的，你这样对比没有可比性的。

**Comment by susyimes** [comment]
viewpager2本身在高端机型上表现不如viewpager
