### ISSUE TITLE
点击事件不触发可能是什么原因

### ISSUE THREAD

**Issue by Stone-s** [youth5201314/banner#848]

**Comment by Stone-s** [comment]
compileOptions{
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
添加完这段的代码就解决了

**Comment by youth5201314** [comment]
因为用了lambda，所有要jdk8

**Comment by shuhao1022** [comment]
> 因为用了lambda，所有要jdk8

用了jdk8还是不行啊

**Comment by liubei111** [comment]
先setAdapter()，再设置点击事件

**Comment by Jessiqi** [comment]
> > 因为用了lambda，所有要jdk8
> 
> 用了jdk8还是不行啊

我在项目中集成了也是不行 ，你是怎么解决的？
