### ISSUE TITLE
setAdapter卡死导致ANR

### ISSUE THREAD

**Issue by Gaocb715x** [youth5201314/banner#849]
调用setAdapter方法会卡死导致ANR

**Comment by youth5201314** [comment]
你是第一个反馈anr的，这个问题这么明显，要是有问题的话应该不会更新了这么就才出现的。你仔细看下你自己的代码确定下是不是banner导致，可以运行下demo看看是否也有问题来排除下，如果demo也有问题，你再详细反馈下！
