### ISSUE TITLE
页面恢复可见之后，能否立即滚动？

### ISSUE THREAD

**Issue by 287138531** [youth5201314/banner#852]
或者说页面不可见仍计时，到恢复可见时，就可以滚动

**Comment by youth5201314** [comment]
恢复可见后，会开始重新计时的！如果恢复可见后直接混动，那么就会有一张图片在不可见前刚好滑到它，然后在次可见时用户还没怎么看清就没了，在正常产品中这种情况是不合理的，就算是在做广告pv也不合理。你要是想要这种效果可以自己在不可见前将时间设置的小点，然后可见后在还原回去。或者记录不可见前的位置，可见时直接setCurrentItem到下一个就行了！
