### ISSUE TITLE
关于banner阴影

### ISSUE THREAD

**Issue by TangyiruGit** [youth5201314/banner#853]
![image](https://user-images.githubusercontent.com/43714686/86428043-65095380-bd1e-11ea-97da-3338a6a3f84f.png)
大佬，想请教下banner2.0提供的画廊模式，如果想要给每个banner加上阴影能实现吗？现在底色纯白，图片也是纯白的情况下显示不太友好

**Comment by youth5201314** [comment]
可以，整个item都是你自己写的，加上阴影也很简单啊，比如你用cardview包裹下
