### ISSUE TITLE
能不能方式设置空状态页面？

### ISSUE THREAD

**Issue by wuwenbo5** [youth5201314/banner#855]
当传进去的list为空或者size为0的时候，显示一个空状态页面；

**Comment by mao19951015** [comment]
我觉得吧，这个在外面自己判断一下比较合理，无图片不显示轮播图

**Comment by youth5201314** [comment]
楼上说的是对的，这个空状态的显示，设计的样式不确定性太强了，内置这个功能可能也不一定能达到使用者的要求
