### ISSUE TITLE
魅族效果，轮播循环后回到首位置 第二张图片闪烁

### ISSUE THREAD

**Issue by knight-danger** [youth5201314/banner#856]
版本：2.0.12
手机型号：华为、魅族
系统版本：10、8
业务环境：
如题，在 Demo 中 setBannerGalleryMZ 设置 itemWidth 大一些就可以看到这个情况

![image](https://user-images.githubusercontent.com/18062637/86872163-4b954c80-c10e-11ea-88b4-ed55b41d7173.png)
![image](https://user-images.githubusercontent.com/18062637/86872174-4f28d380-c10e-11ea-913b-4a69c62776a0.png)

**Comment by Star3513** [comment]
https://github.com/youth5201314/banner/issues/995#issuecomment-1447424631
测试可以解决
