### ISSUE TITLE
感觉和1.4比变复杂了

### ISSUE THREAD

**Issue by belongLMF** [youth5201314/banner#857]
本来我只需要在activity中设置要加载的图片就可以了，现在需要单独设置adapter个databean，请问2.0还能在activity中设置加载的图片吗？

**Comment by qqtaominqq** [comment]
同感

**Comment by youth5201314** [comment]
只是加载图片的话，可以使用默认的图片适配器。其他类型没有提供是因为可变性要求不确定 
banner.setAdapter(new BannerImageAdapter<DataBean>(DataBean.getTestData3()) {
                    @Override
                    public void onBindView(BannerImageHolder holder, DataBean data, int position, int size) {
                        //图片加载自己实现
                        Glide.with(holder.itemView)
                             .load(data.imageUrl)
                             .apply(RequestOptions.bitmapTransform(new RoundedCorners(30)))
                             .into(holder.imageView);
                    }
                });
