### ISSUE TITLE
你好！recycleview列表中用banner，如果banner只漏出一部分，轮播的时候recycleview滑动使banner漏出来，能否设置不滑动；

### ISSUE THREAD

**Issue by longdexinz** [youth5201314/banner#858]
recycleview列表中用banner，如果banner只漏出一部分，轮播的时候recycleview会自动滑动，使banner漏出来，能否设置不滑动；

**Comment by youth5201314** [comment]
这个你只能监听recycleview的滑动以及item的是否可见来判断，banner内部肯定是不知道你是嵌套的recycleview，也不知道你是否只露出了一部分
