### ISSUE TITLE
banner 设置setStartPosition(0); 无效 设置 adapter 数据源之前

### ISSUE THREAD

**Issue by liudaohong** [youth5201314/banner#859]

**Comment by liudaohong** [comment]
2.0.12版本

**Comment by liudaohong** [comment]
发现问题了 是 在 设置   isInfiniteLoop  不轮询就不会有问题

**Comment by youth5201314** [comment]
实际测试没有问题的，不知道你怎么用的，不管你设不设置isInfiniteLoop ，setStartPosition和setCurrentItem都能使用。其次setStartPosition(0)这个在无限循环时是无意义的设置。0是放的最后一张，1才是放的第一张。你禁止了无限循环可以生效那是因为0代表的是第一张。你可以自己了解先无限循环的原理就应该明白了
