### ISSUE TITLE
banner放到Recyclerview中时手动滑动很困难

### ISSUE THREAD

**Issue by ArtisanM** [youth5201314/banner#86]
必须手指横向滑动才能出发banner的翻页，稍微往竖直方向偏一点就变成RecyclerView的竖直滑动了

**Comment by ArtisanM** [comment]
RecyclerView外面嵌套的Ultra-pull-to-refresh  是不是和这个下拉刷新组件有关系啊

**Comment by ArtisanM** [comment]
我的banner是作为rv的第一个item显示的

**Comment by a362310485** [comment]
请教如何解决的？

**Comment by ArtisanM** [comment]
UltraPTR要开启disableHorizontalMove 然后还要对UltraPTR源码做一些修改  具体可以参照他的issue，里面有人反馈这个问题
