### ISSUE TITLE
banner刚加载出来还不能 向左滑动 需要先向右滑动 后才能向左滑动 

### ISSUE THREAD

**Issue by liudaohong** [youth5201314/banner#860]

**Comment by youth5201314** [comment]
具体点啊！

**Comment by baixxx** [comment]
@youth5201314 @liudaohong 
我也遇到这个问题，就是banner第一次展示的时候，不能向左滑动；
手动向右滑动一次后，才可以向左滑动

**Comment by Kacent123** [comment]
> 具体点啊！

他的意思是在设置循环模式下, 第一次加载数据的时候 无法向右滑动 (即直接看最后一个),要向左滑动一个 到脚表1后 ,才能向右滑
