### ISSUE TITLE
CoordinatorLayout+ViewPager  上滑banner不能联动

### ISSUE THREAD

**Issue by Luckylll** [youth5201314/banner#861]
banner在ViewPager的fragment中，上滑banner不松手  CoordinatorLayout没有收缩效果，使用方法setIntercept(false) 也无效

**Comment by youth5201314** [comment]
像这种问题，你要是还没解决，可以写一个demo给我，不然我不好还原你的场景的，再一个我也不能每个问题都去模拟一下，太费时了！希望理解！

**Comment by Luckylll** [comment]
使用 banner?.viewPager2?.getChildAt(0)?.isNestedScrollingEnabled = false 处理了

**Comment by LvZhenDong** [comment]
我也遇到这个问题了，直接设置banner的isNestedScrollingEnabled为false也可以解决
