### ISSUE TITLE
界面销毁时，报java.lang.NullPointerException

### ISSUE THREAD

**Issue by YongJianZhou** [youth5201314/banner#864]
作者你好：
addBannerLifecycleObserver后，界面销毁的时候，会调用banner的destory(),getViewPager2().unregisterOnPageChangeCallback(mPageChangeCallback)的时候，ViewPager已经为null
日志如下：
java.lang.NullPointerException

Attempt to invoke virtual method 'void androidx.viewpager2.widget.ViewPager2.unregisterOnPageChangeCallback(androidx.viewpager2.widget.ViewPager2$OnPageChangeCallback)' on a null object reference

**Comment by youth5201314** [comment]
这个是加了null判断的啊，你用的是哪个版本？我这测试正常呢

**Comment by YongJianZhou** [comment]
版本是2.0.10,我这边看到的banner类里的getViewPager2只是加了@NonNull。我是在activity的pageradapter里的fragment调用的addBannerLifecycleObserver。

**Comment by YongJianZhou** [comment]
更新了2.1.0，看到加了判空了，谢谢回复
