### ISSUE TITLE
2.0的轮播图  我添加动画 没反应 还是直接切换图片 没有从左往右的效果

### ISSUE THREAD

**Issue by 594238813** [youth5201314/banner#869]
view.bvp_banner.addPageTransformer( MarginPageTransformer(BannerUtils.dp2px(10f).toInt()));

**Comment by youth5201314** [comment]
MarginPageTransformer是系统提供设置间距的，这个没有动画效果，你可以试下内置的其他PageTransformer，也可以自定义
