### ISSUE TITLE
轮番的过渡不流畅

### ISSUE THREAD

**Issue by cwjfeifei** [youth5201314/banner#87]
快速滑动stopAutoPlay，静止的时候startAutoPlay，但是从滑动到静止时，图片轮番的过渡不流畅，望能改进一下

**Comment by youth5201314** [comment]
1.能给个图最好，可能我理解的和你不一样
2.我理解的你的描述，让我觉得很没有必要的操作，我的开始和结束设计之初是为了生命周期考虑的，请问一个软件你会提供开始和暂停的轮播的操作按钮吗？难道用户还会进行开始和暂停啊?
