### ISSUE TITLE
大佬画廊效果时，当itemWidth设置为0，pageMargin不是0的时候没有效果了，我看代码加了itemWidth大于0的判断，可否让其为0也生效

### ISSUE THREAD

**Issue by huyi3211** [youth5201314/banner#870]
setRecyclerViewPadding(leftItemWidth > 0 ? (int) BannerUtils.dp2px(leftItemWidth + pageMargin) : 0,
                rightItemWidth > 0 ? (int) BannerUtils.dp2px(rightItemWidth + pageMargin) : 0);

**改为**
 setRecyclerViewPadding(leftItemWidth >= 0 ? (int) BannerUtils.dp2px(leftItemWidth + pageMargin) : 0,
                rightItemWidth >= 0 ? (int) BannerUtils.dp2px(rightItemWidth + pageMargin) : 0);

**Comment by youth5201314** [comment]
这样改的意义何在啊？左右都不显示图片了还叫画廊效果吗？如果你想左右多一点间距 ，那你还不如直接在布局中设置或者直接设置LayoutParams来改变
