### ISSUE TITLE
带视频的轮播广告，经常视频控件实例获取不到，导致没法自动播放

### ISSUE THREAD

**Issue by ollie100** [youth5201314/banner#873]
是看了你demo，然后照着做了以后发现的问题，后续有解决我会回复上去

**Comment by lixiaokuan0819** [comment]
banner.addBannerLifecycleObserver(this)
                .setAdapter(new MultipleTypesAdapter(this, DataBean.getTestDataVideo()))
                .setIndicator(new NumIndicator(this))
                .setIndicatorGravity(IndicatorConfig.Direction.RIGHT)
                .addOnPageChangeListener(new OnPageChangeListener() {
                    @Override
                    public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {

                    }

                    @Override
                    public void onPageSelected(int position) {
                        Log.e("--","position:"+position);
                        if (player == null) {
                            RecyclerView.ViewHolder viewHolder = banner.getAdapter().getViewHolder();
                            if (viewHolder instanceof VideoHolder) {
                                VideoHolder holder = (VideoHolder) viewHolder;
                                player = holder.player;
                            }

                            if (viewHolder instanceof ImageHolder) {
                                ImageHolder holder = (ImageHolder) viewHolder;
                                //player = holder.player;
                            }
                            return;
                        }
                        if (position != 0) {
                            player.onVideoReset();
                        }
                    }

                    @Override
                    public void onPageScrollStateChanged(int state) {

                    }
                });
    }
仿淘宝的这段代码有问题，滑到第一个的时候viewHolder instanceof VideoHolder经常为false，导致拿不到palyer实例

**Comment by ollie100** [comment]
是的，就是这个问题

**Comment by ollie100** [comment]
是的，就是这个问题，还有手动start和stop，banner也是没有起作用

**Comment by lixiaokuan0819** [comment]
> 是的，就是这个问题，还有手动start和stop，banner也是没有起作用

这个问题你解决了么？

**Comment by MatthewDevelop** [comment]
同问，第一次轮播正常，后面getViewHolder返回的就不对了，有大佬解决了吗？

**Comment by MatthewDevelop** [comment]
已经解决了，item数量小于4的时候，第一遍轮播完之后。后面每次getViewHolder,返回的都是列表最后的一个holder类型，所以列表数量小于4的时候可以用集合存储需player，一遍轮播之后，通过自己的集合来取player进行播放

**Comment by MatthewDevelop** [comment]
![image](https://user-images.githubusercontent.com/23044942/95945792-d37da780-0e1d-11eb-98f1-8619dc27fd57.png)

**Comment by ZevShiShi** [comment]
`java`
class MultipleTypesAdapter(context: Context, datas: MutableList<BannerBean>?) :
    BannerAdapter<BannerBean, RecyclerView.ViewHolder>(datas) {

    private val mContext: Context = context
    private var videoHolder: VideoHolder? = null

    override fun onCreateHolder(parent: ViewGroup?, viewType: Int): RecyclerView.ViewHolder {
        return when (viewType) {
            0 -> ImageHolder(BannerUtils.getView(parent!!, R.layout.item_banner_image))
            1 -> {
                videoHolder = VideoHolder(BannerUtils.getView(parent!!, R.layout.item_banner_video))
                return videoHolder!!
            }
            else -> ImageHolder(BannerUtils.getView(parent!!, R.layout.item_banner_image))
        }
    }

    override fun getItemViewType(position: Int): Int {
        return getData(getRealPosition(position)).viewType
    }

    override fun onBindView(
        holder: RecyclerView.ViewHolder?,
        data: BannerBean?,
        position: Int,
        size: Int
    ) {
        when (holder!!.itemViewType) {
            0 -> {
                val roundedCorners = RoundedCorners(10)
                val options = RequestOptions.bitmapTransform(roundedCorners)
                Glide.with(mContext)
                    .load(data?.bannerUrl)
                    .apply(options)
                    .into((holder as ImageHolder?)!!.imageView)
            }
            1 -> {
//                videoHolder = holder as VideoHolder?
                PlayerFactory.setPlayManager(Exo2PlayerManager::class.java) // EXO模式
                GSYVideoManager.instance().enableRawPlay(BaseApplication.context) // 启用raw资源支持
                val uri = "rawresource://" + mContext.packageName + "/" + R.raw.banner_video
                (holder as VideoHolder).videoView.setUp(uri, true, null)
                holder.videoView.backButton.visibility = View.GONE
                //增加封面

                val uri2 = "android.resource://" + mContext.packageName + "/" + R.raw.banner_video
                val retriever = MediaMetadataRetriever()
                retriever.setDataSource(mContext, Uri.parse(uri2))
                val bmp = retriever.getFrameAtTime(0, MediaMetadataRetriever.OPTION_CLOSEST_SYNC)

                val imageView = ImageView(mContext)
                imageView.scaleType = ImageView.ScaleType.CENTER_CROP
                imageView.setImageBitmap(bmp)
                holder.videoView.thumbImageView = imageView // 关联封面
            }
        }
    }

    fun getVideoHolder(): VideoHolder {
        return videoHolder!!
    }

    inner class ImageHolder(view: View) : RecyclerView.ViewHolder(view) {
        var imageView: ImageView = view as ImageView
    }


    inner class VideoHolder(view: View) : RecyclerView.ViewHolder(view) {
        var videoView: StandardGSYVideoPlayer =
            ((view as ViewGroup).getChildAt(0)) as StandardGSYVideoPlayer
    }

}

**Comment by ZevShiShi** [comment]
'''java
class MultipleTypesAdapter(context: Context, datas: MutableList<BannerBean>?) :
    BannerAdapter<BannerBean, RecyclerView.ViewHolder>(datas) {

    private val mContext: Context = context
    private var videoHolder: VideoHolder? = null

    override fun onCreateHolder(parent: ViewGroup?, viewType: Int): RecyclerView.ViewHolder {
        return when (viewType) {
            0 -> ImageHolder(BannerUtils.getView(parent!!, R.layout.item_banner_image))
            1 -> {
                videoHolder = VideoHolder(BannerUtils.getView(parent!!, R.layout.item_banner_video))
                return videoHolder!!
            }
            else -> ImageHolder(BannerUtils.getView(parent!!, R.layout.item_banner_image))
        }
    }

    override fun getItemViewType(position: Int): Int {
        return getData(getRealPosition(position)).viewType
    }

    override fun onBindView(
        holder: RecyclerView.ViewHolder?,
        data: BannerBean?,
        position: Int,
        size: Int
    ) {
        when (holder!!.itemViewType) {
            0 -> {
                val roundedCorners = RoundedCorners(10)
                val options = RequestOptions.bitmapTransform(roundedCorners)
                Glide.with(mContext)
                    .load(data?.bannerUrl)
                    .apply(options)
                    .into((holder as ImageHolder?)!!.imageView)
            }
            1 -> {
//                videoHolder = holder as VideoHolder?
                PlayerFactory.setPlayManager(Exo2PlayerManager::class.java) // EXO模式
                GSYVideoManager.instance().enableRawPlay(BaseApplication.context) // 启用raw资源支持
                val uri = "rawresource://" + mContext.packageName + "/" + R.raw.banner_video
                (holder as VideoHolder).videoView.setUp(uri, true, null)
                holder.videoView.backButton.visibility = View.GONE
                //增加封面

                val uri2 = "android.resource://" + mContext.packageName + "/" + R.raw.banner_video
                val retriever = MediaMetadataRetriever()
                retriever.setDataSource(mContext, Uri.parse(uri2))
                val bmp = retriever.getFrameAtTime(0, MediaMetadataRetriever.OPTION_CLOSEST_SYNC)

                val imageView = ImageView(mContext)
                imageView.scaleType = ImageView.ScaleType.CENTER_CROP
                imageView.setImageBitmap(bmp)
                holder.videoView.thumbImageView = imageView // 关联封面
            }
        }
    }

    fun getVideoHolder(): VideoHolder {
        return videoHolder!!
    }

    inner class ImageHolder(view: View) : RecyclerView.ViewHolder(view) {
        var imageView: ImageView = view as ImageView
    }


    inner class VideoHolder(view: View) : RecyclerView.ViewHolder(view) {
        var videoView: StandardGSYVideoPlayer =
            ((view as ViewGroup).getChildAt(0)) as StandardGSYVideoPlayer
    }

}
'''

**Comment by ZevShiShi** [comment]
`class MultipleTypesAdapter(context: Context, datas: MutableList<BannerBean>?) :
    BannerAdapter<BannerBean, RecyclerView.ViewHolder>(datas) {

    private val mContext: Context = context
    private var videoHolder: VideoHolder? = null

    override fun onCreateHolder(parent: ViewGroup?, viewType: Int): RecyclerView.ViewHolder {
        return when (viewType) {
            0 -> ImageHolder(BannerUtils.getView(parent!!, R.layout.item_banner_image))
            1 -> {
                videoHolder = VideoHolder(BannerUtils.getView(parent!!, R.layout.item_banner_video))
                return videoHolder!!
            }
            else -> ImageHolder(BannerUtils.getView(parent!!, R.layout.item_banner_image))
        }
    }

    override fun getItemViewType(position: Int): Int {
        return getData(getRealPosition(position)).viewType
    }

    override fun onBindView(
        holder: RecyclerView.ViewHolder?,
        data: BannerBean?,
        position: Int,
        size: Int
    ) {
        when (holder!!.itemViewType) {
            0 -> {
                val roundedCorners = RoundedCorners(10)
                val options = RequestOptions.bitmapTransform(roundedCorners)
                Glide.with(mContext)
                    .load(data?.bannerUrl)
                    .apply(options)
                    .into((holder as ImageHolder?)!!.imageView)
            }
            1 -> {
//                videoHolder = holder as VideoHolder?
                PlayerFactory.setPlayManager(Exo2PlayerManager::class.java) // EXO模式
                GSYVideoManager.instance().enableRawPlay(BaseApplication.context) // 启用raw资源支持
                val uri = "rawresource://" + mContext.packageName + "/" + R.raw.banner_video
                (holder as VideoHolder).videoView.setUp(uri, true, null)
                holder.videoView.backButton.visibility = View.GONE
                //增加封面

                val uri2 = "android.resource://" + mContext.packageName + "/" + R.raw.banner_video
                val retriever = MediaMetadataRetriever()
                retriever.setDataSource(mContext, Uri.parse(uri2))
                val bmp = retriever.getFrameAtTime(0, MediaMetadataRetriever.OPTION_CLOSEST_SYNC)

                val imageView = ImageView(mContext)
                imageView.scaleType = ImageView.ScaleType.CENTER_CROP
                imageView.setImageBitmap(bmp)
                holder.videoView.thumbImageView = imageView // 关联封面
            }
        }
    }

    fun getVideoHolder(): VideoHolder {
        return videoHolder!!
    }

    inner class ImageHolder(view: View) : RecyclerView.ViewHolder(view) {
        var imageView: ImageView = view as ImageView
    }


    inner class VideoHolder(view: View) : RecyclerView.ViewHolder(view) {
        var videoView: StandardGSYVideoPlayer =
            ((view as ViewGroup).getChildAt(0)) as StandardGSYVideoPlayer
    }

}`

**Comment by ZevShiShi** [comment]
MultipleTypesAdapter.class 添加一个外部的VideoHolder 在onCreateHolder方法中获取到VideoHolder的实例，适配器内容暴露一个获取VideoHolder的实例方法就可以了，具体代码
```java
class MultipleTypesAdapter(context: Context, datas: MutableList<BannerBean>?) :
    BannerAdapter<BannerBean, RecyclerView.ViewHolder>(datas) {

    private val mContext: Context = context
    private var videoHolder: VideoHolder? = null

    override fun onCreateHolder(parent: ViewGroup?, viewType: Int): RecyclerView.ViewHolder {
        return when (viewType) {
            0 -> ImageHolder(BannerUtils.getView(parent!!, R.layout.item_banner_image))
            1 -> {
                videoHolder = VideoHolder(BannerUtils.getView(parent!!, R.layout.item_banner_video))
                return videoHolder!!
            }
            else -> ImageHolder(BannerUtils.getView(parent!!, R.layout.item_banner_image))
        }
    }

    override fun getItemViewType(position: Int): Int {
        return getData(getRealPosition(position)).viewType
    }

    override fun onBindView(
        holder: RecyclerView.ViewHolder?,
        data: BannerBean?,
        position: Int,
        size: Int
    ) {
        when (holder!!.itemViewType) {
            0 -> {
                val roundedCorners = RoundedCorners(10)
                val options = RequestOptions.bitmapTransform(roundedCorners)
                Glide.with(mContext)
                    .load(data?.bannerUrl)
                    .apply(options)
                    .into((holder as ImageHolder?)!!.imageView)
            }
            1 -> {
//                videoHolder = holder as VideoHolder?
                PlayerFactory.setPlayManager(Exo2PlayerManager::class.java) // EXO模式
                GSYVideoManager.instance().enableRawPlay(BaseApplication.context) // 启用raw资源支持
                val uri = "rawresource://" + mContext.packageName + "/" + R.raw.banner_video
                (holder as VideoHolder).videoView.setUp(uri, true, null)
                holder.videoView.backButton.visibility = View.GONE
                //增加封面

                val uri2 = "android.resource://" + mContext.packageName + "/" + R.raw.banner_video
                val retriever = MediaMetadataRetriever()
                retriever.setDataSource(mContext, Uri.parse(uri2))
                val bmp = retriever.getFrameAtTime(0, MediaMetadataRetriever.OPTION_CLOSEST_SYNC)

                val imageView = ImageView(mContext)
                imageView.scaleType = ImageView.ScaleType.CENTER_CROP
                imageView.setImageBitmap(bmp)
                holder.videoView.thumbImageView = imageView // 关联封面
            }
        }
    }

    fun getVideoHolder(): VideoHolder {
        return videoHolder!!
    }

    inner class ImageHolder(view: View) : RecyclerView.ViewHolder(view) {
        var imageView: ImageView = view as ImageView
    }


    inner class VideoHolder(view: View) : RecyclerView.ViewHolder(view) {
        var videoView: StandardGSYVideoPlayer =
            ((view as ViewGroup).getChildAt(0)) as StandardGSYVideoPlayer
    }

}
```

**Comment by ZevShiShi** [comment]
我是这样做的，思路和上面差不多，在MultipleTypesAdapter.class里写一个map集合，保存索引和对应VideoHolder的实例，内部在暴露一个获取VideoHolder实例的方法就可以了，索引和实例一一对应，这样就算写多个视频也可以一一获取
```java
class MultipleTypesAdapter(context: Context, datas: MutableList<BannerBean>?) :
    BannerAdapter<BannerBean, RecyclerView.ViewHolder>(datas) {

    private val mContext: Context = context
    private var videoHolder: VideoHolder? = null
    private var maps: LinkedHashMap<Int, VideoHolder> = LinkedHashMap()

    override fun onCreateHolder(parent: ViewGroup?, viewType: Int): RecyclerView.ViewHolder {
        return when (viewType) {
            0 -> ImageHolder(BannerUtils.getView(parent!!, R.layout.item_banner_image))
            1 -> {
                videoHolder = VideoHolder(BannerUtils.getView(parent!!, R.layout.item_banner_video))
                return videoHolder!!
            }
            else -> ImageHolder(BannerUtils.getView(parent!!, R.layout.item_banner_image))
        }
    }

    override fun getItemViewType(position: Int): Int {
        return getData(getRealPosition(position)).viewType
    }

    override fun onBindView(
        holder: RecyclerView.ViewHolder?,
        data: BannerBean?,
        position: Int,
        size: Int
    ) {
        when (holder!!.itemViewType) {
            0 -> {
                val roundedCorners = RoundedCorners(10)
                val options = RequestOptions.bitmapTransform(roundedCorners)
                Glide.with(mContext)
                    .load(data?.bannerUrl)
                    .apply(options)
                    .into((holder as ImageHolder?)!!.imageView)
            }
            1 -> {
//                videoHolder = holder as VideoHolder?
                maps[position] = (holder as VideoHolder?)!!
                PlayerFactory.setPlayManager(Exo2PlayerManager::class.java) // EXO模式
                GSYVideoManager.instance().enableRawPlay(BaseApplication.context) // 启用raw资源支持
                val uri = "rawresource://" + mContext.packageName + "/" + R.raw.banner_video
                (holder as VideoHolder).videoView.setUp(uri, true, null)
                holder.videoView.backButton.visibility = View.GONE
                //增加封面

                val uri2 = "android.resource://" + mContext.packageName + "/" + R.raw.banner_video
                val retriever = MediaMetadataRetriever()
                retriever.setDataSource(mContext, Uri.parse(uri2))
                val bmp = retriever.getFrameAtTime(0, MediaMetadataRetriever.OPTION_CLOSEST_SYNC)

                val imageView = ImageView(mContext)
                imageView.scaleType = ImageView.ScaleType.CENTER_CROP
                imageView.setImageBitmap(bmp)
                holder.videoView.thumbImageView = imageView // 关联封面
            }
        }
    }

    fun getVideoHolder(pos: Int): VideoHolder {
        return maps[pos]!!
    }

    inner class ImageHolder(view: View) : RecyclerView.ViewHolder(view) {
        var imageView: ImageView = view as ImageView
    }


    inner class VideoHolder(view: View) : RecyclerView.ViewHolder(view) {
        var videoView: StandardGSYVideoPlayer =
            ((view as ViewGroup).getChildAt(0)) as StandardGSYVideoPlayer
    }

}
```

外部调用
```java
   videoView = bannerAdapter?.getVideoHolder(0)?.videoView
                    LogUtils.d("onPageSelected=======$position===$videoView")
                    if (position != 0) {
                        videoView?.onVideoReset()
                    }
```

**Comment by ZevShiShi** [comment]
解决小于4个的item的复用问题
    我是这样做的，思路和上面差不多，在MultipleTypesAdapter.class里写一个map集合，在onBindView保存索引和对应VideoHolder的实例，内部在暴露一个获取VideoHolder实例的方法就可以了，索引和实例一一对应，这样就算写多个视频也可以一一获取，
    还有在小于4个的情况下RecyclerView.ViewHolder会出现复用错乱的情况，所以需要在onBindViewHolder中做一个判断，小于4个不复用，否则复用
```java
class MultipleTypesAdapter(context: Context, datas: MutableList<BannerBean>?) :
    BannerAdapter<BannerBean, RecyclerView.ViewHolder>(datas) {

    private val mContext: Context = context
    private var maps: LinkedHashMap<Int, VideoHolder> = LinkedHashMap()
    private var playListener: PlayerListener? = null

    override fun onCreateHolder(parent: ViewGroup?, viewType: Int): RecyclerView.ViewHolder {
        LogUtils.d("onCreateHolder=======")
        return when (viewType) {
            0 -> ImageHolder(BannerUtils.getView(parent!!, R.layout.item_banner_image))
            1 -> VideoHolder(BannerUtils.getView(parent!!, R.layout.item_banner_video))
            else -> ImageHolder(BannerUtils.getView(parent!!, R.layout.item_banner_image))
        }
    }

    fun setPlayListener(playListener: PlayerListener?) {
        this.playListener = playListener
    }

    override fun getItemViewType(position: Int): Int {
        return getData(getRealPosition(position)).viewType
    }

    /**
     * 解决小于4个的item的复用问题
    我是这样做的，思路和上面差不多，在MultipleTypesAdapter.class里写一个map集合，在onBindView保存索引和对应VideoHolder的实例，内部在暴露一个获取VideoHolder实例的方法就可以了，索引和实例一一对应，这样就算写多个视频也可以一一获取，
    还有在小于4个的情况下RecyclerView.ViewHolder会出现复用错乱的情况，所以需要在onBindViewHolder中做一个判断，小于4个不复用，否则复用
     *
     */
    override fun onBindViewHolder(
        holder: RecyclerView.ViewHolder,
        position: Int,
        payloads: MutableList<Any>
    ) {
        LogUtils.d("onBindViewHolder===============$mDatas")
        if (mDatas.size < 4) {
            holder.setIsRecyclable(false)
        } else {
            holder.setIsRecyclable(true)
        }
        super.onBindViewHolder(holder, position, payloads)
    }


    override fun onBindView(
        holder: RecyclerView.ViewHolder?,
        data: BannerBean?,
        position: Int,
        size: Int
    ) {
        when (holder!!.itemViewType) {
            0 -> {
                val roundedCorners = RoundedCorners(10)
                val options = RequestOptions.bitmapTransform(roundedCorners)
                Glide.with(mContext)
                    .load(data?.bannerUrl)
                    .apply(options)
                    .into((holder as ImageHolder?)!!.imageView)
            }
            1 -> {
                maps[position] = (holder as VideoHolder?)!!
                LogUtils.d("onBindView========${holder.videoView}=====${getRealPosition(position)}")
                PlayerFactory.setPlayManager(Exo2PlayerManager::class.java) // EXO模式
                GSYVideoManager.instance().enableRawPlay(BaseApplication.context) // 启用raw资源支持
                val uri = "rawresource://" + mContext.packageName + "/" + R.raw.banner_video
                holder.videoView.setUp(uri, true, null)
                holder.videoView.backButton.visibility = View.GONE
                holder.videoView.setPlayListener(playListener)

                //增加封面
                val uri2 = "android.resource://" + mContext.packageName + "/" + R.raw.banner_video
                val retriever = MediaMetadataRetriever()
                retriever.setDataSource(mContext, Uri.parse(uri2))
                val bmp = retriever.getFrameAtTime(0, MediaMetadataRetriever.OPTION_CLOSEST_SYNC)

                val imageView = ImageView(mContext)
                imageView.scaleType = ImageView.ScaleType.CENTER_CROP
                imageView.setImageBitmap(bmp)
                holder.videoView.thumbImageView = imageView // 关联封面
            }
        }
    }

    fun getVideoHolder(pos: Int): VideoHolder? {
        return maps[pos]
    }

    inner class ImageHolder(view: View) : RecyclerView.ViewHolder(view) {
        var imageView: ImageView = view as ImageView
    }


    inner class VideoHolder(view: View) : RecyclerView.ViewHolder(view) {
        var videoView: NormalGSYVideoPlayerEx =
            ((view as ViewGroup).getChildAt(0)) as NormalGSYVideoPlayerEx
    }

}
```

**Comment by houweiAndroid** [comment]
点击了播放，划到第4个item，在回来视频被释放了，老哥们有遇到这个情况么？
