### ISSUE TITLE
组合设置RectangleIndicator和setIndicatorRadius的问题

### ISSUE THREAD

**Issue by jeffreyxuworld** [youth5201314/banner#874]
文档中的：
banner_indicator_selected_width 指示器选中的宽度，默认7dp （对RectangleIndicator无效）
banner.setIndicatorSelectedWidth((int) BannerUtils.dp2px(25));
可是实际demo中是有对RectangleIndicator设置的，而且结果是有效的，是否文档写的有问题？
然后我这边需求，指示器用RectangleIndicator，并且需要设置圆角，banner.setIndicatorRadius((int) BannerUtils.dp2px(8))
代码如下：
        banner.setAdapter(new ImageNetAdapter(DataBean.getTestData3()));
        banner.setBannerRound(BannerUtils.dp2px(5));
        banner.setIndicator(new RectangleIndicator(this));
        banner.setIndicatorGravity(IndicatorConfig.Direction.RIGHT);
        banner.setIndicatorSelectedWidth((int) BannerUtils.dp2px(25));
        banner.setIndicatorSpace((int) BannerUtils.dp2px(8));
        banner.setIndicatorRadius((int) BannerUtils.dp2px(8));

run出来的效果，会有bug，比如你写在另外个ConstraintLayoutBannerActivity里面，从MainActivity跳入到里面，第一次显示正常，退出ConstraintLayoutBannerActivity再进入这个页面，可能就会出问题。指示器从第一个直接跳到第三个，而且banner到最后个的时候，一直回不到第一个，在死循环。

**Comment by youth5201314** [comment]
1、文档更新漏了已经修改
2、我测试你反馈的bug没有复现，你用的是否是最新版本，然后你看下目标页是否设置了生命周期控制，我有几个版本为了测试时去掉了
