### ISSUE TITLE
当滑动到最后一站图片，下一张 短暂的显示空白

### ISSUE THREAD

**Issue by kotle** [youth5201314/banner#876]
当滑动到第一张，上一张短暂的显示空白
这个是正常的
![image](https://user-images.githubusercontent.com/25656015/88419062-14fe4800-ce17-11ea-85f3-5c5aed5b0a0f.png)
这个是出现问题的
![image](https://user-images.githubusercontent.com/25656015/88418896-d9637e00-ce16-11ea-910e-5c1cd31df1a6.png)

**Comment by HairySnow** [comment]
同样我也遇到这个问题

**Comment by jiangw0419** [comment]
me too

**Comment by payne1107** [comment]
怎么解决的

**Comment by payne1107** [comment]
> 当滑动到第一张，上一张短暂的显示空白 这个是正常的 ![image](https://user-images.githubusercontent.com/25656015/88419062-14fe4800-ce17-11ea-85f3-5c5aed5b0a0f.png) 这个是出现问题的 ![image](https://user-images.githubusercontent.com/25656015/88418896-d9637e00-ce16-11ea-910e-5c1cd31df1a6.png)

解决了吗
