### ISSUE TITLE
banner 销毁时报错

### ISSUE THREAD

**Issue by 504254103** [youth5201314/banner#879]
banner绑定在fragment中 ：
banner.addBannerLifecycleObserver(MainBaseActivity.instance)
                            .setPageTransformer(new ViewPager2.PageTransformer() {
                                @Override
                                public void transformPage(@NonNull View page, float position) {

                                }
                            })
                            .setAdapter(new ImageAdapter(bannerUrls))
                            .setPageTransformer(new AlphaPageTransformer())
                            .setIndicator(new CircleIndicator(MainBaseActivity.instance))
                            .start();
当MainBaseActivity（外部activity）销毁时 报错 且不是必现
java.lang.RuntimeException:Unable to destroy activity {androidphone.dit.yd/androidphone.dit.yd.act.base.MainBaseActivity}: java.lang.RuntimeException: Failed to call observer method

Attempt to invoke virtual method 'void androidx.viewpager2.widget.ViewPager2.unregisterOnPageChangeCallback(androidx.viewpager2.widget.ViewPager2$OnPageChangeCallback)' on a null object reference   com.youth.banner.Banner.destroy(Banner.java:575)

**Comment by youth5201314** [comment]
是用的最新版吗？

**Comment by 504254103** [comment]
用的2.0.9

**Comment by youth5201314** [comment]
用最新版试试
