### ISSUE TITLE
能否支持轮播到最后一页时回滚到第一页

### ISSUE THREAD

**Issue by ArtisanM** [youth5201314/banner#88]
在最后一页时：
手动右滑就到头了，不会到下一页；
触发自动轮播则往左回到到第一页。

第一页同理。

**Comment by youth5201314** [comment]
是支持循环轮播的好吗？

**Comment by ArtisanM** [comment]
你没明白我的意思，现在的循环是无限循环，用户看起来好像轮播图是无限个的样子。
我的意思是播完最后一页后，向左回滚到第一页，而不是现在的向右继续播第一页

**Comment by youth5201314** [comment]
向左非常简单，你自己改下吧，就一个定位而已！我实在是不能理解你怎么想的，那么差的体验拿来干啥呢？你可以在市面上找下看看会不会有人那么做！
