### ISSUE TITLE
Compilation warning: Unchecked call to setAdapter(BA) as member of the raw type

### ISSUE THREAD

**Issue by urchinstarz** [youth5201314/banner#880]
提示 ：Compilation warning: Unchecked call to setAdapter(DA) as member of the raw type
使用的是 ImageNetAdapter；查了一下好像是说 泛型解析的问题。。但不知道怎么处理。。求助一下

**Comment by youth5201314** [comment]
贴一下你的代码看看，稍微完整点

**Comment by shuaisong** [comment]
ArrayList<String> strings = new ArrayList<String>();
        banner.setAdapter(new BannerImageAdapter<String>(strings) {
            @Override
            public void onBindView(BannerImageHolder holder, String data, int position, int size) {
                showImg(holder.imageView, data);
            }
        }).setIndicator(new CircleIndicator(this)).addBannerLifecycleObserver(this);

**Comment by Naruto-1996** [comment]
警告：Unchecked call to setAdapter(DA) as member of the raw type
fragment 中使用的  

@Override
  public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
    super.onViewCreated(view, savedInstanceState);
    binding.slidersRollPager
      .addBannerLifecycleObserver(this)
      .setAdapter(new HomeSliderImageAdapter(DataBean.getTestData3()),true)
      .setPageTransformer(new ZoomOutPageTransformer())
      .setIndicator(new CircleIndicator(getContext()))
      .setOnBannerListener(new OnBannerListener() {
        @Override
        public void OnBannerClick(Object data, int position) {
         Log.i("点击了" , position + "");
        }
      });
  }

**Comment by QianHong** [comment]
大佬们，这个问题怎么解决了？
