### ISSUE TITLE
2.0版本存在如下问题

### ISSUE THREAD

**Issue by ssj2020** [youth5201314/banner#881]
2.0版本存在如下问题:
1.在recyclerview+banner(banner在顶部)的情况下,banner过顶一半,自动翻页会自动回滚到顶部,夺取焦点能解决,
2.在bugly捕捉日志,在部分手机,如vivo系列,直接闪退,其他手机正常,报如下错误:
java.lang.NullPointerException
Attempt to invoke virtual method 'boolean androidx.recyclerview.widget.RecyclerView.canScrollVertically(int)' on a null object reference;

1 androidx.recyclerview.widget.RecyclerView$LayoutManager.onInitializeAccessibilityNodeInfo(RecyclerView.java:10378)
--
2 androidx.viewpager2.widget.ViewPager2$LinearLayoutManagerImpl.onInitializeAccessibilityNodeInfo(ViewPager2.java:1017)
3 com.youth.banner.util.ProxyLayoutManger.onInitializeAccessibilityNodeInfo(ProxyLayoutManger.java:98)
4 androidx.recyclerview.widget.RecyclerView$LayoutManager.onInitializeAccessibilityNodeInfo(RecyclerView.java:10348)
5 androidx.recyclerview.widget.RecyclerViewAccessibilityDelegate.onInitializeAccessibilityNodeInfo(RecyclerViewAccessibilityDelegate.java:74)
6 androidx.core.view.AccessibilityDelegateCompat$AccessibilityDelegateAdapter.onInitializeAccessibilityNodeInfo(AccessibilityDelegateCompat.java:86)
7 android.view.View.onInitializeAccessibilityNodeInfo(View.java:6090)
8 android.view.View.createAccessibilityNodeInfoInternal(View.java:6051)
9 android.view.View$AccessibilityDelegate.createAccessibilityNodeInfo(View.java:22352)
10 android.view.View.createAccessibilityNodeInfo(View.java:6034)
11 android.view.accessibility.AccessibilityRecord.setSource(AccessibilityRecord.java:145)
12 android.view.accessibility.AccessibilityRecord.setSource(AccessibilityRecord.java:119)
13 android.view.View.onInitializeAccessibilityEventInternal(View.java:5988)
14 android.view.View$AccessibilityDelegate.onInitializeAccessibilityEvent(View.java:22264)
15 androidx.core.view.AccessibilityDelegateCompat.onInitializeAccessibilityEvent(AccessibilityDelegateCompat.java:256)
16 androidx.recyclerview.widget.RecyclerViewAccessibilityDelegate.onInitializeAccessibilityEvent(RecyclerViewAccessibilityDelegate.java:80)
17 androidx.core.view.AccessibilityDelegateCompat$AccessibilityDelegateAdapter.onInitializeAccessibilityEvent(AccessibilityDelegateCompat.java:76)
18 android.view.View.onInitializeAccessibilityEvent(View.java:5974)
19 androidx.viewpager2.widget.ViewPager2$RecyclerViewImpl.onInitializeAccessibilityEvent(ViewPager2.java:982)
20 android.view.View.sendAccessibilityEventUncheckedInternal(View.java:5841)
21 android.view.View$AccessibilityDelegate.sendAccessibilityEventUnchecked(View.java:22203)
22 androidx.core.view.AccessibilityDelegateCompat.sendAccessibilityEventUnchecked(AccessibilityDelegateCompat.java:195)
23 androidx.core.view.AccessibilityDelegateCompat$AccessibilityDelegateAdapter.sendAccessibilityEventUnchecked(AccessibilityDelegateCompat.java:112)
24 android.view.View.sendAccessibilityEventUnchecked(View.java:5824)
25 androidx.recyclerview.widget.RecyclerView.sendAccessibilityEventUnchecked(RecyclerView.java:3736)
26 android.view.View.sendAccessibilityEventInternal(View.java:5803)
27 android.view.View$AccessibilityDelegate.sendAccessibilityEvent(View.java:22161)
28 androidx.core.view.AccessibilityDelegateCompat.sendAccessibilityEvent(AccessibilityDelegateCompat.java:173)
29 androidx.core.view.AccessibilityDelegateCompat$AccessibilityDelegateAdapter.sendAccessibilityEvent(AccessibilityDelegateCompat.java:107)
30 android.view.View.sendAccessibilityEvent(View.java:5768)
31 android.view.View$SendViewScrolledAccessibilityEvent.run(View.java:22079)
32 android.os.Handler.handleCallback(Handler.java:739)
33 android.os.Handler.dispatchMessage(Handler.java:95)
34 android.os.Looper.loop(Looper.java:148)
35 android.app.ActivityThread.main(ActivityThread.java:5619)
36 java.lang.reflect.Method.invoke(Native Method)
37 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
38 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)

 问题指向viewpager2,切换成banner1.14.10版本正常

**Comment by ssj2020** [comment]
注:使用的版本并非最新版本,经过测试,最新版本也存在闪退问题

**Comment by youth5201314** [comment]
具体下你使用的最新版是哪个版本？

**Comment by androidmoyan** [comment]
2.1.0

**Comment by androidmoyan** [comment]
用的是最新的, RecyclerView  添加头部 Banner 然后  来回滑动后,  轮播图 自动轮播是3s  3s过后,recyclerView就会跳动到不定的位置
