### ISSUE TITLE
indicator是否能從banner移出

### ISSUE THREAD

**Issue by kunwei99** [youth5201314/banner#882]
剛剛發現這個好套件，但不知道此套件能否將indicator另外放
例 XML :
```
<banner>
</banner>
...
<indicator>
</indicator>
```

**Comment by hkhv** [comment]
可以自定义的

**Comment by everyline** [comment]
![image](https://user-images.githubusercontent.com/8476579/90083187-69288800-dd44-11ea-8e43-883c010a1bdd.png)

**Comment by youth5201314** [comment]
可以实现的，现在我在考虑是否需要将指示器的自定义样式从banner中移动到
