### ISSUE TITLE
偷懒不想自己新建适配器

### ISSUE THREAD

**Issue by gkj17** [youth5201314/banner#892]
文档说使用BannerImageAdapter<。。> 可是没有提供这个类  是忘记了吗。。。

**Comment by gzl003** [comment]
/**
 * @author user
 */
public abstract class BaseBannerLoader implements ImageLoaderInterface<BaseBannerItem> {

    @Override
    public void displayImage(Context context, Object path, BaseBannerItem imageView) {
        displayBanner(path, imageView);
    }

    @Override
    public BaseBannerItem createImageView(Context context) {
        return new BaseBannerItem(context) {
            @Override
            protected View createView(Context context) {
                return createBanner(context);
            }
        };
    }

    /**
     * item布局
     *
     * @return
     */
    public abstract View createBanner(Context context);

    /**
     * 展示banner
     *
     * @param path
     * @param item
     */
    public abstract void displayBanner(Object path, BaseBannerItem item);
}




public abstract class BaseBannerItem extends RelativeLayout {

    public BaseBannerItem(Context context) {
        this(context, null);
    }

    public BaseBannerItem(Context context, AttributeSet attrs) {
        this(context, attrs, 0);
    }

    public BaseBannerItem(Context context, AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
        init(context);
    }

    private void init(Context context) {
        addView(createView(context));
    }

    /**
     * 创建布局
     *
     * @param context
     * @return
     */
    protected abstract View createView(Context context);
}

**Comment by gzl003** [comment]
![image](https://user-images.githubusercontent.com/9498945/90871661-02534080-e3ce-11ea-875b-afd6e8791b61.png)

**Comment by gzl003** [comment]
`activeBanner.setImageLoader(new BaseBannerLoader() {
                        private SimpleDraweeView imageView;

                        @Override
                        public View createBanner(Context context) {
                            View view = View.inflate(context, R.layout.vip_banner_layout, null);
                            imageView = view.findViewById(R.id.banner_img);
                            return view;
                        }

                        @Override
                        public void displayBanner(Object path, BaseBannerItem item) {
                            AccountActive.ActiveItem data = (AccountActive.ActiveItem) path;
                            ImageLoadHelper.displayImage(imageView, data.pic);
                        }
                    }).setDelayTime(5000)`

**Comment by youth5201314** [comment]
@gkj17 你确定是用的最新版本吗？
