### ISSUE TITLE
如何让两边的图片靠近中间的图片？

### ISSUE THREAD

**Issue by Kyle91** [youth5201314/banner#894]
想达到的效果是，缩小间距，屏幕上能显示3张图片。左右两张图片能露出来一点

**Comment by youth5201314** [comment]
提供的有这种效果，这个具体的使用方式你可以看文档和demo

**Comment by payne1107** [comment]
左右两张图片能露出来一点  能设置左右两边漏出来的尺寸吗？ 就是设置露出来多大的db  就是设置中间的图片多宽
