### ISSUE TITLE
为什么默认显示最后一项

### ISSUE THREAD

**Issue by hexu2016** [youth5201314/banner#897]
怎么设置默认显示第一项呢?banner.setCurrentItem(0)好像没有用额,banner.setCurrentItem(1)好像可以,但是指示器位置不对

**Comment by youth5201314** [comment]
BannerUtils.getRealPosition（）可以获取真实位置。你可以了解下无限轮播的原理，首尾各放了一张图占位

**Comment by doujiangyt** [comment]
@hexu2016 2.1.0的版本不要使用bannerAdapter.setDatas()方法去设置数据，去通过banner.setDatas()方法设置数据，就可以了

**Comment by zjxuzhj** [comment]
> @hexu2016 2.1.0的版本不要使用bannerAdapter.setDatas()方法去设置数据，去通过banner.setDatas()方法设置数据，就可以了

真是我的救星
