### ISSUE TITLE
下个版本更新，可以把viewpager2的offscreenPageLimit()方法开放出来配置吗？

### ISSUE THREAD

**Issue by ollie100** [youth5201314/banner#899]
目前是框架里写死了1，getViewpager2()再设置offscreenPageLimit也是无效的
![image](https://user-images.githubusercontent.com/13077703/91829923-a661a500-ec74-11ea-83f8-81e9cf5697a2.png)

**Comment by initialjie** [comment]
为啥再设置offscreenPageLimit还是无效？
