### ISSUE TITLE
加载网络图片，会出现部分Image只有纯色值，没有完整图片，

### ISSUE THREAD

**Issue by cereuz** [youth5201314/banner#902]
问题描述：
1. 加载网络图片，会出现部分Image只有纯色值，没有完整图片。
2. 布局在分类页面Fragment中的RecycleView添加的header。  
3. 使用Glide加载的网络图片  ：   Glide.with(context).load(Url).placeholder(LoadingImg).into(iv);
4. 使用版本   implementation 'com.youth.banner:banner:2.1.0'
5. 手机：华为手机，安卓10系统
![cutQQ图片20200907134158](https://user-images.githubusercontent.com/7812152/92352130-ff678800-f10f-11ea-8ea4-c5fb7e9d704c.png)
![QQ图片20200907134102](https://user-images.githubusercontent.com/7812152/92352137-01314b80-f110-11ea-8e12-3283eba906cc.png)

图见附件

**Comment by ClayLinW** [comment]
使用glide指定图片的宽高override(int width, int height)
