### ISSUE TITLE
 Pages must fill the whole ViewPager2 (use match_parent)

### ISSUE THREAD

**Issue by hedongBlog** [youth5201314/banner#905]
这个问题很奇葩，就在fragment中使用了自定义的adapter，就报错了，用自带的adapter不会错

**Comment by breakadmin** [comment]
离谱

**Comment by liaodongxiaoxiao** [comment]
onCreateHolder里这样写试试：

LayoutInflater.from(this.context).inflate(
        resource,
        parent,
        false
    )

**Comment by 330132662** [comment]
幸亏搜了一下 要不然一时半会还研究不明白
