### ISSUE TITLE
切换其他页面再切回来，banner的imageview缩小了，详情请看描述和图片

### ISSUE THREAD

**Issue by Alexxiaopang** [youth5201314/banner#908]
问题描述：
首页使用banner（viewpage2+Fragment）切换到其他页面，再回来首页，偶现banner里面的第一张图片缩小，等到播放延迟的时候到了之后，恢复正常，使用的是ScaleInTransformer，
问题截图：
![1599788548(1)](https://user-images.githubusercontent.com/13740721/92842173-cf70fb00-f415-11ea-99b4-4f47f9c7959b.png)

版本：com.youth.banner:banner:2.1.0
banner配置：
        homeBanner.setAdapter(new ImageNetAdapter(getActivity(),null))
                .setIndicator(new RectangleIndicator(getActivity()))
                .setIndicatorNormalWidth((int) getResources().getDimension(R.dimen.dp_10))
                .setIndicatorSelectedWidth((int)getResources().getDimension(R.dimen.dp_4))
                .setIndicatorSpace((int) getResources().getDimension(R.dimen.dp_3))
                .addPageTransformer(new ScaleInTransformer())
手动和生命周期绑定都试过，adapter是简单的image，用的是glide加载

**Comment by 87620089** [comment]
这个我上次提了个  后来找到原因了 你检查下adapter的xml
