### ISSUE TITLE
统一个UI下banner与可滚动的textview共存时，banner切换会使正在滚动文字的textview重置

### ISSUE THREAD

**Issue by LankyBin-lb** [youth5201314/banner#909]
如题所述，由于滚动字幕的textview需要有焦点，所以重写return的isFocused始终为true
banner每五秒切换一次的时候会使正在滚动字幕的TextView重头开始滚动，
我一开始以为时banner抢了focus的缘故，将bannerfocusable设为false之后效果依旧。

**Comment by youth5201314** [comment]
无法复现你的问题，这要看你怎么实现的textview的轮播了，我只能用我的方式实现没有问题，同时banner也支持字幕的滚动的，如果未解决你可以提供详细的代码

**Comment by AdminQQZ** [comment]
提供demo给作者，减少烧脑

**Comment by LankyBin-lb** [comment]
我把两个空间放在不分开的父布局下就没有这个问题了。。。可能是我动态布局的，banner可以滚动字幕？那我也用用试试，TextView的滚动字幕很不好用
