### ISSUE TITLE
viewpager2+fragment+recyclerview嵌套banner生命周期

### ISSUE THREAD

**Issue by kxbyte** [youth5201314/banner#910]
viewpager2+fragment+recyclerview嵌套banner应该怎么控制他的生命周期，每个fragment都有一个recyclerview嵌套的banner，怎么在切换fragment切换的时候暂停上一个fragment里的banner停止轮播？

**Comment by hexu2016** [comment]
我的做法是监听fragment状态,onStart时候 onHidden时候,刷新数据时候,都判断一下,如果fragment显示并且started,则start轮播,否则stop轮播..刷新数据时候也最后判断一下状态,因为我看源码监听了adapter数据源的变化,也会自动进行start,因为可能fragment处于stop或hidden时候,这个时候数据请求过来了也会导致开始自动轮播.

**Comment by 416zxj** [comment]
我也是ViewPage + Fragment + recyclerview，然后在Adapter中设置banner，想知道怎么关联fragment状态，让不可见得fragment停止轮播
