### ISSUE TITLE
Glide加载图片，从最后一个滑动到第一个的时候，第一个图片展示前会闪烁一下，没找到问题，求解

### ISSUE THREAD

**Issue by wuwenbo5** [youth5201314/banner#917]

**Comment by wuwenbo5** [comment]
Glide.with(holder.itemView.context)
                        .load(url)
                        .error(R.drawable.ic_default_color)
                        .diskCacheStrategy(DiskCacheStrategy.RESOURCE)
                        .skipMemoryCache(true)
                        .apply(RequestOptions.bitmapTransform(CenterCrop()))
                        .into(）

**Comment by wuwenbo5** [comment]
首尾相互切换的时候就会出现这种情况

**Comment by GravesMrma** [comment]
我也遇到这个问题了。有解决办法吗？

**Comment by wuwenbo5** [comment]
> 我也遇到这个问题了。有解决办法吗？

skipMemoryCache(true)
不使用内存缓存的话就会出现这个问题，加上上面这句话就没事，但是我的业务逻辑不能使用内存

**Comment by GravesMrma** [comment]
我刚看了一下 我们的问题好像不一样  我遇到的问题是 感觉像是有两个计时任务同时执行  切换很快并且乱了

**Comment by Uqhs** [comment]
我也遇到这个问题了，最后一张滑动到第一张的时候出现闪烁一下，感觉是将中间的几张图片闪出来了，请问楼主怎么解决的呀

**Comment by 2472114784** [comment]
我也遇到闪烁问题，发现是glide加载图片的时候加载中默认图片和url图片切换的效果，所以感觉是闪烁问题，但是只是在切换到第一张的时候会出现，可能也是viewpager2的复用问题，导致glide重新加载图片造成的闪烁现象，目前我的处理方式是去掉默认图片，就没有闪烁问题了
