### ISSUE TITLE
CoordinatorLayout +AppBarLayout +Banner卡顿问题！

### ISSUE THREAD

**Issue by 6cwong** [youth5201314/banner#919]
我使用CoordinatorLayout +AppBarLayout  AppBarLayout 里面包裹了banner和其他的控件，当banner开始自动滚动的瞬间 进行CoordinatorLayout 上下滑动有明显的卡顿，等banner滚动结束后静止状态下上下滑动不会卡顿。
我观察了该现象应该是CoordinatorLayout所嵌套的控件进行UI更新时都会影响到CoordinatorLayout的上下滑动，有哪位大神有解决方案的？

**Comment by 6cwong** [comment]
> CoordinatorLayout滑动时禁用banner的自动轮播，嘿嘿

我目前的做法也是这样的，我发现CoordinatorLayout 里面所嵌套的控件只要进行更新view的操作都会造成CoordinatorLayout 滑动的卡顿！对CoordinatorLayout 的机制不是特别了解也无从下手去改这个问题！

**Comment by 372900192** [comment]
setIntercept(false)
