### ISSUE TITLE
请问支持加载更多功能吗？

### ISSUE THREAD

**Issue by soul7630** [youth5201314/banner#920]
你好，我这边有这么一个功能，滑动到底以后，需要一个加载更多的footer，如图所示，现在没有什么思路，请教大佬该如何实现呢？
<img width="562" alt="0C369EC4-2753-4361-86CD-FC1315FC4E88" src="https://user-images.githubusercontent.com/11975164/93749894-4a63be00-fc2d-11ea-9a4a-aafc83e7838c.png">

**Comment by TonyStonem** [comment]
虽然看不到图片，但觉得应该好实现的。
自定义自己的Adapter 继承BannerAdapter，getItemViewType中position == list.lastIndex 时返回footer 的类型，onCreateHolder时通过viewType 判断返回自己的page 还是 footer即可。
由于多了一个footer ，记得itemCount要多一个

**Comment by soul7630** [comment]
> 虽然看不到图片，但觉得应该好实现的。
> 自定义自己的Adapter 继承BannerAdapter，getItemViewType中position为最后一个时返回footer 的类型，onCreateHolder时通过viewType 判断返回自己的page 还是 footer即可。由于多了一个footer ，记得itemCount要多一个

谢谢大佬，已经实现，用了另一种方式

**Comment by houweiAndroid** [comment]
> > 虽然看不到图片，但觉得应该好实现的。
> > 自定义自己的Adapter 继承BannerAdapter，getItemViewType中position为最后一个时返回footer 的类型，onCreateHolder时通过viewType 判断返回自己的page 还是 footer即可。由于多了一个footer ，记得itemCount要多一个
> 
> 谢谢大佬，已经实现，用了另一种方式

想请问一下，您用的哪种方式实现的呢？

**Comment by soul7630** [comment]
> > > 虽然看不到图片，但觉得应该好实现的。
> > > 自定义自己的Adapter 继承BannerAdapter，getItemViewType中position为最后一个时返回footer 的类型，onCreateHolder时通过viewType 判断返回自己的page 还是 footer即可。由于多了一个footer ，记得itemCount要多一个
> > 
> > 
> > 谢谢大佬，已经实现，用了另一种方式
> 
> 想请问一下，您用的哪种方式实现的呢？

布局使用RecycleView，然后使用横向刷新，添加自定义footer就可以了
