### ISSUE TITLE
在使用Banner时 发现position不是从0开始及解决方法

### ISSUE THREAD

**Issue by TonyStonem** [youth5201314/banner#921]
版本：2.1.0

问题描述：

由于首页东西较多，所以是先给Banner 设置adapter 给一个空的list ，然后网络请求下来数据后再给list 进行赋值，然后adapter.notifyDataSetChanged()
这样做后发现我的Banner 加载的第一个page 不是position 为 0 的，而是list.lastIndex，导致页面顺序异常
后续的下拉刷新list.clear() ，adapter.notifyDataSetChanged()也是类似的问题

解决方案：

后来我这样做，数据请求下来，list 赋值后再设置Banner 的adapter
下拉刷新list.clear() 后及新数据赋值后，再adapter.notifyDataSetChanged()，解决了这个问题

我觉得应该是不能在数据源为空的时候设置adapter 和调用adapter.notifyDataSetChanged()

**Comment by qiaoyhh** [comment]
我也遇到这个问题，也是这样做的，但是没有效果a

**Comment by duronggang** [comment]
我也遇到这个问题

**Comment by TonyStonem** [comment]
> 我也遇到这个问题，也是这么做的，但是没有效果a
不好意思现在才看到，如果不行的话可以这样试一下：直接使用一个有数据的list，观察是否正常

**Comment by TonyStonem** [comment]
> 我也遇到这个问题

解决了吗，我去他的源码看了，list为空和不为空的时候做了不同的处理，导致index异常了

**Comment by hiliving** [comment]
我也遇到同样的问题了，请问怎么解决呢

**Comment by ptliao** [comment]
banner.adapter.notifyDataSetChanged()
   banner.setCurrentItem(1, false)
   banner.setIndicatorPageChange()
   banner.start()

我目前的方案是刷新数据后，在重新设置下currentItem，动画重新启动

**Comment by Ha2ryZhang** [comment]
我也遇到同样的问题了，请问怎么解决呢

**Comment by Ha2ryZhang** [comment]
> 我也遇到同样的问题了，请问怎么解决呢

另一个issue看到的 解决了
调用banner.setDatas()，而不是adapter的setDatas()
或者你调用了adapter.setDatas()后调用setCurrentItem(1, false);
