### ISSUE TITLE
指示器为啥不能在banner外面

### ISSUE THREAD

**Issue by everyline** [youth5201314/banner#922]
![image](https://user-images.githubusercontent.com/8476579/93840603-877a8f80-fcc3-11ea-843d-57723c8bbe2e.png)
![image](https://user-images.githubusercontent.com/8476579/93840608-8e090700-fcc3-11ea-8483-6b0d96eb6f0d.png)

指示器就是不能替换默认的指示器

**Comment by youth5201314** [comment]
参考demo
