### ISSUE TITLE
你好，我使用的是1.4.10的老版本，嵌套在 ViewPager2 中使用，有滑动冲突，想请教一下这个怎么解决？

### ISSUE THREAD

**Issue by jhwsx** [youth5201314/banner#923]
我的工程是 `ViewPager2` + `Fragment` 的，然后在一个 `Fragment` 里面有用到 `Banner` 来展示轮播图。
当手指滑动轮播图时，直接就切到了 `ViewPager2` 的下一个 `Fragment`。

我现在还没有解决好这个问题。

**Comment by 17610071766** [comment]
解决了吗？我还没解决，我也遇到了这个问题。

**Comment by jhwsx** [comment]
没有呢，不太会弄。

**Comment by 17610071766** [comment]
我换了，没用这个banner了

**Comment by jhwsx** [comment]
用的哪一个，可以解决这个问题？

**Comment by 17610071766** [comment]
可以的

**Comment by 330676687** [comment]
2.1.0问题依然存在😂

**Comment by keluokeda** [comment]
> 我换了，没用这个banner了

老哥换了哪个banner啊，分享出来一下啊

**Comment by keluokeda** [comment]
@17610071766 老哥换的是哪个banner啊，我现在也遇到这个问题了

**Comment by Eaydroid** [comment]
可以参考google提供的方案，我通过这个解决了
https://github.com/android/views-widgets-samples/blob/master/ViewPager2/app/src/main/java/androidx/viewpager2/integration/testapp/NestedScrollableHost.kt#L71
