### ISSUE TITLE
在banner高度固定图片高度自适应的情况能让图片居中显示吗

### ISSUE THREAD

**Issue by dzq0906** [youth5201314/banner#927]
banner控件
<com.youth.banner.Banner
                    android:id="@+id/home_bga"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_marginTop="@dimen/dp_5"
                    android:layout_marginBottom="@dimen/dp_5"
                    android:maxHeight="500dp"
                    android:minHeight="300dp"
                    android:layout_gravity="center_vertical"
                    banner:banner_infinite_loop="false"
                    banner:banner_radius="5dp"
                    banner:banner_indicator_normal_width="@dimen/dp_7"
                    banner:banner_indicator_selected_width="@dimen/dp_7"
                    banner:banner_indicator_normal_color="@color/e5e5e5"
                    banner:banner_indicator_selected_color="@color/basecolor" />

imageview控件
    <ImageView
        android:id="@+id/pageview_iv"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:scaleType="fitXY"
        android:adjustViewBounds="true" />

可以让imageview居中吗

**Comment by youth5201314** [comment]
可以，布局是你自己实现的跟banner无关哦
