### ISSUE TITLE
在CoordinatorLayout+AppBarLayout中向上滑动banner 页面滑不动

### ISSUE THREAD

**Issue by wangxiongtao** [youth5201314/banner#931]
<androidx.coordinatorlayout.widget.CoordinatorLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical"
        tools:context=".home.MarketFragment">

        <com.google.android.material.appbar.AppBarLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

            <com.youth.banner.Banner
                app:layout_scrollFlags="scroll"
                android:id="@+id/banner"
                android:layout_width="match_parent"
                android:layout_height="115dp"
                android:layout_marginLeft="15dp"
                android:layout_marginRight="15dp"
                app:bannerAdapter="@{marketVm.bannerAdapter}"
                app:bannerChangeListener="@{marketVm.pageChangeListener}"
                app:bannerList="@{marketVm.bannerList}"
                app:bannerListener="@{marketVm.bannerListener}" />

            <TextView
                android:layout_width="match_parent"
                android:layout_height="45dp"
                android:background="@color/colorAccent" />
        </com.google.android.material.appbar.AppBarLayout>
        <androidx.core.widget.NestedScrollView
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:layout_behavior="@string/appbar_scrolling_view_behavior">

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="外链图片转存中…(img-Cpfgrgm7-1567999875484)]外链图片转存中…(img-Cpfgrgm7-1567999875484)]外链图片转存中…(img-Cpfgrgm7-1567999875484)]外链图片转存中…(img-Cpfgrgm7-1567999875484)]外链图片转存中…(img-Cpfgrgm7-1567999875484)]外链图片转存中…(img-Cpfgrgm7-1567999875484)]外链图片转存中…(img-Cpfgrgm7-1567999875484)]外链图片转存中…(img-Cpfgrgm7-1567999875484)]外链图片转存中…(img-Cpfgrgm7-1567999875484)]外链图片转存中…(img-Cpfgrgm7-1567999875484)]外链图片转存中…(img-Cpfgrgm7-1567999875484)]外链图片转存中…(img-Cpfgrgm7-1567999875484)]外链图片转存中…(img-Cpfgrgm7-1567999875484)]外链图片转存中…(img-Cpfgrgm7-1567999875484)]外链图片转存中…(img-Cpfgrgm7-1567999875484)]外链图片转存中…(img-Cpfgrgm7-1567999875484)]外链图片转存中…(img-Cpfgrgm7-1567999875484)]外链图片转存中…(img-Cpfgrgm7-1567999875484)]外链图片转存中…(img-Cpfgrgm7-1567999875484)]外链图片转存中…(img-Cpfgrgm7-1567999875484)]外链图片转存中…(img-Cpfgrgm7-1567999875484)]外链图片转存中…(img-Cpfgrgm7-1567999875484)]外链图片转存中…(img-Cpfgrgm7-1567999875484)]外链图片转存中…(img-Cpfgrgm7-1567999875484)]外链图片转存中…(img-Cpfgrgm7-1567999875484)]外链图片转存中…(img-Cpfgrgm7-1567999875484)]外链图片转存中…(img-Cpfgrgm7-1567999875484)]外链图片转存中…(img-Cpfgrgm7-1567999875484)]外链图片转存中…(img-Cpfgrgm7-1567999875484)]外链图片转存中…(img-Cpfgrgm7-1567999875484)]外链图片转存中…(img-Cpfgrgm7-1567999875484)]外链图片转存中…(img-Cpfgrgm7-1567999875484)]外链图片转存中…(img-Cpfgrgm7-1567999875484)]外链图片转存中…(img-Cpfgrgm7-1567999875484)]外链图片转存中…(img-Cpfgrgm7-1567999875484)]外链图片转存中…(img-Cpfgrgm7-1567999875484)]"
                android:textSize="30sp" />

        </androidx.core.widget.NestedScrollView>

我之前用的老版本(没有AndroidX)没问题，现在换的2.1.0就出现这个问题

    </androidx.coordinatorlayout.widget.CoordinatorLayout>

**Comment by gkj17** [comment]
你的Coll呢

**Comment by youth5201314** [comment]
这个demo有例子的，你看看呢
