### ISSUE TITLE
数据size=2是错位

### ISSUE THREAD

**Issue by lawkentdev** [youth5201314/banner#932]
当数据源size=2时并且开启首尾连接播放，指示器显示position=0,页面显示的内容却是position=1的图片

**Comment by hazyrain** [comment]
一样。。

**Comment by youth5201314** [comment]
这不叫错位，首尾各放了一张图片作为过渡，所以多了2个item，你可以去看下无限循环实现的原理。

**Comment by wu928320442** [comment]
我也遇到了 这个问题怎么解决呢 这是个特殊情况下的bug吧
