### ISSUE TITLE
Banner轮播自动获取焦点的问题

### ISSUE THREAD

**Issue by bombp** [youth5201314/banner#933]
Banner 通过 addHeadView添加进RecycleView后，滑动RecycleView使Banner半隐藏，Banner轮播时RecycleView自动滑动回顶部

**Comment by hanxiaofeng** [comment]
请问这个问题如何处理的？

**Comment by QIMOU** [comment]
同问同问，好严重的bug，我是在上方一个banner 下半部分是samrtrefresh + rv 结果出现自动上滑
