### ISSUE TITLE
重新设置适配器的问题

### ISSUE THREAD

**Issue by gkj17** [youth5201314/banner#934]
您好。想问一哈   如何实现 banner的  高度自适应呢？像小红书那样的。
想配合【CollapsingToolbarLayout】 实现对应的效果

**Comment by youth5201314** [comment]
监听你图片的高度变化改变banner的高度就行了

**Comment by gkj17** [comment]
谢谢，实现了！



在 2020-10-13 15:54:35，"Spring" <notifications@github.com> 写道：

监听你图片的高度变化改变banner的高度就行了
