### ISSUE TITLE
使用setBannerGalleryEffect设置了画廊效果,右边留空,到最后一页时,想在空白处加个“更多”的按钮

### ISSUE THREAD

**Issue by Aicent** [youth5201314/banner#952]
使用setBannerGalleryEffect设置了画廊效果,右边留空,到最后一页时,想在空白处加个“更多”的按钮,不清楚有没有这个方法?
或者提供个思路也好.

**Comment by sohnyi** [comment]
不循环， 数据源手动添加一个更多条目
