### ISSUE TITLE
Banner V2.1.0 设置指示器默认色和选中色不生效问题

### ISSUE THREAD

**Issue by cdalwyn** [youth5201314/banner#953]
![福昕截屏20201030152532901](https://user-images.githubusercontent.com/46589715/97672039-57918980-1ac4-11eb-9712-9b36cf7aaac6.PNG)

环境： 版本V2.1.0 AndroidX Kotlin 
问题复现：如图
情况描述：选用库默认的三种指示器配置默认背景色和选中背景色都不生效

**Comment by moon2star** [comment]
解决了么 我这里也是设置banner指示器颜色无效，指示器不显示

**Comment by DarkerWanglei** [comment]
我这样设置也不生效，xml里写倒是正常的

**Comment by songdaren123** [comment]
把动态设置属性的代码放在设置adapter之后，因为在设置adaper时里面又调用了 initIndicator(); 这个方法用的默认值
`
 /**
     * 设置banner的适配器
     */
    public Banner setAdapter(BA adapter) {
        if (adapter == null) {
            throw new NullPointerException(getContext().getString(R.string.banner_adapter_null_error));
        }
        this.mAdapter = adapter;
        if (!isInfiniteLoop()) {
            mAdapter.setIncreaseCount(0);
        }
        mAdapter.registerAdapterDataObserver(mAdapterDataObserver);
        mViewPager2.setAdapter(adapter);
        setCurrentItem(mStartPosition, false);
        initIndicator();
        return this;
    }

`

**Comment by cdalwyn** [comment]
> 把动态设置属性的代码放在设置adapter之后，因为在设置adaper时里面又调用了 initIndicator(); 这个方法用的默认值
> `
> /**
> * 设置banner的适配器
> */
> public Banner setAdapter(BA adapter) {
> if (adapter == null) {
> throw new NullPointerException(getContext().getString(R.string.banner_adapter_null_error));
> }
> this.mAdapter = adapter;
> if (!isInfiniteLoop()) {
> mAdapter.setIncreaseCount(0);
> }
> mAdapter.registerAdapterDataObserver(mAdapterDataObserver);
> mViewPager2.setAdapter(adapter);
> setCurrentItem(mStartPosition, false);
> initIndicator();
> return this;
> }
> 
> `

我尝试在setAdapter之后或者之前设置，都不生效呢
