### ISSUE TITLE
当banner在fragment中并且自动轮播的过程中，切换到其他的fragment，会导致banner停留在一半

### ISSUE THREAD

**Issue by HairySnow** [youth5201314/banner#956]
![IMG_20201111_154855](https://user-images.githubusercontent.com/24764220/98784159-a7ae0b80-2435-11eb-977e-cf07adadfc8e.jpg)
如图

**Comment by HairySnow** [comment]
> ![IMG_20201111_154855](https://user-images.githubusercontent.com/24764220/98784159-a7ae0b80-2435-11eb-977e-cf07adadfc8e.jpg)
> 如图

已解决这个问题，在adapter中增加如下代码
![YKYYV ~1NY5O~8F}P`0G4 F](https://user-images.githubusercontent.com/24764220/98787855-0033d780-243b-11eb-8eaf-b380d40529a6.png)
mViewPager2是在Banner中获取的
![IFPM6MM(E)1LN95 K`M499B](https://user-images.githubusercontent.com/24764220/98787995-2e191c00-243b-11eb-8800-90dca3dd6cb4.png)
 最后在fragment中的onResume方法中加上以下代码，让recyclerView滚动到正确位置
![K6}V%J(MIRN`)O_48(ANOFO](https://user-images.githubusercontent.com/24764220/98788112-59037000-243b-11eb-938d-c85218331281.png)

**Comment by Felix1030** [comment]
这个好像不会生效 还是会留一部分
