### ISSUE TITLE
到了第二张图会会显示0.1秒然后就会消失

### ISSUE THREAD

**Issue by yanxudong1** [youth5201314/banner#959]
有两张图片到第二张图的时候会瞬间消失
![微信截图_20201116180915](https://user-images.githubusercontent.com/28141527/99240050-e3cadd00-2836-11eb-9505-8987a1429a1f.png)

![12212121181221](https://user-images.githubusercontent.com/28141527/99240339-4fad4580-2837-11eb-905e-fbe5a8fea0a3.png)

**Comment by KnnethKong** [comment]
楼上解决了吗
