### ISSUE TITLE
您好，不知道是我没有正确使用还是小bug。

### ISSUE THREAD

**Issue by gaohequan** [youth5201314/banner#96]
public void update(List<?> imageUrls) {
        this.imageUrls.clear();
        this.imageUrls.addAll(imageUrls);
        this.count = this.imageUrls.size();
        start();
    }
使用update方法的时候  如果对象是list = new ArrayList()然后add数据进去没有问题。
如果是list.clear()然后add数据进去，就会出现各种各样的问题，比如指示器不见，手动翻转崩溃等。

**Comment by youth5201314** [comment]
大哥，首先这里接收的是集合，如果你是通过arrays直接转换的集合，那么是没有办法实现addAll的，你检查下你是否是这种写法，其次在添加前，清空以前的数据有问题吗？我的demo也同样使用测试过，你可以对照着有什么不同！

**Comment by gaohequan** [comment]
ArrayList<String> defaultList = new ArrayList<String>();
                defaultList.add("aaa");
                defaultList.add("bbb");
                ArrayList<String> mArrayList = new ArrayList<String>();
                //第一种
                mArrayList = new ArrayList<String>();
                for(String item : defaultList){
                    mArrayList.add(item);
                }
                mBanner.update(mArrayList);
                //第二种
                mArrayList.clear();
                for(String item : defaultList){
                    mArrayList.add(item);
                }
                mBanner.update(mArrayList);

我的意思是这样 第一种没问题 第二种有问题  ，
可能是对象的引用原因吧。（本人理解错误就不必回了 - -#）

**Comment by youth5201314** [comment]
首先你的代码我看着就有几个问题，效率还低。你的错误本身都是你自己造成的！

![qq 20161220095854](https://cloud.githubusercontent.com/assets/8827239/21335592/edf6e17c-c69a-11e6-906b-f8eeef2b5e7a.png)

**Comment by gaohequan** [comment]
我只是举一个例子。。。原始的数据是网络请求而来 然后对象里面的String抽离出来。然后两种写法也只写了一种。。。这个问题关了吧。不讨论了  ：）
