### ISSUE TITLE
如何使ImageView 填充Banner。 

### ISSUE THREAD

**Issue by Moonwing2020** [youth5201314/banner#960]
我的图片比较长， 不知道怎么做填充处理。

**Comment by Jeromeer** [comment]
设置imageview为fit_xy,然后拿到图片的宽高比,根据宽度铺满屏幕算出图片应该占多少高度,不知道理解的对不对

**Comment by Moonwing2020** [comment]
是的， 多谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jerome"<notifications@github.com&gt;; 
发送时间: 2020年11月24日(星期二) 下午3:37
收件人: "youth5201314/banner"<banner@noreply.github.com&gt;; 
抄送: "竹林箫声"<hxgame2020@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [youth5201314/banner] 如何使ImageView 填充Banner。  (#960)





 
设置imageview为fit_xy,然后拿到图片的宽高比,根据宽度铺满屏幕算出图片应该占多少高度,不知道理解的对不对
