### ISSUE TITLE
指示器的属性动态设置不生效

### ISSUE THREAD

**Issue by Florian-31** [youth5201314/banner#961]
banner.indicator = RectangleIndicator(context)
                    banner.setIndicatorGravity(IndicatorConfig.Direction.LEFT)
                    banner.setBannerRound(Utils.dipToPx(context, 4).toFloat())
                    banner.setIndicatorSelectedColorRes(R.color.color_ffffff)
                    banner.setIndicatorNormalColorRes(R.color.color_8f8f8f)
                    banner.setIndicatorSpace(BannerUtils.dp2px(4f).toInt())
                    banner.setIndicatorRadius(2)

这么设置，除了居左生效了，其他的属性都没有生效，xml里设置是生效的，

**Comment by protectedMan** [comment]
是的,我也遇到这个问题, 应该是个bug

**Comment by songdaren123** [comment]
> banner.indicator = RectangleIndicator(context)
> banner.setIndicatorGravity(IndicatorConfig.Direction.LEFT)
> banner.setBannerRound(Utils.dipToPx(context, 4).toFloat())
> banner.setIndicatorSelectedColorRes(R.color.color_ffffff)
> banner.setIndicatorNormalColorRes(R.color.color_8f8f8f)
> banner.setIndicatorSpace(BannerUtils.dp2px(4f).toInt())
> banner.setIndicatorRadius(2)
> 
> 这么设置，除了居左生效了，其他的属性都没有生效，xml里设置是生效的，

把动态设置属性的代码放在设置adapter之后，因为在设置adaper时里面又调用了 initIndicator(); 里面设置的默认值

**Comment by DarkerWanglei** [comment]
有道理&nbsp;

郁闷
 &nbsp;


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "songdaren123"<notifications@github.com&gt;; 
发送时间: 2020年12月7日(星期一) 下午4:54
收件人: "youth5201314/banner"<banner@noreply.github.com&gt;; 
抄送: "不知觉"<912436316@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [youth5201314/banner] 指示器的属性动态设置不生效 (#961)



banner.indicator = RectangleIndicator(context)
 banner.setIndicatorGravity(IndicatorConfig.Direction.LEFT)
 banner.setBannerRound(Utils.dipToPx(context, 4).toFloat())
 banner.setIndicatorSelectedColorRes(R.color.color_ffffff)
 banner.setIndicatorNormalColorRes(R.color.color_8f8f8f)
 banner.setIndicatorSpace(BannerUtils.dp2px(4f).toInt())
 banner.setIndicatorRadius(2)
 这么设置，除了居左生效了，其他的属性都没有生效，xml里设置是生效的，
  把动态设置属性的代码放在设置adapter之后，因为在设置adaper时里面又调用了 initIndicator(); 里面设置的默认值

**Comment by ptliao** [comment]
看源码是banner中的这个方法导致的

private void initIndicatorAttr() {
        if (indicatorMargin != 0) {
            setIndicatorMargins(new IndicatorConfig.Margins(indicatorMargin));
        } else if (indicatorMarginLeft != 0
                || indicatorMarginTop != 0
                || indicatorMarginRight != 0
                || indicatorMarginBottom != 0) {
            setIndicatorMargins(new IndicatorConfig.Margins(
                    indicatorMarginLeft,
                    indicatorMarginTop,
                    indicatorMarginRight,
                    indicatorMarginBottom));
        }
        if (indicatorSpace > 0) {
            setIndicatorSpace(indicatorSpace);
        }
        if (indicatorGravity != IndicatorConfig.Direction.CENTER) {
            setIndicatorGravity(indicatorGravity);
        }
        if (normalWidth > 0) {
            setIndicatorNormalWidth(normalWidth);
        }
        if (selectedWidth > 0) {
            setIndicatorSelectedWidth(selectedWidth);
        }

        if (indicatorHeight > 0) {
            setIndicatorHeight(indicatorHeight);
        }
        if (indicatorRadius > 0) {
            setIndicatorRadius(indicatorRadius);
        }
        setIndicatorNormalColor(normalColor);
        setIndicatorSelectedColor(selectedColor);
    }

最好的解决办法是，直接在banner控件xml中设置该值
private void initTypedArray(Context context, AttributeSet attrs) {
        if (attrs == null) {
            return;
        }
        TypedArray a = context.obtainStyledAttributes(attrs, R.styleable.Banner);
        mBannerRadius = a.getDimensionPixelSize(R.styleable.Banner_banner_radius, 0);
        mLoopTime = a.getInt(R.styleable.Banner_banner_loop_time, BannerConfig.LOOP_TIME);
        mIsAutoLoop = a.getBoolean(R.styleable.Banner_banner_auto_loop, BannerConfig.IS_AUTO_LOOP);
        mIsInfiniteLoop = a.getBoolean(R.styleable.Banner_banner_infinite_loop, BannerConfig.IS_INFINITE_LOOP);
        normalWidth = a.getDimensionPixelSize(R.styleable.Banner_banner_indicator_normal_width, BannerConfig.INDICATOR_NORMAL_WIDTH);
        selectedWidth = a.getDimensionPixelSize(R.styleable.Banner_banner_indicator_selected_width, BannerConfig.INDICATOR_SELECTED_WIDTH);
        normalColor = a.getColor(R.styleable.Banner_banner_indicator_normal_color, BannerConfig.INDICATOR_NORMAL_COLOR);
        selectedColor = a.getColor(R.styleable.Banner_banner_indicator_selected_color, BannerConfig.INDICATOR_SELECTED_COLOR);
        indicatorGravity = a.getInt(R.styleable.Banner_banner_indicator_gravity, IndicatorConfig.Direction.CENTER);
        indicatorSpace = a.getDimensionPixelSize(R.styleable.Banner_banner_indicator_space, 0);
        indicatorMargin = a.getDimensionPixelSize(R.styleable.Banner_banner_indicator_margin, 0);
        indicatorMarginLeft = a.getDimensionPixelSize(R.styleable.Banner_banner_indicator_marginLeft, 0);
        indicatorMarginTop = a.getDimensionPixelSize(R.styleable.Banner_banner_indicator_marginTop, 0);
        indicatorMarginRight = a.getDimensionPixelSize(R.styleable.Banner_banner_indicator_marginRight, 0);
        indicatorMarginBottom = a.getDimensionPixelSize(R.styleable.Banner_banner_indicator_marginBottom, 0);
        indicatorHeight = a.getDimensionPixelSize(R.styleable.Banner_banner_indicator_height, BannerConfig.INDICATOR_HEIGHT);
        indicatorRadius = a.getDimensionPixelSize(R.styleable.Banner_banner_indicator_radius, BannerConfig.INDICATOR_RADIUS);
        int orientation = a.getInt(R.styleable.Banner_banner_orientation, HORIZONTAL);
        setOrientation(orientation);
        setInfiniteLoop();
        a.recycle();
    }
