### ISSUE TITLE
那个仓库才能用?

### ISSUE THREAD

**Issue by YuDongZhang** [youth5201314/banner#962]
Could not find com.youth.banner:banner:2.0.0.
Searched in the following locations:
    file:/C:/Users/86130/AppData/Local/Android/Sdk/extras/m2repository/com/youth/banner/banner/2.0.0/banner-2.0.0.pom
    file:/C:/Users/86130/AppData/Local/Android/Sdk/extras/m2repository/com/youth/banner/banner/2.0.0/banner-2.0.0.jar
    file:/C:/Users/86130/AppData/Local/Android/Sdk/extras/google/m2repository/com/youth/banner/banner/2.0.0/banner-2.0.0.pom
    file:/C:/Users/86130/AppData/Local/Android/Sdk/extras/google/m2repository/com/youth/banner/banner/2.0.0/banner-2.0.0.jar
    file:/C:/Users/86130/AppData/Local/Android/Sdk/extras/android/m2repository/com/youth/banner/banner/2.0.0/banner-2.0.0.pom
    file:/C:/Users/86130/AppData/Local/Android/Sdk/extras/android/m2repository/com/youth/banner/banner/2.0.0/banner-2.0.0.jar
    https://dl.google.com/dl/android/maven2/com/youth/banner/banner/2.0.0/banner-2.0.0.pom
    https://dl.google.com/dl/android/maven2/com/youth/banner/banner/2.0.0/banner-2.0.0.jar
    https://jcenter.bintray.com/com/youth/banner/banner/2.0.0/banner-2.0.0.pom
    https://jcenter.bintray.com/com/youth/banner/banner/2.0.0/banner-2.0.0.jar
    https://repo1.maven.org/maven2/com/youth/banner/banner/2.0.0/banner-2.0.0.pom
    https://repo1.maven.org/maven2/com/youth/banner/banner/2.0.0/banner-2.0.0.jar
    https://jitpack.io/com/youth/banner/banner/2.0.0/banner-2.0.0.pom
    https://jitpack.io/com/youth/banner/banner/2.0.0/banner-2.0.0.jar
Required by:
    project :app

**Comment by youth5201314** [comment]
jcenter()
