### ISSUE TITLE
竖向仿头条的滚动条可以触摸无限滑动

### ISSUE THREAD

**Issue by Power-Android** [youth5201314/banner#969]
如题，我在嵌套smartrefreshlayout时 里边的banner可以用手去滑动banner里边的内容

**Comment by Power-Android** [comment]
/**
     * 禁止手动滑动
     *
     * @param enabled true 允许，false 禁止
     */
    public Banner setUserInputEnabled(boolean enabled) {
        getViewPager2().setUserInputEnabled(enabled);
        return this;
    }

已找到解决方案。

**Comment by billdizl** [comment]
你用今日头条的这种模式,刷新数据会不会出现索引越界的情况呢?
