### ISSUE TITLE
圆点指示器问题

### ISSUE THREAD

**Issue by MirrorFlower** [youth5201314/banner#97]
今天在项目中发现，结合TabLayout使用有点问题，比如页面顶部由Tablayout形成的可滑动的若干Tab选项，我第一个Tab中的Fragment使用的这个库，然后往后整体滑动Tab，再滑回来，发现指示器圆点个数出现加倍的情况

**Comment by youth5201314** [comment]
刚测试过了，没有你发现你说的问题，还是检查你自己的代码吧！
