### ISSUE TITLE
banner.setAdapter有泛型警告咋解决呢

### ISSUE THREAD

**Issue by liu-xinhui** [youth5201314/banner#970]
![image](https://user-images.githubusercontent.com/7698511/100984463-b8115c00-3585-11eb-85cb-55eb3bad120d.png)

**Comment by Naruto-1996** [comment]
怎么解决呢

**Comment by 258917407** [comment]
![image](https://user-images.githubusercontent.com/49682753/113390978-55aa5a00-93c5-11eb-8b17-b16e1cfdf61b.png)
kotlin里咋设置setAdapter？ 提示 需要: Nothing!

**Comment by beike6688** [comment]
已解决

//这样设置就行了，不要用 banner.setAdapter() 方法，BannerImageAdapter继承 BannerAdapter
banner.adapter =  BannerImageAdapter(BannerDataBean.getTestData())

**Comment by xiaoxing1992** [comment]
> kotlin设置适配器，已解决：
> 
> //这样设置就行了，不要用 banner.setAdapter() 方法，BannerImageAdapter继承 BannerAdapter
> banner.adapter = BannerImageAdapter(BannerDataBean.getTestData())

我的怎么没有adapter

**Comment by cuixiaodong** [comment]
> > kotlin设置适配器，已解决：
> > //这样设置就行了，不要用 banner.setAdapter() 方法，BannerImageAdapter继承 BannerAdapter
> > banner.adapter = BannerImageAdapter(BannerDataBean.getTestData())
> 
> 我的怎么没有adapter

我这也是2.2.1、2.2.2版本，没有这个adapter

**Comment by kornan** [comment]
> > > kotlin设置，已解决：
> > > //这样设置就行了，不要用banner.setAdapter()方法，BannerImageAdapter继承BannerAdapterbanner.adapter 
> > > = BannerImageAdapter(BannerDataBean.getTestData())
> > 
> > 
> > 我的怎么没有适配器
> 
> 我这也是2.2.1、2.2.2版本，没有这个适配器

我用的是2.2.2，banner是val ，无法赋值

**Comment by kornan** [comment]
> > > > kotlin设置，已解决：
> > > > //这样设置就行了，不要用banner.setAdapter()方法，BannerImageAdapter继承BannerAdapterbanner.adapter
> > > > = BannerImageAdapter(BannerDataBean.getTestData())
> > > 
> > > 
> > > 我的怎么没有适配器
> > 
> > 
> > 我这也是2.2.1、2.2.2版本，没有这个适配器
> 
> 我用的是2.2.2，banner是val ，无法赋值

换回2.1.0可以正常使用

**Comment by pxpxp** [comment]
以上方法都不行

**Comment by pxpxp** [comment]
找到里面有kotlin写法
val banner2 = (banner as Banner<YourBean, YourCustomAdapter>)
先强转，之后就没泛型报错了

**Comment by ilovexy2tom** [comment]
val banner2 = (banner as Banner<String, BannerImageAdapter<String>>)
        banner2.setAdapter(object : BannerImageAdapter<String>(arrayListOf()) {
            override fun onBindView(holder: BannerImageHolder?, data: String?, position: Int, size: Int) {

            }
        }).addBannerLifecycleObserver(this) //添加生命周期观察者
                .setIndicator(CircleIndicator(requireContext()))
