### ISSUE TITLE
关于首尾图片切换过程中的闪烁问题

### ISSUE THREAD

**Issue by Qdafengzi** [youth5201314/banner#973]
一开始我以为是Gif图的问题，第一张是Gif图最后一张是正常图，结果都换成正常图片还是不行，仔细测试了一下，大于4张图的时候 ，从最后一张切换到第一张或者第一张滑动到最后一张都会出现闪烁的问题。看提bug的人很多，但是没有一个能有效解决的方案。是ViewPager2缓存问题还是Glide本身问题，还是banner的问题呢？求解决。

**Comment by lsy6829308** [comment]
请问解决了，同样遇到这个问题

**Comment by caik13** [comment]
我用的  2.1.0版本，用的 viewpager2,
我在加载图片时 用 Glide 设置图片圆角，在收尾相接时会闪一下；
后来我改成 用 banner组件的设置圆角，不用Glide设置圆角，发现不闪了。
希望对你们有用

**Comment by Temtion** [comment]
> 我用的 2.1.0版本，用的 viewpager2,
> 我在加载图片时 用 Glide 设置图片圆角，在收尾相接时会闪一下；
> 后来我改成 用 banner组件的设置圆角，不用Glide设置圆角，发现不闪了。
> 希望对你们有用

我这边还是会闪

**Comment by zhangbingbing889** [comment]
请问有什么解决方法吗？我这没设置圆角，也是闪

**Comment by yswheye** [comment]
2.2.2还是有问题，第一个item叠加一个gif，每次从最后一个滚动到第一个时gif都会闪烁一下

**Comment by Star3513** [comment]
https://github.com/youth5201314/banner/issues/995#issuecomment-1447424631
测试可以解决
