### ISSUE TITLE
indicator支持添加背景资源么？

### ISSUE THREAD

**Issue by whatisjava** [youth5201314/banner#975]
就像这种效果： ![WX20201209-120905](https://user-images.githubusercontent.com/366992/101583883-651d2600-3a17-11eb-9b69-039aa45e0595.png)

**Comment by 972223177** [comment]
> 就像这种效果： ![WX20201209-120905](https://user-images.githubusercontent.com/366992/101583883-651d2600-3a17-11eb-9b69-039aa45e0595.png)

哥你是咋实现的，可以分享下吗

**Comment by whatisjava** [comment]
> > 就像这种效果： ![WX20201209-120905](https://user-images.githubusercontent.com/366992/101583883-651d2600-3a17-11eb-9b69-039aa45e0595.png)
> 
> 哥你是咋实现的，可以分享下吗

不好意思，刚看到，还需要吗？可以加我QQ 407039746

**Comment by alphater** [comment]
> > > 就像这种效果： ![WX20201209-120905](https://user-images.githubusercontent.com/366992/101583883-651d2600-3a17-11eb-9b69-039aa45e0595.png)
> > 
> > 
> > 哥你是咋实现的，可以分享下吗
> 
> 不好意思，刚看到，还需要吗？可以加我QQ 407039746

大佬，你怎么实现的呢？

**Comment by 972223177** [comment]
诚聘网络兼职工资日结!还不错~
详情请登陆招聘网站http://brorx.cn/?;
