### ISSUE TITLE
关于轮播一张图和多张图循环模式和肺循环模式时的currentItem问题，循环模式首位衔接闪屏问题（可能我使用不当）

### ISSUE THREAD

**Issue by dyl169** [youth5201314/banner#976]
设置循环模式下
1.当banner一张图时获得到的currentItem为0
2.当banner多张图时（我自己使用的为5张图时）currentItem为+1，同时首位衔接时会出现 闪屏的情况（我使用的是画廊效果）
![image](https://user-images.githubusercontent.com/19199353/101850673-31680a80-3b95-11eb-8223-b4cbaaeb928f.png)

设置非循环模式下
我更新adapter发现当前的页面会变小，前一个变大 ，似乎把前一个作为了当前页（操作步骤为5张banner第一次滑动到最后一张，更新adapter，我尝试重新setCurrentItem但会有其他问题）
![image](https://user-images.githubusercontent.com/19199353/101850844-84da5880-3b95-11eb-8cb2-0acf2478509e.png)

**Comment by dyl169** [comment]
麻烦大佬有空看下

**Comment by iamlfc** [comment]
我也遇到了同样的问题，你那边处理掉了吗？

**Comment by dyl169** [comment]
> 我也遇到了同样的问题，你那边处理掉了吗？

暂时没有，可能是viewPager2的毛病

**Comment by iamlfc** [comment]
旧版本(使用 viewpager)  的你那边又遇到过不？我在考虑要不要切换成旧版本的试试

**Comment by iamlfc** [comment]
可以通过这 addOnPageChangeListener  监听方法 自己保存当前状态  规避掉这个问题

**Comment by dyl169** [comment]
我这边没有试过旧版本 因为support包已经从我的项目里剔除了

**Comment by dyl169** [comment]
> 可以通过这 addOnPageChangeListener 监听方法 自己保存当前状态 规避掉这个问题

我改为viewPager了  现在没什么问题

**Comment by caik13** [comment]
我用的  2.1.0版本，用的 viewpager2,
我在加载图片时 用 Glide 设置图片圆角，在收尾相接时会闪一下；
后来我改成 用 banner组件的设置圆角，不用Glide设置圆角，发现不闪了。
希望对你们有用

**Comment by jlglyyx** [comment]
![image](https://user-images.githubusercontent.com/51355162/103184220-09e1a380-48f2-11eb-9802-e514dc1e5326.png)
我是去掉这一行就不闪烁了（勿喷）

**Comment by jlglyyx** [comment]
我去掉 banner.setBannerRound(30f); 就不闪了（可能每个人情况不同)

**Comment by zhangjianzhu** [comment]
用到了GlideUrl，要给url addHeader，试了不用addHeader就不会闪，可是不用又不行，有点头疼

**Comment by Star3513** [comment]
https://github.com/youth5201314/banner/issues/995#issuecomment-1447424631
测试可以解决

**Comment by LXLYHM** [comment]
遇到了视频轮播闪一下的问题，有人遇到吗？怎么解决求取经
