### ISSUE TITLE
【建议】嵌套在CoordinatorLayout中时候上下滑动失效

### ISSUE THREAD

**Issue by leichangwen** [youth5201314/banner#978]
事件拦截 isIntercept标志位换个位置
原代码：
    @Override
    public boolean onInterceptTouchEvent(MotionEvent event) {
        if (!getViewPager2().isUserInputEnabled() || !isIntercept) {
            return super.onInterceptTouchEvent(event);
        }
        switch (event.getAction()) {
            case MotionEvent.ACTION_DOWN:
                mStartX = event.getX();
                mStartY = event.getY();
                getParent().requestDisallowInterceptTouchEvent(true);
                break;
修改后：
    @Override
    public boolean onInterceptTouchEvent(MotionEvent event) {
        if (!getViewPager2().isUserInputEnabled()) {
            return super.onInterceptTouchEvent(event);
        }
        switch (event.getAction()) {
            case MotionEvent.ACTION_DOWN:
                mStartX = event.getX();
                mStartY = event.getY();
                if (isIntercept) {
                    getParent().requestDisallowInterceptTouchEvent(true);
                }
                break;

**Comment by mhz-tiantian** [comment]
这个修改完, 以后上下滑动还是失效啊

**Comment by 372900192** [comment]
setIntercept(false)

**Comment by getglory** [comment]
> 这个修改完, 以后上下滑动还是失效啊

不需要修改。调用banner.setIntercept(false)方法就行了。看了楼上的回复才知道
