### ISSUE TITLE
banner.getCurrentItem(),或者banner.getViewPager2().getCurrentItem() 获取到的pos不稳定

### ISSUE THREAD

**Issue by bakonMa** [youth5201314/banner#982]
version：v2.1.0
banner.getCurrentItem(),或者banner.getViewPager2().getCurrentItem()
获取到的pos不稳定，通过addOnPageChangeListener获取到的才准确
求修复此bug

**Comment by onecoders** [comment]
BannerUtils.getRealPosition(true, mBanner.currentItem, mBanner.realCount)
