### ISSUE TITLE
能维护一下这个问题吗？

### ISSUE THREAD

**Issue by OkamiyGit** [youth5201314/banner#987]
首页轮播图，切其他页面，过一会在切回首页，时不时会出现轮播图显示半页的情况，时不时还会出现指示器在1，轮播图已经在在第3或者第4，出现情况都是轮播页面前后台会出现。  2.1.0版本，抽空能维护一下吗

**Comment by mlp1995** [comment]
试试页面不显示的时候 调用 stop 方法停止滚动, 然页面展示出来再滚动;

**Comment by PostLiu** [comment]
`出现半页的情况大概率是因为添加`addBannerLifecycleObserver`造成的

**Comment by HairySnow** [comment]
> 出现半页的情况大概率是因为添加`addBannerLifecycleObserver`造成的

应该不是的，主动管理生命周期也会这样

**Comment by HairySnow** [comment]
> 首页轮播图，切其他页面，过一会在切回首页，时不时会出现轮播图显示半页的情况，时不时还会出现指示器在1，轮播图已经在在第3或者第4，出现情况都是轮播页面前后台会出现。 2.1.0版本，抽空能维护一下吗

轮播在fragment中显示半页的，我也有这样的问题，现在修改了一下，我测试不会这样了，你可以参考一下

《主要代码》在banner的adapter中增加如下方法，其中mViewPager2可以从banner中获取到
public void snapToCorrectPage() {
        if (mViewPager2 != null) {
            RecyclerView recyclerView = (RecyclerView) mViewPager2.getChildAt(0);
            RecyclerView.OnFlingListener onFlingListener = recyclerView.getOnFlingListener();
            if (onFlingListener instanceof PagerSnapHelper) {
                PagerSnapHelper pagerSnapHelper = (PagerSnapHelper) onFlingListener;
                snapToPage(pagerSnapHelper, recyclerView);
            }
        }
    }

    void snapToPage(PagerSnapHelper pagerSnapHelper, RecyclerView recyclerView) {
        if (recyclerView.getLayoutManager() == null || pagerSnapHelper == null) {
            return;
        }
        // Method copied from PagerSnapHelper#snapToTargetExistingView
        // When fixing something here, make sure to update that method as well
//参考ViewPager2的snapToPage()方法
        View view = pagerSnapHelper.findSnapView(recyclerView.getLayoutManager());
        if (view == null) {
            return;
        }
        int[] snapDistance = pagerSnapHelper.calculateDistanceToFinalSnap(recyclerView.getLayoutManager(), view);
        if (snapDistance == null) {
            return;
        }
        if (snapDistance[0] != 0 || snapDistance[1] != 0) {
//必须使用smoothScrollBy,否则仍然会显示半页
            recyclerView.smoothScrollBy(snapDistance[0], snapDistance[1]);
        }
    }

之后在fragment的onResume方法中调用snapToCorrectPage()方法

**Comment by PostLiu** [comment]
感谢分享,有空试试
