### ISSUE TITLE
不管是1.4.10还是2.1.0，编译都会失败，不引进包，就没有问题。

### ISSUE THREAD

**Issue by songyunbiao** [youth5201314/banner#988]
10:14	Gradle sync failed: Project build was cancelled
		Consult IDE log for more details (Help | Show Log) (3 m 15 s 62 ms)

Cause: connect timed out
<img width="972" alt="WX20201225-104601@2x" src="https://user-images.githubusercontent.com/9216385/103115791-ea067180-469e-11eb-99b0-2e63374fe9b2.png">

**Comment by mlp1995** [comment]
感觉像是 网不好....
