### ISSUE TITLE
postion初始位置不是0

### ISSUE THREAD

**Issue by jackli12** [youth5201314/banner#991]
override fun onBindView(
        holder: BannerViewHolder?,
        data: BannerBean?,
        position: Int,
        size: Int
    ) {｝
 复写这个方法，发现默认位置不是从0开始，看源码是BannerUtils里重新计算了位置,
`public static int getRealPosition(boolean isIncrease, int position, int realCount) {
        if (!isIncrease) {
            return position;
        }
        int realPosition;
        if (position == 0) {
            realPosition = realCount - 1;
        } else if (position == realCount + 1) {
            realPosition = 0;
        } else {
            realPosition = position - 1;
        }
        return realPosition;
    }`
不明白为什么要这样计算，还是说是bug，要用真实数据的个数-1，没看懂，现在遇到的问题是真实位置与数据List不能对应起来

**Comment by 1009095162** [comment]
老哥你解决了吗，我也遇到了

**Comment by jackli12** [comment]
`setAdapter`的時候第二个参数isInfiniteLoop设置为false即可

**Comment by ZakAnun** [comment]
@jackli12 
这不是 bug，可以看到如果没有修改 increaseCount 的话，会比原先多两个 item，用于实现轮播的。
不太清楚你说的不能对应起来是什么情景，但是轮播到下一个的逻辑是: (banner.getCurrentItem() + 1) % count

**Comment by NamedWu** [comment]
优先设置adapter,然后获取网络数据再次刷新数据，会出现这个bug,进去的position不知道到哪里去了，设置currentPosition==0也不管用，希望作者解决下。

**Comment by ZakAnun** [comment]
> 优先设置adapter,然后获取网络数据再次刷新数据，会出现这个bug,进去的position不知道到哪里去了，设置currentPosition==0也不管用，希望作者解决下。

看看代码实现

**Comment by NamedWu** [comment]
> > 优先设置adapter,然后获取网络数据再次刷新数据，会出现这个bug,进去的position不知道到哪里去了，设置currentPosition==0也不管用，希望作者解决下。
> 
> 看看代码实现

------set adapter---
adapter = DetailBannerAdapter(viewModel.bannerList.value, viewModel)
bannerProductDetail.adapter = adapter
bannerProductDetail.addBannerLifecycleObserver(this).indicator = CircleIndicator(this)

----obserrve mData----
viewModel.bannerList.observe(this, Observer {
            if (it == null || it.isEmpty()) {
                return@Observer
            }
            adapter.setDatas(viewModel.bannerList.value)
            bannerProductDetail.currentItem = 0
            adapter.notifyDataSetChanged()
        })

adapter 只是个普通继承
class DetailBannerAdapter(mDatas:List<String?>?): BannerAdapter<String, DetailBannerAdapter.BannerViewHolder>(mDatas)

**Comment by NamedWu** [comment]
目前自己找了个独特的方法设置当前位置为0 ，只要设置currentItem==mData.size+1,即可让banner处于位置0.目前看源码，mData+1不会下标越界

**Comment by ZakAnun** [comment]
> 目前自己找了个独特的方法设置当前位置为0 ，只要设置currentItem=mData.size+1,即可让banner处于位置0.目前看源码，mData。size+1不会下标越界

设置数据后，调用 setCurrentItem 和 notityItemChanged 就可以
