### ISSUE TITLE
banner 能设置viewPager2自带的fragmentStateAdapter? 

### ISSUE THREAD

**Issue by 15189611** [youth5201314/banner#993]
banner 能设置viewPager2自带的fragmentStateAdapter?  我现在的需求不是只有图片，我想viewPager2里面滑动使用的是fragment,, 请求帮助～

**Comment by qinyang1018** [comment]
@15189611  你实现了吗？我现在也有类似的需求

**Comment by keaitao0321** [comment]
有人这样用了吗？我也有这个需求

**Comment by challengefengxin** [comment]
同问
