### ISSUE TITLE
新版本轮播结束后，刷新会闪一下

### ISSUE THREAD

**Issue by zhou880220** [youth5201314/banner#995]
之前用1.4.1的版本没有这个问题，新版本从最后一张图片切到第一张时会闪一下，有空白出现，体验不是很好。
此外，设置第一张貌似不是0，是1。

**Comment by zhangjianzhu** [comment]
我也遇到了这个问题，2.1版本轮播结束后，刷新会闪一下，请问你找到解决办法了嘛

**Comment by Temtion** [comment]
也遇到了这个问题，很影响体验，大家有解决方案吗？

**Comment by xoax** [comment]
我也遇到了这个问题

**Comment by summer-xx** [comment]
他轮播动画那块，定位真实位置时有点问题。

**Comment by zoomzb** [comment]
怎么解决的？

**Comment by summer-xx** [comment]
你怎么找到我的，他的原因在于；循环下标计算的地方除了问题。但是那个地方他用的静态方法写的。所以不好改，或者你可以下载源码去修复，另外一个是，可以去重新实现一套循环逻辑去替换掉他默认的。你看看他的代码吧，有一个接口允许你去更改这块，如果你只是想解决循环不闪烁的问题，那还有一个更简单的方法，就是让返回循环的大小取一个很大的数值，也可以需要闪烁，但是你响应点击事件需要注意索引位置要处理一下，否则，会越界。具体的细节，你可以加我QQ283675199.
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "youth5201314/banner"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月3日(星期六) 中午11:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [youth5201314/banner] 新版本轮播结束后，刷新会闪一下 (#995)





 
怎么解决的？

**Comment by Jerry805** [comment]
我也遇到了这个问题，2.2.2版本，无限循环轮播，从第一个滑动到最后一个，从最后一个滑动到第一个，画面会刷新闪一下，请问怎么修复的呢？

**Comment by badjone** [comment]
不解决了吗,这个问题是

**Comment by Star3513** [comment]
这个闪烁是由于图片加载框架Glide和自动轮播机制一起造成的
自欧东轮播机制是加入有4张图片，那么就会轮播6张，
这样播放到最后一张的时候会直接刷新到第一张，这样的瞬间切换，Glide等加载图片框架没有那么快，所以造成了闪烁
我觉得解决办法有两个
解决办法一:
       吧图片缓存成bitmap，示例代码
       `HomePagerBannerAdapterBean adapterBean = getData(position);
        if (!TextUtils.isEmpty(adapterBean.getUrl())) {
            viewBinding.ivBanner.setImageDrawable(adapterBean.getImageDrawable());
            Glide.with(mLayoutInflater.getContext())
                    .load(ImageLoadUtils.getLoadUrl(adapterBean.getUrl()))
                    .placeholder(adapterBean.getImageDrawable())
                    .dontAnimate()
                    .into(new CustomTarget<Drawable>() {
                        @Override
                        public void onResourceReady(@NonNull Drawable resource, @Nullable Transition<? super Drawable> transition) {
                            viewBinding.ivBanner.setImageDrawable(resource);
                            if (holder.getAbsoluteAdapterPosition() == 1) {
                                adapterBean.setImageDrawable(resource);
                            }
                        }

                        @Override
                        public void onLoadCleared(@Nullable Drawable placeholder) {

                        }
                    });
        }`
解决办法二:
         优化这种自动轮播，让自动轮播有无限多张图，而不是播放到最后一个就自动切换到第一个

**Comment by wuh876** [comment]
> 这个闪烁是由于图片加载框架Glide和自动轮播机制一起造成的 自欧东轮播机制是加入有4张图片，那么就会轮播6张， 这样播放到最后一张的时候会直接刷新到第一张，这样的瞬间切换，Glide等加载图片框架没有那么快，所以造成了闪烁 我觉得解决办法有两个 解决办法一: 吧图片缓存成bitmap，示例代码
> 
> <img alt="image" width="991" src="https://user-images.githubusercontent.com/31870329/221729046-68a76268-f7db-4dc9-a923-1efebfd2b6ee.png">
> 
> 解决办法二: 优化这种自动轮播，让自动轮播有无限多张图，而不是播放到最后一个就自动切换到第一个

轮播视频怎么处理的

**Comment by LXLYHM** [comment]
> > 这个闪烁是由于图片加载框架Glide和自动轮播机制一起造成的 自欧东轮播机制是加入有4张图片，那么就会轮播6张， 这样播放到最后一张的时候会直接刷新到第一张，这样的瞬间切换，Glide等加载图片框架没有那么快，所以造成了闪烁 我觉得解决办法有两个 解决办法一: 吧图片缓存成bitmap，示例代码
> > <img alt="image" width="991" src="https://user-images.githubusercontent.com/31870329/221729046-68a76268-f7db-4dc9-a923-1efebfd2b6ee.png">
> > 解决办法二: 优化这种自动轮播，让自动轮播有无限多张图，而不是播放到最后一个就自动切换到第一个
> 
> 轮播视频怎么处理的

一样轮播视频遇到闪一下的过程，请问有解决了吗？是怎么处理的？
