### ISSUE TITLE
数组越界异常闪退

### ISSUE THREAD

**Issue by Haha003** [youth5201314/banner#996]
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionBannerViewHolder{379450 position=4 id=-1, oldPos=-1, pLpos:-1 no parent} androidx.viewpager2.widget.ViewPager2$RecyclerViewImpl{689a57c VFED..... ........ 0,0-1014,371 #1},

1、设置三张图片，在第一张和第二张滑动的间隙，调用adapter的notifyDatasSet()会闪退

**Comment by Haha003** [comment]
更新数据用setData就不会出现这个问题了

**Comment by BuYaoZheYangHaoMa** [comment]
不要多次setAdapter，多次设置数据源setData
